using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Numerics;
using Content.Client.Localization;
using Content.Shared.CCVar;
using Content.Shared.GameTicking.Prototypes;
using Content.Client.UserInterface.Screens;
using Content.Shared.HUD;
using Content.Shared._WH40K.Chat.Translation;
using Content.Shared._WH40K.Interface;
using Content.Shared._WH40K.Notifications;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MiscTab : Control, ILocalizedControl
{
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly ILocalizationManager _localization = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private const string LobbyBackgroundModeServer = "server";
    private const string LobbyBackgroundModeStatic = "static";
    private const string LobbyBackgroundModeAnimated = "animated";
    private const string LobbyBackgroundUnknownTitleLoc = "lobby-state-background-unknown-title";

    private readonly OptionDropDownCVar<string> _themeOption;
    private readonly OptionDropDownCVar<string> _layoutOption;
    private readonly OptionDropDownCVar<string> _languageOption;
    private readonly OptionCheckboxCVar _chatTranslationEnabledOption;
    private readonly OptionDropDownCVar<string> _chatTranslationLanguageOption;
    private readonly OptionDropDownCVar<string> _lobbyBackgroundModeOption;
    private readonly OptionDropDownCVar<string> _lobbyStaticBackgroundOption;
    private readonly OptionDropDownCVar<string> _lobbyAnimatedBackgroundOption;
    private readonly OptionDropDownCVar<string> _notificationModeOption;
    private readonly OptionDropDownCVar<bool> _notificationChatOption;
    private readonly NotificationCategoryOptionCVar _notificationCategoriesOption;
    private readonly NotificationCategoryButton _notificationCategoryButton;

    public MiscTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Channel can be null in replays so.
        // ReSharper disable once ConditionalAccessQualifierIsNonNullableAccordingToAPIContract
        ShowOocPatronColor.Visible = _playerManager.LocalSession?.Channel?.UserData.PatronTier is { };

        _themeOption = Control.AddOptionDropDown(CCVars.WH40KInterfaceThemePreference, DropDownHudTheme, BuildThemeEntries());
        _layoutOption = Control.AddOptionDropDown(CCVars.UILayout, DropDownHudLayout, BuildLayoutEntries());
        _languageOption = Control.AddOptionDropDown(CVars.LocCultureName, DropDownLanguage, BuildLanguageEntries());
        _chatTranslationEnabledOption = Control.AddOptionCheckBox(CCVars.WH40KChatTranslationPreferenceEnabled, ChatTranslationEnabledCheckBox);
        _chatTranslationLanguageOption = Control.AddOptionDropDown(CCVars.WH40KChatTranslationPreferenceLanguage, DropDownChatTranslationLanguage, BuildChatTranslationLanguageEntries());
        _lobbyBackgroundModeOption = Control.AddOptionDropDown(CCVars.LobbyBackgroundType, DropDownLobbyBackgroundType, BuildLobbyBackgroundModeOptions());
        _lobbyStaticBackgroundOption = Control.AddOptionDropDown(CCVars.LobbyStaticBackground, DropDownLobbyStaticBackground, BuildLobbyBackgroundOptions(animated: false));
        _lobbyAnimatedBackgroundOption = Control.AddOptionDropDown(CCVars.LobbyAnimatedBackground, DropDownLobbyAnimatedBackground, BuildLobbyBackgroundOptions(animated: true));
        NormalizeNotificationDisplayModeCVar();
        _notificationModeOption = Control.AddOptionDropDown(CCVars.WH40KNotificationDisplayMode, DropDownNotificationMode, BuildNotificationModeEntries());
        _notificationChatOption = Control.AddOptionDropDown(CCVars.WH40KNotificationChatEnabled, DropDownNotificationChat, BuildNotificationChatEntries());
        _notificationCategoryButton = new NotificationCategoryButton();
        NotificationCategoryDropdownHost.AddChild(_notificationCategoryButton);
        _notificationCategoriesOption = Control.AddOption(new NotificationCategoryOptionCVar(
            Control,
            _cfg,
            CCVars.WH40KNotificationEnabledCategories,
            _notificationCategoryButton,
            BuildNotificationCategoryEntries));

        Control.AddOptionCheckBox(CVars.DiscordEnabled, DiscordRich);
        Control.AddOptionCheckBox(CCVars.ShowOocPatronColor, ShowOocPatronColor);
        Control.AddOptionCheckBox(CCVars.LoocAboveHeadShow, ShowLoocAboveHeadCheckBox);
        Control.AddOptionCheckBox(CCVars.HudHeldItemShow, ShowHeldItemCheckBox);
        Control.AddOptionCheckBox(CCVars.CombatModeIndicatorsPointShow, ShowCombatModeIndicatorsCheckBox);
        Control.AddOptionCheckBox(CCVars.OpaqueStorageWindow, OpaqueStorageWindowCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatEnableFancyBubbles, FancySpeechBubblesCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatFancyNameBackground, FancyNameBackgroundsCheckBox);
        Control.AddOptionCheckBox(CCVars.StaticStorageUI, StaticStorageUI);
        Control.AddOptionPercentSlider(CCVars.WH40KNotificationSoundVolume, NotificationSoundVolumeSlider);
        Control.AddOptionPercentSlider(CCVars.LobbyPanelOpacity, LobbyPanelOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.LobbyCustomizationPanelOpacity, CustomizationPanelOpacitySlider);

        _chatTranslationEnabledOption.ImmediateValueChanged += UpdateChatTranslationLanguageSelectorState;
        _lobbyBackgroundModeOption.ImmediateValueChanged += UpdateLobbyBackgroundSelectorVisibility;
        Control.Initialize();
        UpdateChatTranslationLanguageSelectorState(_cfg.GetCVar(CCVars.WH40KChatTranslationPreferenceEnabled));
        UpdateLobbyBackgroundSelectorVisibilityFromDropDown();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateLobbyBackgroundSelectorVisibilityFromDropDown();
    }

    public void Relocalize()
    {
        UiStyleHeaderLabel.Text = Loc.GetString("ui-options-general-ui-style");
        NotificationsHeaderLabel.Text = Loc.GetString("ui-options-general-wh40k-notifications");
        LanguageHeaderLabel.Text = Loc.GetString("ui-options-general-language-translation");
        LobbyHeaderLabel.Text = Loc.GetString("ui-options-general-lobby");
        DiscordHeaderLabel.Text = Loc.GetString("ui-options-general-discord");
        SpeechHeaderLabel.Text = Loc.GetString("ui-options-general-speech");
        CursorHeaderLabel.Text = Loc.GetString("ui-options-general-cursor");
        StorageHeaderLabel.Text = Loc.GetString("ui-options-general-storage");

        DropDownHudTheme.Title = Loc.GetString("ui-options-hud-theme");
        DropDownHudLayout.Title = Loc.GetString("ui-options-hud-layout");
        DropDownNotificationMode.Title = Loc.GetString("ui-options-wh40k-notifications-mode");
        DropDownNotificationChat.Title = Loc.GetString("ui-options-wh40k-notifications-chat");
        NotificationCategoryFilterLabel.Text = Loc.GetString("ui-options-wh40k-notifications-categories");
        NotificationSoundVolumeSlider.Title = Loc.GetString("ui-options-wh40k-notifications-sound-volume");
        DropDownLanguage.Title = Loc.GetString("ui-options-language");
        DropDownChatTranslationLanguage.Title = Loc.GetString("ui-options-chat-translation-language");
        DropDownLobbyBackgroundType.Title = Loc.GetString("ui-options-lobby-background-type");
        DropDownLobbyStaticBackground.Title = Loc.GetString("ui-options-lobby-static-background");
        DropDownLobbyAnimatedBackground.Title = Loc.GetString("ui-options-lobby-animated-background");
        LobbyPanelOpacitySlider.Title = Loc.GetString("ui-options-lobby-panel-opacity");
        CustomizationPanelOpacitySlider.Title = Loc.GetString("ui-options-customization-panel-opacity");
        ChatTranslationEnabledCheckBox.Text = Loc.GetString("ui-options-chat-translation-enabled");
        DiscordRich.Text = Loc.GetString("ui-options-discordrich");
        ShowOocPatronColor.Text = Loc.GetString("ui-options-show-ooc-patron-color");
        ShowLoocAboveHeadCheckBox.Text = Loc.GetString("ui-options-show-looc-on-head");
        FancySpeechBubblesCheckBox.Text = Loc.GetString("ui-options-fancy-speech");
        FancyNameBackgroundsCheckBox.Text = Loc.GetString("ui-options-fancy-name-background");
        ShowHeldItemCheckBox.Text = Loc.GetString("ui-options-show-held-item");
        ShowCombatModeIndicatorsCheckBox.Text = Loc.GetString("ui-options-show-combat-mode-indicators");
        OpaqueStorageWindowCheckBox.Text = Loc.GetString("ui-options-opaque-storage-window");
        StaticStorageUI.Text = Loc.GetString("ui-options-static-storage-ui");

        _themeOption.ReloadOptions(BuildThemeEntries());
        _layoutOption.ReloadOptions(BuildLayoutEntries());
        _notificationModeOption.ReloadOptions(BuildNotificationModeEntries());
        _notificationChatOption.ReloadOptions(BuildNotificationChatEntries());
        _notificationCategoriesOption.ReloadOptions(BuildNotificationCategoryEntries());
        _languageOption.ReloadOptions(BuildLanguageEntries());
        _chatTranslationLanguageOption.ReloadOptions(BuildChatTranslationLanguageEntries());
        _lobbyBackgroundModeOption.ReloadOptions(BuildLobbyBackgroundModeOptions());
        _lobbyStaticBackgroundOption.ReloadOptions(BuildLobbyBackgroundOptions(animated: false));
        _lobbyAnimatedBackgroundOption.ReloadOptions(BuildLobbyBackgroundOptions(animated: true));
        Control.RefreshLocalization();
        UpdateChatTranslationLanguageSelectorState(_cfg.GetCVar(CCVars.WH40KChatTranslationPreferenceEnabled));
        UpdateLobbyBackgroundSelectorVisibilityFromDropDown();
    }

    private IReadOnlyCollection<OptionDropDownCVar<string>.ValueOption> BuildThemeEntries()
    {
        var themes = _prototypeManager.EnumeratePrototypes<HudThemePrototype>().ToList();
        themes.Sort();

        var themeEntries = new List<OptionDropDownCVar<string>.ValueOption>(themes.Count + 1)
        {
            new(WH40KInterfaceThemes.Auto, Loc.GetString("ui-options-hud-theme-auto"))
        };

        foreach (var gear in themes)
        {
            themeEntries.Add(new OptionDropDownCVar<string>.ValueOption(gear.ID, Loc.GetString(gear.Name)));
        }

        return themeEntries;
    }

    private IReadOnlyCollection<OptionDropDownCVar<string>.ValueOption> BuildLobbyBackgroundModeOptions()
    {
        return
        [
            new OptionDropDownCVar<string>.ValueOption(LobbyBackgroundModeServer, Loc.GetString("ui-options-lobby-background-type-server")),
            new OptionDropDownCVar<string>.ValueOption(LobbyBackgroundModeStatic, Loc.GetString("ui-options-lobby-background-type-static")),
            new OptionDropDownCVar<string>.ValueOption(LobbyBackgroundModeAnimated, Loc.GetString("ui-options-lobby-background-type-animated")),
        ];
    }

    private IReadOnlyCollection<OptionDropDownCVar<string>.ValueOption> BuildNotificationModeEntries()
    {
        return
        [
            new OptionDropDownCVar<string>.ValueOption(WH40KNotificationMetadata.DisplayModeFull, Loc.GetString("ui-options-wh40k-notifications-mode-full")),
            new OptionDropDownCVar<string>.ValueOption(WH40KNotificationMetadata.DisplayModeCompact, Loc.GetString("ui-options-wh40k-notifications-mode-compact")),
            new OptionDropDownCVar<string>.ValueOption(WH40KNotificationMetadata.DisplayModeOff, Loc.GetString("ui-options-wh40k-notifications-mode-off")),
        ];
    }

    private void NormalizeNotificationDisplayModeCVar()
    {
        var mode = _cfg.GetCVar(CCVars.WH40KNotificationDisplayMode);
        if (string.Equals(mode, WH40KNotificationMetadata.DisplayModeFull, StringComparison.OrdinalIgnoreCase) ||
            string.Equals(mode, WH40KNotificationMetadata.DisplayModeCompact, StringComparison.OrdinalIgnoreCase) ||
            string.Equals(mode, WH40KNotificationMetadata.DisplayModeOff, StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        _cfg.SetCVar(CCVars.WH40KNotificationDisplayMode, WH40KNotificationMetadata.DisplayModeFull);
    }

    private IReadOnlyCollection<OptionDropDownCVar<bool>.ValueOption> BuildNotificationChatEntries()
    {
        return
        [
            new OptionDropDownCVar<bool>.ValueOption(true, Loc.GetString("ui-options-wh40k-notifications-chat-enabled")),
            new OptionDropDownCVar<bool>.ValueOption(false, Loc.GetString("ui-options-wh40k-notifications-chat-disabled")),
        ];
    }

    private IReadOnlyList<NotificationCategoryEntry> BuildNotificationCategoryEntries()
    {
        return
        [
            new NotificationCategoryEntry(WH40KNotificationCategory.Critical, Loc.GetString("ui-options-wh40k-notifications-category-critical")),
            new NotificationCategoryEntry(WH40KNotificationCategory.Point, Loc.GetString("ui-options-wh40k-notifications-category-point")),
            new NotificationCategoryEntry(WH40KNotificationCategory.Weather, Loc.GetString("ui-options-wh40k-notifications-category-weather")),
            new NotificationCategoryEntry(WH40KNotificationCategory.Event, Loc.GetString("ui-options-wh40k-notifications-category-event")),
            new NotificationCategoryEntry(WH40KNotificationCategory.Objective, Loc.GetString("ui-options-wh40k-notifications-category-objective")),
            new NotificationCategoryEntry(WH40KNotificationCategory.Mission, Loc.GetString("ui-options-wh40k-notifications-category-mission")),
            new NotificationCategoryEntry(WH40KNotificationCategory.Economy, Loc.GetString("ui-options-wh40k-notifications-category-economy")),
            new NotificationCategoryEntry(WH40KNotificationCategory.Reinforcement, Loc.GetString("ui-options-wh40k-notifications-category-reinforcement")),
            new NotificationCategoryEntry(WH40KNotificationCategory.Info, Loc.GetString("ui-options-wh40k-notifications-category-info")),
        ];
    }

    private IReadOnlyCollection<OptionDropDownCVar<string>.ValueOption> BuildLobbyBackgroundOptions(bool animated)
    {
        var options = new List<OptionDropDownCVar<string>.ValueOption>
        {
            new(string.Empty, Loc.GetString("ui-options-lobby-background-auto")),
        };

        foreach (var proto in _prototypeManager.EnumeratePrototypes<LobbyBackgroundPrototype>()
                     .OrderBy(GetBackgroundDisplayName))
        {
            if (animated && proto.BackgroundGif == null)
                continue;

            if (!animated && proto.Background == null)
                continue;

            options.Add(new OptionDropDownCVar<string>.ValueOption(proto.ID, GetBackgroundDisplayName(proto)));
        }

        return options;
    }

    private string GetBackgroundDisplayName(LobbyBackgroundPrototype proto)
    {
        if (proto.Title == LobbyBackgroundUnknownTitleLoc)
            return proto.ID;

        var localizedTitle = Loc.GetString(proto.Title);
        var plainTitle = FormattedMessage.RemoveMarkupPermissive(localizedTitle).Trim();
        return string.IsNullOrWhiteSpace(plainTitle) ? proto.ID : plainTitle;
    }

    private void UpdateLobbyBackgroundSelectorVisibility(string mode)
    {
        var normalized = string.IsNullOrWhiteSpace(mode) ? LobbyBackgroundModeServer : mode.ToLowerInvariant();
        DropDownLobbyStaticBackground.Visible = normalized == LobbyBackgroundModeStatic;
        DropDownLobbyAnimatedBackground.Visible = normalized == LobbyBackgroundModeAnimated;
    }

    private void UpdateLobbyBackgroundSelectorVisibilityFromDropDown()
    {
        var selectedMode = DropDownLobbyBackgroundType.Button.SelectedMetadata as string
                           ?? _cfg.GetCVar(CCVars.LobbyBackgroundType);
        UpdateLobbyBackgroundSelectorVisibility(selectedMode);
    }

    private IReadOnlyCollection<OptionDropDownCVar<string>.ValueOption> BuildLayoutEntries()
    {
        var layoutEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var layout in Enum.GetValues(typeof(ScreenType)))
        {
            layoutEntries.Add(new OptionDropDownCVar<string>.ValueOption(layout.ToString()!, Loc.GetString($"ui-options-hud-layout-{layout.ToString()!.ToLower()}")));
        }

        return layoutEntries;
    }

    private IReadOnlyCollection<OptionDropDownCVar<string>.ValueOption> BuildLanguageEntries()
    {
        var cultures = _localization.GetFoundCultures();
        cultures.Sort((a, b) => string.Compare(a.NativeName, b.NativeName, StringComparison.CurrentCultureIgnoreCase));

        var entries = new List<OptionDropDownCVar<string>.ValueOption>(cultures.Count);

        foreach (var culture in cultures)
        {
            entries.Add(new OptionDropDownCVar<string>.ValueOption(culture.Name, FormatCultureLabel(culture)));
        }

        return entries;
    }

    private IReadOnlyCollection<OptionDropDownCVar<string>.ValueOption> BuildChatTranslationLanguageEntries()
    {
        return
        [
            new OptionDropDownCVar<string>.ValueOption(string.Empty, Loc.GetString("ui-options-chat-translation-language-auto")),
            new OptionDropDownCVar<string>.ValueOption(WH40KChatTranslationMarkup.EnglishLanguageCode, FormatCultureLabel(CultureInfo.GetCultureInfo("en-US"))),
            new OptionDropDownCVar<string>.ValueOption(WH40KChatTranslationMarkup.RussianLanguageCode, FormatCultureLabel(CultureInfo.GetCultureInfo("ru-RU"))),
        ];
    }

    private void UpdateChatTranslationLanguageSelectorState(bool enabled)
    {
        DropDownChatTranslationLanguage.Visible = enabled;
    }

    private static string FormatCultureLabel(CultureInfo culture)
    {
        var label = !string.IsNullOrWhiteSpace(culture.NativeName)
            ? culture.NativeName
            : !string.IsNullOrWhiteSpace(culture.DisplayName)
                ? culture.DisplayName
                : culture.Name;

        if (!string.IsNullOrWhiteSpace(label))
        {
            var chars = label.ToCharArray();
            chars[0] = char.ToUpper(chars[0], culture);
            label = new string(chars);
        }

        return string.Concat(label, " [", culture.Name, "]");
    }

    private readonly record struct NotificationCategoryEntry(WH40KNotificationCategory Category, string Label)
    {
        public string Id => WH40KNotificationMetadata.CategoryId(Category);
    }

    private sealed class NotificationCategoryOptionCVar : BaseOptionCVar<string>
    {
        private readonly NotificationCategoryButton _button;
        private readonly Func<IReadOnlyList<NotificationCategoryEntry>> _buildEntries;
        private IReadOnlyList<NotificationCategoryEntry> _entries;

        protected override string Value
        {
            get => string.Join(',', _button.SelectedKeys);
            set
            {
                _button.DeselectAll();
                var selected = value
                    .Split([',', ';', '\n', '\r'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                    .ToHashSet(StringComparer.OrdinalIgnoreCase);

                foreach (var entry in _entries)
                {
                    if (selected.Contains(entry.Id))
                        _button.SelectKey(entry.Id);
                }

                UpdateLabel();
            }
        }

        public NotificationCategoryOptionCVar(
            OptionsTabControlRow controller,
            IConfigurationManager cfg,
            CVarDef<string> cVar,
            NotificationCategoryButton button,
            Func<IReadOnlyList<NotificationCategoryEntry>> buildEntries)
            : base(controller, cfg, cVar)
        {
            _button = button;
            _buildEntries = buildEntries;
            _entries = buildEntries();
            Populate();

            _button.SelectionChanged += () =>
            {
                UpdateLabel();
                ValueChanged();
            };
        }

        public void ReloadOptions(IReadOnlyList<NotificationCategoryEntry> entries)
        {
            var current = Value;
            _entries = entries;
            Populate();
            Value = current;
        }

        public override void RefreshLocalization()
        {
            ReloadOptions(_buildEntries());
        }

        private void Populate()
        {
            _button.Clear();
            foreach (var entry in _entries)
            {
                _button.AddItem(entry.Label, entry.Id);
            }

            UpdateLabel();
        }

        private void UpdateLabel()
        {
            var selected = _button.SelectedKeys;
            if (selected.Count == 0)
            {
                _button.Label = Loc.GetString("ui-options-wh40k-notifications-categories-none");
                return;
            }

            if (selected.Count == _entries.Count)
            {
                _button.Label = Loc.GetString("ui-options-wh40k-notifications-categories-all");
                return;
            }

            if (selected.Count == 1)
            {
                var labels = selected
                    .Select(id => _entries.FirstOrDefault(entry => string.Equals(entry.Id, id, StringComparison.OrdinalIgnoreCase)).Label)
                    .Where(label => !string.IsNullOrWhiteSpace(label));

                _button.Label = string.Join(", ", labels);
                return;
            }

            _button.Label = Loc.GetString("ui-options-wh40k-notifications-categories-count", ("count", selected.Count));
        }
    }

    private sealed class NotificationCategoryButton : ContainerButton
    {
        private readonly Popup _popup;
        private readonly ScrollContainer _scroll;
        private readonly BoxContainer _popupBox;
        private readonly Label _label;
        private readonly Dictionary<string, CheckBox> _checkBoxes = new(StringComparer.OrdinalIgnoreCase);
        private readonly List<string> _selectedKeys = new();

        public event Action? SelectionChanged;

        public IReadOnlyList<string> SelectedKeys => _selectedKeys;

        public string? Label
        {
            get => _label.Text;
            set => _label.Text = value;
        }

        public NotificationCategoryButton()
        {
            AddStyleClass(StyleClassButton);
            HorizontalExpand = false;
            MinSize = new Vector2(220f, 0f);

            OnPressed += _ => TogglePopup(true);

            var hBox = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
            };
            AddChild(hBox);

            _label = new Label
            {
                StyleClasses = { OptionButton.StyleClassOptionButton },
                HorizontalExpand = true,
                ClipText = true,
            };
            hBox.AddChild(_label);

            hBox.AddChild(new TextureRect
            {
                StyleClasses = { OptionButton.StyleClassOptionTriangle },
                VerticalAlignment = VAlignment.Center,
            });

            _popupBox = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                MinSize = new Vector2(220f, 0f),
            };

            _scroll = new ScrollContainer
            {
                Children = { _popupBox },
                ReturnMeasure = true,
                MaxHeight = 245,
            };

            _popup = new Popup
            {
                Children =
                {
                    new PanelContainer
                    {
                        StyleClasses = { OptionButton.StyleClassOptionsBackground },
                    },
                    _scroll,
                },
                StyleClasses = { OptionButton.StyleClassPopup },
            };
            _popup.OnPopupHide += () => _popup.Orphan();
        }

        public void AddItem(string label, string key)
        {
            if (_checkBoxes.ContainsKey(key))
                throw new ArgumentException("An item with the same key already exists.");

            var checkBox = new CheckBox
            {
                Text = label,
                HorizontalExpand = true,
            };
            checkBox.OnPressed += _ => ToggleKey(key, checkBox.Pressed);

            _checkBoxes.Add(key, checkBox);
            _popupBox.AddChild(checkBox);
        }

        public void Clear()
        {
            TogglePopup(false);
            _checkBoxes.Clear();
            _selectedKeys.Clear();
            _popupBox.DisposeAllChildren();
        }

        public void DeselectAll()
        {
            foreach (var checkBox in _checkBoxes.Values)
            {
                checkBox.Pressed = false;
            }

            _selectedKeys.Clear();
        }

        public void SelectKey(string key)
        {
            if (!_checkBoxes.TryGetValue(key, out var checkBox))
                return;

            checkBox.Pressed = true;
            if (!_selectedKeys.Contains(key, StringComparer.OrdinalIgnoreCase))
                _selectedKeys.Add(key);
        }

        private void ToggleKey(string key, bool selected)
        {
            if (selected)
            {
                if (!_selectedKeys.Contains(key, StringComparer.OrdinalIgnoreCase))
                    _selectedKeys.Add(key);
            }
            else
            {
                _selectedKeys.RemoveAll(existing => string.Equals(existing, key, StringComparison.OrdinalIgnoreCase));
            }

            SelectionChanged?.Invoke();
        }

        private void TogglePopup(bool show)
        {
            if (show)
            {
                if (_popup.Parent != null)
                {
                    TogglePopup(false);
                    return;
                }

                if (Root == null)
                    throw new InvalidOperationException("No UI root! We can't pop up!");

                var globalPos = GlobalPosition;
                globalPos.Y += Size.Y + 1;
                _scroll.Measure(Window?.Size ?? Vector2Helpers.Infinity);
                var desired = _scroll.DesiredSize;
                var box = UIBox2.FromDimensions(globalPos, new Vector2(Math.Max(desired.X, Width), desired.Y));
                Root.ModalRoot.AddChild(_popup);
                _popup.Open(box);
                return;
            }

            _popup.Close();
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();
            TogglePopup(false);
        }
    }
}
