using System;
using Content.Client.Localization;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Options.UI.Tabs;

public enum WH40KMetaProgressResetConfirmationStep : byte
{
    FirstWarning,
    FinalWarning
}

[GenerateTypedNameReferences]
public sealed partial class WH40KMetaProgressResetConfirmationWindow : FancyWindow, ILocalizedControl
{
    [Dependency] private  IGameTiming _timing = default!;

    private readonly WH40KMetaProgressResetConfirmationStep _step;
    private readonly TimeSpan _unlockAt;

    public event Action? Confirmed;

    public WH40KMetaProgressResetConfirmationWindow(WH40KMetaProgressResetConfirmationStep step)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _step = step;
        _unlockAt = _timing.CurTime + TimeSpan.FromSeconds(10);

        CancelButton.OnPressed += _ => Close();
        ConfirmButton.OnPressed += _ =>
        {
            if (GetRemainingSeconds() > 0)
                return;

            Confirmed?.Invoke();
            Close();
        };

        Relocalize();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateConfirmButton();
    }

    public void Relocalize()
    {
        Title = Loc.GetString(_step == WH40KMetaProgressResetConfirmationStep.FirstWarning
            ? "ui-options-meta-progression-reset-warning-one-title"
            : "ui-options-meta-progression-reset-warning-two-title");

        BodyLabel.SetMessage(Loc.GetString(_step == WH40KMetaProgressResetConfirmationStep.FirstWarning
            ? "ui-options-meta-progression-reset-warning-one-body"
            : "ui-options-meta-progression-reset-warning-two-body"));

        FooterLabel.SetMessage(Loc.GetString(_step == WH40KMetaProgressResetConfirmationStep.FirstWarning
            ? "ui-options-meta-progression-reset-warning-one-footer"
            : "ui-options-meta-progression-reset-warning-two-footer"));

        CancelButton.Text = Loc.GetString("ui-options-meta-progression-reset-cancel");
        UpdateConfirmButton();
    }

    private void UpdateConfirmButton()
    {
        var remaining = GetRemainingSeconds();
        ConfirmButton.Disabled = remaining > 0;
        ConfirmButton.Text = remaining > 0
            ? Loc.GetString("ui-options-meta-progression-reset-confirm-wait", ("seconds", remaining))
            : Loc.GetString(_step == WH40KMetaProgressResetConfirmationStep.FirstWarning
                ? "ui-options-meta-progression-reset-continue"
                : "ui-options-meta-progression-reset-confirm");
    }

    private int GetRemainingSeconds()
    {
        var remaining = (_unlockAt - _timing.CurTime).TotalSeconds;
        return Math.Max(0, (int) Math.Ceiling(remaining));
    }
}
