using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Lobby.UI.Loadouts;

/// <summary>
/// A collapsible container that holds the list of available weapon mods for a loadout.
/// Mirrors <see cref="SubLoadoutContainer"/> but for the gear-button mod list.
/// Exposes its internal <see cref="BoxContainer"/> via <see cref="Grid"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WeaponModListContainer : PanelContainer
{
    public BoxContainer Grid => ModGridContainer;
}
