using Content.Shared._WH40K.Weapons.Mods;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Loadouts;

/// <summary>
/// A single weapon-mod entry in the mod list shown by the gear button.
/// Shows the mod's sprite preview and a toggle button to select/deselect it for a slot.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WeaponModEntry : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _protoManager = default!;

    private readonly EntityUid? _entity;

    public Button Select => ModSelectButton;

    /// <summary>
    /// WH40K: The mod-host slot this entry installs into (e.g. "optic", "stock").
    /// Used by the parent mod list to reset other entries in the SAME slot when this one
    /// is selected (one mod per slot).
    /// </summary>
    public string SlotId { get; }

    public string? Text
    {
        get => ModSelectButton.Text;
        set => ModSelectButton.Text = value;
    }

    public WeaponModEntry(EntProtoId proto, string slotId)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SlotId = slotId;
        ModSelectButton.Text = GetName(proto);

        if (_protoManager.TryIndex(proto, out var modProto))
        {
            _entity = _entManager.SpawnEntity(proto, MapCoordinates.Nullspace);
            ModSprite.SetEntity(_entity);

            var spriteTooltip = new Tooltip();
            spriteTooltip.SetMessage(FormattedMessage.FromUnformatted(_entManager.GetComponent<MetaDataComponent>(_entity.Value).EntityDescription));
            TooltipSupplier = _ => spriteTooltip;
        }
    }

    private string GetName(EntProtoId proto)
    {
        if (!_protoManager.TryIndex(proto, out var modProto))
            return proto;

        var name = Loc.GetString($"ent-{modProto.ID}");
        return string.IsNullOrEmpty(name) || name == $"ent-{modProto.ID}" ? modProto.ID : name;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (!disposing)
            return;

        _entManager.DeleteEntity(_entity);
    }
}
