- type: job
  id: Enginseer
  name: job-name-enginseer
  description: job-description-enginseer
  playTimeTracker: JobEnginseer
  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
    - !type:DepartmentTimeRequirement
      department: Imperium
      time: 4h
    - !type:RoleTimeRequirement
      role: JobNovice
      time: 2.5h
  startingGear: EnginseerGear
  icon: "JobIconEnginseer"
  supervisors: job-supervisors-ce
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: EnginseerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    back: ClothingBackpackTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    eyes: ClothingEyesHudTechPriest
    outerClothing: ClothingOuterHardsuitTechpriest
    pocket1: WH40KStandardTacticalMapTablet
    id: EnginseerDogTag

- type: chameleonOutfit
  id: EnginseerChameleonOutfit
  job: Enginseer
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    eyes: ClothingEyesHudTechPriest
    outerClothing: ClothingOuterHardsuitTechpriest
