- type: job
  id: Explorator
  name: job-name-explorator
  description: job-description-explorator
  playTimeTracker: JobExplorator
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
    - !type:DepartmentTimeRequirement
      department: Imperium
      time: 4h
    - !type:RoleTimeRequirement
      role: JobNovice
      time: 2.5h
  icon: "JobIconExplorator"
  startingGear: ExploratorGear
  supervisors: job-supervisors-wh40k-mechanicus-priest
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KStrategicPointUpgradeSkill
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External
  - Engineering

- type: startingGear
  id: ExploratorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    back: ClothingBackpackTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    eyes: ClothingEyesHudTechPriest
    outerClothing: ClothingOuterHardsuitTechpriest
    mask: ClothingMaskGasTechPriest
    pocket1: WH40KStandardTacticalMapTablet
    id: ExploratorDogTag

- type: chameleonOutfit
  id: ExploratorChameleonOutfit
  job: Explorator
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    eyes: ClothingEyesHudTechPriest
    outerClothing: ClothingOuterHardsuitTechpriest
    mask: ClothingMaskGasTechPriest

