- type: job
  id: Lexmechanic
  name: job-name-lexmechanic
  description: job-description-lexmechanic
  playTimeTracker: JobLexmechanic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Imperium
      time: 6h
    - !type:RoleTimeRequirement
      role: JobNovice
      time: 2.5h
  startingGear: LexmechanicGear
  icon: "JobIconLexmechanic"
  supervisors: job-supervisors-ce
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  - Research
  - ResearchDirector

- type: startingGear
  id: LexmechanicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    back: ClothingBackpackTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    eyes: ClothingEyesHudTechPriest
    mask: ClothingMaskGasTechPriest
    id: PassengerPDA

- type: chameleonOutfit
  id: LexmechanicChameleonOutfit
  job: Lexmechanic
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    eyes: ClothingEyesHudTechPriest
    mask: ClothingMaskGasTechPriest
