- type: job
  id: Lexmechanic
  name: job-name-lexmechanic
  description: job-description-lexmechanic
  displayWeight: 80
  playTimeTracker: JobLexmechanic
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: LexmechanicGear
  special:
  - !type:AddComponentSpecial
    components:
      - type: IntrinsicRadioTransmitter
        channels:
        - Binary
      - type: ActiveRadio
        channels:
        - Binary
      - type: IntrinsicRadioReceiver
  icon: "JobIconLexmechanic"
  supervisors: job-supervisors-wh40k-mechanicus-priest
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  - Research
  - ResearchDirector

- type: startingGear
  id: LexmechanicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    outerClothing: ClothingOuterHardsuitTechpriestUnremoveadble
    ears: ClothingHeadsetVoxBackpackImperium
    pocket1: WH40KStandardTacticalMapTablet
    id: LexmechanicDogTag

- type: chameleonOutfit
  id: LexmechanicChameleonOutfit
  job: Lexmechanic
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    eyes: ClothingEyesHudTechPriest

