- type: job
  id: Novice
  name: job-name-novice
  description: job-description-novice
  playTimeTracker: JobNovice
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: NoviceGear
  icon: "JobIconNovice"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: NoviceGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    back: ClothingBackpackTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    pocket1: WH40KStandardTacticalMapTablet
    id: NoviceDogTag

- type: chameleonOutfit
  id: NoviceChameleonOutfit
  job: Novice
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
