using Content.Client.UserInterface.Systems.Chat.Controls;
using Content.Client.UserInterface.Systems.Chat.RichText;
using Content.Shared.Chat;
using Content.Shared.Input;
using Content.Client.Localization;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Input;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client.UserInterface.Systems.Chat.Widgets;

[GenerateTypedNameReferences]
[Virtual]
public partial class ChatBox : UIWidget, ILocalizedControl
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly ILogManager _log = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly ISawmill _sawmill;
    private readonly ChatUIController _controller;
    private readonly Dictionary<uint, int> _messageEntryIndices = new();
    private bool _warnedMessageUpdateFallback;
    private bool _suppressEmojiAliasRewrite;

    public bool Main { get; set; }

    public ChatSelectChannel SelectedChannel => ChatInput.ChannelSelector.SelectedChannel;

    public ChatBox()
    {
        RobustXamlLoader.Load(this);
        _sawmill = _log.GetSawmill("chat");

        ChatInput.Input.OnTextEntered += OnTextEntered;
        ChatInput.Input.OnKeyBindDown += OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged += OnTextChanged;
        ChatInput.Input.OnFocusEnter += OnFocusEnter;
        ChatInput.Input.OnFocusExit += OnFocusExit;
        ChatInput.ChannelSelector.OnChannelSelect += OnChannelSelect;
        ChatInput.FilterButton.Popup.OnChannelFilter += OnChannelFilter;
        ChatInput.FilterButton.Popup.OnNewHighlights += OnNewHighlights;
        _controller = UserInterfaceManager.GetUIController<ChatUIController>();
        _controller.MessageAdded += OnMessageAdded;
        _controller.HighlightsUpdated += OnHighlightsUpdated;
        _controller.RegisterChat(this);
    }

    private void OnTextEntered(LineEditEventArgs args)
    {
        _controller.SendMessage(this, SelectedChannel);
    }

    private void OnMessageAdded(ChatMessage msg)
    {
        _sawmill.Debug($"{msg.Channel}: {msg.Message}");
        if (!ChatInput.FilterButton.Popup.IsActive(msg.Channel))
        {
            return;
        }

        if (msg is { Read: false, AudioPath: { } audioPath })
            _entManager.System<AudioSystem>().PlayGlobal(new SoundPathSpecifier(audioPath), Filter.Local(), false, AudioParams.Default.WithVolume(msg.AudioVolume));

        msg.Read = true;

        var color = msg.MessageColorOverride ?? msg.Channel.TextColor();
        var wrappedMessage = _controller.GetChatDisplayMessage(msg);

        AddLine(wrappedMessage, color, _controller.IsEmojiAllowed(msg.Channel), msg.ServerMessageId);
    }

    private void OnHighlightsUpdated(string highlights)
    {
        ChatInput.FilterButton.Popup.UpdateHighlights(highlights);
    }

    private void OnChannelSelect(ChatSelectChannel channel)
    {
        _controller.UpdateSelectedChannel(this);
    }

    public void Repopulate()
    {
        var scrollBar = GetContentsScrollBar();
        var wasAtEnd = scrollBar?.IsAtEnd ?? true;
        var previousScroll = scrollBar?.Value ?? 0f;

        ClearDisplayedMessages();

        foreach (var message in _controller.History)
        {
            OnMessageAdded(message.Item2);
        }

        if (scrollBar == null)
            return;

        if (wasAtEnd)
            scrollBar.Value = scrollBar.MaxValue;
        else
            scrollBar.Value = previousScroll;
    }

    public void Relocalize()
    {
        ChatInput.RefreshLocalization();
        _controller.UpdateSelectedChannel(this);
    }

    private void OnChannelFilter(ChatChannel channel, bool active)
    {
        ClearDisplayedMessages();

        foreach (var message in _controller.History)
        {
            OnMessageAdded(message.Item2);
        }

        if (active)
        {
            _controller.ClearUnfilteredUnreads(channel);
        }
    }

    private void OnNewHighlights(string highlighs)
    {
        _controller.UpdateHighlights(highlighs);
    }

    public void AddLine(string message, Color color, bool allowAliasMarkup, uint? serverMessageId = null)
    {
        if (serverMessageId is { } messageId)
            _messageEntryIndices[messageId] = Contents.EntryCount;

        Contents.AddMessage(ChatEmojiRichText.BuildChatLine(message, color, allowAliasMarkup, _prototypeManager), tagsAllowed: null);
    }

    public bool TryUpdateMessage(ChatMessage msg)
    {
        if (msg.ServerMessageId is not { } messageId)
            return false;

        if (!_messageEntryIndices.TryGetValue(messageId, out var entryIndex))
            return false;

        var color = msg.MessageColorOverride ?? msg.Channel.TextColor();
        var wrappedMessage = _controller.GetChatDisplayMessage(msg);

        if (!TryRebuildTailFromHistory(entryIndex, messageId))
        {
            if (!_warnedMessageUpdateFallback)
            {
                _warnedMessageUpdateFallback = true;
                _sawmill.Warning("Falling back to full chat repopulation for message updates because tail rebuild failed.");
            }

            Repopulate();
        }

        return true;
    }

    private bool TryRebuildTailFromHistory(int entryIndex, uint messageId)
    {
        var historyIndex = FindHistoryIndex(messageId);
        if (historyIndex == null)
            return false;

        var scrollBar = GetContentsScrollBar();
        var wasAtEnd = scrollBar?.IsAtEnd ?? true;
        var previousScroll = scrollBar?.Value ?? 0f;

        RemoveDisplayedTail(entryIndex);

        for (var i = historyIndex.Value; i < _controller.History.Count; i++)
        {
            OnMessageAdded(_controller.History[i].Item2);
        }

        if (scrollBar == null)
            return true;

        if (wasAtEnd)
            scrollBar.Value = scrollBar.MaxValue;
        else
            scrollBar.Value = previousScroll;

        return true;
    }

    private int? FindHistoryIndex(uint messageId)
    {
        for (var i = 0; i < _controller.History.Count; i++)
        {
            if (_controller.History[i].Item2.ServerMessageId == messageId)
                return i;
        }

        return null;
    }

    private void RemoveDisplayedTail(int entryIndex)
    {
        for (var i = Contents.EntryCount - 1; i >= entryIndex; i--)
        {
            Contents.RemoveEntry(new Index(i));
        }

        var staleIds = new List<uint>();
        foreach (var (messageId, index) in _messageEntryIndices)
        {
            if (index >= entryIndex)
                staleIds.Add(messageId);
        }

        foreach (var staleId in staleIds)
        {
            _messageEntryIndices.Remove(staleId);
        }
    }

    private void ClearDisplayedMessages()
    {
        _messageEntryIndices.Clear();
        Contents.Clear();
    }

    private VScrollBar? GetContentsScrollBar()
    {
        for (var i = 0; i < Contents.ChildCount; i++)
        {
            if (Contents.GetChild(i) is VScrollBar scrollBar)
                return scrollBar;
        }

        return null;
    }

    public void Focus(ChatSelectChannel? channel = null)
    {
        var input = ChatInput.Input;
        var selectStart = Index.End;

        if (channel != null)
            ChatInput.ChannelSelector.Select(channel.Value);

        input.IgnoreNext = true;
        input.GrabKeyboardFocus();

        input.CursorPosition = input.Text.Length;
        input.SelectionStart = selectStart.GetOffset(input.Text.Length);
    }

    public void CycleChatChannel(bool forward)
    {
        var idx = Array.IndexOf(ChannelSelectorPopup.ChannelSelectorOrder, SelectedChannel);
        do
        {
            // go over every channel until we find one we can actually select.
            idx += forward ? 1 : -1;
            idx = MathHelper.Mod(idx, ChannelSelectorPopup.ChannelSelectorOrder.Length);
        } while ((_controller.SelectableChannels & ChannelSelectorPopup.ChannelSelectorOrder[idx]) == 0);

        SafelySelectChannel(ChannelSelectorPopup.ChannelSelectorOrder[idx]);
    }

    public void SafelySelectChannel(ChatSelectChannel toSelect)
    {
        toSelect = _controller.MapLocalIfGhost(toSelect);
        if ((_controller.SelectableChannels & toSelect) == 0)
            return;

        ChatInput.ChannelSelector.Select(toSelect);
    }

    private void OnInputKeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.TextReleaseFocus)
        {
            ChatInput.Input.ReleaseKeyboardFocus();
            ChatInput.Input.Clear();
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelForward)
        {
            CycleChatChannel(true);
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelBackward)
        {
            CycleChatChannel(false);
            args.Handle();
        }
    }

    private void OnTextChanged(LineEditEventArgs args)
    {
        if (!_suppressEmojiAliasRewrite)
        {
            var effectiveChannel = _controller.ResolveEffectiveInputChannel(this);
            if (_controller.IsEmojiAllowed(effectiveChannel))
            {
                var input = ChatInput.Input;
                var rewritten = ChatEmoji.ReplaceAliases(input.Text, input.CursorPosition, _prototypeManager, out var newCursorPosition);
                if (!string.Equals(rewritten, input.Text, StringComparison.Ordinal))
                {
                    _suppressEmojiAliasRewrite = true;
                    input.SetText(rewritten);
                    input.CursorPosition = newCursorPosition;
                    input.SelectionStart = newCursorPosition;
                    _suppressEmojiAliasRewrite = false;
                }
            }
        }

        // Update channel select button to correct channel if we have a prefix.
        _controller.UpdateSelectedChannel(this);

        // Warn typing indicator about change
        _controller.NotifyChatTextChange();
    }

    private void OnFocusEnter(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        _controller.NotifyChatFocus(true);
    }

    private void OnFocusExit(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        _controller.NotifyChatFocus(false);
    }

    [Obsolete]
    protected override void Dispose(bool disposing)
    {
#pragma warning disable CS0618
        base.Dispose(disposing);
#pragma warning restore CS0618

        if (!disposing) return;
        _controller.UnregisterChat(this);
        ChatInput.Input.OnTextEntered -= OnTextEntered;
        ChatInput.Input.OnKeyBindDown -= OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged -= OnTextChanged;
        ChatInput.ChannelSelector.OnChannelSelect -= OnChannelSelect;
    }
}
