using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Client.Viewport;
using Content.Client._WH40K.Interface;
using Content.Shared.DeviceNetwork;
using Content.Shared.SurveillanceCamera;
using Content.Shared.SurveillanceCamera.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Graphics;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client.SurveillanceCamera.UI;

[GenerateTypedNameReferences]
public sealed partial class SurveillanceCameraMonitorWindow : FancyWindow
{
    private static readonly ProtoId<ShaderPrototype> CameraStaticShader = "CameraStatic";

    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public event Action<string, string?>? CameraSelected;
    public event Action<string>? SubnetOpened;
    public event Action? CameraRefresh;
    public event Action? SubnetRefresh;
    public event Action? CameraSwitchTimer;
    public event Action? CameraDisconnect;

    private readonly FixedEye _defaultEye = new();
    private readonly Dictionary<string, int> _subnetMap = new();
    private readonly List<CameraRosterListData> _allCameraEntries = new();
    private readonly Dictionary<string, string> _cameraNames = new();

    private SurveillanceCameraMonitorTheme _theme = SurveillanceCameraMonitorTheme.Default;
    private string _titleText = string.Empty;
    private string _subtitleText = string.Empty;
    private string _currentAddress = string.Empty;
    private string _currentSubnet = string.Empty;
    private EntityUid? _mapUid;
    private bool _isSwitching;
    private int _visibleCameraCount;
    private CameraFeedState? _lastStatusFlashState;
    private CameraFeedState? _lastFeedFlashState;
    private string? _lastFeedFlashAddress;
    private string? _lastFeedFlashSubnet;

    private MonitorViewMode _viewMode = MonitorViewMode.Roster;

    public SurveillanceCameraMonitorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var texture = _resourceCache.GetTexture("/Textures/Interface/Nano/square_black.png");
        var shader = _prototypeManager.Index(CameraStaticShader).Instance().Duplicate();

        CameraView.ViewportSize = new Vector2i(720, 560);
        CameraView.Eye = _defaultEye;
        CameraViewBackground.Stretch = TextureRect.StretchMode.Scale;
        CameraViewBackground.Texture = texture;
        CameraViewBackground.ShaderOverride = shader;

        ViewModeTabs.TabsVisible = false;
        ViewModeTabs.CurrentTab = 0;

        CameraSearchBar.OnTextChanged += _ => ApplyCameraFilter();
        CameraList.ItemPressed += OnCameraListPressed;
        CameraList.GenerateItem += GenerateCameraButton;

        SubnetSelector.OnItemSelected += args =>
        {
            var subnet = args.Button.GetItemMetadata(args.Id) as string;
            if (!string.IsNullOrWhiteSpace(subnet))
                SubnetOpened?.Invoke(subnet);
        };

        SubnetRefreshButton.OnPressed += _ => SubnetRefresh?.Invoke();
        CameraRefreshButton.OnPressed += _ => CameraRefresh?.Invoke();
        CameraDisconnectButton.OnPressed += _ => CameraDisconnect?.Invoke();

        RosterTabButton.OnPressed += _ => SetViewMode(MonitorViewMode.Roster);
        MapTabButton.OnPressed += _ => SetViewMode(MonitorViewMode.Map);

        CameraMap.EnableCameraSelection = true;
        CameraMap.CameraSelected += OnCameraMapSelected;

        ApplyTheme();
        SetViewMode(MonitorViewMode.Roster);
        RefreshAllReadouts();
    }

    public void SetEntity(EntityUid uid)
    {
        var metaData = _entityManager.GetComponent<MetaDataComponent>(uid);
        _titleText = metaData.EntityName;
        _subtitleText = string.IsNullOrWhiteSpace(metaData.EntityDescription)
            ? Loc.GetString("surveillance-camera-monitor-ui-header-subtitle-fallback")
            : metaData.EntityDescription;
        _theme = SurveillanceCameraMonitorStyles.ResolveTheme(metaData.EntityPrototype?.ID);

        ApplyTheme();
        RefreshAllReadouts();
    }

    public void UpdateState(IEye? eye, HashSet<string> subnets, string activeAddress, string activeSubnet, Dictionary<string, string> cameras)
    {
        _currentAddress = activeAddress;
        _currentSubnet = activeSubnet;

        CameraMap.SetActiveCameraAddress(activeAddress);
        CameraMap.SetAvailableSubnets(subnets);

        RebuildSubnetSelector(subnets, activeSubnet);

        if (subnets.Count > 0 && string.IsNullOrEmpty(activeSubnet))
        {
            PopulateCameraEntries(Array.Empty<KeyValuePair<string, string>>());
            SetCameraView(eye);
            RefreshAllReadouts();
            SubnetOpened?.Invoke(subnets.OrderBy(ResolveSubnetDisplayName).First());
            return;
        }

        PopulateCameraEntries(cameras);
        SetCameraView(eye);
        RefreshAllReadouts();
    }

    public void OnSwitchTimerComplete()
    {
        _isSwitching = false;
        CameraView.Visible = CameraView.Eye != _defaultEye;
        CameraViewBackground.Visible = CameraView.Eye == _defaultEye;
        RefreshAllReadouts();
    }

    public void SetMap(EntityUid mapUid)
    {
        CameraMap.MapUid = _mapUid = mapUid;
    }

    private void OnCameraListPressed(BaseButton.ButtonEventArgs _, ListData data)
    {
        if (data is not CameraRosterListData entry)
            return;

        CameraSelected?.Invoke(entry.Address, null);
    }

    private void GenerateCameraButton(ListData data, ListContainerButton button)
    {
        if (data is not CameraRosterListData entry)
            return;

        var control = new SurveillanceCameraMonitorEntry();
        control.ApplyState(entry.CameraName, entry.Address, entry.IsCurrent, _theme);

        button.AddChild(control);
        button.MinSize = new Vector2(0f, 68f);
        var normalStyle = SurveillanceCameraMonitorStyles.CreatePanelStyle(
            entry.IsCurrent ? _theme.SurfaceBackground : _theme.PanelAltBackground,
            entry.IsCurrent ? _theme.Accent.WithAlpha(0.82f) : _theme.BorderColor,
            0);
        var hoverStyle = SurveillanceCameraMonitorStyles.CreatePanelStyle(
            _theme.SurfaceBackground,
            _theme.Accent.WithAlpha(0.88f),
            0);
        button.StyleBoxOverride = normalStyle;
        button.ToolTip = $"{entry.CameraName}\n{entry.Address}";
        button.OnMouseEntered += _ =>
        {
            button.StyleBoxOverride = hoverStyle;
            WH40KUiChrome.PlayHoverFlash(control, "hover-flash");
        };
        button.OnMouseExited += _ => button.StyleBoxOverride = normalStyle;
    }

    private void RebuildSubnetSelector(HashSet<string> subnets, string activeSubnet)
    {
        if (subnets.Count == 0)
        {
            if (!SubnetSelector.Disabled || SubnetSelector.ItemCount != 1)
            {
                SubnetSelector.Clear();
                SubnetSelector.AddItem(Loc.GetString("surveillance-camera-monitor-ui-no-subnets"), 0);
                SubnetSelector.Disabled = true;
            }

            _subnetMap.Clear();
            return;
        }

        var orderedSubnets = subnets.OrderBy(ResolveSubnetDisplayName).ToList();
        var knownSubnetsMatch = _subnetMap.Count == orderedSubnets.Count &&
                                new HashSet<string>(_subnetMap.Keys).SetEquals(orderedSubnets);

        if (SubnetSelector.Disabled || !knownSubnetsMatch)
        {
            SubnetSelector.Clear();
            SubnetSelector.Disabled = false;
            _subnetMap.Clear();

            foreach (var subnet in orderedSubnets)
            {
                var id = AddSubnet(subnet);
                _subnetMap[subnet] = id;
            }
        }

        if (!string.IsNullOrEmpty(activeSubnet) && _subnetMap.TryGetValue(activeSubnet, out var subnetId))
            SubnetSelector.SelectId(subnetId);
    }

    private int AddSubnet(string subnet)
    {
        var id = _subnetMap.Count;
        SubnetSelector.AddItem(ResolveSubnetDisplayName(subnet), id);
        SubnetSelector.SetItemMetadata(id, subnet);
        return id;
    }

    private void PopulateCameraEntries(IEnumerable<KeyValuePair<string, string>> cameras)
    {
        _allCameraEntries.Clear();
        _cameraNames.Clear();

        foreach (var (address, name) in cameras
                     .OrderBy(pair => pair.Value, StringComparer.CurrentCultureIgnoreCase)
                     .ThenBy(pair => pair.Key, StringComparer.CurrentCultureIgnoreCase))
        {
            var displayName = string.IsNullOrWhiteSpace(name)
                ? address
                : name;

            _cameraNames[address] = displayName;
            _allCameraEntries.Add(new CameraRosterListData(address)
            {
                CameraName = displayName,
                SearchText = $"{displayName} {address}",
                IsCurrent = address == _currentAddress,
                SortIndex = _allCameraEntries.Count,
            });
        }

        ApplyCameraFilter();
    }

    private void ApplyCameraFilter()
    {
        var search = CameraSearchBar.Text.Trim();
        var filtered = string.IsNullOrWhiteSpace(search)
            ? _allCameraEntries
            : _allCameraEntries
                .Where(entry => entry.SearchText.Contains(search, StringComparison.CurrentCultureIgnoreCase))
                .ToList();

        _visibleCameraCount = filtered.Count;
        CameraList.PopulateList(filtered.Cast<ListData>().ToList());

        CameraListEmptyLabel.Visible = filtered.Count == 0;
        CameraList.Visible = filtered.Count > 0;
        CameraListEmptyLabel.Text = Loc.GetString(string.IsNullOrWhiteSpace(search)
            ? "surveillance-camera-monitor-ui-roster-empty"
            : "surveillance-camera-monitor-ui-roster-empty-search");

        CameraListSubtitleLabel.SetMessage(
            Loc.GetString(
                "surveillance-camera-monitor-ui-roster-subtitle",
                ("visible", _visibleCameraCount),
                ("total", _allCameraEntries.Count)),
            defaultColor: _theme.SecondaryText);

        VisibleValueLabel.Text = Loc.GetString(
            "surveillance-camera-monitor-ui-feed-visible-value",
            ("visible", _visibleCameraCount),
            ("total", _allCameraEntries.Count));

        RefreshAllReadouts();
    }

    private void SetCameraView(IEye? eye)
    {
        var eyeChanged = eye != CameraView.Eye || CameraView.Eye == null;
        CameraView.Eye = eye ?? _defaultEye;
        CameraDisconnectButton.Disabled = eye == null;

        if (eye == null)
        {
            _isSwitching = false;
            CameraView.Visible = false;
            CameraViewBackground.Visible = true;
            return;
        }

        if (eyeChanged)
        {
            _isSwitching = true;
            CameraView.Visible = false;
            CameraViewBackground.Visible = true;
            CameraSwitchTimer?.Invoke();
            return;
        }

        CameraView.Visible = !_isSwitching;
        CameraViewBackground.Visible = _isSwitching;
    }

    private void SetViewMode(MonitorViewMode viewMode)
    {
        _viewMode = viewMode;
        ViewModeTabs.CurrentTab = (int) viewMode;

        SurveillanceCameraMonitorStyles.ApplyButtonTheme(
            RosterTabButton,
            viewMode == MonitorViewMode.Roster
                ? SurveillanceCameraMonitorStyles.CreatePrimaryButtonStyle(_theme)
                : SurveillanceCameraMonitorStyles.CreateSecondaryButtonStyle(_theme),
            _theme.PrimaryText);
        SurveillanceCameraMonitorStyles.ApplyButtonTheme(
            MapTabButton,
            viewMode == MonitorViewMode.Map
                ? SurveillanceCameraMonitorStyles.CreatePrimaryButtonStyle(_theme)
                : SurveillanceCameraMonitorStyles.CreateSecondaryButtonStyle(_theme),
            _theme.PrimaryText);

        RefreshFooter();
    }

    private void ApplyTheme()
    {
        Title = string.IsNullOrWhiteSpace(_titleText)
            ? Loc.GetString("surveillance-camera-monitor-ui-window")
            : _titleText;
        HeaderTitleLabel.Text = WH40KUiChrome.DecorateTitle(WH40KUiChrome.Eye, Title);
        StatusPanelTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(StatusPanelTitleLabel.Text, WH40KUiChrome.DiamondNested);
        SubnetCardLabel.Text = WH40KUiChrome.DecorateIfMissing(SubnetCardLabel.Text, WH40KUiChrome.Diamond);
        CameraCardLabel.Text = WH40KUiChrome.DecorateIfMissing(CameraCardLabel.Text, WH40KUiChrome.DiamondOutline);
        ActiveSubnetCardLabel.Text = WH40KUiChrome.DecorateIfMissing(ActiveSubnetCardLabel.Text, WH40KUiChrome.Cog);
        FeedCardLabel.Text = WH40KUiChrome.DecorateIfMissing(FeedCardLabel.Text, WH40KUiChrome.Blade);
        NetworkPanelTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(NetworkPanelTitleLabel.Text, WH40KUiChrome.Cog);
        ModePanelTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(ModePanelTitleLabel.Text, WH40KUiChrome.DiamondNested);
        CameraListTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(CameraListTitleLabel.Text, WH40KUiChrome.Diamond);
        MapTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(MapTitleLabel.Text, WH40KUiChrome.Eye);
        FeedTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(FeedTitleLabel.Text, WH40KUiChrome.Blade);
        SetWrappedText(
            HeaderSubtitleLabel,
            string.IsNullOrWhiteSpace(_subtitleText)
                ? Loc.GetString("surveillance-camera-monitor-ui-header-subtitle-fallback")
                : _subtitleText,
            _theme.SecondaryText);
        SetWrappedText(NetworkPanelSubtitleLabel, Loc.GetString("surveillance-camera-monitor-ui-network-subtitle"), _theme.SecondaryText);
        SetWrappedText(MapSubtitleLabel, Loc.GetString("surveillance-camera-monitor-ui-map-subtitle"), _theme.SecondaryText);
        SetWrappedText(FeedSubtitleLabel, Loc.GetString("surveillance-camera-monitor-ui-feed-subtitle-offline"), _theme.SecondaryText);

        RootFrame.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.WindowBackground, _theme.BorderStrongColor, 0);
        HeaderPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelBackground, _theme.BorderStrongColor, 0);
        StatusPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);
        SubnetCard.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);
        CameraCard.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);
        ActiveSubnetCard.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);
        FeedCard.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);

        CommandPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelBackground, _theme.BorderStrongColor, 0);
        NetworkPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);
        ModePanel.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);
        SearchPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);

        CameraListPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelBackground, _theme.BorderStrongColor, 0);
        CameraListHeaderPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreateEdgePanelStyle(
            _theme.HeaderBackground,
            _theme.BorderStrongColor,
            new Thickness(0f, 0f, 0f, 1f),
            0);
        CameraListBodyPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreateEdgePanelStyle(
            _theme.PanelBackground,
            Color.Transparent,
            new Thickness(0f),
            0);

        MapPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelBackground, _theme.BorderStrongColor, 0);
        MapHeaderPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreateEdgePanelStyle(
            _theme.HeaderBackground,
            _theme.BorderStrongColor,
            new Thickness(0f, 0f, 0f, 1f),
            0);
        MapBodyPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreateEdgePanelStyle(
            _theme.PanelBackground,
            Color.Transparent,
            new Thickness(0f),
            0);
        LegendPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);

        FeedPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelBackground, _theme.BorderStrongColor, 0);
        FeedHeaderPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreateEdgePanelStyle(
            _theme.HeaderBackground,
            _theme.BorderStrongColor,
            new Thickness(0f, 0f, 0f, 1f),
            0);
        FeedViewportPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.FeedBackground, _theme.BorderStrongColor, 0);

        SubnetRoutingBadge.PanelOverride = SurveillanceCameraMonitorStyles.CreateBadgeStyle(_theme.PanelBackground, _theme.BorderColor, 10, 6);
        VisibleBadge.PanelOverride = SurveillanceCameraMonitorStyles.CreateBadgeStyle(_theme.PanelBackground, _theme.BorderColor, 10, 6);
        LinkBadge.PanelOverride = SurveillanceCameraMonitorStyles.CreateBadgeStyle(_theme.PanelAltBackground, _theme.BorderColor, 10, 6);
        AddressBadge.PanelOverride = SurveillanceCameraMonitorStyles.CreateBadgeStyle(_theme.PanelAltBackground, _theme.BorderColor, 10, 6);
        FeedSubnetBadge.PanelOverride = SurveillanceCameraMonitorStyles.CreateBadgeStyle(_theme.PanelAltBackground, _theme.BorderColor, 10, 6);

        LegendActivePanel.PanelOverride = SurveillanceCameraMonitorStyles.CreateBadgeStyle(_theme.PanelBackground, _theme.BorderColor, 8, 6);
        LegendSelectedPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreateBadgeStyle(_theme.PanelBackground, _theme.BorderColor, 8, 6);
        LegendInactivePanel.PanelOverride = SurveillanceCameraMonitorStyles.CreateBadgeStyle(_theme.PanelBackground, _theme.BorderColor, 8, 6);
        LegendInvalidPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreateBadgeStyle(_theme.PanelBackground, _theme.BorderColor, 8, 6);

        CameraSearchBar.StyleBoxOverride = SurveillanceCameraMonitorStyles.CreateInputStyle(_theme);
        SurveillanceCameraMonitorStyles.ApplyOptionButtonTheme(SubnetSelector, _theme);
        SurveillanceCameraMonitorStyles.ApplyButtonTheme(SubnetRefreshButton, SurveillanceCameraMonitorStyles.CreateSecondaryButtonStyle(_theme), _theme.PrimaryText);
        SurveillanceCameraMonitorStyles.ApplyButtonTheme(CameraRefreshButton, SurveillanceCameraMonitorStyles.CreatePrimaryButtonStyle(_theme), _theme.PrimaryText);
        SurveillanceCameraMonitorStyles.ApplyButtonTheme(CameraDisconnectButton, SurveillanceCameraMonitorStyles.CreateDangerButtonStyle(_theme), _theme.PrimaryText);

        HeaderTitleLabel.FontColorOverride = _theme.Accent;
        StatusPanelTitleLabel.FontColorOverride = _theme.LabelText;
        NetworkPanelTitleLabel.FontColorOverride = _theme.Accent;
        ModePanelTitleLabel.FontColorOverride = _theme.Accent;
        CameraListTitleLabel.FontColorOverride = _theme.Accent;
        MapTitleLabel.FontColorOverride = _theme.Accent;
        FeedTitleLabel.FontColorOverride = _theme.Accent;
        FooterLabel.SetMessage(FooterLabel.Text ?? string.Empty, defaultColor: _theme.SecondaryText);

        foreach (var label in new[]
                 {
                     SubnetCardLabel,
                     CameraCardLabel,
                     ActiveSubnetCardLabel,
                     FeedCardLabel,
                     RoutingKeyLabel,
                     VisibleKeyLabel,
                     LinkKeyLabel,
                     AddressKeyLabel,
                     FeedSubnetKeyLabel
                 })
        {
            label.FontColorOverride = _theme.LabelText;
        }

        foreach (var label in new[]
                 {
                     SubnetValueLabel,
                     CameraValueLabel,
                     ActiveSubnetValueLabel,
                     FeedValueLabel,
                     RoutingValueLabel,
                     VisibleValueLabel,
                     LinkValueLabel,
                     AddressValueLabel,
                     FeedSubnetValueLabel,
                     StatusValueLabel
                 })
        {
            label.FontColorOverride = _theme.PrimaryText;
        }

        foreach (var label in new[]
                 {
                     LegendActiveLabel,
                     LegendSelectedLabel,
                     LegendInactiveLabel,
                     LegendInvalidLabel
                 })
        {
            label.FontColorOverride = _theme.PrimaryText;
        }

        CameraListEmptyLabel.FontColorOverride = _theme.SecondaryText;
        WH40KUiChrome.StartLoopingPulse(HeaderTitleLabel, "title-pulse", new Color(0.8f, 0.8f, 0.8f, 1f), Color.White, 3.1f);
        WH40KUiChrome.StartLoopingPulse(FeedHeaderPanel, "feed-pulse", new Color(0.72f, 0.72f, 0.72f, 1f), Color.White, 4.3f);
    }

    private void RefreshAllReadouts()
    {
        RefreshStatusPanel();
        RefreshSummaryCards();
        RefreshFeedPane();
        RefreshFooter();
    }

    private void RefreshStatusPanel()
    {
        var state = GetFeedState();
        var color = GetFeedStateColor(state);
        var changed = _lastStatusFlashState != state;
        _lastStatusFlashState = state;

        StatusPanel.PanelOverride = SurveillanceCameraMonitorStyles.CreatePanelStyle(_theme.PanelAltBackground, color.WithAlpha(0.82f), 0);
        StatusValueLabel.Text = Loc.GetString(GetFeedStateLocKey(state));
        StatusValueLabel.FontColorOverride = color;
        SetWrappedText(StatusHintLabel, Loc.GetString(GetFeedStateHintLocKey(state)), _theme.SecondaryText);
        if (changed)
            WH40KUiChrome.PlayHoverFlash(StatusPanel, "status-flash", new Color(0.86f, 0.86f, 0.9f, 1f), 0.18f);
    }

    private void RefreshSummaryCards()
    {
        SubnetValueLabel.Text = _subnetMap.Count.ToString();
        CameraValueLabel.Text = _allCameraEntries.Count.ToString();
        ActiveSubnetValueLabel.Text = string.IsNullOrWhiteSpace(_currentSubnet)
            ? Loc.GetString("surveillance-camera-monitor-ui-active-subnet-none")
            : ResolveSubnetDisplayName(_currentSubnet);

        var stateLoc = Loc.GetString(GetFeedStateLocKey(GetFeedState()));
        FeedValueLabel.Text = stateLoc;
        FeedValueLabel.FontColorOverride = GetFeedStateColor(GetFeedState());

        RoutingValueLabel.Text = string.IsNullOrWhiteSpace(_currentSubnet)
            ? Loc.GetString("surveillance-camera-monitor-ui-active-subnet-none")
            : ResolveSubnetDisplayName(_currentSubnet);
    }

    private void RefreshFeedPane()
    {
        var state = GetFeedState();
        var stateColor = GetFeedStateColor(state);
        var hasCamera = !string.IsNullOrWhiteSpace(_currentAddress);
        var cameraName = ResolveActiveCameraName();
        var changed = _lastFeedFlashState != state ||
                      !string.Equals(_lastFeedFlashAddress, _currentAddress, StringComparison.Ordinal) ||
                      !string.Equals(_lastFeedFlashSubnet, _currentSubnet, StringComparison.Ordinal);

        _lastFeedFlashState = state;
        _lastFeedFlashAddress = _currentAddress;
        _lastFeedFlashSubnet = _currentSubnet;

        FeedTitleLabel.Text = hasCamera
            ? WH40KUiChrome.DecorateIfMissing(Loc.GetString("surveillance-camera-monitor-ui-feed-title"), WH40KUiChrome.Blade)
            : WH40KUiChrome.DecorateIfMissing(Loc.GetString("surveillance-camera-monitor-ui-feed-title-offline"), WH40KUiChrome.Blade);
        FeedTitleLabel.FontColorOverride = _theme.Accent;

        SetWrappedText(
            FeedSubtitleLabel,
            hasCamera
                ? Loc.GetString("surveillance-camera-monitor-ui-feed-subtitle", ("camera", cameraName))
                : Loc.GetString("surveillance-camera-monitor-ui-feed-subtitle-offline"),
            hasCamera ? _theme.PrimaryText : _theme.SecondaryText);

        LinkValueLabel.Text = Loc.GetString(GetFeedStateLocKey(state));
        LinkValueLabel.FontColorOverride = stateColor;
        AddressValueLabel.Text = hasCamera
            ? _currentAddress
            : Loc.GetString("surveillance-camera-monitor-ui-feed-address-none");
        FeedSubnetValueLabel.Text = string.IsNullOrWhiteSpace(_currentSubnet)
            ? Loc.GetString("surveillance-camera-monitor-ui-active-subnet-none")
            : ResolveSubnetDisplayName(_currentSubnet);
        if (changed)
            WH40KUiChrome.PlayHoverFlash(FeedHeaderPanel, "feed-flash", new Color(0.86f, 0.86f, 0.9f, 1f), 0.18f);
    }

    private void RefreshFooter()
    {
        var footerKey = GetFeedState() == CameraFeedState.Disconnected
            ? "surveillance-camera-monitor-ui-footer-offline"
            : _viewMode == MonitorViewMode.Map
                ? "surveillance-camera-monitor-ui-footer-map"
                : "surveillance-camera-monitor-ui-footer-roster";

        SetWrappedText(FooterLabel, Loc.GetString(footerKey), _theme.SecondaryText);
    }

    private CameraFeedState GetFeedState()
    {
        if (CameraView.Eye == _defaultEye)
            return CameraFeedState.Disconnected;

        return _isSwitching
            ? CameraFeedState.Connecting
            : CameraFeedState.Live;
    }

    private Color GetFeedStateColor(CameraFeedState state)
    {
        return state switch
        {
            CameraFeedState.Live => _theme.SuccessAccent,
            CameraFeedState.Connecting => _theme.WarningAccent,
            _ => _theme.DangerAccent,
        };
    }

    private string ResolveActiveCameraName()
    {
        if (string.IsNullOrWhiteSpace(_currentAddress))
            return Loc.GetString("surveillance-camera-monitor-ui-feed-subtitle-offline");

        return _cameraNames.TryGetValue(_currentAddress, out var cameraName)
            ? cameraName
            : _currentAddress;
    }

    private string ResolveSubnetDisplayName(string subnet)
    {
        if (_prototypeManager.TryIndex<DeviceFrequencyPrototype>(subnet, out var frequency) &&
            frequency.Name != null)
        {
            return Loc.GetString(frequency.Name);
        }

        return subnet;
    }

    private static string GetFeedStateLocKey(CameraFeedState state)
    {
        return state switch
        {
            CameraFeedState.Live => "surveillance-camera-monitor-ui-status-ready-card",
            CameraFeedState.Connecting => "surveillance-camera-monitor-ui-status-connecting-card",
            _ => "surveillance-camera-monitor-ui-status-offline-card",
        };
    }

    private static string GetFeedStateHintLocKey(CameraFeedState state)
    {
        return state switch
        {
            CameraFeedState.Live => "surveillance-camera-monitor-ui-status-hint-ready",
            CameraFeedState.Connecting => "surveillance-camera-monitor-ui-status-hint-connecting",
            _ => "surveillance-camera-monitor-ui-status-hint-offline",
        };
    }

    private void OnCameraMapSelected(NetEntity netEntity)
    {
        if (_mapUid is null || !_entityManager.TryGetComponent<SurveillanceCameraMapComponent>(_mapUid.Value, out var mapComp))
            return;

        if (!mapComp.Cameras.TryGetValue(netEntity, out var marker) || !marker.Active)
            return;

        if (!string.IsNullOrEmpty(marker.Address))
            CameraSelected?.Invoke(marker.Address, marker.Subnet);
        else
            _entityManager.RaisePredictiveEvent(new RequestCameraMarkerUpdateMessage(netEntity));
    }

    private static void SetWrappedText(RichTextLabel label, string text, Color color)
    {
        label.SetMessage(text.Replace("\\n", "\n", StringComparison.Ordinal), defaultColor: color);
    }

    private enum MonitorViewMode
    {
        Roster = 0,
        Map = 1,
    }

    private enum CameraFeedState
    {
        Disconnected,
        Connecting,
        Live,
    }
}

public sealed record CameraRosterListData(string Address) : ListData
{
    public string CameraName = string.Empty;
    public string SearchText = string.Empty;
    public bool IsCurrent;
    public int SortIndex;
}
