using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;

namespace Content.Client._RMC14.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorDetail : Control
{
    private static readonly Animation FadeIn = new()
    {
        Length = TimeSpan.FromSeconds(0.25),
        AnimationTracks =
        {
            new AnimationTrackControlProperty
            {
                Property = nameof(Modulate),
                InterpolationMode = AnimationInterpolationMode.Linear,
                KeyFrames =
                {
                    new AnimationTrackProperty.KeyFrame(new Color(1f, 1f, 1f, 0f), 0f),
                    new AnimationTrackProperty.KeyFrame(Color.White, 0.25f, Easings.OutCubic),
                }
            }
        }
    };

    public CMAutomatedVendorDetail()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Plays a fade-in animation when the detail panel is revealed.
    /// </summary>
    public void AnimateOpen()
    {
        if (HasRunningAnimation("fadeIn"))
            StopAnimation("fadeIn");
        Modulate = new Color(1f, 1f, 1f, 0f);
        PlayAnimation(FadeIn, "fadeIn");
    }
}
