using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;

namespace Content.Client._RMC14.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorEntry : Control
{
    private static readonly Color InfoNormal = Color.FromHex("#5A5030");
    private static readonly Color InfoActive = Color.FromHex("#D4AA30");

    public CMAutomatedVendorEntry()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Cascading fade-in when entries are first built.
    /// </summary>
    public void AnimateAppear(float delay)
    {
        Modulate = new Color(1f, 1f, 1f, 0f);
        var anim = new Animation
        {
            Length = TimeSpan.FromSeconds(delay + 0.2),
            AnimationTracks =
            {
                new AnimationTrackControlProperty
                {
                    Property = nameof(Modulate),
                    InterpolationMode = AnimationInterpolationMode.Linear,
                    KeyFrames =
                    {
                        new AnimationTrackProperty.KeyFrame(new Color(1f, 1f, 1f, 0f), delay),
                        new AnimationTrackProperty.KeyFrame(Color.White, 0.2f, Easings.OutCubic),
                    }
                }
            }
        };
        PlayAnimation(anim, "appear");
    }

    /// <summary>
    /// Highlights the "i" info label when this entry's detail is shown.
    /// </summary>
    public void SetInfoActive(bool active)
    {
        InfoLabel.FontColorOverride = active ? InfoActive : InfoNormal;
    }
}

