using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;

namespace Content.Client._RMC14.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorPanel : Control
{
    public static readonly Color DefaultColor = Color.FromHex("#111218");
    public static readonly Color DefaultBorderColor = Color.FromHex("#2A2418");
    public static readonly Color DefaultHoveredColor = Color.FromHex("#1A1A24");
    private static readonly Color DisabledColor = Color.FromHex("#0A0A0E");

    // Brief flash on hover state change — dims and restores for smooth feel
    private static readonly Animation HoverFlash = new()
    {
        Length = TimeSpan.FromSeconds(0.15),
        AnimationTracks =
        {
            new AnimationTrackControlProperty
            {
                Property = nameof(Modulate),
                InterpolationMode = AnimationInterpolationMode.Linear,
                KeyFrames =
                {
                    new AnimationTrackProperty.KeyFrame(new Color(0.75f, 0.75f, 0.8f, 1f), 0f),
                    new AnimationTrackProperty.KeyFrame(Color.White, 0.15f, Easings.OutQuad),
                }
            }
        }
    };

    public Color Color = DefaultColor;
    public Color BorderColor = DefaultBorderColor;
    public Color HoveredColor = DefaultHoveredColor;

    public CMAutomatedVendorPanel()
    {
        RobustXamlLoader.Load(this);

        Button.OnDrawModeChanged += UpdateColor;
        UpdateColor();
    }

    private void UpdateColor()
    {
        var panel = (StyleBoxFlat) Panel.PanelOverride!;
        panel.BackgroundColor = Button.Disabled
            ? DisabledColor
            : (Button.IsHovered ? HoveredColor : Color);
        panel.BorderColor = BorderColor;

        // Animate a brief dim→restore on each state change for smooth transitions
        if (!Button.Disabled)
        {
            if (Panel.HasRunningAnimation("hover"))
                Panel.StopAnimation("hover");
            Panel.PlayAnimation(HoverFlash, "hover");
        }
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        UpdateColor();
    }
}

