using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;

namespace Content.Client._RMC14.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorWindow : DefaultWindow
{
    // Subtle pulsing glow on the ⚙ gear icon
    private static readonly Animation GearPulse = new()
    {
        Length = TimeSpan.FromSeconds(3),
        AnimationTracks =
        {
            new AnimationTrackControlProperty
            {
                Property = nameof(Control.Modulate),
                InterpolationMode = AnimationInterpolationMode.Linear,
                KeyFrames =
                {
                    new AnimationTrackProperty.KeyFrame(new Color(0.75f, 0.75f, 0.75f, 1f), 0f),
                    new AnimationTrackProperty.KeyFrame(Color.White, 1.5f, Easings.InOutSine),
                    new AnimationTrackProperty.KeyFrame(new Color(0.75f, 0.75f, 0.75f, 1f), 1.5f, Easings.InOutSine),
                }
            }
        }
    };

    // Slow breathing pulse on the bottom gold accent line
    private static readonly Animation AccentPulse = new()
    {
        Length = TimeSpan.FromSeconds(4),
        AnimationTracks =
        {
            new AnimationTrackControlProperty
            {
                Property = nameof(Control.Modulate),
                InterpolationMode = AnimationInterpolationMode.Linear,
                KeyFrames =
                {
                    new AnimationTrackProperty.KeyFrame(new Color(0.5f, 0.5f, 0.5f, 1f), 0f),
                    new AnimationTrackProperty.KeyFrame(Color.White, 2f, Easings.InOutSine),
                    new AnimationTrackProperty.KeyFrame(new Color(0.5f, 0.5f, 0.5f, 1f), 2f, Easings.InOutSine),
                }
            }
        }
    };

    public CMAutomatedVendorWindow()
    {
        RobustXamlLoader.Load(this);

        GearIcon.AnimationCompleted += _ => GearIcon.PlayAnimation(GearPulse, "pulse");
        GearIcon.PlayAnimation(GearPulse, "pulse");

        BottomAccent.AnimationCompleted += _ => BottomAccent.PlayAnimation(AccentPulse, "pulse");
        BottomAccent.PlayAnimation(AccentPulse, "pulse");
    }
}

