using System;
using Content.Client._WH40K.Interface;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchServerEntryControl : BoxContainer
{
    private const string AccentPulseKey = "accent-pulse";

    private readonly WH40KResearchConsoleTheme _theme;
    private readonly Color _accentColor;
    private bool? _selected;

    public readonly int ServerId;

    public event Action<int>? OnPressed;

    public ResearchServerEntryControl(int serverId, string serverName, bool selected, WH40KResearchConsoleTheme theme)
    {
        RobustXamlLoader.Load(this);

        _theme = theme;
        _accentColor = ResolveAccentColor(serverName, theme);
        ServerId = serverId;

        SelectButton.StyleBoxOverride = CreateTransparentButtonStyle();
        SelectedBadgePanel.PanelOverride = WH40KResearchConsoleStyles.CreateBadgeStyle(
            theme.SurfaceBackground.WithAlpha(0.96f),
            _accentColor.WithAlpha(0.9f),
            0,
            0);

        var decoratedName = WH40KUiChrome.DecorateIfMissing(serverName, WH40KUiChrome.DiamondOutline);
        ServerNameLabel.Text = decoratedName;
        ServerNameLabel.ToolTip = serverName;
        ServerIdLabel.Text = Loc.GetString("research-client-server-selection-menu-server-id", ("id", serverId));
        SelectedBadgeLabel.Text = Loc.GetString("research-client-server-selection-menu-server-state-selected");
        SelectedBadgeLabel.FontColorOverride = theme.PrimaryText;

        SelectButton.OnPressed += _ => OnPressed?.Invoke(ServerId);
        SelectButton.OnMouseEntered += _ => WH40KUiChrome.PlayHoverFlash(CardPanel, "hover-flash", _accentColor.WithAlpha(0.78f));

        ApplySelection(selected);
    }

    public void ApplySelection(bool selected)
    {
        if (_selected == selected)
            return;

        _selected = selected;
        CardPanel.PanelOverride = WH40KResearchConsoleStyles.CreatePanelStyle(
            selected ? _theme.SurfaceHoverBackground : _theme.SurfaceBackground,
            selected ? _accentColor.WithAlpha(0.92f) : _theme.BorderColor,
            0);
        AccentBar.PanelOverride = CreateAccentBarStyle(
            selected
                ? _accentColor.WithAlpha(0.92f)
                : _theme.BorderStrongColor.WithAlpha(0.8f));

        SelectedBadgePanel.Visible = selected;
        ServerNameLabel.FontColorOverride = _theme.PrimaryText;
        ServerIdLabel.FontColorOverride = _theme.SecondaryText;
        ServerStateLabel.Text = Loc.GetString(selected
            ? "research-client-server-selection-menu-server-state-linked"
            : "research-client-server-selection-menu-server-state-available");
        ServerStateLabel.FontColorOverride = selected
            ? _accentColor
            : _theme.SecondaryText;

        if (selected)
        {
            WH40KUiChrome.StartLoopingPulse(
                AccentBar,
                AccentPulseKey,
                _theme.BorderStrongColor.WithAlpha(0.8f),
                _accentColor.WithAlpha(0.96f),
                3.8f);
        }
        else
        {
            if (AccentBar.HasRunningAnimation(AccentPulseKey))
                AccentBar.StopAnimation(AccentPulseKey);

            AccentBar.Modulate = Color.White;
        }
    }

    private static StyleBoxFlat CreateTransparentButtonStyle()
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.Transparent,
            BorderColor = Color.Transparent,
            BorderThickness = new Thickness(0f),
            ContentMarginLeftOverride = 0,
            ContentMarginTopOverride = 0,
            ContentMarginRightOverride = 0,
            ContentMarginBottomOverride = 0,
        };
    }

    private static StyleBoxFlat CreateAccentBarStyle(Color color)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = color,
        };
    }

    private static Color ResolveAccentColor(string serverName, WH40KResearchConsoleTheme theme)
    {
        var upperName = serverName.ToUpperInvariant();

        if (upperName.Contains("HERETIC") || upperName.Contains("CHAOS"))
            return Color.FromHex("#C7483F".AsSpan());

        if (upperName.Contains("IMPERIUM") || upperName.Contains("IMPERIAL"))
            return Color.FromHex("#C9A94C".AsSpan());

        return theme.Accent;
    }
}
