using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Content.Client._WH40K.Interface;

namespace Content.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class TechnologyCardControl : Control
{
    public Action? OnPressed;
    public string TechnologyId { get; private set; } = string.Empty;

    private readonly WH40KResearchConsoleTheme _theme;
    private readonly IPrototypeManager _prototypeManager;
    private readonly SpriteSystem _spriteSys;

    public TechnologyCardControl(
        TechnologyPrototype technology,
        IPrototypeManager prototypeManager,
        SpriteSystem spriteSys,
        FormattedMessage description,
        int points,
        bool hasAccess,
        bool researchBusy,
        bool isActiveResearch,
        WH40KResearchConsoleTheme theme)
    {
        RobustXamlLoader.Load(this);

        _theme = theme;
        _prototypeManager = prototypeManager;
        _spriteSys = spriteSys;

        ResearchButton.OnPressed += _ => OnPressed?.Invoke();
        ResearchButton.OnMouseEntered += _ => WH40KUiChrome.PlayHoverFlash(CardPanel, "hover-flash");
        ApplyState(technology, description, points, hasAccess, researchBusy, isActiveResearch);
    }

    public void ApplyState(
        TechnologyPrototype technology,
        FormattedMessage description,
        int points,
        bool hasAccess,
        bool researchBusy,
        bool isActiveResearch)
    {
        TechnologyId = technology.ID;
        var discipline = _prototypeManager.Index<TechDisciplinePrototype>(technology.Discipline);
        var accent = _theme.Enabled ? _theme.Accent : discipline.Color;

        CardPanel.PanelOverride = WH40KResearchConsoleStyles.CreatePanelStyle(_theme.SurfaceBackground, _theme.BorderColor, 0);
        HeaderPanel.PanelOverride = WH40KResearchConsoleStyles.CreateEdgePanelStyle(
            _theme.HeaderBackground,
            accent.WithAlpha(0.84f),
            new Thickness(0f, 0f, 0f, 1f),
            0);
        TechnologyIconPanel.PanelOverride = WH40KResearchConsoleStyles.CreateBadgeStyle(_theme.PreviewBackground, _theme.BorderColor, 4, 4);

        DisciplineTexture.Texture = _spriteSys.Frame0(discipline.Icon);
        TechnologyTexture.Texture = _spriteSys.Frame0(technology.Icon);
        var displayName = WH40KUiChrome.DecorateIfMissing(Loc.GetString(technology.Name), WH40KUiChrome.Diamond);
        TechnologyNameLabel.Text = displayName;
        TechnologyNameLabel.FontColorOverride = _theme.PrimaryText;
        TechnologyNameLabel.ToolTip = displayName;
        DisciplineLineLabel.Text = $"{WH40KUiChrome.Arrow} {Loc.GetString(discipline.Name)} | {Loc.GetString("research-console-tier-badge", ("tier", technology.Tier))}";
        DisciplineLineLabel.FontColorOverride = accent;
        UnlocksLabel.SetMessage(description, defaultColor: _theme.SecondaryText);

        StyleBoxFlat buttonStyle;

        if (!hasAccess)
        {
            ResearchButton.Text = Loc.GetString("research-console-card-status-restricted");
            ResearchButton.ToolTip = Loc.GetString("research-console-no-access-popup");
            buttonStyle = WH40KResearchConsoleStyles.CreateDangerButtonStyle(_theme);
        }
        else if (isActiveResearch)
        {
            ResearchButton.Text = Loc.GetString("research-console-menu-server-research-button-active");
            ResearchButton.ToolTip = Loc.GetString("research-console-research-active-tooltip");
            buttonStyle = WH40KResearchConsoleStyles.CreateSecondaryButtonStyle(_theme);
        }
        else if (researchBusy)
        {
            ResearchButton.Text = Loc.GetString("research-console-menu-server-research-button-busy");
            ResearchButton.ToolTip = Loc.GetString("research-console-research-busy-tooltip");
            buttonStyle = WH40KResearchConsoleStyles.CreateSecondaryButtonStyle(_theme);
        }
        else if (points < technology.Cost)
        {
            ResearchButton.Text = Loc.GetString("research-console-card-status-no-points");
            ResearchButton.ToolTip = Loc.GetString(
                "research-console-research-not-enough-points-tooltip",
                ("cost", technology.Cost),
                ("points", points));
            buttonStyle = WH40KResearchConsoleStyles.CreateDangerButtonStyle(_theme);
        }
        else
        {
            ResearchButton.Text = Loc.GetString("research-console-menu-server-research-button");
            ResearchButton.ToolTip = null;
            buttonStyle = WH40KResearchConsoleStyles.CreatePrimaryButtonStyle(_theme);
        }

        WH40KResearchConsoleStyles.ApplyButtonTheme(ResearchButton, buttonStyle, _theme.PrimaryText);
        ResearchButton.Disabled = points < technology.Cost || !hasAccess || researchBusy;
    }
}
