using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Content.Client._WH40K.Interface;

namespace Content.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class TechnologyCardControl : Control
{
    public Action? OnPressed;

    public TechnologyCardControl(
        TechnologyPrototype technology,
        IPrototypeManager prototypeManager,
        SpriteSystem spriteSys,
        FormattedMessage description,
        int points,
        bool hasAccess,
        bool researchBusy,
        bool isActiveResearch,
        WH40KResearchConsoleTheme theme)
    {
        RobustXamlLoader.Load(this);

        var discipline = prototypeManager.Index<TechDisciplinePrototype>(technology.Discipline);
        var accent = theme.Enabled ? theme.Accent : discipline.Color;

        CardPanel.PanelOverride = WH40KResearchConsoleStyles.CreatePanelStyle(theme.SurfaceBackground, theme.BorderColor, 0);
        HeaderPanel.PanelOverride = WH40KResearchConsoleStyles.CreateEdgePanelStyle(
            theme.HeaderBackground,
            accent.WithAlpha(0.84f),
            new Thickness(0f, 0f, 0f, 1f),
            0);
        TechnologyIconPanel.PanelOverride = WH40KResearchConsoleStyles.CreateBadgeStyle(theme.PreviewBackground, theme.BorderColor, 4, 4);

        DisciplineTexture.Texture = spriteSys.Frame0(discipline.Icon);
        TechnologyTexture.Texture = spriteSys.Frame0(technology.Icon);
        var displayName = WH40KUiChrome.DecorateIfMissing(Loc.GetString(technology.Name), WH40KUiChrome.Diamond);
        TechnologyNameLabel.Text = displayName;
        TechnologyNameLabel.FontColorOverride = theme.PrimaryText;
        TechnologyNameLabel.ToolTip = displayName;
        DisciplineLineLabel.Text = $"{WH40KUiChrome.Arrow} {Loc.GetString(discipline.Name)} | {Loc.GetString("research-console-tier-badge", ("tier", technology.Tier))}";
        DisciplineLineLabel.FontColorOverride = accent;
        UnlocksLabel.SetMessage(description, defaultColor: theme.SecondaryText);

        StyleBoxFlat buttonStyle;

        if (!hasAccess)
        {
            ResearchButton.Text = Loc.GetString("research-console-card-status-restricted");
            ResearchButton.ToolTip = Loc.GetString("research-console-no-access-popup");
            buttonStyle = WH40KResearchConsoleStyles.CreateDangerButtonStyle(theme);
        }
        else if (isActiveResearch)
        {
            ResearchButton.Text = Loc.GetString("research-console-menu-server-research-button-active");
            ResearchButton.ToolTip = Loc.GetString("research-console-research-active-tooltip");
            buttonStyle = WH40KResearchConsoleStyles.CreateSecondaryButtonStyle(theme);
        }
        else if (researchBusy)
        {
            ResearchButton.Text = Loc.GetString("research-console-menu-server-research-button-busy");
            ResearchButton.ToolTip = Loc.GetString("research-console-research-busy-tooltip");
            buttonStyle = WH40KResearchConsoleStyles.CreateSecondaryButtonStyle(theme);
        }
        else if (points < technology.Cost)
        {
            ResearchButton.Text = Loc.GetString("research-console-card-status-no-points");
            ResearchButton.ToolTip = Loc.GetString(
                "research-console-research-not-enough-points-tooltip",
                ("cost", technology.Cost),
                ("points", points));
            buttonStyle = WH40KResearchConsoleStyles.CreateDangerButtonStyle(theme);
        }
        else
        {
            ResearchButton.Text = Loc.GetString("research-console-menu-server-research-button");
            buttonStyle = WH40KResearchConsoleStyles.CreatePrimaryButtonStyle(theme);
        }

        WH40KResearchConsoleStyles.ApplyButtonTheme(ResearchButton, buttonStyle, theme.PrimaryText);
        ResearchButton.Disabled = points < technology.Cost || !hasAccess || researchBusy;
        ResearchButton.OnPressed += _ => OnPressed?.Invoke();
        ResearchButton.OnMouseEntered += _ => WH40KUiChrome.PlayHoverFlash(CardPanel, "hover-flash");
    }
}
