using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;

namespace Content.Client.Administration.UI.BanList.RoleBans;

[GenerateTypedNameReferences]
public sealed partial class RoleBanListHeader : ContainerButton
{
    public RoleBanListHeader()
    {
        RobustXamlLoader.Load(this);
        BackgroundPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1B1A14"),
            BorderColor = Color.FromHex("#6E5A2F"),
            BorderThickness = new Thickness(1)
        };
    }
}
