using System;
using System.Linq;
using Content.Client.Localization;
using Content.Client.UserInterface.Controls;
using Content.Shared._WH40K.Command;
using Content.Shared._WH40K.GameMode;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client._WH40K.Command;

[GenerateTypedNameReferences]
public sealed partial class WH40KCommandNodeWindow : FancyWindow, ILocalizedControl
{
    private const string NoDoctrineSelectedLoc = "w40k-cmd-doctrine-card-none";
    private const string NoDoctrineThemeLoc = "w40k-cmd-doctrine-card-none-theme";
    private const string BattleTacticCooldownReadyLoc = "w40k-cmd-battle-tactic-window-cooldown-ready";
    private const string BattleTacticCooldownActiveLoc = "w40k-cmd-battle-tactic-window-cooldown-active";

    public event Action? OnUpgradePressed;
    public event Action? OnTeamCompositionPressed;
    public event Action? OnTacticalBonusesPressed;
    public event Action? OnDoctrinePressed;
    public event Action? OnBattleTacticPressed;

    private readonly Color _fallbackAccent = WH40KCommandUiStyles.DefaultAccent;
    private WH40KCommandNodeBoundUserInterfaceState? _latestState;
    private string _activeBattleTacticName = string.Empty;
    private string _activeBattleTacticDescription = string.Empty;

    public WH40KCommandNodeWindow()
    {
        RobustXamlLoader.Load(this);

        UpgradeButton.OnPressed += _ => OnUpgradePressed?.Invoke();
        TeamCompositionButton.OnPressed += _ => OnTeamCompositionPressed?.Invoke();
        TacticalBonusesButton.OnPressed += _ => OnTacticalBonusesPressed?.Invoke();
        DoctrineButton.OnPressed += _ => OnDoctrinePressed?.Invoke();
        BattleTacticButton.OnPressed += _ => OnBattleTacticPressed?.Invoke();

        Relocalize();
    }

    public void Relocalize()
    {
        Title = Loc.GetString("w40k-cmd-window-title");
        HeaderTitleLabel.Text = Loc.GetString("w40k-cmd-header-title");
        HeaderSubtitleLabel.Text = Loc.GetString("w40k-cmd-header-subtitle");
        RailTitleLabel.Text = Loc.GetString("w40k-cmd-rail-title");
        BaseCardTitleLabel.Text = Loc.GetString("w40k-cmd-base-card-title");
        ReadinessCardTitleLabel.Text = Loc.GetString("w40k-cmd-readiness-card-title");
        OperationsTitleLabel.Text = Loc.GetString("w40k-cmd-operations-title");
        DoctrineCardTitleLabel.Text = Loc.GetString("w40k-cmd-doctrine-card-title");
        BattleTacticCardTitleLabel.Text = Loc.GetString("w40k-cmd-battle-tactic-card-title");
        MissionCardTitleLabel.Text = Loc.GetString("w40k-cmd-mission-card-title");
        CompositionCardTitleLabel.Text = Loc.GetString("w40k-cmd-composition-card-title");
        IntelCardTitleLabel.Text = Loc.GetString("w40k-cmd-intel-card-title");

        UpgradeButton.Text = Loc.GetString("w40k-cmd-upgrade-button");
        DoctrineButton.Text = Loc.GetString("w40k-cmd-doctrine-open-button");
        BattleTacticButton.Text = Loc.GetString("w40k-cmd-battle-tactic-open-button");
        TeamCompositionButton.Text = Loc.GetString("w40k-cmd-team-composition-open-button");
        TacticalBonusesButton.Text = Loc.GetString("w40k-cmd-tactical-bonuses-open-button");

        if (_latestState != null)
        {
            UpdateState(_latestState);
            return;
        }

        FooterLabel.Text = Loc.GetString("w40k-cmd-footer-idle");
    }

    public void UpdateState(WH40KCommandNodeBoundUserInterfaceState state)
    {
        _latestState = state;

        var accent = WH40KTeamIdentityClientResolver.ResolveAccentColor(state.TeamId, _fallbackAccent);
        ApplyAccent(state, accent);
        ApplyHeader(state);
        ApplyBaseStatus(state, accent);
        ApplyReadiness(state);
        ApplyImmediateActions(state);
        ApplyDoctrineCard(state);
        ApplyBattleTacticCard(state);
        ApplyMissionCard(state);
        ApplyCompositionCard(state);
        ApplyIntelCard(state);
        ApplyFooter(state);
    }

    public void SetBattleTacticPreview(string tacticName, string tacticDescription)
    {
        _activeBattleTacticName = string.IsNullOrWhiteSpace(tacticName)
            ? Loc.GetString("w40k-cmd-battle-tactic-default-name")
            : tacticName;
        _activeBattleTacticDescription = string.IsNullOrWhiteSpace(tacticDescription)
            ? Loc.GetString("w40k-cmd-battle-tactic-default-description")
            : tacticDescription;

        if (_latestState == null)
            return;

        ApplyBattleTacticCard(_latestState);
    }

    private void ApplyAccent(WH40KCommandNodeBoundUserInterfaceState state, Color accent)
    {
        HeaderPanel.PanelOverride = WH40KCommandUiStyles.CreateBorderPanelStyle(
            WH40KCommandUiStyles.HeaderBackground,
            accent,
            2);
        CommandRail.PanelOverride = WH40KCommandUiStyles.CreateBorderPanelStyle(
            WH40KCommandUiStyles.PanelBackground,
            WH40KCommandUiStyles.MutedBorder,
            2);
        OperationsPanel.PanelOverride = WH40KCommandUiStyles.CreateBorderPanelStyle(
            WH40KCommandUiStyles.PanelBackgroundAlt,
            WH40KCommandUiStyles.StrongBorder,
            2);
        RailHeaderPanel.PanelOverride = WH40KCommandUiStyles.CreateHeaderStripStyle(accent);
        OperationsHeaderPanel.PanelOverride = WH40KCommandUiStyles.CreateHeaderStripStyle(accent);
        FooterPanel.PanelOverride = WH40KCommandUiStyles.CreateBorderPanelStyle(
            WH40KCommandUiStyles.FooterBackground,
            WH40KCommandUiStyles.MutedBorder,
            1);

        BaseStatusCard.PanelOverride = WH40KCommandUiStyles.CreateCardStyle(WH40KCommandUiStyles.CardBackground, accent);
        ReadinessCard.PanelOverride = WH40KCommandUiStyles.CreateCardStyle(
            WH40KCommandUiStyles.CardBackground,
            WH40KCommandUiStyles.MutedBorder);
        ImmediateActionsCard.PanelOverride = WH40KCommandUiStyles.CreateCardStyle(
            WH40KCommandUiStyles.CardBackground,
            WH40KCommandUiStyles.MutedBorder);

        DoctrineCard.PanelOverride = WH40KCommandUiStyles.CreateCardStyle(
            WH40KCommandUiStyles.CardBackground,
            ResolveDoctrineBorderColor(state, accent));
        BattleTacticCard.PanelOverride = WH40KCommandUiStyles.CreateCardStyle(
            WH40KCommandUiStyles.CardBackground,
            WH40KCommandUiStyles.MutedBorder);
        MissionCard.PanelOverride = WH40KCommandUiStyles.CreateCardStyle(
            WH40KCommandUiStyles.CardBackground,
            ResolveMissionBorderColor(state, accent));
        CompositionCard.PanelOverride = WH40KCommandUiStyles.CreateCardStyle(
            WH40KCommandUiStyles.CardBackground,
            WH40KCommandUiStyles.MutedBorder);
        IntelCard.PanelOverride = WH40KCommandUiStyles.CreateCardStyle(
            WH40KCommandUiStyles.CardBackground,
            WH40KCommandUiStyles.MutedBorder);

        TeamBadge.PanelOverride = WH40KCommandUiStyles.CreateBadgeStyle(Color.FromHex("#203227".AsSpan()), accent);
        PhaseBadge.PanelOverride = ResolvePhaseBadgeStyle(state.Phase, accent);
        LevelBadge.PanelOverride = WH40KCommandUiStyles.CreateBadgeStyle(
            Color.FromHex("#26314A".AsSpan()),
            WH40KCommandUiStyles.InfoBadge);
        StatusBadge.PanelOverride = ResolveStatusBadgeStyle(state, accent);
        RoundBadge.PanelOverride = WH40KCommandUiStyles.CreateBadgeStyle(
            Color.FromHex("#22313B".AsSpan()),
            accent);

        BaseProgressBar.BackgroundStyleBoxOverride = WH40KCommandUiStyles.CreateProgressBackgroundStyle();
        BaseProgressBar.ForegroundStyleBoxOverride = WH40KCommandUiStyles.CreateProgressForegroundStyle(accent);

        HeaderTitleLabel.ModulateSelfOverride = accent;
        TeamBadgeLabel.ModulateSelfOverride = Color.White;
        PhaseBadgeLabel.ModulateSelfOverride = Color.White;
        LevelBadgeLabel.ModulateSelfOverride = Color.White;
        StatusBadgeLabel.ModulateSelfOverride = Color.White;
        RoundBadgeLabel.ModulateSelfOverride = Color.White;
    }

    private void ApplyHeader(WH40KCommandNodeBoundUserInterfaceState state)
    {
        var resolvedTeam = ResolveLocalizedOrRaw(state.TeamName);
        var teamName = string.IsNullOrWhiteSpace(resolvedTeam) ? "?" : resolvedTeam.ToUpperInvariant();
        var phaseName = Loc.GetString(GetPhaseKey(state.Phase));

        HeaderSubtitleLabel.Text = Loc.GetString("w40k-cmd-header-subtitle-team", ("team", resolvedTeam));
        TeamBadgeLabel.Text = teamName;
        PhaseBadgeLabel.Text = phaseName;
        LevelBadgeLabel.Text = Loc.GetString("w40k-cmd-level-badge", ("level", state.BaseLevel));
        StatusBadgeLabel.Text = BuildStatusBadgeText(state);
        RoundBadgeLabel.Text = Loc.GetString(
            "w40k-cmd-round-badge",
            ("time", FormatDuration(state.RoundElapsedSeconds)));
    }

    private void ApplyBaseStatus(WH40KCommandNodeBoundUserInterfaceState state, Color accent)
    {
        BaseLevelLineLabel.Text = Loc.GetString("w40k-cmd-level", ("level", state.BaseLevel));
        FrontPointsLineLabel.Text = Loc.GetString("w40k-cmd-points", ("points", state.FrontPoints));
        CommandPointsLineLabel.Text = Loc.GetString("w40k-cmd-command-points", ("points", state.CommandPoints));
        DevelopmentPointsLineLabel.Text = Loc.GetString("w40k-cmd-development-points", ("points", state.CommandPoints));

        var (progress, segmentCurrent, segmentTotal) = CalculateBaseProgress(state);
        BaseProgressBar.Value = progress;
        BaseProgressBar.ForegroundStyleBoxOverride = WH40KCommandUiStyles.CreateProgressForegroundStyle(accent);

        BaseProgressLineLabel.Text = state.PointsToNextLevel is { } pointsLeft
            ? Loc.GetString(
                "w40k-cmd-base-progress-current",
                ("current", segmentCurrent),
                ("total", segmentTotal),
                ("left", pointsLeft))
            : Loc.GetString("w40k-cmd-base-progress-max");
    }

    private void ApplyReadiness(WH40KCommandNodeBoundUserInterfaceState state)
    {
        EventStatusLabel.Text = BuildCompactText(BuildEventReadinessText(state.TeamEventRuntime), 112);
        EventStatusLabel.ModulateSelfOverride = WH40KCommandUiStyles.SoftText;
        FocusLineLabel.Text = BuildCompactText(BuildFocusText(state), 118);
        FocusLineLabel.ModulateSelfOverride = WH40KCommandUiStyles.MutedText;
    }

    private void ApplyImmediateActions(WH40KCommandNodeBoundUserInterfaceState state)
    {
        UpgradeLineLabel.Text = Loc.GetString(
            "w40k-cmd-upgrade-line",
            ("level", state.UpgradeLevel),
            ("cost", state.UpgradeCost));

        UpgradeButton.Disabled = state.UpgradeCost <= 0 || state.CommandPoints < state.UpgradeCost;
    }

    private void ApplyDoctrineCard(WH40KCommandNodeBoundUserInterfaceState state)
    {
        WH40KCommandNodeDoctrineWindow.DoctrineDisplay? doctrineDisplay = string.IsNullOrWhiteSpace(state.ActiveDoctrineId)
            ? null
            : WH40KCommandNodeDoctrineWindow.ResolveDoctrineDisplay(state.ActiveDoctrineId, state.TeamId);

        DoctrineCardStateLabel.Text = doctrineDisplay?.Name ?? Loc.GetString(NoDoctrineSelectedLoc);
        DoctrineCardThemeLabel.Text = BuildCompactText(
            doctrineDisplay?.Summary ?? Loc.GetString("w40k-cmd-doctrine-card-selection-hint"),
            110);
        DoctrineCardThemeLabel.ModulateSelfOverride = doctrineDisplay == null
            ? WH40KCommandUiStyles.MutedText
            : WH40KCommandUiStyles.SoftText;
    }

    private void ApplyBattleTacticCard(WH40KCommandNodeBoundUserInterfaceState state)
    {
        if (string.IsNullOrWhiteSpace(_activeBattleTacticName))
        {
            _activeBattleTacticName = Loc.GetString("w40k-cmd-battle-tactic-default-name");
            _activeBattleTacticDescription = Loc.GetString("w40k-cmd-battle-tactic-default-description");
        }

        BattleTacticNameLabel.Text = _activeBattleTacticName;
        BattleTacticCooldownLabel.Text = state.BattleTacticCooldownSeconds > 0
            ? Loc.GetString(
                BattleTacticCooldownActiveLoc,
                ("time", FormatDuration(state.BattleTacticCooldownSeconds)))
            : Loc.GetString(BattleTacticCooldownReadyLoc);
    }

    private void ApplyMissionCard(WH40KCommandNodeBoundUserInterfaceState state)
    {
        var mission = ResolveActiveMission(state);
        if (mission == null)
        {
            MissionTitleLabel.Text = Loc.GetString("w40k-cmd-mission-status-none-title");
            MissionStatusLabel.Text = Loc.GetString("w40k-cmd-mission-status-none-detail");
            MissionRewardLabel.Text = Loc.GetString("w40k-cmd-mission-status-none-description");
            MissionRewardLabel.ModulateSelfOverride = WH40KCommandUiStyles.MutedText;
            return;
        }

        MissionTitleLabel.Text = ResolveLocalizedOrRaw(mission.MissionTitle);
        MissionStatusLabel.Text = Loc.GetString(
            "w40k-cmd-mission-status-active",
            ("scope", ResolveMissionScopeLabel(mission.Scope)),
            ("time", FormatDuration(mission.RemainingSeconds)));
        MissionRewardLabel.Text = Loc.GetString(
            "w40k-cmd-mission-status-reward",
            ("major", mission.RewardMajorDevelopmentPoints),
            ("minor", mission.RewardMinorDevelopmentPoints),
            ("tempo", mission.RewardTempoBonusPercent));
        MissionRewardLabel.ModulateSelfOverride = WH40KCommandUiStyles.SoftText;
    }

    private void ApplyCompositionCard(WH40KCommandNodeBoundUserInterfaceState state)
    {
        CompositionSummaryLabel.Text = ResolveLocalizedOrRaw(state.TeamCompositionSummary);
        CompositionStaffingLabel.Text = BuildPreviewBlock(
            state.TeamCompositionStaffingLines,
            2,
            "w40k-cmd-composition-card-no-staffing");
        CompositionStaffingLabel.ModulateSelfOverride = WH40KCommandUiStyles.SoftText;
    }

    private void ApplyIntelCard(WH40KCommandNodeBoundUserInterfaceState state)
    {
        var intel = state.BonusIntel;
        IntelSummaryLabel.Text = Loc.GetString(
            "w40k-cmd-intel-summary",
            ("engineering", intel.EngineeringTier),
            ("logistics", intel.LogisticsTier),
            ("passive", intel.NodePassiveFrontPointsPerTick));
        IntelDetailLabel.Text = BuildIntelDetailText(intel);
        IntelDetailLabel.ModulateSelfOverride = WH40KCommandUiStyles.SoftText;
    }

    private void ApplyFooter(WH40KCommandNodeBoundUserInterfaceState state)
    {
        FooterLabel.Text = CanUpgradeNode(state)
            ? Loc.GetString("w40k-cmd-footer-upgrade-ready", ("cost", state.UpgradeCost))
            : CanCallReinforcement(state)
                ? Loc.GetString("w40k-cmd-footer-reinforcement-ready", ("cost", state.ReinforcementCost))
                : BuildCompactText(BuildFocusText(state), 176);
    }

    private static bool CanUpgradeNode(WH40KCommandNodeBoundUserInterfaceState state)
    {
        return state.UpgradeCost > 0 && state.CommandPoints >= state.UpgradeCost;
    }

    private static bool CanCallReinforcement(WH40KCommandNodeBoundUserInterfaceState state)
    {
        return state.Phase == WH40KBattlePhase.Assault &&
               state.ReinforcementCost > 0 &&
               state.CommandPoints >= state.ReinforcementCost &&
               state.ReinforcementCooldownSeconds <= 0;
    }

    private static string BuildStatusBadgeText(WH40KCommandNodeBoundUserInterfaceState state)
    {
        return CanUpgradeNode(state) || CanCallReinforcement(state)
            ? Loc.GetString("w40k-cmd-status-badge-ready")
            : Loc.GetString("w40k-cmd-status-badge-limited");
    }

    private static StyleBoxFlat ResolvePhaseBadgeStyle(WH40KBattlePhase phase, Color accent)
    {
        return phase switch
        {
            WH40KBattlePhase.Preparation => WH40KCommandUiStyles.CreateBadgeStyle(
                Color.FromHex("#26314A".AsSpan()),
                WH40KCommandUiStyles.InfoBadge),
            WH40KBattlePhase.Assault => WH40KCommandUiStyles.CreateBadgeStyle(
                Color.FromHex("#3A2E1D".AsSpan()),
                accent),
            WH40KBattlePhase.Apocalypse => WH40KCommandUiStyles.CreateBadgeStyle(
                Color.FromHex("#3A2A2A".AsSpan()),
                WH40KCommandUiStyles.DangerBadge),
            _ => WH40KCommandUiStyles.CreateBadgeStyle(
                Color.FromHex("#26314A".AsSpan()),
                WH40KCommandUiStyles.InfoBadge)
        };
    }

    private static StyleBoxFlat ResolveStatusBadgeStyle(WH40KCommandNodeBoundUserInterfaceState state, Color accent)
    {
        if (CanUpgradeNode(state) || CanCallReinforcement(state))
        {
            return WH40KCommandUiStyles.CreateBadgeStyle(
                Color.FromHex("#223B2F".AsSpan()),
                WH40KCommandUiStyles.ReadyBadge);
        }

        if (state.Phase >= WH40KBattlePhase.Apocalypse)
        {
            return WH40KCommandUiStyles.CreateBadgeStyle(
                Color.FromHex("#3A2A2A".AsSpan()),
                WH40KCommandUiStyles.DangerBadge);
        }

        return WH40KCommandUiStyles.CreateBadgeStyle(
            Color.FromHex("#22313B".AsSpan()),
            accent);
    }

    private static Color ResolveMissionBorderColor(WH40KCommandNodeBoundUserInterfaceState state, Color accent)
    {
        return ResolveActiveMission(state) != null ? accent : WH40KCommandUiStyles.MutedBorder;
    }

    private static Color ResolveDoctrineBorderColor(WH40KCommandNodeBoundUserInterfaceState state, Color accent)
    {
        return string.IsNullOrWhiteSpace(state.ActiveDoctrineId) ? WH40KCommandUiStyles.MutedBorder : accent;
    }

    private static (float Value, int SegmentCurrent, int SegmentTotal) CalculateBaseProgress(
        WH40KCommandNodeBoundUserInterfaceState state)
    {
        if (state.PointsToNextLevel == null)
            return (1f, 1, 1);

        if (state.LevelThresholds.Length == 0)
        {
            var total = Math.Max(1, state.PointsToNextLevel.Value);
            return (0f, 0, total);
        }

        var level = Math.Max(1, state.BaseLevel);
        var thresholds = state.LevelThresholds;

        var segmentStart = 0;
        if (level > 1)
        {
            var previousThresholdIndex = Math.Clamp(level - 2, 0, thresholds.Length - 1);
            segmentStart = thresholds[previousThresholdIndex];
        }

        var currentThresholdIndex = Math.Clamp(level - 1, 0, thresholds.Length - 1);
        var segmentEnd = thresholds[currentThresholdIndex];

        if (segmentEnd <= segmentStart)
        {
            var fallbackTotal = Math.Max(1, state.PointsToNextLevel.Value + Math.Max(0, state.FrontPoints - segmentStart));
            var fallbackCurrent = Math.Clamp(fallbackTotal - state.PointsToNextLevel.Value, 0, fallbackTotal);
            return ((float) fallbackCurrent / fallbackTotal, fallbackCurrent, fallbackTotal);
        }

        var segmentTotal = segmentEnd - segmentStart;
        var segmentCurrent = Math.Clamp(state.FrontPoints - segmentStart, 0, segmentTotal);
        var value = Math.Clamp((float) segmentCurrent / segmentTotal, 0f, 1f);
        return (value, segmentCurrent, segmentTotal);
    }

    private static string BuildFocusText(WH40KCommandNodeBoundUserInterfaceState state)
    {
        var upgradeHint = state.CommandPoints >= state.UpgradeCost
            ? Loc.GetString("w40k-cmd-focus-upgrade-ready", ("cost", state.UpgradeCost))
            : Loc.GetString("w40k-cmd-focus-upgrade-wait", ("cost", state.UpgradeCost));

        return state.PointsToNextLevel is { } pointsLeft
            ? Loc.GetString("w40k-cmd-focus-next-level", ("points", pointsLeft), ("upgrade", upgradeHint))
            : Loc.GetString("w40k-cmd-focus-max-level", ("upgrade", upgradeHint));
    }

    private static string BuildEventReadinessText(WH40KCommandTeamEventRuntimeState runtime)
    {
        if (!runtime.HasProfile)
            return Loc.GetString("w40k-cmd-event-status-disabled");

        if (runtime.HasActiveEvent)
        {
            return Loc.GetString(
                "w40k-cmd-event-status-active",
                ("title", ResolveLocalizedOrRaw(runtime.ActiveEventTitle)),
                ("time", FormatDuration(runtime.ActiveRemainingSeconds)));
        }

        if (runtime.NextRollSeconds > 0)
        {
            return Loc.GetString(
                "w40k-cmd-event-status-next",
                ("time", FormatDuration(runtime.NextRollSeconds)));
        }

        return Loc.GetString("w40k-cmd-event-status-waiting");
    }

    private static string BuildIntelDetailText(WH40KCommandNodeBonusIntelState intel)
    {
        return BuildCompactText(
            Loc.GetString(
                "w40k-cmd-intel-detail",
                ("interval", FormatDuration((int) MathF.Ceiling(intel.NodePassiveIntervalSeconds))),
                ("eng_speed", intel.EngineeringSpeedBonusPercent),
                ("log_eta", intel.LogisticsTierDeliveryReductionMinutes),
                ("log_discount", intel.LogisticsExternalPriceDiscountPercent),
                ("ore_tier", intel.OreExtractorTier)),
            124);
    }

    private static string BuildPreviewBlock(string[] lines, int maxLines, string emptyLoc)
    {
        if (lines.Length == 0)
            return Loc.GetString(emptyLoc);

        return string.Join(" | ", lines
            .Take(maxLines)
            .Select(line => BuildCompactText(line, 52))
            .Where(line => !string.IsNullOrWhiteSpace(line)));
    }

    private static WH40KCommandMissionRuntimeState? ResolveActiveMission(WH40KCommandNodeBoundUserInterfaceState state)
    {
        if (state.TeamMissionRuntime.IsActive)
            return state.TeamMissionRuntime;

        if (state.GlobalMissionRuntime.IsActive)
            return state.GlobalMissionRuntime;

        return null;
    }

    private static string ResolveMissionScopeLabel(WH40KCommandDynamicMissionScope scope)
    {
        return scope switch
        {
            WH40KCommandDynamicMissionScope.Global => Loc.GetString("w40k-cmd-mission-board-scope-global"),
            WH40KCommandDynamicMissionScope.Faction => Loc.GetString("w40k-cmd-mission-board-scope-faction"),
            _ => Loc.GetString("w40k-cmd-mission-board-scope-global")
        };
    }

    private static string ResolveLocalizedOrRaw(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return string.Empty;

        if (IoCManager.Resolve<ILocalizationManager>().TryGetString(value, out var localized) && !string.IsNullOrWhiteSpace(localized))
            return localized!;

        return value;
    }

    private static string BuildCompactText(string text, int maxCharacters)
    {
        var resolved = ResolveLocalizedOrRaw(text);
        if (string.IsNullOrWhiteSpace(resolved))
            return string.Empty;

        var normalized = resolved
            .Replace("\\n", "\n", StringComparison.Ordinal)
            .Replace("\r", "\n", StringComparison.Ordinal);

        var lines = normalized
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(CollapseWhitespace)
            .Where(line => !string.IsNullOrWhiteSpace(line))
            .ToArray();

        var compact = lines.Length == 0
            ? CollapseWhitespace(normalized)
            : string.Join(" | ", lines);

        if (compact.Length <= maxCharacters)
            return compact;

        var shortened = compact[..Math.Max(1, maxCharacters - 3)].TrimEnd(' ', ',', ';', '|', '.', ':');
        return $"{shortened}...";
    }

    private static string CollapseWhitespace(string text)
    {
        return string.Join(" ", text.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries));
    }

    private static string FormatDuration(int seconds)
    {
        var clamped = Math.Max(0, seconds);
        var minutes = clamped / 60;
        var secs = clamped % 60;
        return $"{minutes:00}:{secs:00}";
    }

    private static string GetPhaseKey(WH40KBattlePhase phase)
    {
        return phase switch
        {
            WH40KBattlePhase.Preparation => "wh40k-phase-preparation-name",
            WH40KBattlePhase.Assault => "wh40k-phase-assault-name",
            WH40KBattlePhase.Apocalypse => "wh40k-phase-apocalypse-name",
            _ => "wh40k-phase-preparation-name"
        };
    }

}
