using Content.Client.Stylesheets;
using Content.Client.Localization;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget, ILocalizedControl
{
    public GhostTargetWindow TargetWindow { get; }

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? ReturnToLobbyPressed;
    public event Action? GhostRolesPressed;
    private int? _currentRoles;
    private bool? _canReturnToBody;
    private int _prevNumberRoles;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);

        TargetWindow = new GhostTargetWindow();

        MouseFilter = MouseFilterMode.Ignore;

        ReturnToLobbyButton.OnPressed += _ => ReturnToLobbyPressed?.Invoke();
        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleClass.Negative);

        Relocalize();
    }

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    public void Update(int? roles, bool? canReturnToBody)
    {
        _currentRoles = roles;
        _canReturnToBody = canReturnToBody;

        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleClass.Negative);
            }

            _prevNumberRoles = (int)roles;
        }

        TargetWindow.Populate();
    }

    public void Relocalize()
    {
        ReturnToLobbyButton.Text = Loc.GetString("ghost-gui-return-to-lobby-button");
        ReturnToBodyButton.Text = Loc.GetString("ghost-gui-return-to-body-button");
        GhostWarpButton.Text = Loc.GetString("ghost-gui-ghost-warp-button");

        if (_currentRoles != null)
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", _currentRoles.Value));
        else
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", 0));

        ReturnToBodyButton.Disabled = !_canReturnToBody ?? true;
        TargetWindow.Relocalize();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }
}
