- type: job
  id: HColonel
  name: job-name-hcolonel
  description: job-description-colonel
  playTimeTracker: JobHColonel
  startingGear: HeresyColonelGear
  icon: "JobIconColonel"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KFriendlyFireAllowed
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: HeresyColonelGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCultist1
    gloves: ClothingHandsGlovesCombatcult
    shoes: ClothingShoesChaosBoots2
    ears: ClothingHeadsetVoxBackpack
    outerClothing: ClothingOuterArmorCultistCoat
    belt: chaosbelt
    neck: NecklaceChaosCultistReflectWeak
    head: ClothingHeadScarfChaos
    id: HColonelDogTag
  inhand:
    - ChaosMachete
