- type: job
  id: HCommissar
  name: job-name-hcommissar
  description: job-description-commissar
  playTimeTracker: JobHCommissar
  setPreference: false
  startingGear: HeresyCommissarGear
  icon: "JobIconCommissar"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: HeresyCommissarGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCommissar
    gloves: ClothingHandsGlovesCombatcult
    shoes: ClothingShoesChaosBoots2
    belt: chaosbelt2
    ears: ClothingHeadsetVoxBackpack
    head: ClothingHeadCommissar
    id: HCommissarDogTag
