- type: job
  id: HEnginseer
  name: job-name-henginseer
  description: job-description-enginseer
  playTimeTracker: JobHEnginseer
  setPreference: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Imperium
      time: 4h
    - !type:RoleTimeRequirement
      role: JobNovice
      time: 2.5h
  startingGear: EnginseerGear
  icon: "JobIconEnginseer"
  supervisors: job-supervisors-ce
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: chameleonOutfit
  id: HEnginseerChameleonOutfit
  job: HEnginseer
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    eyes: ClothingEyesHudTechPriest
    outerClothing: ClothingOuterHardsuitTechpriest
