- type: job
  id: HEnginseer
  name: job-name-henginseer
  description: job-description-henginseer
  playTimeTracker: JobHEnginseer
  setPreference: false
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
    - !type:DepartmentTimeRequirement
      department: Imperium
      time: 4h
    - !type:RoleTimeRequirement
      role: JobNovice
      time: 2.5h
  startingGear: HEnginseerGear
  icon: "JobIconEnginseer"
  supervisors: job-supervisors-wh40k-dark-mechanicum-priest
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KChaosGiftRole
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: HEnginseerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    back: ClothingBackpackTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    eyes: ClothingEyesHudTechPriest
    outerClothing: ClothingOuterHardsuitTechpriest
    pocket1: WH40KStandardTacticalMapTablet
    id: HEnginseerDogTag

- type: chameleonOutfit
  id: HEnginseerChameleonOutfit
  job: HEnginseer
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    eyes: ClothingEyesHudTechPriest
    outerClothing: ClothingOuterHardsuitTechpriest

