- type: job
  id: HExplorator
  name: job-name-hexplorator
  description: job-description-explorator
  playTimeTracker: JobHExplorator
  requirements:
    - !type:DepartmentTimeRequirement
      department: Imperium
      time: 4h
    - !type:RoleTimeRequirement
      role: JobNovice
      time: 2.5h
  icon: "JobIconExplorator"
  startingGear: ExploratorGear
  supervisors: job-supervisors-qm
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External
  - Engineering

- type: chameleonOutfit
  id: HExploratorChameleonOutfit
  job: HExplorator
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    eyes: ClothingEyesHudTechPriest
    outerClothing: ClothingOuterHardsuitTechpriest
    mask: ClothingMaskGasTechPriest
