- type: job
  id: HGuardsman
  name: job-name-hguardsman
  description: job-description-hguardsman
  playTimeTracker: JobHGuardsman
  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
      - Felinid
  startingGear: HeresyGuardsmanGear
  icon: "JobIconHGuardsman"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadAssignable
      - type: WH40KChaosGiftRole
      - type: WH40KMoraleExecutionTarget
      - type: WH40KGuardsmanVoice
      - type: Vocal
        sounds:
          Male: WH40KGuardsmanMaleHuman
          Female: WH40KGuardsmanFemaleHuman
          Unsexed: WH40KGuardsmanMaleHuman
  access:
  - Maintenance
  - External

- type: startingGear
  id: HeresyGuardsmanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCultist1
    back: ClothingBackpackCULT1
    shoes: ClothingShoesChaosBoots1
    belt: chaosbelt2
    head: ClothingHeadHelmetFlakCHAOS
    outerClothing: ClothingOuterArmorChaosVest
    pocket1: WH40KStandardTacticalMapTablet
    id: HGuardsmanDogTag

