- type: job
  id: HGuardsman
  name: job-name-hguardsman
  description: job-description-guardsman
  playTimeTracker: JobHGuardsman
  startingGear: HeresyGuardsmanGear
  icon: "JobIconGuardsman"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: HeresyGuardsmanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCultist1
    back: ClothingBackpackCULT1
    shoes: ClothingShoesChaosBoots1
    belt: chaosbelt2
    head: ClothingHeadHelmetFlakCHAOS
    outerClothing: ClothingOuterArmorChaosVest
