- type: job
  id: HLexmechanic
  name: job-name-hlexmechanic
  description: job-description-lexmechanic
  playTimeTracker: JobHLexmechanic
  setPreference: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Imperium
      time: 6h
    - !type:RoleTimeRequirement
      role: JobNovice
      time: 2.5h
  startingGear: LexmechanicGear
  icon: "JobIconLexmechanic"
  supervisors: job-supervisors-ce
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  - Research
  - ResearchDirector

- type: chameleonOutfit
  id: HLexmechanicChameleonOutfit
  job: HLexmechanic
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    eyes: ClothingEyesHudTechPriest
    mask: ClothingMaskGasTechPriest
