- type: job
  id: HLexmechanic
  name: job-name-hlexmechanic
  description: job-description-hlexmechanic
  displayWeight: 30
  playTimeTracker: JobHLexmechanic
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: HLexmechanicGear
  special:
  - !type:AddComponentSpecial
    components:
      - type: IntrinsicRadioTransmitter
        channels:
        - Binary1
      - type: ActiveRadio
        channels:
        - Binary1
      - type: IntrinsicRadioReceiver
  icon: "JobIconHLexmechanic"
  supervisors: job-supervisors-ce
  canBeAntag: false
#  special:
#  - !type:AddComponentSpecial
#    components:
#      - type: WH40KChaosGiftRole
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  - Research
  - ResearchDirector

- type: startingGear
  id: HLexmechanicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    outerClothing: ClothingOuterHardsuitTechpriestUnremoveadble
    ears: ClothingHeadsetVoxBackpackHeretics
    pocket1: WH40KStandardTacticalMapTablet
    id: HLexmechanicDogTag

- type: chameleonOutfit
  id: HLexmechanicChameleonOutfit
  job: HLexmechanic
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
    gloves: ClothingHandsGlovesTechpriest
    ears: ClothingHeadsetVoxBackpackHeretics
    eyes: ClothingEyesHudTechPriest
