- type: job
  id: HMagos
  name: job-name-hmagos
  description: job-description-hmagos
  playTimeTracker: JobHMagos
  setPreference: false
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
      # - !type:CharacterTraitRequirement
      #   inverted: true
      #   traits:
      #     - Foreigner
      #     - ForeignerLight
    - !type:DepartmentTimeRequirement
      department: Imperium
      time: 15h
    - !type:RoleTimeRequirement
      role: JobNovice
      time: 2.5h
  weight: 10
  startingGear: MagosGear
  icon: "JobIconMagos"
  requireAdminNotify: true
  supervisors: job-supervisors-wh40k-dark-mechanicum-magos
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Research
  - Medical
  - ResearchDirector
  - Cargo
  - Salvage
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: WH40KChaosGiftRole
      - type: CommandStaff
  # afterLoadoutSpecial:
  # - !type:ModifyEnvirosuitSpecial
  #   charges: 8
  # - !type:ModifyEnvirohelmSpecial
  #   powerCell: PowerCellPotato

