- type: job
  id: HMedic
  name: job-name-hmedic
  description: job-description-hmedic
  playTimeTracker: JobHMedic
  startingGear: HeresyMedicGear
  icon: "JobIconHMedic"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadAssignable
      - type: WH40KChaosGiftRole
  access:
  - Maintenance
  - External
  - Medical

- type: startingGear
  id: HeresyMedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCultist1
    back: ClothingBackpackCULT2
    shoes: ClothingShoesChaosBoots2
    belt: chaosbelt2
    head: ClothingHeadHelmetFlakCHAOS
    outerClothing: ClothingOuterArmorFlakVestMed
    pocket1: WH40KStandardTacticalMapTablet
    id: HMedicDogTag

