- type: job
  id: HMedic
  name: job-name-hmedic
  description: job-description-medic
  playTimeTracker: JobHMedic
  startingGear: HeresyMedicGear
  icon: "JobIconMedic"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: HeresyMedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCultist1
    back: ClothingBackpackCULT2
    shoes: ClothingShoesChaosBoots2
    belt: chaosbelt2
    head: ClothingHeadHelmetFlakCHAOS
    outerClothing: ClothingOuterArmorFlakVestMed
    id: HMedicDogTag
