- type: job
  id: HNovice
  name: job-name-hnovice
  description: job-description-novice
  playTimeTracker: JobHNovice
  startingGear: NoviceGear
  icon: "JobIconNovice"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
