- type: job
  id: HNovice
  name: job-name-hnovice
  description: job-description-hnovice
  playTimeTracker: JobHNovice
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: NoviceGear
  setPreference: false
  icon: "JobIconNovice"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KChaosGiftRole
  access:
  - Maintenance
  - Engineering
  - External

- type: chameleonOutfit
  id: HNoviceChameleonOutfit
  job: HNovice
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
