- type: job
  id: HNovice
  name: job-name-hnovice
  description: job-description-novice
  playTimeTracker: JobHNovice
  startingGear: NoviceGear
  setPreference: false
  icon: "JobIconNovice"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External

- type: chameleonOutfit
  id: HNoviceChameleonOutfit
  job: HNovice
  equipment:
    jumpsuit: ClothingUniformJumpsuitTechpriest
    shoes: ClothingShoesBootsworkTechpriest
    belt: ClothingBeltUtilityEngineering
