- type: job
  id: HSergeantHWS
  name: job-name-hsergeant-hws
  description: job-description-sergeant-hws
  playTimeTracker: JobHSergeantHWS
  startingGear: HeresySergeantGear
  icon: "JobIconSergeantHWS"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
