- type: job
  id: HSergeantSWS
  name: job-name-hsergeant-sws
  description: job-description-sergeant-sws
  playTimeTracker: JobHSergeantSWS
  setPreference: false
  startingGear: HeresySergeantGear
  icon: "JobIconSergeantSWS"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
