- type: job
  id: HSpecialistHWS
  name: job-name-hspecialist-hws
  description: job-description-specialist-hws
  playTimeTracker: JobHSpecialistHWS
  startingGear: HeresyGuardsmanGear
  icon: "JobIconSpecialistHWS"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
