- type: job
  id: HSpecialistSWS
  name: job-name-hspecialist-sws
  description: job-description-hspecialist-sws
  playTimeTracker: JobHSpecialistSWS
  setPreference: false
  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: HeresyGuardsmanGear
  icon: "JobIconSpecialistSWS"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadAssignable
      - type: WH40KChaosGiftRole
  access:
  - Maintenance
  - External

