- type: job
  id: HTanker
  name: job-name-htanker
  description: job-description-htanker
  playTimeTracker: JobHTanker
  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
      - Felinid
      - Vulpkanin
  startingGear: HeresyGuardsmanGear
  icon: "JobIconHTanker"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadAssignable
      - type: WH40KChaosGiftRole
  access:
  - Maintenance
  - External
  - Engineering

