- type: job
  id: HTankComm
  name: job-name-htank-comm
  description: job-description-tank-comm
  playTimeTracker: JobHTankComm
  setPreference: false
  startingGear: HeresySergeantGear
  icon: "JobIconTankComm"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
