using System;
using System.Globalization;
using Content.Client.EnergyDome.UI.Controls;
using Content.Shared.EnergyDome;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.EnergyDome.UI;

[GenerateTypedNameReferences]
public sealed partial class EnergyDomeWindow : DefaultWindow
{
    private readonly StyleBoxFlat _chargeBarStyle = new();
    private readonly StyleBoxFlat _overloadBarStyle = new();
    private readonly StyleBoxFlat _threatHeatStyle = new() { BackgroundColor = Color.FromHex("#d56e45") };
    private readonly StyleBoxFlat _threatPiercingStyle = new() { BackgroundColor = Color.FromHex("#d7b75c") };
    private readonly StyleBoxFlat _threatOtherStyle = new() { BackgroundColor = Color.FromHex("#6f7a92") };

    private EnergyDomeBuiState? _state;
    private bool _suppressSelectionEvents;

    public event Action? TogglePressed;
    public event Action<EnergyDomeOperationMode>? ModeChanged;
    public event Action<EnergyDomeSizePreset>? SizeChanged;
    public event Action<EnergyDomeColorPreset>? ColorChanged;
    public event Action<EnergyDomeWallSide>? WallSideChanged;
    public event Action<EnergyDomeAutoResponseProfile>? AutoProfileChanged;

    public EnergyDomeWindow()
    {
        RobustXamlLoader.Load(this);
        InitializeStyleOverrides();
        InitializeOptionButtons();
        HookEvents();
    }

    public void ApplyState(EnergyDomeBuiState state)
    {
        _state = state;

        StatusValueLabel.Text = Loc.GetString(GetStatusLocKey(state));
        ToggleButton.Text = state.GlobalEnabled
            ? Loc.GetString("energy-dome-ui-toggle-off")
            : Loc.GetString("energy-dome-ui-toggle-on");

        var chargePercent = Math.Clamp((int) MathF.Round(state.ChargeFraction * 100f), 0, 100);
        ChargeLabel.Text = Loc.GetString("energy-dome-ui-charge", ("value", chargePercent));
        ChargeBar.Value = state.ChargeFraction;
        _chargeBarStyle.BackgroundColor = Color.InterpolateBetween(Color.FromHex("#d06a53"), Color.FromHex("#54c38a"), state.ChargeFraction);

        var overloadPercent = Math.Clamp((int) MathF.Round(state.OverloadFraction * 100f), 0, 100);
        OverloadLabel.Text = Loc.GetString("energy-dome-ui-overload", ("value", overloadPercent));
        OverloadBar.Value = state.OverloadFraction;
        _overloadBarStyle.BackgroundColor = Color.InterpolateBetween(Color.FromHex("#5aa96c"), Color.FromHex("#d76853"), state.OverloadFraction);

        PassiveDrawLabel.Text = Loc.GetString("energy-dome-ui-passive-draw", ("value", FormatFixedOneDecimal(state.PassiveDrawPerSecond)));
        UptimeLabel.Text = float.IsInfinity(state.PredictedUptimeSeconds)
            ? Loc.GetString("energy-dome-ui-uptime-unlimited")
            : Loc.GetString("energy-dome-ui-uptime-seconds", ("value", FormatFixedOneDecimal(Math.Max(0f, state.PredictedUptimeSeconds))));
        CooldownLabel.Text = state.CooldownRemainingSeconds > 0
            ? Loc.GetString("energy-dome-ui-cooldown-seconds", ("value", state.CooldownRemainingSeconds))
            : Loc.GetString("energy-dome-ui-cooldown-ready");

        ThreatHeatLabel.Text = Loc.GetString("energy-dome-ui-threat-heat", ("value", ToPercent(state.HeatThreatFraction)));
        ThreatPiercingLabel.Text = Loc.GetString("energy-dome-ui-threat-piercing", ("value", ToPercent(state.PiercingThreatFraction)));
        ThreatOtherLabel.Text = Loc.GetString("energy-dome-ui-threat-other", ("value", ToPercent(state.OtherThreatFraction)));
        ThreatHeatBar.Value = state.HeatThreatFraction;
        ThreatPiercingBar.Value = state.PiercingThreatFraction;
        ThreatOtherBar.Value = state.OtherThreatFraction;

        FriendlyInsideLabel.Text = Loc.GetString("energy-dome-ui-iff-friendly", ("count", state.FriendlyInside));
        HostileInsideLabel.Text = Loc.GetString("energy-dome-ui-iff-hostile", ("count", state.HostileInside));
        LinkedPeersLabel.Text = Loc.GetString("energy-dome-ui-linked-peers", ("count", state.LinkedPeerCount));

        ModeOption.Disabled = !state.UseModeProfiles;
        SizeOption.Disabled = !state.UseSizeColorProfiles;
        ColorOption.Disabled = !state.UseSizeColorProfiles || state.ColorSelectionLocked;
        WallSideOption.Disabled = state.Mode != EnergyDomeOperationMode.Wall;
        ProfileOption.Disabled = !state.UseAutoResponseProfiles;

        _suppressSelectionEvents = true;
        ModeOption.SelectId((int) state.Mode);
        SizeOption.SelectId((int) state.Size);
        ColorOption.SelectId((int) state.Color);
        WallSideOption.SelectId((int) state.WallSide);
        ProfileOption.SelectId((int) state.AutoResponseProfile);
        _suppressSelectionEvents = false;

        if (PreviewControl is EnergyDomePreviewControl preview)
            preview.ApplyState(state);

        if (LinkedMapControl is EnergyDomeLinkedCellMapControl linkedMap)
            linkedMap.ApplyNodes(state.LinkedNodes);

        RecommendationList.RemoveAllChildren();
        foreach (var key in state.RecommendationLocKeys)
        {
            RecommendationList.AddChild(new Label
            {
                Text = $"- {Loc.GetString(key)}"
            });
        }
    }

    private void InitializeStyleOverrides()
    {
        ChargeBar.ForegroundStyleBoxOverride = _chargeBarStyle;
        OverloadBar.ForegroundStyleBoxOverride = _overloadBarStyle;
        ThreatHeatBar.ForegroundStyleBoxOverride = _threatHeatStyle;
        ThreatPiercingBar.ForegroundStyleBoxOverride = _threatPiercingStyle;
        ThreatOtherBar.ForegroundStyleBoxOverride = _threatOtherStyle;
    }

    private void InitializeOptionButtons()
    {
        ModeOption.AddItem(Loc.GetString("energy-dome-mode-bubble"), (int) EnergyDomeOperationMode.Bubble);
        ModeOption.AddItem(Loc.GetString("energy-dome-mode-wall"), (int) EnergyDomeOperationMode.Wall);

        SizeOption.AddItem(Loc.GetString("energy-dome-size-small"), (int) EnergyDomeSizePreset.Small);
        SizeOption.AddItem(Loc.GetString("energy-dome-size-medium"), (int) EnergyDomeSizePreset.Medium);
        SizeOption.AddItem(Loc.GetString("energy-dome-size-huge"), (int) EnergyDomeSizePreset.Huge);

        ColorOption.AddItem(Loc.GetString("energy-dome-color-red"), (int) EnergyDomeColorPreset.Red);
        ColorOption.AddItem(Loc.GetString("energy-dome-color-blue"), (int) EnergyDomeColorPreset.Blue);

        WallSideOption.AddItem(Loc.GetString("energy-dome-wall-side-front"), (int) EnergyDomeWallSide.Front);
        WallSideOption.AddItem(Loc.GetString("energy-dome-wall-side-right"), (int) EnergyDomeWallSide.Right);
        WallSideOption.AddItem(Loc.GetString("energy-dome-wall-side-back"), (int) EnergyDomeWallSide.Back);
        WallSideOption.AddItem(Loc.GetString("energy-dome-wall-side-left"), (int) EnergyDomeWallSide.Left);

        ProfileOption.AddItem(Loc.GetString("energy-dome-ui-profile-balanced"), (int) EnergyDomeAutoResponseProfile.Balanced);
        ProfileOption.AddItem(Loc.GetString("energy-dome-ui-profile-sustain"), (int) EnergyDomeAutoResponseProfile.Sustain);
        ProfileOption.AddItem(Loc.GetString("energy-dome-ui-profile-hold-line"), (int) EnergyDomeAutoResponseProfile.HoldLine);
    }

    private void HookEvents()
    {
        ToggleButton.OnPressed += _ => TogglePressed?.Invoke();

        ModeOption.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);
            if (_suppressSelectionEvents)
                return;

            ModeChanged?.Invoke((EnergyDomeOperationMode) args.Id);
        };

        SizeOption.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);
            if (_suppressSelectionEvents)
                return;

            SizeChanged?.Invoke((EnergyDomeSizePreset) args.Id);
        };

        ColorOption.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);
            if (_suppressSelectionEvents)
                return;

            ColorChanged?.Invoke((EnergyDomeColorPreset) args.Id);
        };

        WallSideOption.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);
            if (_suppressSelectionEvents)
                return;

            WallSideChanged?.Invoke((EnergyDomeWallSide) args.Id);
        };

        ProfileOption.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);
            if (_suppressSelectionEvents)
                return;

            AutoProfileChanged?.Invoke((EnergyDomeAutoResponseProfile) args.Id);
        };
    }

    private static int ToPercent(float value)
    {
        return Math.Clamp((int) MathF.Round(value * 100f), 0, 100);
    }

    private static string FormatFixedOneDecimal(float value)
    {
        return MathF.Max(0f, value).ToString("0.0", CultureInfo.InvariantCulture);
    }

    private static string GetStatusLocKey(EnergyDomeBuiState state)
    {
        if (state.WaitingRecharge)
            return "energy-dome-status-cooldown";

        if (!state.Enabled)
            return "energy-dome-status-idle";

        if (state.Contested)
            return "energy-dome-status-contested";

        if (state.OverloadFraction >= 0.60f)
            return "energy-dome-status-stressed";

        return "energy-dome-status-active";
    }
}

