- type: job
  id: WH40KChaplain
  name: job-name-chaplain
  description: job-description-chaplain
  displayWeight: 60
  playTimeTracker: JobWH40KChaplain
  requirements:
    - !type:RoleTimeRequirement
      role: JobSergeant
      time: 1h
    - !type:RoleTimeRequirement
      role: JobGuardsman
      time: 2h
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: WH40KChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-wh40k-imperium-chaplain
  access:
  - Chapel
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
    - type: Reflect
      reflectProb: 0.4
      spread: 90
    - type: Vocal
      sounds:
        Male: W40KOffMale
        Female: W40KOffFemale
        Unsexed: W40KOffMale
- type: startingGear
  id: WH40KChaplainGear
  equipment:
    jumpsuit: WH40KClothingUniformJumpsuitChaplain
    shoes: ClothingShoesBootsChaplain
    belt: ClothingBeltChaplain
    ears: ClothingHeadsetVoxBackpackImperium
    outerClothing: ClothingOuterChaplainRobe
    neck: ClothingNeckInqusition
    id: ChaplainDogTag
    pocket1: WH40KBible
