- type: job
  id: Colonel
  name: job-name-colonel
  description: job-description-colonel
  playTimeTracker: JobColonel
  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: ColonelGear
  icon: "JobIconColonel"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadLeader
      - type: WH40KFriendlyFireAllowed
      - type: WH40KOfficerVoice
      - type: WH40KMoraleExecution
        cooldownSeconds: 1200
        auraRadius: 10
        buffDurationSeconds: 300
        speedMultiplier: 1.1
        outgoingDamageMultiplier: 1.1
        incomingDamageMultiplier: 0.9
      - type: Vocal
        sounds:
          Male: WH40KOfficerMaleHuman
          Female: WH40KOfficerFemaleHuman
          Unsexed: WH40KOfficerMaleHuman
  access:
  - Maintenance
  - External
  - Command
  - Medical
  - Cargo
  - Engineering
  - Research

- type: startingGear
  id: ColonelGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColonel
    gloves: ClothingHandsGlovesCombatColonel
    shoes: ClothingShoesGenBoots
    ears: ClothingHeadsetVoxBackpackImperium
    head: ClothingHeadOfficer
    belt: colbelt
    neck: Colonelcloak
    outerClothing: ClothingOuterArmorFlakVestGen
    pocket1: WH40KCommandTacticalMapTablet
    id: ColonelDogTag
  inhand:
    - WHPowerSaberImperial
