- type: job
  id: Colonel
  name: job-name-colonel
  description: job-description-colonel
  displayWeight: 130
  playTimeTracker: JobColonel
  requirements:
    - !type:RoleTimeRequirement
      role: JobLieutenant
      time: 4h
    - !type:OverallPlaytimeRequirement
      time: 24h
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: ColonelGear
  icon: "JobIconColonel"
  supervisors: job-supervisors-wh40k-imperium-colonel
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadLeader
      - type: WH40KFriendlyFireAllowed
      - type: WH40KOfficerVoice
      - type: WH40KMoraleExecution
        cooldownSeconds: 300
        auraRadius: 10
        buffDurationSeconds: 300
        speedMultiplier: 1.1
        outgoingDamageMultiplier: 1.1
        incomingDamageMultiplier: 0.9
      - type: Vocal
        sounds:
          Male: W40KOffMale
          Female: W40KOffFemale
          Unsexed: W40KOffMale
  access:
  - Maintenance
  - External
  - Command
  - Medical
  - Cargo
  - Engineering
  - Research

- type: startingGear
  id: ColonelGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColonel
    gloves: ClothingHandsGlovesCombatColonel
    shoes: ClothingShoesGenBoots
    ears: ClothingHeadsetVoxBackpackImperium
    head: ClothingHeadOfficer
    belt: colbelt
    outerClothing: ClothingOuterArmorFlakVestGen
    pocket1: WH40KCommandTacticalMapTablet
    id: ColonelDogTag
