- type: job
  id: Commissar
  name: job-name-commissar
  description: job-description-commissar
  displayWeight: 120
  playTimeTracker: JobCommissar
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 12h
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: CommissarGear
  icon: "JobIconCommissar"
  supervisors: job-supervisors-wh40k-imperium-commissar
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadLeader
      - type: WH40KFriendlyFireAllowed
      - type: WH40KCommissarVoice
      - type: WH40KMoraleExecution
        cooldownSeconds: 300
        auraRadius: 10
        buffDurationSeconds: 300
        speedMultiplier: 1.1
        outgoingDamageMultiplier: 1.1
        incomingDamageMultiplier: 0.9
      - type: Vocal
        sounds:
          Male: W40KComMale
          Female: W40KComFemale
          Unsexed: W40KComMale
  access:
  - Maintenance
  - External
  - Command
  - Medical
  - Cargo
  - Engineering
  - Research

- type: startingGear
  id: CommissarGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCommissar
    gloves: ClothingHandsGlovesCombatCommissar
    shoes: ClothingShoesCommissarBoots
    belt: Comibelt
    ears: ClothingHeadsetVoxBackpackImperium
    head: ClothingHeadCommissar
    outerClothing: ClothingOuterArmorCommissar
    id: CommissarDogTag
    pocket1: Bugle
    pocket2: WH40KCommandTacticalMapTablet
