- type: job
  id: Guardsman
  name: job-name-guardsman
  description: job-description-guardsman
  playTimeTracker: JobGuardsman
  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
      - Felinid
  startingGear: GuardsmanGear
  icon: "JobIconGuardsman"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadAssignable
      - type: WH40KMoraleExecutionTarget
      - type: WH40KGuardsmanVoice
      - type: Vocal
        sounds:
          Male: W40KGdMale
          Female: W40KGdFemale
          Unsexed: W40KGdMale
  access:
  - Maintenance
  - External

- type: startingGear
  id: GuardsmanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGuardsman
    back: ClothingBackpackGuard
    id: GuardsmanDogTag
