- type: job
  id: Medic
  name: job-name-medic
  description: job-description-medic
  displayWeight: 20
  playTimeTracker: JobMedic
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
      - Felinid
  startingGear: MedicGear
  icon: "JobIconMedic"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadAssignable
      - type: WH40KChirurgeonCpr
  access:
  - Maintenance
  - External
  - Medical

- type: startingGear
  id: MedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGuardsman
    back: ClothingBackpackGuard
    shoes: ClothingShoesAnkleBoots
    belt: guardbelt
    head: ClothingHeadHelmetFlakMed
    outerClothing: ClothingOuterArmorFlakVestMed
    id: MedicDogTag
