- type: job
  id: Psyker
  name: job-name-psyker
  description: job-description-psyker
  playTimeTracker: JobPsyker
  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: PsykerGear
  icon: "JobIconPsyker"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadAssignable
      - type: WH40KMoraleExecutionTarget
      - type: WH40KPsykerRole
  access:
  - Maintenance
  - External

- type: startingGear
  id: PsykerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPsykerSanctioned
    back: ClothingBackpackPsykerSatchel
    shoes: ClothingShoesPsykerBoots
    belt: psybelt
    head: ClothingHeadHelmetPsyker
    outerClothing: ClothingOuterPsykerWardCoat
    id: GuardsmanDogTag
