- type: job
  id: SergeantSWS
  name: job-name-sergeant-sws
  description: job-description-sergeant-sws
  playTimeTracker: JobSergeantSWS
  startingGear: SergeantGear
  icon: "JobIconSergeantSWS"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
