- type: job
  id: Sergeant
  name: job-name-sergeant
  description: job-description-sergeant
  displayWeight: 70
  playTimeTracker: JobSergeant
  requirements:
    - !type:RoleTimeRequirement
      role: JobGuardsman
      time: 1.5h
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: SergeantGear
  icon: "JobIconSergeant"
  supervisors: job-supervisors-wh40k-imperium-sergeant
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadLeader
      - type: WH40KFriendlyFireAllowed
      - type: WH40KOfficerVoice
      - type: WH40KMoraleExecution
        cooldownSeconds: 1200
        auraRadius: 10
        buffDurationSeconds: 300
        speedMultiplier: 1.1
        outgoingDamageMultiplier: 1.1
        incomingDamageMultiplier: 0.9
      - type: Vocal
        sounds:
          Male: W40KOffMale
          Female: W40KOffFemale
          Unsexed: W40KOffMale
  access:
  - Maintenance
  - External
  - Command
  - Medical
  - Cargo
  - Engineering
  - Research

- type: job
  id: SergeantSWS
  name: job-name-sergeant-sws
  description: job-description-sergeant-sws
  playTimeTracker: JobSergeantSWS
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: SergeantGear
  icon: "JobIconSergeantSWS"
  supervisors: job-supervisors-wh40k-imperium-sergeant
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadLeader
      - type: WH40KFriendlyFireAllowed
      - type: WH40KOfficerVoice
      - type: WH40KMoraleExecution
        cooldownSeconds: 1200
        auraRadius: 10
        buffDurationSeconds: 300
        speedMultiplier: 1.1
        outgoingDamageMultiplier: 1.1
        incomingDamageMultiplier: 0.9
      - type: Vocal
        sounds:
          Male: W40KOffMale
          Female: W40KOffFemale
          Unsexed: W40KOffMale
  access:
  - Maintenance
  - External
  - Command
  - Medical
  - Cargo
  - Engineering
  - Research

- type: job
  id: SergeantHWS
  name: job-name-sergeant-hws
  description: job-description-sergeant-hws
  playTimeTracker: JobSergeantHWS
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: SergeantGear
  icon: "JobIconSergeantHWS"
  supervisors: job-supervisors-wh40k-imperium-sergeant
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadLeader
      - type: WH40KFriendlyFireAllowed
      - type: WH40KOfficerVoice
      - type: WH40KMoraleExecution
        cooldownSeconds: 1200
        auraRadius: 10
        buffDurationSeconds: 300
        speedMultiplier: 1.1
        outgoingDamageMultiplier: 1.1
        incomingDamageMultiplier: 0.9
      - type: Vocal
        sounds:
          Male: W40KOffMale
          Female: W40KOffFemale
          Unsexed: W40KOffMale
  access:
  - Maintenance
  - External
  - Command
  - Medical
  - Cargo
  - Engineering
  - Research

- type: startingGear
  id: SergeantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGuardsman
    shoes: ClothingShoesAnkleBoots
    ears: ClothingHeadsetVoxBackpackImperium
    belt: offbelt
    eyes: ClothingEyesHudGuard
    pocket1: WH40KStandardTacticalMapTablet
    id: SergeantDogTag
