- type: job
  id: SpecialistSWS
  name: job-name-specialist-sws
  description: job-description-specialist-sws
  playTimeTracker: JobSpecialistSWS
  startingGear: GuardsmanSpesSpecGear
  icon: "JobIconSpecialistSWS"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: GuardsmanSpesSpecGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGuardsman
    back: ClothingBackpackGuard
    shoes: ClothingShoesAnkleBoots
    belt: guardbelt
    mask: ClothingMaskGasGuardsman
    head: ClothingHeadHelmetFlakResp
    eyes: ClothingEyesHudGuard
    outerClothing: ClothingOuterArmorFlakVestLight
    id: GuardsmanDogTag
