- type: job
  id: SpecialistHWS
  name: job-name-specialist-hws
  description: job-description-specialist-hws
  playTimeTracker: JobSpecialistHWS
  startingGear: GuardsmanSpecGear
  icon: "JobIconSpecialistHWS"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: GuardsmanHevSpecGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGuardsman
    back: ClothingBackpackGuard
    shoes: ClothingShoesAnkleBoots
    belt: guardbelt
    mask: ClothingMaskGasGuardsman
    head: ClothingHeadHelmetFlakResp
    eyes: ClothingEyesHudGuard
    outerClothing: ClothingOuterArmorFlakVest
    id: GuardsmanDogTag
