- type: job
  id: SpecialistHWS
  name: job-name-specialist-hws
  description: job-description-specialist-hws
  playTimeTracker: JobSpecialistHWS
  setPreference: false
  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: GuardsmanHevSpecGear
  icon: "JobIconSpecialistHWS"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadAssignable
      - type: WH40KGuardsmanVoice
      - type: Vocal
        sounds:
          Male: WH40KGuardsmanMaleHuman
          Female: WH40KGuardsmanFemaleHuman
          Unsexed: WH40KGuardsmanMaleHuman
  access:
  - Maintenance
  - External

- type: startingGear
  id: GuardsmanHevSpecGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGuardsman
    back: ClothingBackpackGuard
    shoes: ClothingShoesAnkleBoots
    belt: guardbelt
    mask: ClothingMaskGasGuardsman
    head: ClothingHeadHelmetFlakResp
    eyes: ClothingEyesHudGuard
    outerClothing: ClothingOuterArmorFlakVest
    pocket1: WH40KStandardTacticalMapTablet
    id: GuardsmanDogTag

