- type: job
  id: SpecialistSWS
  name: job-name-specialist-sws
  description: job-description-specialist-sws
  playTimeTracker: JobSpecialistSWS
  setPreference: false
  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: GuardsmanSpesSpecGear
  icon: "JobIconSpecialistSWS"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadAssignable
      - type: WH40KGuardsmanVoice
      - type: Vocal
        sounds:
          Male: WH40KGuardsmanMaleHuman
          Female: WH40KGuardsmanFemaleHuman
          Unsexed: WH40KGuardsmanMaleHuman
  access:
  - Maintenance
  - External

- type: startingGear
  id: GuardsmanSpesSpecGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGuardsman
    back: ClothingBackpackGuard
    shoes: ClothingShoesAnkleBoots
    belt: guardbelt
    mask: ClothingMaskGasGuardsman
    head: ClothingHeadHelmetFlakResp
    eyes: ClothingEyesHudGuard
    outerClothing: ClothingOuterArmorFlakVestLight
    pocket1: WH40KStandardTacticalMapTablet
    id: GuardsmanDogTag

