- type: job
  id: Tanker
  name: job-name-tanker
  description: job-description-tanker
  playTimeTracker: JobTanker
  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: GuardsmanGear
  icon: "JobIconTanker"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadAssignable
      - type: WH40KGuardsmanVoice
      - type: Vocal
        sounds:
          Male: W40KGdMale
          Female: W40KGdFemale
          Unsexed: W40KGdMale
  access:
  - Maintenance
  - External
  - Engineering

