- type: job
  id: Tanker
  name: job-name-tanker
  description: job-description-tanker
  playTimeTracker: JobTanker
  startingGear: GuardsmanGear
  icon: "JobIconTanker"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
