- type: job
  id: TankComm
  name: job-name-tank-comm
  description: job-description-tank-comm
  playTimeTracker: JobTankComm
  setPreference: false
  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: TankCommGear
  icon: "JobIconTankComm"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadLeader
  access:
  - Maintenance
  - External
  - Command
  - Medical
  - Cargo
  - Engineering
  - Research

- type: startingGear
  id: TankCommGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOfficer
    shoes: ClothingShoesGenBoots
    ears: ClothingHeadsetVoxBackpackImperium
    belt: offbelt
    head: ClothingHeadOfficer
    outerClothing: ClothingOuterArmorOfficer
    pocket1: WH40KCommandTacticalMapTablet
    id: TankCommDogTag

