- type: job
  id: TitheSupplier
  name: job-name-tithe-supplier
  description: job-description-tithe-supplier
  displayWeight: 40
  playTimeTracker: JobTitheSupplier
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
      - Felinid
  startingGear: TitheSupplierGear
  icon: "JobIconCargo"
  supervisors: job-supervisors-wh40k-imperium-munitorum
  canBeAntag: false
  access:
  - Maintenance
  - External
  - Cargo

- type: job
  id: MunitorumOfficer
  name: job-name-munitorum-officer
  description: job-description-munitorum-officer
  displayWeight: 90
  playTimeTracker: JobMunitorumOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobTitheSupplier
      time: 2h
    - !type:RoleTimeRequirement
      role: JobVoxScout
      time: 0.5h
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
      - Felinid
  startingGear: MunitorumOfficerGear
  icon: "JobIconCargoOfficer"
  supervisors: job-supervisors-wh40k-imperium-munitorum
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadLeader
      - type: WH40KFriendlyFireAllowed
      - type: WH40KMoraleExecution
        cooldownSeconds: 1200
        auraRadius: 10
        buffDurationSeconds: 300
        speedMultiplier: 1.1
        outgoingDamageMultiplier: 1.1
        incomingDamageMultiplier: 0.9
      - type: Vocal
        sounds:
          Male: W40KOffMale
          Female: W40KOffFemale
          Unsexed: W40KOffMale
  access:
  - Maintenance
  - External
  - Command
  - Medical
  - Cargo
  - Engineering
  - Research

- type: startingGear
  id: TitheSupplierGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGuardsman
    back: ClothingBackpackGuard
    shoes: ClothingShoesAnkleBoots
    belt: guardbelt
    head: ClothingHeadHelmetFlak
    ears: ClothingHeadsetVoxBackpackImperium
    outerClothing: ClothingOuterArmorMunitorumVest
    pocket1: WH40KStandardTacticalMapTablet
    id: TitheSupplierDogTag

- type: startingGear
  id: MunitorumOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGuardsman
    back: ClothingBackpackGuard
    shoes: ClothingShoesAnkleBoots
    belt: guardbelt
    head: ClothingHeadHelmetFlak
    ears: ClothingHeadsetVoxBackpackImperium
    outerClothing: ClothingOuterArmorMunitorumCoat
    pocket1: WH40KStandardTacticalMapTablet
    id: MunitorumOfficerDogTag
