- type: job
  id: VoxScout
  name: job-name-vox-scout
  description: job-description-vox-scout
  displayWeight: 30
  playTimeTracker: JobVoxScout
  requirements:
    - !type:RoleTimeRequirement
      role: JobTitheSupplier
      time: 1h
    - !type:RoleTimeRequirement
      role: JobGuardsman
      time: 1h
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
      - Felinid
  startingGear: VoxScoutGear
  icon: "JobIconVoxScout"
  supervisors: job-supervisors-wh40k-imperium-line
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadAssignable
      - type: WH40KMoraleExecutionTarget
      - type: WH40KGuardsmanVoice
      - type: Vocal
        sounds:
          Male: W40KGdMale
          Female: W40KGdFemale
          Unsexed: W40KGdMale
  access:
  - Maintenance
  - External

- type: startingGear
  id: VoxScoutGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGuardsman
    back: ClothingBackpackVox
    ears: ClothingHeadsetVoxBackpackImperium
    shoes: ClothingShoesAnkleBoots
    belt: guardbelt
    head: ClothingHeadHelmetFlak
    outerClothing: ClothingOuterArmorFlakVestLight
    pocket1: Binoculars
    pocket2: WH40KStandardTacticalMapTablet
    id: VoxScoutDogTag
