- type: wh40kStrategicPointProfile
  id: WH40KStrategicPointResource
  pointType: Resource
  upgrades:
    2:
      seconds: 30
      materials:
        Steel: 10
        Glass: 10
    3:
      seconds: 90
      materials:
        Steel: 20
        Glass: 20
        Uranium: 5
  tiers:
    1:
      maxHp: 750
      teamXpIncome: 1
      fundsIncome: 90
      destroyTeamXpReward: 5
      destroyInfluenceReward: 1
    2:
      maxHp: 1500
      teamXpIncome: 2
      fundsIncome: 500
      destroyTeamXpReward: 12
      destroyInfluenceReward: 3
    3:
      maxHp: 2000
      teamXpIncome: 3
      fundsIncome: 1000
      destroyTeamXpReward: 25
      destroyInfluenceReward: 6

- type: wh40kStrategicPointProfile
  id: WH40KStrategicPointResearch
  pointType: Research
  upgrades:
    2:
      seconds: 30
      materials:
        Steel: 10
        Glass: 10
    3:
      seconds: 90
      materials:
        Steel: 20
        Glass: 20
        Plasma: 5
  tiers:
    1:
      maxHp: 750
      teamXpIncome: 1
      researchIncome: 20
      artifactIncome: 1
      destroyTeamXpReward: 5
      destroyInfluenceReward: 1
    2:
      maxHp: 1500
      teamXpIncome: 2
      researchIncome: 60
      artifactIncome: 2
      destroyTeamXpReward: 12
      destroyInfluenceReward: 3
    3:
      maxHp: 2000
      teamXpIncome: 3
      researchIncome: 120
      artifactIncome: 3
      destroyTeamXpReward: 25
      destroyInfluenceReward: 6

- type: wh40kStrategicPointProfile
  id: WH40KStrategicPointInfluence
  pointType: Influence
  upgrades:
    2:
      seconds: 30
      materials:
        Steel: 10
        Glass: 10
    3:
      seconds: 90
      materials:
        Steel: 20
        Glass: 20
        Plasteel: 5
  tiers:
    1:
      maxHp: 750
      teamXpIncome: 1
      influenceIncome: 1
      destroyTeamXpReward: 5
      destroyInfluenceReward: 1
    2:
      maxHp: 1500
      teamXpIncome: 2
      influenceIncome: 5
      destroyTeamXpReward: 12
      destroyInfluenceReward: 3
    3:
      maxHp: 2000
      teamXpIncome: 3
      influenceIncome: 10
      destroyTeamXpReward: 25
      destroyInfluenceReward: 6
