- type: wh40kStrategicPointProfile
  id: WH40KStrategicPointResource
  pointType: Resource
  upgrades:
    2:
      seconds: 30
      materials:
        Steel: 20
        Glass: 20
    3:
      seconds: 60
      materials:
        Steel: 40
        Glass: 40
        Uranium: 10
  tiers:
    1:
      maxHp: 250
      teamXpIncome: 1
      fundsIncome: 30
      destroyTeamXpReward: 5
      destroyInfluenceReward: 1
    2:
      maxHp: 500
      teamXpIncome: 2
      fundsIncome: 70
      destroyTeamXpReward: 12
      destroyInfluenceReward: 3
    3:
      maxHp: 750
      teamXpIncome: 3
      fundsIncome: 130
      destroyTeamXpReward: 25
      destroyInfluenceReward: 6

- type: wh40kStrategicPointProfile
  id: WH40KStrategicPointResearch
  pointType: Research
  upgrades:
    2:
      seconds: 30
      materials:
        Steel: 20
        Glass: 20
    3:
      seconds: 60
      materials:
        Steel: 40
        Glass: 40
        Plasma: 10
  tiers:
    1:
      maxHp: 250
      teamXpIncome: 1
      researchIncome: 15
      destroyTeamXpReward: 5
      destroyInfluenceReward: 1
    2:
      maxHp: 500
      teamXpIncome: 2
      researchIncome: 40
      destroyTeamXpReward: 12
      destroyInfluenceReward: 3
    3:
      maxHp: 750
      teamXpIncome: 3
      researchIncome: 80
      destroyTeamXpReward: 25
      destroyInfluenceReward: 6

- type: wh40kStrategicPointProfile
  id: WH40KStrategicPointInfluence
  pointType: Influence
  upgrades:
    2:
      seconds: 30
      materials:
        Steel: 20
        Glass: 20
    3:
      seconds: 60
      materials:
        Steel: 40
        Glass: 40
        Plasteel: 10
  tiers:
    1:
      maxHp: 250
      teamXpIncome: 1
      influenceIncome: 1
      destroyTeamXpReward: 5
      destroyInfluenceReward: 1
    2:
      maxHp: 500
      teamXpIncome: 2
      influenceIncome: 2
      destroyTeamXpReward: 12
      destroyInfluenceReward: 3
    3:
      maxHp: 750
      teamXpIncome: 3
      influenceIncome: 4
      destroyTeamXpReward: 25
      destroyInfluenceReward: 6
