using Content.Client.Localization;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminTab : Control, ILocalizedControl
    {
        public AdminTab()
        {
            RobustXamlLoader.Load(this);
            Relocalize();
        }

        public void Relocalize()
        {
            BanPanelButton.Text = Loc.GetString("admin-player-actions-window-ban");
            MutePanelButton.Text = Loc.GetString("admin-player-actions-window-mute");
            AdminGhostButton.Text = Loc.GetString("admin-player-actions-window-admin-ghost");
            PermissionsButton.Text = Loc.GetString("admin-player-actions-window-permissions");
            AnnounceButton.Text = Loc.GetString("admin-player-actions-window-announce");
            ShuttleButton.Text = Loc.GetString("admin-player-actions-window-shuttle");
            AdminLogsButton.Text = Loc.GetString("admin-player-actions-window-admin-logs");
            ScreenCheckButton.Text = Loc.GetString("admin-player-actions-window-screen-check");
            AdminFaxButton.Text = Loc.GetString("admin-player-actions-window-admin-fax");
            AdminChatButton.Text = Loc.GetString("admin-player-actions-window-admin-chat");
        }
    }
}
