using System;
using Content.Client._WH40K.Interface;
using Content.Client.Localization;
using Content.Client.UserInterface.Controls;
using Content.Shared._WH40K.Psyker;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._WH40K.Psyker.UI;

[GenerateTypedNameReferences]
public sealed partial class WH40KChaosSkrizhalCultistWindow : FancyWindow, ILocalizedControl
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly SpriteSystem _sprite;

    private readonly StyleBoxFlat _levelProgressBackgroundStyle = new()
    {
        BackgroundColor = Color.FromHex("#1A2430")
    };

    private readonly StyleBoxFlat _levelProgressForegroundStyle = new()
    {
        BackgroundColor = Color.FromHex("#60748B")
    };

    private readonly StyleBoxFlat _warpProgressBackgroundStyle = new()
    {
        BackgroundColor = Color.FromHex("#111A22")
    };

    private readonly StyleBoxFlat _warpProgressForegroundStyle = new()
    {
        BackgroundColor = Color.FromHex("#5579A5")
    };

    private readonly StyleBoxFlat _instabilityProgressBackgroundStyle = new()
    {
        BackgroundColor = Color.FromHex("#111A22")
    };

    private readonly StyleBoxFlat _instabilityProgressForegroundStyle = new()
    {
        BackgroundColor = Color.FromHex("#A86058")
    };

    private readonly StyleBoxFlat _rootFrameStyle;
    private readonly StyleBoxFlat _headerStyle;
    private readonly StyleBoxFlat _leaderSealStyle;
    private readonly StyleBoxFlat _telemetryStyle;
    private readonly StyleBoxFlat _directiveStyle;
    private readonly StyleBoxFlat _abilitiesStyle;
    private readonly StyleBoxFlat _bottomAccentStyle;
    private readonly StyleBoxFlat[] _cardStyles = new StyleBoxFlat[4];

    private WH40KChaosSkrizhalCultistBuiState? _state;

    public WH40KChaosSkrizhalCultistWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entityManager.System<SpriteSystem>();

        _rootFrameStyle = (StyleBoxFlat) RootFramePanel.PanelOverride!;
        _headerStyle = (StyleBoxFlat) HeaderPanel.PanelOverride!;
        _leaderSealStyle = (StyleBoxFlat) LeaderSealPanel.PanelOverride!;
        _telemetryStyle = (StyleBoxFlat) TelemetryPanel.PanelOverride!;
        _directiveStyle = (StyleBoxFlat) DirectivePanel.PanelOverride!;
        _abilitiesStyle = (StyleBoxFlat) AbilitiesPanel.PanelOverride!;
        _bottomAccentStyle = (StyleBoxFlat) BottomAccent.PanelOverride!;

        _cardStyles[0] = CreateCardStyle();
        _cardStyles[1] = CreateCardStyle();
        _cardStyles[2] = CreateCardStyle();
        _cardStyles[3] = CreateCardStyle();
        GiftOnePanel.PanelOverride = _cardStyles[0];
        GiftTwoPanel.PanelOverride = _cardStyles[1];
        GiftThreePanel.PanelOverride = _cardStyles[2];
        PassivePanel.PanelOverride = _cardStyles[3];

        LevelProgressBar.BackgroundStyleBoxOverride = _levelProgressBackgroundStyle;
        LevelProgressBar.ForegroundStyleBoxOverride = _levelProgressForegroundStyle;
        WarpChargeBar.BackgroundStyleBoxOverride = _warpProgressBackgroundStyle;
        WarpChargeBar.ForegroundStyleBoxOverride = _warpProgressForegroundStyle;
        WarpInstabilityBar.BackgroundStyleBoxOverride = _instabilityProgressBackgroundStyle;
        WarpInstabilityBar.ForegroundStyleBoxOverride = _instabilityProgressForegroundStyle;

        Relocalize();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_state != null)
            RefreshLiveTelemetry(_state);
    }

    public void Relocalize()
    {
        Title = Loc.GetString("wh40k-chaos-cultist-title");
        HeaderKickerLabel.Text = WH40KUiChrome.DecorateTitle(WH40KUiChrome.DiamondOutline, Loc.GetString("wh40k-chaos-cultist-kicker"));
        LeaderTitleLabel.Text = Loc.GetString("wh40k-chaos-cultist-leader-title");
        TelemetryTitleLabel.Text = WH40KUiChrome.DecorateTitle(WH40KUiChrome.Eye, Loc.GetString("wh40k-chaos-cultist-telemetry-title"));
        DirectiveTitleLabel.Text = WH40KUiChrome.DecorateTitle(WH40KUiChrome.Cog, Loc.GetString("wh40k-chaos-cultist-directive-title"));
        AbilitiesTitleLabel.Text = WH40KUiChrome.DecorateTitle(WH40KUiChrome.Blade, Loc.GetString("w40k-ch-abilities-header"));

        if (_state != null)
            ApplyState(_state);
    }

    public void ApplyState(WH40KChaosSkrizhalCultistBuiState state)
    {
        var firstApply = _state == null;
        _state = state;

        if (firstApply)
            PlayIntroAnimations();

        var patronLoc = Loc.GetString(WH40KChaosUiShared.GetPatronLocKey(state.Patron));
        var branchTitle = Loc.GetString(WH40KChaosUiShared.GetBranchTitleKey(state.Patron));
        var xpProgress = state.NextLevelXp <= 0f
            ? 1f
            : Math.Clamp(state.LevelXp / state.NextLevelXp, 0f, 1f);

        PathTitleLabel.Text = WH40KUiChrome.DecorateTitle(WH40KUiChrome.Eye, branchTitle);
        HeaderStatusLabel.Text = ResolveHeaderStatusText(state);
        LeaderNameLabel.Text = ResolveLeaderDisplayName(state);
        LeaderStatusLabel.Text = ResolveLeaderSoulStatusText(state);

        PatronLabel.Text = Loc.GetString("w40k-ch-patron", ("patron", patronLoc));
        LevelLabel.Text = Loc.GetString("w40k-ch-level", ("level", state.Level), ("max", state.MaxLevel));
        XpLabel.Text = Loc.GetString(
            "w40k-ch-xp",
            ("current", WH40KChaosUiShared.FormatNumber(state.LevelXp)),
            ("next", WH40KChaosUiShared.FormatNumber(state.NextLevelXp)));
        PassiveIncomeLabel.Text = Loc.GetString(
            "w40k-ch-passive-income",
            ("xp", WH40KChaosUiShared.FormatNumber(state.PassiveXpPerTick)),
            ("seconds", state.PassiveXpIntervalSeconds));
        LevelProgressBar.Value = xpProgress;

        DirectiveLeadLabel.Text = ResolveDirectiveStatusText(state);
        DirectiveDoctrineLabel.Text = state.PrimaryGiftSlot != 0
            ? Loc.GetString(
                "wh40k-chaos-cultist-footer-summary-primary",
                ("gift", Loc.GetString(WH40KChaosUiShared.GetGiftTitleKey(state.Patron, state.PrimaryGiftSlot))))
            : Loc.GetString("wh40k-chaos-cultist-footer-summary-unset");

        ApplyGiftCard(GiftOnePanel, 1, state, _cardStyles[0], GiftOneIcon, GiftOneBadgeLabel, GiftOneTitleLabel, GiftOneDescriptionLabel, GiftOneStatusLabel);
        ApplyGiftCard(GiftTwoPanel, 2, state, _cardStyles[1], GiftTwoIcon, GiftTwoBadgeLabel, GiftTwoTitleLabel, GiftTwoDescriptionLabel, GiftTwoStatusLabel);
        ApplyGiftCard(GiftThreePanel, 3, state, _cardStyles[2], GiftThreeIcon, GiftThreeBadgeLabel, GiftThreeTitleLabel, GiftThreeDescriptionLabel, GiftThreeStatusLabel);
        ApplyPassiveCard(state);

        ApplyAccent(state.Patron);
        RefreshLiveTelemetry(state);
    }

    private void RefreshLiveTelemetry(WH40KChaosSkrizhalCultistBuiState state)
    {
        var patron = state.Patron;
        var progression = default(WH40KChaosGiftProgressionComponent?);
        var warp = default(WH40KWarpResourceComponent?);
        var instability = default(WH40KWarpInstabilityComponent?);

        if (_player.LocalEntity is { Valid: true } uid)
        {
            progression = _entityManager.GetComponentOrNull<WH40KChaosGiftProgressionComponent>(uid);
            warp = _entityManager.GetComponentOrNull<WH40KWarpResourceComponent>(uid);
            instability = _entityManager.GetComponentOrNull<WH40KWarpInstabilityComponent>(uid);
            if (progression != null && progression.AttunedPatron != WH40KChaosPatron.None)
                patron = progression.AttunedPatron;
        }

        var warpCurrent = warp?.CurrentCharge ?? 0f;
        var warpMax = Math.Max(1f, warp?.MaxCharge ?? 100f);
        var instabilityCurrent = instability?.CurrentInstability ?? 0f;
        var instabilityMax = Math.Max(1f, instability?.MaxInstability ?? 100f);
        var warpFraction = Math.Clamp(warpCurrent / warpMax, 0f, 1f);
        var instabilityFraction = Math.Clamp(instabilityCurrent / instabilityMax, 0f, 1f);
        WarpChargeLabel.Text = Loc.GetString(
            "w40k-ch-telemetry-warp",
            ("current", WH40KChaosUiShared.FormatNumber(warpCurrent)),
            ("max", WH40KChaosUiShared.FormatNumber(warpMax)));
        WarpInstabilityLabel.Text = Loc.GetString(
            "w40k-ch-telemetry-instability",
            ("current", WH40KChaosUiShared.FormatNumber(instabilityCurrent)),
            ("max", WH40KChaosUiShared.FormatNumber(instabilityMax)));

        WarpChargeBar.Value = warpFraction;
        WarpInstabilityBar.Value = instabilityFraction;
        ApplyAccent(patron, instabilityFraction);
    }

    private void ApplyGiftCard(
        PanelContainer panel,
        int slot,
        WH40KChaosSkrizhalCultistBuiState state,
        StyleBoxFlat style,
        TextureRect iconRect,
        Label badgeLabel,
        Label titleLabel,
        RichTextLabel descriptionLabel,
        Label statusLabel)
    {
        var unlocked = IsGiftSlotUnlocked(state, slot);
        var primary = state.PrimaryGiftSlot == slot;

        panel.Visible = unlocked;
        if (!unlocked)
            return;

        iconRect.Texture = _sprite.Frame0(WH40KChaosUiShared.GetGiftIconSpecifier(state.Patron, slot));
        badgeLabel.Text = ResolveGiftBadge(primary, unlocked);
        titleLabel.Text = Loc.GetString(WH40KChaosUiShared.GetGiftTitleKey(state.Patron, slot));
        descriptionLabel.Text = Loc.GetString(WH40KChaosUiShared.GetGiftDescriptionKey(state.Patron, slot));
        statusLabel.Text = ResolveGiftStatus(state, slot);

        UpdateCardStyle(style, state.Patron, unlocked, primary);
    }

    private void ApplyPassiveCard(WH40KChaosSkrizhalCultistBuiState state)
    {
        PassiveIcon.Texture = _sprite.Frame0(WH40KChaosUiShared.GetPatronIconSpecifier(state.Patron));
        PassiveBadgeLabel.Text = Loc.GetString("wh40k-chaos-cultist-card-badge-passive");
        PassiveTitleLabel.Text = Loc.GetString("w40k-ch-passive-title");
        PassiveDescriptionLabel.Text = Loc.GetString("w40k-ch-passive-description");
        PassiveStatusLabel.Text = Loc.GetString("w40k-ch-passive-status-open-readonly");

        UpdateCardStyle(_cardStyles[3], state.Patron, true, false);
    }

    private void ApplyAccent(WH40KChaosPatron patron, float instabilityFraction = 0f)
    {
        var accent = WH40KChaosUiShared.ResolvePatronAccent(patron);
        var brightAccent = WH40KChaosUiShared.LightenColor(accent, 0.28f);

        _levelProgressForegroundStyle.BackgroundColor = accent;
        _warpProgressForegroundStyle.BackgroundColor = WH40KChaosUiShared.MixColor(Color.FromHex("#2F77DC"), accent, 0.35f);
        _instabilityProgressForegroundStyle.BackgroundColor = WH40KChaosUiShared.MixColor(Color.FromHex("#C25A44"), accent, 0.18f + instabilityFraction * 0.12f);
        _rootFrameStyle.BackgroundColor = WH40KChaosUiShared.MixColor(Color.FromHex("#081018"), accent, 0.05f);
        _rootFrameStyle.BorderColor = accent.WithAlpha(0.42f);
        _headerStyle.BackgroundColor = WH40KChaosUiShared.MixColor(Color.FromHex("#101A24"), accent, 0.08f);
        _headerStyle.BorderColor = accent.WithAlpha(0.54f);
        _leaderSealStyle.BackgroundColor = WH40KChaosUiShared.MixColor(Color.FromHex("#131D28"), accent, 0.10f);
        _leaderSealStyle.BorderColor = accent.WithAlpha(0.62f);
        _telemetryStyle.BackgroundColor = WH40KChaosUiShared.MixColor(Color.FromHex("#0F1822"), accent, 0.09f);
        _telemetryStyle.BorderColor = accent.WithAlpha(0.54f);
        _directiveStyle.BackgroundColor = WH40KChaosUiShared.MixColor(Color.FromHex("#121B25"), accent, 0.09f);
        _directiveStyle.BorderColor = accent.WithAlpha(0.52f);
        _abilitiesStyle.BackgroundColor = WH40KChaosUiShared.MixColor(Color.FromHex("#111821"), accent, 0.08f);
        _abilitiesStyle.BorderColor = accent.WithAlpha(0.48f);
        _bottomAccentStyle.BackgroundColor = brightAccent;

        PathTitleLabel.FontColorOverride = brightAccent;
        LeaderNameLabel.FontColorOverride = WH40KChaosUiShared.LightenColor(accent, 0.58f);
        TelemetryTitleLabel.FontColorOverride = brightAccent;
        DirectiveTitleLabel.FontColorOverride = WH40KChaosUiShared.MixColor(Color.FromHex("#D5C086"), brightAccent, 0.32f);

        WH40KUiChrome.StartLoopingPulse(BottomAccent, "cultist-accent", brightAccent.WithAlpha(0.55f), brightAccent, 4.5f);
        WH40KUiChrome.StartLoopingPulse(LeaderSealPanel, "cultist-seal", Color.White, WH40KChaosUiShared.MixColor(Color.White, brightAccent, 0.22f), 5.5f);
    }

    private void PlayIntroAnimations()
    {
        WH40KUiChrome.PlayFadeIn(HeaderPanel, "cultist-header-fade", 0.18f);
        WH40KUiChrome.PlayFadeIn(TelemetryPanel, "cultist-telemetry-fade", 0.2f, 0.05f);
        WH40KUiChrome.PlayFadeIn(DirectivePanel, "cultist-directive-fade", 0.2f, 0.09f);
        WH40KUiChrome.PlayFadeIn(GiftOnePanel, "cultist-card-1", 0.16f, 0.04f);
        WH40KUiChrome.PlayFadeIn(GiftTwoPanel, "cultist-card-2", 0.16f, 0.08f);
        WH40KUiChrome.PlayFadeIn(GiftThreePanel, "cultist-card-3", 0.16f, 0.12f);
        WH40KUiChrome.PlayFadeIn(PassivePanel, "cultist-card-4", 0.16f, 0.16f);
    }

    private static StyleBoxFlat CreateCardStyle()
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#131D28"),
            BorderColor = Color.FromHex("#425769"),
            BorderThickness = new Thickness(1f),
            ContentMarginLeftOverride = 10f,
            ContentMarginTopOverride = 8f,
            ContentMarginRightOverride = 10f,
            ContentMarginBottomOverride = 8f,
        };
    }

    private static void UpdateCardStyle(StyleBoxFlat style, WH40KChaosPatron patron, bool unlocked, bool primary)
    {
        var accent = WH40KChaosUiShared.ResolvePatronAccent(patron);
        var baseColor = Color.FromHex("#131D28");
        style.BackgroundColor = unlocked
            ? WH40KChaosUiShared.MixColor(baseColor, accent, primary ? 0.24f : 0.16f)
            : baseColor;
        style.BorderColor = primary
            ? Color.FromHex("#D7BC72")
            : unlocked
                ? accent.WithAlpha(0.74f)
                : Color.FromHex("#425769");
        style.BorderThickness = new Thickness(primary ? 2f : 1f);
    }

    private static string ResolveGiftBadge(bool primary, bool unlocked)
    {
        if (primary)
            return Loc.GetString("wh40k-chaos-cultist-card-badge-primary");

        return Loc.GetString(unlocked
            ? "wh40k-chaos-cultist-card-badge-unlocked"
            : "wh40k-chaos-cultist-card-badge-dormant");
    }

    private static string ResolveGiftStatus(WH40KChaosSkrizhalCultistBuiState state, int slot)
    {
        if (IsGiftSlotUnlocked(state, slot))
        {
            return Loc.GetString(slot == state.PrimaryGiftSlot
                ? "w40k-ch-card-status-primary-selected-readonly"
                : "w40k-ch-card-status-opened-readonly");
        }

        return Loc.GetString(state.HasActiveLeader
            ? "w40k-ch-card-status-awaiting-leader"
            : "w40k-ch-card-status-no-leader");
    }

    private static string ResolveHeaderStatusText(WH40KChaosSkrizhalCultistBuiState state)
    {
        if (state.HasActiveLeader)
            return Loc.GetString("wh40k-chaos-cultist-status-following");

        return Loc.GetString(state.AwaitingLeaderSuccessor
            ? "wh40k-chaos-cultist-status-awaiting"
            : "wh40k-chaos-cultist-status-unled");
    }

    private static string ResolveDirectiveStatusText(WH40KChaosSkrizhalCultistBuiState state)
    {
        if (state.HasActiveLeader)
            return Loc.GetString("wh40k-chaos-cultist-directive-following");

        return Loc.GetString(state.AwaitingLeaderSuccessor
            ? "wh40k-chaos-cultist-directive-awaiting"
            : "wh40k-chaos-cultist-directive-unled");
    }

    private static string ResolveLeaderSoulStatusText(WH40KChaosSkrizhalCultistBuiState state)
    {
        if (state.HasActiveLeader)
            return Loc.GetString("wh40k-chaos-cultist-leader-present");

        return Loc.GetString(state.AwaitingLeaderSuccessor
            ? "wh40k-chaos-cultist-leader-awaiting"
            : "wh40k-chaos-cultist-leader-missing");
    }

    private static string ResolveLeaderDisplayName(WH40KChaosSkrizhalCultistBuiState state)
    {
        if (state.HasActiveLeader)
            return state.ActiveLeaderName;

        return Loc.GetString(state.AwaitingLeaderSuccessor
            ? "wh40k-chaos-cultist-leader-awaiting-name"
            : "wh40k-chaos-selector-no-leader");
    }

    private static bool IsGiftSlotUnlocked(WH40KChaosSkrizhalCultistBuiState state, int slot)
    {
        return slot switch
        {
            1 => state.GiftSlotOneUnlocked,
            2 => state.GiftSlotTwoUnlocked,
            3 => state.GiftSlotThreeUnlocked,
            _ => false,
        };
    }

}
