using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client._WH40K.Interface;
using Content.Client.Localization;
using Content.Client.UserInterface.Controls;
using Content.Shared._WH40K.Psyker;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Input;
using Robust.Shared.Player;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._WH40K.Psyker.UI;

[GenerateTypedNameReferences]
public sealed partial class WH40KChaosSkrizhalPatronSelectorWindow : FancyWindow, ILocalizedControl
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly SharedAudioSystem _audio;
    private readonly SpriteSystem _sprite;

    private static readonly WH40KChaosPatron[] CardOrder =
    {
        WH40KChaosPatron.Khorne,
        WH40KChaosPatron.Nurgle,
        WH40KChaosPatron.Slaanesh,
        WH40KChaosPatron.Tzeentch,
    };

    private const float CardGap = 42f;
    private const float CardHorizontalPadding = 72f;
    private const float CardTopPadding = 56f;
    private const float CardBottomPadding = 18f;
    private const float SigilEchoSize = 28f;
    private const float WarpBackdropPrimarySize = 368f;
    private const float WarpBackdropSecondarySize = 292f;
    private const float WarpRippleInset = 24f;
    private const float BurstDuration = 0.46f;
    private const float Tau = MathF.PI * 2f;
    private static readonly AudioParams PatronThemeAudioParams = AudioParams.Default.WithVolume(-10f);

    private WH40KChaosSkrizhalPatronSelectorBuiState? _latestState;
    private WH40KChaosPatron _previewPatron = WH40KChaosPatron.Khorne;
    private WH40KChaosPatron _hoverThemePatron = WH40KChaosPatron.None;
    private float _animationTime;
    private float _burstStartedAt = -100f;
    private float _burstIntensity;
    private int _burstSerial;
    private WH40KChaosPatron _burstPatron = WH40KChaosPatron.None;
    private EntityUid? _hoverThemeStream;

    private readonly Dictionary<WH40KChaosPatron, PanelContainer> _entryPanels = new();
    private readonly Dictionary<WH40KChaosPatron, PanelContainer> _entryShadowPanels = new();
    private readonly Dictionary<WH40KChaosPatron, Button> _entryButtons = new();
    private readonly Dictionary<WH40KChaosPatron, PanelContainer> _entryAccentBars = new();
    private readonly Dictionary<WH40KChaosPatron, PanelContainer> _entryHaloPanels = new();
    private readonly Dictionary<WH40KChaosPatron, PanelContainer[]> _entryGiftPanels = new();
    private readonly Dictionary<WH40KChaosPatron, TextureRect[]> _entryGiftIcons = new();
    private readonly Dictionary<WH40KChaosPatron, RichTextLabel> _entryGiftSummaryLabels = new();
    private readonly Dictionary<WH40KChaosPatron, PanelContainer> _entryLeaderPanels = new();
    private readonly Dictionary<WH40KChaosPatron, Label> _entryStatusLabels = new();
    private readonly Dictionary<WH40KChaosPatron, StyleBoxFlat> _entryStyles = new();
    private readonly Dictionary<WH40KChaosPatron, StyleBoxFlat> _entryShadowStyles = new();
    private readonly Dictionary<WH40KChaosPatron, StyleBoxFlat> _entryAccentStyles = new();
    private readonly Dictionary<WH40KChaosPatron, StyleBoxFlat> _entryHaloStyles = new();
    private readonly Dictionary<WH40KChaosPatron, StyleBoxFlat[]> _entryGiftPanelStyles = new();
    private readonly Dictionary<WH40KChaosPatron, StyleBoxFlat> _entryLeaderPanelStyles = new();
    private readonly Dictionary<WH40KChaosPatron, StyleBoxFlat> _entryButtonStyles = new();

    private readonly StyleBoxFlat _cardStageStyle = new();
    private readonly StyleBoxFlat _previewStyle = new();
    private readonly StyleBoxFlat _previewAccentStyle = new();
    private readonly StyleBoxFlat _focusSigilStyle = new();
    private readonly StyleBoxFlat _selectionBurstRingStyle = new();

    private readonly TextureRect[] _warpBackdrops;
    private readonly StyleBoxFlat[] _warpRippleStyles;
    private readonly PanelContainer[] _warpRipples;
    private readonly Label[] _stageRunes;
    private readonly TextureRect _focusSigilEchoPrimary;
    private readonly TextureRect _focusSigilEchoSecondary;
    private readonly PanelContainer _selectionBurstRing;
    private readonly Label[] _ambientMotes;
    private readonly Label[] _burstMotes;

    private static readonly ResPath SkrizhalRsi = new("_WH40K/Interface/Abilities/skrizhali_runes.rsi");
    private static readonly string[] StageRuneGlyphs = { "✶", "⟁", "✧", "◈", "✦", "⟡", "✷", "◇" };
    private static readonly string[] AmbientGlyphs = { "✦", "·", "◇", "✧", "·", "✦" };
    private static readonly string[] BurstGlyphs = { "✦", "◆", "✧", "◇", "✦", "◆", "✧", "◇" };

    private static readonly ResPath MagicActionsRsi = new("Objects/Magic/magicactions.rsi");
    private static readonly ResPath SmokeActionRsi = new("Actions/smokeaction.rsi");
    private static readonly ResPath JumpActionRsi = new("Interface/Actions/jump.rsi");
    private static readonly ResPath EldritchActionsRsi = new("Objects/Magic/Eldritch/eldritch_actions.rsi");
    private static readonly ResPath EnergyKatanaRsi = new("Objects/Weapons/Melee/energykatana.rsi");
    private static readonly ResPath OrgansRsi = new("Mobs/Species/Human/organs.rsi");

    public event Action<WH40KChaosPatron>? PatronSelected;

    public WH40KChaosSkrizhalPatronSelectorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audio = _entityManager.System<SharedAudioSystem>();
        _sprite = _entityManager.System<SpriteSystem>();

        Resizable = false;
        MouseFilter = Control.MouseFilterMode.Stop;

        StripWindowChrome();
        TrimCardBodies();

        RegisterCard(
            WH40KChaosPatron.Khorne,
            KhorneEntryPanel,
            KhorneAccentBar,
            KhorneHaloPanel,
            KhorneSelectButton,
            KhorneLeaderPanel,
            KhorneGiftSummaryLabel,
            KhorneStatusLabel,
            KhorneGiftOnePanel,
            KhorneGiftOneIcon,
            KhorneGiftTwoPanel,
            KhorneGiftTwoIcon,
            KhorneGiftThreePanel,
            KhorneGiftThreeIcon);
        RegisterCard(
            WH40KChaosPatron.Nurgle,
            NurgleEntryPanel,
            NurgleAccentBar,
            NurgleHaloPanel,
            NurgleSelectButton,
            NurgleLeaderPanel,
            NurgleGiftSummaryLabel,
            NurgleStatusLabel,
            NurgleGiftOnePanel,
            NurgleGiftOneIcon,
            NurgleGiftTwoPanel,
            NurgleGiftTwoIcon,
            NurgleGiftThreePanel,
            NurgleGiftThreeIcon);
        RegisterCard(
            WH40KChaosPatron.Slaanesh,
            SlaaneshEntryPanel,
            SlaaneshAccentBar,
            SlaaneshHaloPanel,
            SlaaneshSelectButton,
            SlaaneshLeaderPanel,
            SlaaneshGiftSummaryLabel,
            SlaaneshStatusLabel,
            SlaaneshGiftOnePanel,
            SlaaneshGiftOneIcon,
            SlaaneshGiftTwoPanel,
            SlaaneshGiftTwoIcon,
            SlaaneshGiftThreePanel,
            SlaaneshGiftThreeIcon);
        RegisterCard(
            WH40KChaosPatron.Tzeentch,
            TzeentchEntryPanel,
            TzeentchAccentBar,
            TzeentchHaloPanel,
            TzeentchSelectButton,
            TzeentchLeaderPanel,
            TzeentchGiftSummaryLabel,
            TzeentchStatusLabel,
            TzeentchGiftOnePanel,
            TzeentchGiftOneIcon,
            TzeentchGiftTwoPanel,
            TzeentchGiftTwoIcon,
            TzeentchGiftThreePanel,
            TzeentchGiftThreeIcon);

        _cardStageStyle.BackgroundColor = Color.Transparent;
        _cardStageStyle.BorderColor = Color.Transparent;
        _cardStageStyle.BorderThickness = new Thickness(0f);
        _cardStageStyle.ContentMarginLeftOverride = 0f;
        _cardStageStyle.ContentMarginTopOverride = 0f;
        _cardStageStyle.ContentMarginRightOverride = 0f;
        _cardStageStyle.ContentMarginBottomOverride = 0f;
        CardStagePanel.PanelOverride = _cardStageStyle;

        _previewStyle.BackgroundColor = Color.FromHex("#11151E");
        _previewStyle.BorderColor = Color.FromHex("#4C5E6D");
        _previewStyle.BorderThickness = new Thickness(1f);
        _previewStyle.ContentMarginLeftOverride = 16f;
        _previewStyle.ContentMarginTopOverride = 12f;
        _previewStyle.ContentMarginRightOverride = 16f;
        _previewStyle.ContentMarginBottomOverride = 12f;
        PreviewPanel.PanelOverride = _previewStyle;

        _previewAccentStyle.BackgroundColor = Color.FromHex("#4A3D20");
        PreviewAccentBar.PanelOverride = _previewAccentStyle;

        _focusSigilStyle.BackgroundColor = Color.Transparent;
        _focusSigilStyle.BorderColor = Color.Transparent;
        _focusSigilStyle.BorderThickness = new Thickness(0f);
        _focusSigilStyle.ContentMarginLeftOverride = 0f;
        _focusSigilStyle.ContentMarginTopOverride = 0f;
        _focusSigilStyle.ContentMarginRightOverride = 0f;
        _focusSigilStyle.ContentMarginBottomOverride = 0f;
        FocusSigilPanel.PanelOverride = _focusSigilStyle;
        FocusSigilPanel.MouseFilter = Control.MouseFilterMode.Ignore;

        _selectionBurstRingStyle.BackgroundColor = Color.Transparent;
        _selectionBurstRingStyle.BorderColor = Color.Transparent;
        _selectionBurstRingStyle.BorderThickness = new Thickness(2f);
        _selectionBurstRing = new PanelContainer
        {
            PanelOverride = _selectionBurstRingStyle,
            MouseFilter = Control.MouseFilterMode.Ignore,
            Visible = false,
            Modulate = Color.Transparent,
        };
        CardCanvas.AddChild(_selectionBurstRing);

        _warpBackdrops = new[]
        {
            CreateWarpBackdrop(WarpBackdropPrimarySize),
            CreateWarpBackdrop(WarpBackdropSecondarySize),
        };
        foreach (var backdrop in _warpBackdrops)
        {
            CardCanvas.AddChild(backdrop);
            backdrop.Texture = _sprite.Frame0(new SpriteSpecifier.Rsi(SkrizhalRsi, "skrizhal_chaos"));
        }

        _warpRippleStyles = new StyleBoxFlat[2];
        _warpRipples = new PanelContainer[2];
        for (var i = 0; i < _warpRipples.Length; i++)
        {
            var rippleStyle = CreateWarpRippleStyle();
            var ripple = new PanelContainer
            {
                PanelOverride = rippleStyle,
                MouseFilter = Control.MouseFilterMode.Ignore,
                Modulate = Color.Transparent,
            };

            _warpRippleStyles[i] = rippleStyle;
            _warpRipples[i] = ripple;
            CardCanvas.AddChild(ripple);
        }

        _stageRunes = new Label[StageRuneGlyphs.Length];
        for (var i = 0; i < StageRuneGlyphs.Length; i++)
        {
            _stageRunes[i] = CreateStageRuneLabel(StageRuneGlyphs[i]);
            CardCanvas.AddChild(_stageRunes[i]);
        }

        _focusSigilEchoPrimary = CreateSigilEcho();
        _focusSigilEchoSecondary = CreateSigilEcho();
        CardCanvas.AddChild(_focusSigilEchoPrimary);
        CardCanvas.AddChild(_focusSigilEchoSecondary);

        _ambientMotes = new Label[AmbientGlyphs.Length];
        for (var i = 0; i < AmbientGlyphs.Length; i++)
        {
            _ambientMotes[i] = CreateMoteLabel(AmbientGlyphs[i]);
            CardCanvas.AddChild(_ambientMotes[i]);
        }

        _burstMotes = new Label[BurstGlyphs.Length];
        for (var i = 0; i < BurstGlyphs.Length; i++)
        {
            _burstMotes[i] = CreateMoteLabel(BurstGlyphs[i]);
            CardCanvas.AddChild(_burstMotes[i]);
        }

        EnsureCanvasLayering();

        CardCanvas.OnResized += ArrangeFloatingCards;
        OnVisibilityChanged += OnWindowVisibilityChanged;

        Relocalize();
    }

    protected override void Opened()
    {
        base.Opened();

        SyncOverlayBounds();

        CardStagePanel.Modulate = new Color(1f, 1f, 1f, 0f);
        FocusSigilPanel.Modulate = new Color(1f, 1f, 1f, 0f);
        WH40KUiChrome.PlayFadeIn(CardStagePanel, "chaos-selector-stage-fade", 0.18f);
        WH40KUiChrome.PlayFadeIn(FocusSigilPanel, "chaos-selector-focus-fade", 0.2f, 0.12f);

        for (var i = 0; i < CardOrder.Length; i++)
        {
            var panel = _entryPanels[CardOrder[i]];
            panel.Modulate = Color.White;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        SyncOverlayBounds();

        if (args.DeltaSeconds <= 0f)
            return;

        _animationTime += args.DeltaSeconds;
        ArrangeFloatingCards();
        RefreshEntryStyles();
        UpdateArcaneEffects();
    }

    protected override void Resized()
    {
        base.Resized();
        ArrangeFloatingCards();
    }

    protected override void ExitedTree()
    {
        StopHoverTheme();
        base.ExitedTree();
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Handled || args.Function != EngineKeyFunctions.UIClick)
            return;

        foreach (var patron in CardOrder)
        {
            if (!_entryPanels.TryGetValue(patron, out var panel) || !IsPointInsideControl(panel, args.RelativePosition))
                continue;

            CommitPatron(patron);
            args.Handle();
            return;
        }

        Close();
        args.Handle();
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.None;
    }

    public void ApplyState(WH40KChaosSkrizhalPatronSelectorBuiState state)
    {
        _latestState = state;
        if (state.SelectionLocked && state.CurrentPatron != WH40KChaosPatron.None)
            _previewPatron = state.CurrentPatron;

        RefreshEntryStyles();
        RefreshFooter();
    }

    public void Relocalize()
    {
        Title = Loc.GetString("wh40k-chaos-selector-title");
        InitCardContent();

        if (_latestState != null)
            ApplyState(_latestState);
        else
        {
            RefreshEntryStyles();
            RefreshFooter();
        }
    }

    private void InitCardContent()
    {
        KhorneDomainLabel.Text = Loc.GetString("wh40k-chaos-selector-khorne-domain");
        NurgleDomainLabel.Text = Loc.GetString("wh40k-chaos-selector-nurgle-domain");
        SlaaneshDomainLabel.Text = Loc.GetString("wh40k-chaos-selector-slaanesh-domain");
        TzeentchDomainLabel.Text = Loc.GetString("wh40k-chaos-selector-tzeentch-domain");

        KhorneTitleLabel.Text = Loc.GetString("wh40k-chaos-selector-khorne-title");
        NurgleTitleLabel.Text = Loc.GetString("wh40k-chaos-selector-nurgle-title");
        SlaaneshTitleLabel.Text = Loc.GetString("wh40k-chaos-selector-slaanesh-title");
        TzeentchTitleLabel.Text = Loc.GetString("wh40k-chaos-selector-tzeentch-title");

        KhorneDescriptionLabel.Text = Loc.GetString("wh40k-chaos-selector-khorne-desc");
        NurgleDescriptionLabel.Text = Loc.GetString("wh40k-chaos-selector-nurgle-desc");
        SlaaneshDescriptionLabel.Text = Loc.GetString("wh40k-chaos-selector-slaanesh-desc");
        TzeentchDescriptionLabel.Text = Loc.GetString("wh40k-chaos-selector-tzeentch-desc");

        KhorneIcon.Texture = _sprite.Frame0(new SpriteSpecifier.Rsi(SkrizhalRsi, "skrizhal_khorn"));
        NurgleIcon.Texture = _sprite.Frame0(new SpriteSpecifier.Rsi(SkrizhalRsi, "skrizhal_nurgk"));
        SlaaneshIcon.Texture = _sprite.Frame0(new SpriteSpecifier.Rsi(SkrizhalRsi, "skrizhal_slaanesh"));
        TzeentchIcon.Texture = _sprite.Frame0(new SpriteSpecifier.Rsi(SkrizhalRsi, "skrizhal_tzinch"));

        KhorneGiftSummaryLabel.SetMessage(BuildGiftSummary(WH40KChaosPatron.Khorne));
        NurgleGiftSummaryLabel.SetMessage(BuildGiftSummary(WH40KChaosPatron.Nurgle));
        SlaaneshGiftSummaryLabel.SetMessage(BuildGiftSummary(WH40KChaosPatron.Slaanesh));
        TzeentchGiftSummaryLabel.SetMessage(BuildGiftSummary(WH40KChaosPatron.Tzeentch));

        InitGiftIcons(WH40KChaosPatron.Khorne);
        InitGiftIcons(WH40KChaosPatron.Nurgle);
        InitGiftIcons(WH40KChaosPatron.Slaanesh);
        InitGiftIcons(WH40KChaosPatron.Tzeentch);

        UpdateFocusSigilTextures();
    }

    private void RegisterCard(
        WH40KChaosPatron patron,
        PanelContainer panel,
        PanelContainer accentBar,
        PanelContainer haloPanel,
        Button button,
        PanelContainer leaderPanel,
        RichTextLabel giftSummaryLabel,
        Label statusLabel,
        PanelContainer giftOnePanel,
        TextureRect giftOneIcon,
        PanelContainer giftTwoPanel,
        TextureRect giftTwoIcon,
        PanelContainer giftThreePanel,
        TextureRect giftThreeIcon)
    {
        _entryPanels[patron] = panel;
        _entryAccentBars[patron] = accentBar;
        _entryHaloPanels[patron] = haloPanel;
        _entryButtons[patron] = button;
        _entryGiftPanels[patron] = new[] { giftOnePanel, giftTwoPanel, giftThreePanel };
        _entryGiftIcons[patron] = new[] { giftOneIcon, giftTwoIcon, giftThreeIcon };
        _entryGiftSummaryLabels[patron] = giftSummaryLabel;
        _entryLeaderPanels[patron] = leaderPanel;
        _entryStatusLabels[patron] = statusLabel;

        var cardStyle = CreateEntryStyle(patron);
        var accentStyle = CreateAccentStyle(patron);
        var haloStyle = CreateHaloStyle(patron);
        var giftPanelStyles = new[]
        {
            CreateGiftSlotStyle(patron),
            CreateGiftSlotStyle(patron),
            CreateGiftSlotStyle(patron),
        };
        var leaderPanelStyle = CreateLeaderStyle(patron);
        var buttonStyle = CreateButtonStyle(patron);

        _entryStyles[patron] = cardStyle;
        _entryAccentStyles[patron] = accentStyle;
        _entryHaloStyles[patron] = haloStyle;
        _entryGiftPanelStyles[patron] = giftPanelStyles;
        _entryLeaderPanelStyles[patron] = leaderPanelStyle;
        _entryButtonStyles[patron] = buttonStyle;

        panel.PanelOverride = cardStyle;
        accentBar.PanelOverride = accentStyle;
        haloPanel.PanelOverride = haloStyle;
        giftOnePanel.PanelOverride = giftPanelStyles[0];
        giftTwoPanel.PanelOverride = giftPanelStyles[1];
        giftThreePanel.PanelOverride = giftPanelStyles[2];
        leaderPanel.PanelOverride = leaderPanelStyle;
        button.StyleBoxOverride = buttonStyle;
        panel.MouseFilter = Control.MouseFilterMode.Pass;
        giftSummaryLabel.HorizontalExpand = true;
        statusLabel.Align = Label.AlignMode.Center;
        statusLabel.HorizontalExpand = true;

        var shadowStyle = CreateShadowStyle(patron);
        var shadowPanel = new PanelContainer
        {
            PanelOverride = shadowStyle,
            MouseFilter = Control.MouseFilterMode.Ignore,
            Modulate = Color.White,
        };

        _entryShadowPanels[patron] = shadowPanel;
        _entryShadowStyles[patron] = shadowStyle;
        CardCanvas.AddChild(shadowPanel);

        panel.OnMouseEntered += _ => PreviewPatron(patron, true);
        panel.OnMouseExited += _ => OnCardMouseExited();
        button.OnMouseEntered += _ => PreviewPatron(patron, true);
        button.OnMouseExited += _ => OnCardMouseExited();
        button.OnPressed += _ => CommitPatron(patron);
    }

    private void PreviewPatron(WH40KChaosPatron patron, bool playFlash)
    {
        _previewPatron = patron;
        UpdateHoverTheme(patron);

        if (playFlash)
        {
            var accent = ResolvePatronAccent(patron);
            WH40KUiChrome.PlayHoverFlash(_entryAccentBars[patron], $"chaos-selector-bar-hover-{patron}", accent.WithAlpha(0.92f), 0.16f);
        }

        RefreshEntryStyles();
        RefreshFooter();
    }

    private void OnWindowVisibilityChanged(Control control)
    {
        if (!Visible)
            StopHoverTheme();
    }

    private void OnCardMouseExited()
    {
        if (IsMouseOverAnyPatronCard())
            return;

        StopHoverTheme();
    }

    private bool IsMouseOverAnyPatronCard()
    {
        if (Parent == null || !Visible)
            return false;

        var mousePoint = UserInterfaceManager.MousePositionScaled.Position;
        foreach (var patron in CardOrder)
        {
            if (_entryPanels.TryGetValue(patron, out var panel) && IsPointInsideControl(panel, mousePoint))
                return true;

            if (_entryButtons.TryGetValue(patron, out var button) && IsPointInsideControl(button, mousePoint))
                return true;
        }

        return false;
    }

    private void UpdateHoverTheme(WH40KChaosPatron patron)
    {
        if (_hoverThemePatron == patron && _hoverThemeStream != null)
            return;

        StopHoverTheme();

        ResolvedSoundSpecifier? themePath = ResolvePatronThemePath(patron);
        if (themePath == null)
            return;

        _hoverThemeStream = _audio.PlayGlobal((ResolvedSoundSpecifier?) themePath, Filter.Local(), true, PatronThemeAudioParams)?.Entity;
        _hoverThemePatron = _hoverThemeStream != null ? patron : WH40KChaosPatron.None;
    }

    private void StopHoverTheme()
    {
        _hoverThemeStream = _audio.Stop(_hoverThemeStream);
        _hoverThemePatron = WH40KChaosPatron.None;
    }

    private static ResolvedSoundSpecifier? ResolvePatronThemePath(WH40KChaosPatron patron)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => new ResolvedPathSpecifier(new ResPath("/Audio/_WH40K/ChaosGods/Khorne.ogg")),
            WH40KChaosPatron.Nurgle => new ResolvedPathSpecifier(new ResPath("/Audio/_WH40K/ChaosGods/Nurgle.ogg")),
            WH40KChaosPatron.Slaanesh => new ResolvedPathSpecifier(new ResPath("/Audio/_WH40K/ChaosGods/Slaanesh.ogg")),
            WH40KChaosPatron.Tzeentch => new ResolvedPathSpecifier(new ResPath("/Audio/_WH40K/ChaosGods/Tzeentch.ogg")),
            _ => null,
        };
    }

    private void CommitPatron(WH40KChaosPatron patron)
    {
        _previewPatron = patron;

        if (!IsSelectionLocked())
            PatronSelected?.Invoke(patron);

        RefreshEntryStyles();
        RefreshFooter();
    }

    private void RefreshFooter()
    {
        var patronLoc = Loc.GetString(GetPatronLocKey(_previewPatron));
        PreviewPatronLabel.Text = WH40KUiChrome.DecorateTitle(WH40KUiChrome.Eye, patronLoc);
        UpdateFocusSigilTextures();

        var accent = ResolvePatronAccent(_previewPatron);
        _cardStageStyle.BackgroundColor = accent.WithAlpha(0.015f);
        _cardStageStyle.BorderColor = Color.Transparent;
        _focusSigilStyle.BackgroundColor = Color.Transparent;
        _focusSigilStyle.BorderColor = Color.Transparent;

        WH40KUiChrome.StartLoopingPulse(
            FocusSigilPanel,
            "chaos-selector-focus-pulse",
            accent.WithAlpha(0.72f),
            Color.White,
            2.8f);

        var locked = IsSelectionLocked();
        var currentPatron = _latestState?.CurrentPatron ?? WH40KChaosPatron.None;
        PreviewStatusLabel.Text = locked
            ? Loc.GetString(
                _previewPatron == currentPatron
                    ? "wh40k-chaos-selector-preview-status-locked-current"
                    : "wh40k-chaos-selector-preview-status-locked-other",
                ("patron", Loc.GetString(GetPatronLocKey(currentPatron))))
            : Loc.GetString("wh40k-chaos-selector-preview-status-open", ("patron", patronLoc));
        PreviewCommitNoteLabel.Text = locked
            ? Loc.GetString("wh40k-chaos-selector-preview-note-locked")
            : Loc.GetString("wh40k-chaos-selector-preview-note-open");
    }

    private void RefreshEntryStyles()
    {
        var currentPatron = _latestState?.CurrentPatron ?? WH40KChaosPatron.None;
        var locked = IsSelectionLocked();

        foreach (var patron in CardOrder)
        {
            var style = _entryStyles[patron];
            var accentStyle = _entryAccentStyles[patron];
            var haloStyle = _entryHaloStyles[patron];
            var giftPanelStyles = _entryGiftPanelStyles[patron];
            var leaderPanelStyle = _entryLeaderPanelStyles[patron];
            var buttonStyle = _entryButtonStyles[patron];
            var shadowStyle = _entryShadowStyles[patron];
            var button = _entryButtons[patron];
            var giftIcons = _entryGiftIcons[patron];
            var giftSummaryLabel = _entryGiftSummaryLabels[patron];
            var statusLabel = _entryStatusLabels[patron];
            var panel = _entryPanels[patron];

            var accent = ResolvePatronAccent(patron);
            var baseBackground = ResolveEntryBackground(patron);
            var previewed = patron == _previewPatron;
            var selected = locked && patron == currentPatron;
            var buttonHovered = previewed;
            var haloPulse = 0.5f + 0.5f * MathF.Sin(_animationTime * (1.45f + GetCardPhase(patron) * 0.08f) + GetCardPhase(patron));
            var leaderName = ResolveLeaderName(patron);
            var hasLeader = leaderName != Loc.GetString("wh40k-chaos-selector-no-leader");

            style.BackgroundColor = selected
                ? LightenColor(baseBackground, 0.16f)
                : previewed
                    ? LightenColor(baseBackground, buttonHovered ? 0.14f : 0.1f)
                    : buttonHovered
                        ? LightenColor(baseBackground, 0.06f)
                        : baseBackground;
            style.BorderColor = selected
                ? Color.FromHex("#D7BC72")
                : previewed
                    ? accent.WithAlpha(0.96f)
                    : buttonHovered
                        ? accent.WithAlpha(0.72f)
                        : Color.FromHex("#2A2418");
            style.BorderThickness = new Thickness(previewed || selected ? 2f : 1f);

            shadowStyle.BackgroundColor = accent.WithAlpha(selected
                ? 0.18f
                : previewed
                    ? 0.12f
                    : 0.05f);
            shadowStyle.BorderColor = accent.WithAlpha(selected
                ? 0.46f
                : previewed
                    ? 0.3f
                    : 0.16f);
            shadowStyle.BorderThickness = new Thickness(previewed || selected ? 2f : 1f);

            accentStyle.BackgroundColor = selected
                ? Color.FromHex("#D7BC72")
                : previewed
                    ? LightenColor(accent, 0.14f)
                    : accent.WithAlpha(0.82f);

            haloStyle.BackgroundColor = MixColor(
                ResolvePreviewBackground(patron),
                accent,
                previewed
                    ? 0.14f + haloPulse * 0.06f
                    : 0.08f + haloPulse * 0.04f);
            haloStyle.BorderColor = selected
                ? Color.FromHex("#D7BC72")
                : previewed
                    ? LightenColor(accent, 0.08f).WithAlpha(0.76f + haloPulse * 0.16f)
                    : accent.WithAlpha(0.44f + haloPulse * 0.12f);
            haloStyle.BorderThickness = new Thickness(previewed || selected ? 2f : 1f);

            buttonStyle.BackgroundColor = selected
                ? MixColor(Color.FromHex("#4F536F"), accent, 0.32f)
                : previewed
                    ? MixColor(Color.FromHex("#4A4D6B"), accent, buttonHovered ? 0.24f : 0.18f)
                    : MixColor(Color.FromHex("#4A4D6B"), accent, 0.08f);
            buttonStyle.BorderColor = selected
                ? Color.FromHex("#D7BC72")
                : previewed
                    ? accent.WithAlpha(0.94f)
                    : Color.FromHex("#70779B");
            buttonStyle.BorderThickness = new Thickness(1f);

            var giftBackground = selected
                ? MixColor(ResolvePreviewBackground(patron), accent, 0.26f)
                : previewed
                    ? MixColor(ResolvePreviewBackground(patron), accent, 0.18f + haloPulse * 0.04f)
                    : MixColor(ResolvePreviewBackground(patron), accent, 0.1f);
            var giftBorder = selected
                ? Color.FromHex("#D7BC72")
                : previewed
                    ? LightenColor(accent, 0.12f).WithAlpha(0.88f)
                    : accent.WithAlpha(0.5f);

            foreach (var giftPanelStyle in giftPanelStyles)
            {
                giftPanelStyle.BackgroundColor = giftBackground;
                giftPanelStyle.BorderColor = giftBorder;
                giftPanelStyle.BorderThickness = new Thickness(selected || previewed ? 2f : 1f);
            }

            leaderPanelStyle.BackgroundColor = selected
                ? MixColor(baseBackground, accent, 0.24f)
                : previewed
                    ? MixColor(baseBackground, accent, 0.16f + haloPulse * 0.03f)
                    : MixColor(baseBackground, accent, 0.08f);
            leaderPanelStyle.BorderColor = selected
                ? Color.FromHex("#D7BC72")
                : previewed
                    ? LightenColor(accent, 0.12f).WithAlpha(0.9f)
                    : accent.WithAlpha(0.46f);
            leaderPanelStyle.BorderThickness = new Thickness(selected || previewed ? 2f : 1f);

            foreach (var giftIcon in giftIcons)
            {
                giftIcon.Modulate = Color.White.WithAlpha(selected ? 1f : previewed ? 0.98f : 0.92f);
                giftIcon.TextureScale = new Vector2(selected ? 1.08f : previewed ? 1.04f : 1f);
            }

            giftSummaryLabel.Modulate = Color.White.WithAlpha(selected ? 1f : previewed ? 0.97f : 0.9f);

            button.Text = ResolveButtonText(patron, locked);
            button.Disabled = locked;
            statusLabel.Text = leaderName;
            statusLabel.FontColorOverride = hasLeader
                ? selected
                    ? Color.FromHex("#F5E8D4")
                    : previewed
                        ? LightenColor(accent, 0.34f)
                        : LightenColor(accent, 0.2f)
                : Color.FromHex("#C4C7D2");
        }
    }

    private void UpdateArcaneEffects()
    {
        if (!_entryPanels.TryGetValue(_previewPatron, out var previewPanel))
            return;

        if (!TryGetCardFormationBounds(out var formationTopLeft, out var formationSize, out var formationCenter))
            return;

        var accent = ResolvePatronAccent(_previewPatron);
        var focusCenter = FocusSigilPanel.Position + FocusSigilPanel.Size * 0.5f;
        var cardCenter = previewPanel.Position + previewPanel.Size * new Vector2(0.5f, 0.34f);

        _cardStageStyle.BackgroundColor = accent.WithAlpha(0.01f + (MathF.Sin(_animationTime * 0.72f) + 1f) * 0.006f);
        _cardStageStyle.BorderColor = Color.Transparent;

        UpdateWarpBackdrops(formationCenter, formationSize, accent);
        UpdateWarpRipples(formationTopLeft, formationSize, accent);
        UpdateStageRunes(formationCenter, cardCenter, accent);
        UpdateAmbientMotes(formationCenter, cardCenter, accent);
        UpdateFocusSigilDrift(focusCenter, accent);
    }

    private void UpdateWarpBackdrops(Vector2 formationCenter, Vector2 formationSize, Color accent)
    {
        var primary = _warpBackdrops[0];
        var secondary = _warpBackdrops[1];

        var primarySize = MathF.Max(WarpBackdropPrimarySize, formationSize.X + 220f) + MathF.Sin(_animationTime * 0.72f) * 22f;
        var secondarySize = MathF.Max(WarpBackdropSecondarySize, formationSize.Y + 360f) + MathF.Sin(_animationTime * 0.94f + 0.8f) * 18f;
        var primaryOffset = new Vector2(
            MathF.Cos(_animationTime * 0.32f + GetCardPhase(_previewPatron)) * 34f,
            MathF.Sin(_animationTime * 0.41f) * 18f - formationSize.Y * 0.1f);
        var secondaryOffset = new Vector2(
            MathF.Cos(-_animationTime * 0.38f + 0.6f) * 48f,
            MathF.Sin(-_animationTime * 0.29f + 1.4f) * 26f + formationSize.Y * 0.08f);

        primary.SetWidth = primarySize;
        primary.SetHeight = primarySize;
        primary.TextureScale = new Vector2(1.8f + MathF.Sin(_animationTime * 0.86f) * 0.08f);
        primary.Modulate = LightenColor(accent, 0.18f).WithAlpha(0.065f + (MathF.Sin(_animationTime * 1.1f) + 1f) * 0.018f);
        LayoutContainer.SetPosition(primary, formationCenter + primaryOffset - new Vector2(primarySize * 0.5f, primarySize * 0.5f));

        secondary.SetWidth = secondarySize;
        secondary.SetHeight = secondarySize;
        secondary.TextureScale = new Vector2(1.34f + MathF.Sin(_animationTime * 1.06f + 0.5f) * 0.06f);
        secondary.Modulate = accent.WithAlpha(0.04f + (MathF.Sin(_animationTime * 1.3f + 0.9f) + 1f) * 0.016f);
        LayoutContainer.SetPosition(secondary, formationCenter + secondaryOffset - new Vector2(secondarySize * 0.5f, secondarySize * 0.5f));
    }

    private void UpdateWarpRipples(Vector2 formationTopLeft, Vector2 formationSize, Color accent)
    {
        for (var i = 0; i < _warpRipples.Length; i++)
        {
            var ripple = _warpRipples[i];
            var style = _warpRippleStyles[i];
            var phase = _animationTime * (0.58f + i * 0.11f) + i * 0.9f + GetCardPhase(_previewPatron);
            var spreadX = WarpRippleInset + i * 16f + (MathF.Sin(phase) + 1f) * 10f;
            var spreadY = WarpRippleInset * 0.7f + i * 12f + (MathF.Cos(phase * 1.12f) + 1f) * 7f;
            var drift = new Vector2(
                MathF.Cos(phase * 0.7f) * (5f + i * 1.8f),
                MathF.Sin(phase * 0.63f) * (7f + i * 2.2f));
            var alpha = 0.08f + (MathF.Sin(phase * 1.25f) + 1f) * 0.05f;

            style.BorderColor = LightenColor(accent, 0.14f + i * 0.08f).WithAlpha(alpha);
            style.BackgroundColor = accent.WithAlpha(0.012f + i * 0.008f);
            style.BorderThickness = new Thickness(1f + (1f - i * 0.22f));

            ripple.Modulate = Color.White.WithAlpha(alpha);
            ripple.SetWidth = formationSize.X + spreadX * 2f;
            ripple.SetHeight = formationSize.Y + spreadY * 2f;
            LayoutContainer.SetPosition(ripple, formationTopLeft - new Vector2(spreadX, spreadY) + drift);
        }
    }

    private void UpdateStageRunes(Vector2 focusCenter, Vector2 cardCenter, Color accent)
    {
        if (CardCanvas.Width <= 0f || CardCanvas.Height <= 0f)
            return;

        var highlightCenter = Vector2.Lerp(focusCenter, cardCenter, 0.5f);
        var heightStep = (CardCanvas.Height - 84f) / Math.Max(1, _stageRunes.Length - 1);
        var travelWidth = CardCanvas.Width + 120f;

        for (var i = 0; i < _stageRunes.Length; i++)
        {
            var rune = _stageRunes[i];
            var travel = (_animationTime * (18f + i * 3.2f) + i * 91f) % travelWidth;
            var x = i % 2 == 0
                ? travel - 60f
                : CardCanvas.Width - travel + 60f;
            var baseY = 42f + i * heightStep;
            var y = baseY
                + MathF.Sin(_animationTime * (0.7f + i * 0.04f) + i * 0.8f) * 20f
                + MathF.Sin(_animationTime * 0.35f + i * 1.1f) * 8f;
            var position = new Vector2(x, y);
            var influence = 1f - Math.Clamp(Vector2.Distance(position, highlightCenter) / 420f, 0f, 1f);
            var alpha = 0.06f + (MathF.Sin(_animationTime * 1.15f + i * 0.6f) + 1f) * 0.04f + influence * 0.08f;

            rune.FontColorOverride = i % 2 == 0
                ? LightenColor(accent, 0.16f + influence * 0.14f)
                : MixColor(Color.FromHex("#8A7442"), accent, 0.5f + influence * 0.25f);
            rune.Modulate = Color.White.WithAlpha(alpha);
            LayoutContainer.SetPosition(rune, position);
        }
    }

    private void UpdateFocusSigilDrift(Vector2 focusCenter, Color accent)
    {
        var baseAlpha = 0.18f + (MathF.Sin(_animationTime * 1.8f) + 1f) * 0.08f;
        var mainScale = 0.96f + MathF.Sin(_animationTime * 2.4f) * 0.08f;
        FocusSigilIcon.TextureScale = new Vector2(mainScale, mainScale);
        FocusSigilPanel.Modulate = accent.WithAlpha(0.82f + baseAlpha * 0.12f);

        var primaryOffset = new Vector2(
            MathF.Cos(_animationTime * 1.55f) * 12f,
            MathF.Sin(_animationTime * 1.55f) * 8f);
        var secondaryOffset = new Vector2(
            MathF.Cos(-_animationTime * 1.25f + 0.75f) * 16f,
            MathF.Sin(-_animationTime * 1.25f + 0.75f) * 10f);
        var primaryScale = 0.62f + MathF.Sin(_animationTime * 1.8f + 0.4f) * 0.08f;
        var secondaryScale = 0.54f + MathF.Sin(_animationTime * 1.6f + 1.3f) * 0.06f;

        _focusSigilEchoPrimary.TextureScale = new Vector2(primaryScale, primaryScale);
        _focusSigilEchoSecondary.TextureScale = new Vector2(secondaryScale, secondaryScale);
        _focusSigilEchoPrimary.Modulate = accent.WithAlpha(0.22f + baseAlpha * 0.14f);
        _focusSigilEchoSecondary.Modulate = LightenColor(accent, 0.18f).WithAlpha(0.18f + baseAlpha * 0.1f);

        LayoutContainer.SetPosition(_focusSigilEchoPrimary, focusCenter + primaryOffset - new Vector2(SigilEchoSize * 0.5f, SigilEchoSize * 0.5f));
        LayoutContainer.SetPosition(_focusSigilEchoSecondary, focusCenter + secondaryOffset - new Vector2(SigilEchoSize * 0.5f, SigilEchoSize * 0.5f));
    }

    private void UpdateAmbientMotes(Vector2 focusCenter, Vector2 cardCenter, Color accent)
    {
        for (var i = 0; i < _ambientMotes.Length; i++)
        {
            var mote = _ambientMotes[i];
            var orbitAngle = GetCardPhase(_previewPatron) + i * (Tau / _ambientMotes.Length) + _animationTime * (0.6f + i * 0.05f) * (i % 2 == 0 ? 1f : -1f);
            var radius = 46f + i * 5f + MathF.Sin(_animationTime * 1.3f + i) * 6f;
            var centerBias = i % 2 == 0 ? focusCenter : Vector2.Lerp(focusCenter, cardCenter, 0.34f);
            var offset = new Vector2(
                MathF.Cos(orbitAngle) * radius,
                MathF.Sin(orbitAngle) * (18f + i * 1.5f));
            var shimmer = 0.2f + (MathF.Sin(_animationTime * 2.1f + i * 0.9f) + 1f) * 0.18f;

            mote.FontColorOverride = LightenColor(accent, 0.18f + i * 0.03f);
            mote.Modulate = Color.White.WithAlpha(shimmer);
            mote.Visible = true;
            LayoutContainer.SetPosition(mote, centerBias + offset - new Vector2(6f, 8f));
        }
    }

    private void UpdateSelectionBurst(Color accent)
    {
        var elapsed = _animationTime - _burstStartedAt;
        if (_burstPatron == WH40KChaosPatron.None || elapsed < 0f || elapsed > BurstDuration || !_entryPanels.TryGetValue(_burstPatron, out var burstPanel))
        {
            _selectionBurstRing.Visible = false;

            foreach (var mote in _burstMotes)
            {
                mote.Visible = false;
                mote.Modulate = Color.Transparent;
            }

            return;
        }

        var progress = Math.Clamp(elapsed / BurstDuration, 0f, 1f);
        var eased = EaseOutCubic(progress);
        var expansion = (26f + 48f * eased) * _burstIntensity;
        var ringPosition = burstPanel.Position - new Vector2(expansion * 0.5f, expansion * 0.5f);
        var ringSize = burstPanel.Size + new Vector2(expansion, expansion);
        var ringAlpha = (1f - progress) * (0.85f + _burstIntensity * 0.1f);

        _selectionBurstRingStyle.BorderColor = accent.WithAlpha(ringAlpha);
        _selectionBurstRingStyle.BackgroundColor = accent.WithAlpha((1f - progress) * 0.035f * _burstIntensity);
        _selectionBurstRingStyle.BorderThickness = new Thickness(2f + (1f - progress) * _burstIntensity);
        _selectionBurstRing.Visible = true;
        _selectionBurstRing.Modulate = Color.White.WithAlpha(ringAlpha);
        _selectionBurstRing.SetWidth = ringSize.X;
        _selectionBurstRing.SetHeight = ringSize.Y;
        LayoutContainer.SetPosition(_selectionBurstRing, ringPosition);

        var burstCenter = burstPanel.Position + burstPanel.Size * new Vector2(0.5f, 0.42f);
        for (var i = 0; i < _burstMotes.Length; i++)
        {
            var mote = _burstMotes[i];
            var angle = GetCardPhase(_burstPatron) + _burstSerial * 0.31f + i * (Tau / _burstMotes.Length);
            var direction = new Vector2(MathF.Cos(angle), MathF.Sin(angle) * 0.62f);
            var travel = (16f + 82f * eased) * _burstIntensity;
            var rise = (1f - progress) * 12f;
            var moteAlpha = (1f - progress) * (0.92f - i * 0.04f);

            mote.FontColorOverride = i % 2 == 0 ? LightenColor(accent, 0.34f) : accent;
            mote.Modulate = Color.White.WithAlpha(Math.Max(0f, moteAlpha));
            mote.Visible = moteAlpha > 0.02f;
            LayoutContainer.SetPosition(mote, burstCenter + direction * travel + new Vector2(0f, -rise) - new Vector2(8f, 8f));
        }
    }

    private void ArrangeFloatingCards()
    {
        if (CardCanvas.Width <= 0f || CardCanvas.Height <= 0f)
            return;

        var usableWidth = Math.Max(320f, CardCanvas.Width - CardHorizontalPadding * 2f - CardGap * 3f);
        var cardWidth = usableWidth / 4f;
        var cardHeight = MathF.Min(600f, Math.Max(436f, CardCanvas.Height - CardTopPadding - CardBottomPadding - 112f));
        var stageTop = MathF.Max(CardTopPadding, (CardCanvas.Height - cardHeight) * 0.5f - 10f);

        for (var i = 0; i < CardOrder.Length; i++)
        {
            var patron = CardOrder[i];
            var panel = _entryPanels[patron];
            panel.SetWidth = cardWidth;
            panel.SetHeight = cardHeight;

            var lift = MathF.Sin(_animationTime * 0.92f + GetCardPhase(patron)) * GetCardAmplitude(patron);
            if (patron == _previewPatron)
                lift -= 12f;

            var x = CardHorizontalPadding + i * (cardWidth + CardGap);
            var y = stageTop + GetCardBaseOffset(patron) + lift;
            LayoutContainer.SetPosition(panel, new Vector2(x, y));

            var shadow = _entryShadowPanels[patron];
            var shadowWidth = cardWidth + 30f;
            var shadowHeight = cardHeight + 42f;
            shadow.SetWidth = shadowWidth;
            shadow.SetHeight = shadowHeight;

            var shadowDrift = new Vector2(
                MathF.Cos(_animationTime * 0.34f + GetCardPhase(patron)) * 6f,
                MathF.Sin(_animationTime * 0.28f + GetCardPhase(patron)) * 8f);
            LayoutContainer.SetPosition(
                shadow,
                new Vector2(x - 15f, y + 18f) + shadowDrift);
        }

        var focusWidth = 62f;
        var focusHeight = 62f;
        FocusSigilPanel.SetWidth = focusWidth;
        FocusSigilPanel.SetHeight = focusHeight;
        var focusIndex = Array.IndexOf(CardOrder, _previewPatron);
        if (focusIndex >= 0)
        {
            var focusX = CardHorizontalPadding + focusIndex * (cardWidth + CardGap) + cardWidth * 0.5f - focusWidth * 0.5f;
            var focusY = stageTop + GetCardBaseOffset(_previewPatron) + MathF.Sin(_animationTime * 1.12f + GetCardPhase(_previewPatron)) * 4f - 34f;
            LayoutContainer.SetPosition(FocusSigilPanel, new Vector2(focusX, focusY));
        }
    }

    private void StripWindowChrome()
    {
        CloseButton.Visible = false;
        HelpButton.Visible = false;
        WindowTitle.Visible = false;

        if (ChildCount > 0)
            GetChild(0).Visible = false;

        if (ChildCount <= 1 || GetChild(1) is not BoxContainer windowBox)
            return;

        if (windowBox.ChildCount > 0)
            windowBox.GetChild(0).Visible = false;

        if (windowBox.ChildCount > 1)
            windowBox.GetChild(1).Visible = false;

        ContentsContainer.RectClipContent = false;
    }

    private void TrimCardBodies()
    {
        TrimCardBody(KhorneEntryPanel);
        TrimCardBody(NurgleEntryPanel);
        TrimCardBody(SlaaneshEntryPanel);
        TrimCardBody(TzeentchEntryPanel);
    }

    private static void TrimCardBody(PanelContainer panel)
    {
        if (panel.ChildCount == 0 || panel.GetChild(0) is not BoxContainer contentBox)
            return;

        if (contentBox.ChildCount >= 1 && contentBox.GetChild(contentBox.ChildCount - 1) is Button button)
            contentBox.RemoveChild(button);
    }

    private void SyncOverlayBounds()
    {
        if (Parent == null)
            return;

        if (SetSize != Parent.Size)
            SetSize = Parent.Size;

        if (Position != Vector2.Zero)
            LayoutContainer.SetPosition(this, Vector2.Zero);
    }

    private bool IsPointInsideControl(Control control, Vector2 point)
    {
        var topLeft = Vector2.Zero;

        for (Control? current = control; current != null && current != this; current = current.Parent)
        {
            topLeft += current.Position;
        }

        return point.X >= topLeft.X && point.X <= topLeft.X + control.Size.X &&
               point.Y >= topLeft.Y && point.Y <= topLeft.Y + control.Size.Y;
    }

    private void TriggerCardBurst(WH40KChaosPatron patron, float intensity)
    {
        _burstPatron = patron;
        _burstStartedAt = _animationTime;
        _burstIntensity = Math.Clamp(intensity, 0.35f, 1.15f);
        _burstSerial++;

        var accent = ResolvePatronAccent(patron);
        WH40KUiChrome.PlayHoverFlash(_entryPanels[patron], $"chaos-selector-card-burst-{_burstSerial}", accent.WithAlpha(0.88f), 0.12f);
        WH40KUiChrome.PlayHoverFlash(_entryHaloPanels[patron], $"chaos-selector-halo-burst-{_burstSerial}", accent.WithAlpha(0.96f), 0.14f);
        WH40KUiChrome.PlayHoverFlash(FocusSigilPanel, $"chaos-selector-focus-burst-{_burstSerial}", accent.WithAlpha(0.9f), 0.14f);
    }

    private bool IsSelectionLocked()
    {
        return _latestState?.SelectionLocked ?? false;
    }

    private static StyleBoxFlat CreateEntryStyle(WH40KChaosPatron patron)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = ResolveEntryBackground(patron),
            BorderColor = Color.FromHex("#2A2418"),
            BorderThickness = new Thickness(1f),
            ContentMarginLeftOverride = 16f,
            ContentMarginTopOverride = 14f,
            ContentMarginRightOverride = 16f,
            ContentMarginBottomOverride = 14f
        };
    }

    private static StyleBoxFlat CreateShadowStyle(WH40KChaosPatron patron)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = ResolvePatronAccent(patron).WithAlpha(0.05f),
            BorderColor = ResolvePatronAccent(patron).WithAlpha(0.16f),
            BorderThickness = new Thickness(1f),
        };
    }

    private static StyleBoxFlat CreateAccentStyle(WH40KChaosPatron patron)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = ResolvePatronAccent(patron).WithAlpha(0.82f)
        };
    }

    private static StyleBoxFlat CreateHaloStyle(WH40KChaosPatron patron)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = MixColor(ResolvePreviewBackground(patron), ResolvePatronAccent(patron), 0.12f),
            BorderColor = ResolvePatronAccent(patron).WithAlpha(0.6f),
            BorderThickness = new Thickness(1f),
            ContentMarginLeftOverride = 16f,
            ContentMarginTopOverride = 16f,
            ContentMarginRightOverride = 16f,
            ContentMarginBottomOverride = 16f
        };
    }

    private static StyleBoxFlat CreateGiftSlotStyle(WH40KChaosPatron patron)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = MixColor(ResolvePreviewBackground(patron), ResolvePatronAccent(patron), 0.1f),
            BorderColor = ResolvePatronAccent(patron).WithAlpha(0.5f),
            BorderThickness = new Thickness(1f),
            ContentMarginLeftOverride = 8f,
            ContentMarginTopOverride = 8f,
            ContentMarginRightOverride = 8f,
            ContentMarginBottomOverride = 8f,
        };
    }

    private static StyleBoxFlat CreateLeaderStyle(WH40KChaosPatron patron)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = MixColor(ResolveEntryBackground(patron), ResolvePatronAccent(patron), 0.08f),
            BorderColor = ResolvePatronAccent(patron).WithAlpha(0.46f),
            BorderThickness = new Thickness(1f),
            ContentMarginLeftOverride = 10f,
            ContentMarginTopOverride = 8f,
            ContentMarginRightOverride = 10f,
            ContentMarginBottomOverride = 10f,
        };
    }

    private static StyleBoxFlat CreateButtonStyle(WH40KChaosPatron patron)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = MixColor(Color.FromHex("#4A4D6B"), ResolvePatronAccent(patron), 0.08f),
            BorderColor = Color.FromHex("#70779B"),
            BorderThickness = new Thickness(1f),
            ContentMarginLeftOverride = 14f,
            ContentMarginTopOverride = 10f,
            ContentMarginRightOverride = 14f,
            ContentMarginBottomOverride = 10f
        };
    }

    private TextureRect CreateSigilEcho()
    {
        return new TextureRect
        {
            MinSize = new Vector2(SigilEchoSize, SigilEchoSize),
            SetSize = new Vector2(SigilEchoSize, SigilEchoSize),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            HorizontalAlignment = Control.HAlignment.Center,
            VerticalAlignment = Control.VAlignment.Center,
            MouseFilter = Control.MouseFilterMode.Ignore,
            Modulate = Color.Transparent,
        };
    }

    private static TextureRect CreateWarpBackdrop(float size)
    {
        return new TextureRect
        {
            MinSize = new Vector2(size, size),
            SetSize = new Vector2(size, size),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            MouseFilter = Control.MouseFilterMode.Ignore,
            Modulate = Color.Transparent,
        };
    }

    private static StyleBoxFlat CreateWarpRippleStyle()
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.Transparent,
            BorderColor = Color.Transparent,
            BorderThickness = new Thickness(1f),
        };
    }

    private static Label CreateMoteLabel(string glyph)
    {
        return new Label
        {
            Text = glyph,
            FontColorOverride = Color.White,
            MouseFilter = Control.MouseFilterMode.Ignore,
            Visible = false,
            Modulate = Color.Transparent,
        };
    }

    private static Label CreateStageRuneLabel(string glyph)
    {
        return new Label
        {
            Text = glyph,
            FontColorOverride = Color.White,
            MouseFilter = Control.MouseFilterMode.Ignore,
            Modulate = Color.Transparent,
        };
    }

    private static Color ResolveEntryBackground(WH40KChaosPatron patron)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => Color.FromHex("#151012"),
            WH40KChaosPatron.Nurgle => Color.FromHex("#101510"),
            WH40KChaosPatron.Slaanesh => Color.FromHex("#15101A"),
            WH40KChaosPatron.Tzeentch => Color.FromHex("#10151B"),
            _ => Color.FromHex("#14161D"),
        };
    }

    private static Color ResolvePreviewBackground(WH40KChaosPatron patron)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => Color.FromHex("#131014"),
            WH40KChaosPatron.Nurgle => Color.FromHex("#101412"),
            WH40KChaosPatron.Slaanesh => Color.FromHex("#12101A"),
            WH40KChaosPatron.Tzeentch => Color.FromHex("#10151D"),
            _ => Color.FromHex("#11151E"),
        };
    }

    private static Color ResolvePatronAccent(WH40KChaosPatron patron)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => Color.FromHex("#B94E55"),
            WH40KChaosPatron.Nurgle => Color.FromHex("#5AA866"),
            WH40KChaosPatron.Slaanesh => Color.FromHex("#A56AD4"),
            WH40KChaosPatron.Tzeentch => Color.FromHex("#66AEDC"),
            _ => Color.FromHex("#7B8896"),
        };
    }

    private void InitGiftIcons(WH40KChaosPatron patron)
    {
        if (!_entryGiftIcons.TryGetValue(patron, out var icons))
            return;

        for (var slot = 1; slot <= icons.Length; slot++)
        {
            var icon = icons[slot - 1];
            icon.Texture = _sprite.Frame0(GetGiftIconSpecifier(patron, slot));
            icon.ToolTip = $"{Loc.GetString(GetGiftTitleKey(patron, slot))}\n{Loc.GetString(GetGiftDescriptionKey(patron, slot))}";
        }
    }

    private FormattedMessage BuildGiftSummary(WH40KChaosPatron patron)
    {
        var message = new FormattedMessage();

        for (var slot = 1; slot <= 3; slot++)
        {
            if (slot > 1)
                message.AddText("\n");

            message.PushColor(Color.FromHex("#D7BC72"));
            message.AddText($"{slot}. {Loc.GetString(GetGiftTitleKey(patron, slot))}");
            message.Pop();
            message.AddText("  ");
            message.PushColor(Color.FromHex("#CFD3DD"));
            message.AddText(Loc.GetString(GetGiftBriefKey(patron, slot)));
            message.Pop();
        }

        return message;
    }

    private string ResolveStatusText(WH40KChaosPatron patron, bool locked, WH40KChaosPatron currentPatron)
    {
        if (locked)
        {
            return Loc.GetString(
                patron == currentPatron
                    ? "wh40k-chaos-selector-preview-status-locked-current"
                    : "wh40k-chaos-selector-preview-status-locked-other",
                ("patron", Loc.GetString(GetPatronLocKey(currentPatron))));
        }

        return Loc.GetString("wh40k-chaos-selector-preview-status-open", ("patron", Loc.GetString(GetPatronLocKey(patron))));
    }

    private string ResolveLeaderName(WH40KChaosPatron patron)
    {
        if (_latestState == null)
            return Loc.GetString("wh40k-chaos-selector-no-leader");

        return patron switch
        {
            WH40KChaosPatron.Khorne => _latestState.KhorneLeaderName,
            WH40KChaosPatron.Nurgle => _latestState.NurgleLeaderName,
            WH40KChaosPatron.Slaanesh => _latestState.SlaaneshLeaderName,
            WH40KChaosPatron.Tzeentch => _latestState.TzeentchLeaderName,
            _ => Loc.GetString("wh40k-chaos-selector-no-leader"),
        };
    }

    private string ResolveButtonText(WH40KChaosPatron patron, bool locked)
    {
        if (locked)
            return Loc.GetString("wh40k-chaos-selector-commit-button-locked");

        return patron == _previewPatron
            ? Loc.GetString("wh40k-chaos-selector-commit-button", ("patron", Loc.GetString(GetPatronLocKey(patron))))
            : Loc.GetString("wh40k-chaos-selector-select-button");
    }

    private void UpdateFocusSigilTextures()
    {
        var texture = _sprite.Frame0(new SpriteSpecifier.Rsi(SkrizhalRsi, GetPatronIconState(_previewPatron)));
        FocusSigilIcon.Texture = texture;
        _focusSigilEchoPrimary.Texture = texture;
        _focusSigilEchoSecondary.Texture = texture;
    }

    private void EnsureCanvasLayering()
    {
        var layer = 0;

        foreach (var backdrop in _warpBackdrops)
        {
            backdrop.SetPositionInParent(layer++);
        }

        foreach (var ripple in _warpRipples)
        {
            ripple.SetPositionInParent(layer++);
        }

        foreach (var patron in CardOrder)
        {
            _entryShadowPanels[patron].SetPositionInParent(layer++);
        }

        foreach (var rune in _stageRunes)
        {
            rune.SetPositionInParent(layer++);
        }

        FocusSigilPanel.SetPositionInParent(layer++);

        foreach (var patron in CardOrder)
        {
            _entryPanels[patron].SetPositionInParent(layer++);
        }

        _selectionBurstRing.SetPositionInParent(layer++);
        _focusSigilEchoPrimary.SetPositionInParent(layer++);
        _focusSigilEchoSecondary.SetPositionInParent(layer++);

        foreach (var mote in _ambientMotes)
        {
            mote.SetPositionInParent(layer++);
        }

        foreach (var mote in _burstMotes)
        {
            mote.SetPositionInParent(layer++);
        }
    }

    private static Color MixColor(Color from, Color to, float amount)
    {
        amount = Math.Clamp(amount, 0f, 1f);
        return new Color(
            from.R + (to.R - from.R) * amount,
            from.G + (to.G - from.G) * amount,
            from.B + (to.B - from.B) * amount,
            from.A + (to.A - from.A) * amount);
    }

    private static Color LightenColor(Color color, float amount)
    {
        amount = Math.Clamp(amount, 0f, 1f);
        return new Color(
            color.R + (1f - color.R) * amount,
            color.G + (1f - color.G) * amount,
            color.B + (1f - color.B) * amount,
            color.A);
    }

    private bool TryGetCardFormationBounds(out Vector2 topLeft, out Vector2 size, out Vector2 center)
    {
        topLeft = Vector2.Zero;
        size = Vector2.Zero;
        center = Vector2.Zero;

        var initialized = false;
        var minX = 0f;
        var minY = 0f;
        var maxX = 0f;
        var maxY = 0f;

        foreach (var patron in CardOrder)
        {
            if (!_entryPanels.TryGetValue(patron, out var panel) || panel.Width <= 0f || panel.Height <= 0f)
                continue;

            var panelMinX = panel.Position.X;
            var panelMinY = panel.Position.Y;
            var panelMaxX = panel.Position.X + panel.Size.X;
            var panelMaxY = panel.Position.Y + panel.Size.Y;

            if (!initialized)
            {
                minX = panelMinX;
                minY = panelMinY;
                maxX = panelMaxX;
                maxY = panelMaxY;
                initialized = true;
                continue;
            }

            minX = MathF.Min(minX, panelMinX);
            minY = MathF.Min(minY, panelMinY);
            maxX = MathF.Max(maxX, panelMaxX);
            maxY = MathF.Max(maxY, panelMaxY);
        }

        if (!initialized)
            return false;

        topLeft = new Vector2(minX, minY);
        size = new Vector2(maxX - minX, maxY - minY);
        center = topLeft + size * 0.5f;
        return true;
    }

    private static float EaseOutCubic(float value)
    {
        value = Math.Clamp(value, 0f, 1f);
        var inv = 1f - value;
        return 1f - inv * inv * inv;
    }

    private static float GetCardPhase(WH40KChaosPatron patron)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => 0.15f,
            WH40KChaosPatron.Nurgle => 1.35f,
            WH40KChaosPatron.Slaanesh => 2.2f,
            WH40KChaosPatron.Tzeentch => 3.05f,
            _ => 0f,
        };
    }

    private static float GetCardAmplitude(WH40KChaosPatron patron)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => 8f,
            WH40KChaosPatron.Nurgle => 11f,
            WH40KChaosPatron.Slaanesh => 9f,
            WH40KChaosPatron.Tzeentch => 12f,
            _ => 8f,
        };
    }

    private static float GetCardBaseOffset(WH40KChaosPatron patron)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => 8f,
            WH40KChaosPatron.Nurgle => -4f,
            WH40KChaosPatron.Slaanesh => 10f,
            WH40KChaosPatron.Tzeentch => -2f,
            _ => 0f,
        };
    }

    private static string GetDescriptionKey(WH40KChaosPatron patron)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => "wh40k-chaos-selector-khorne-desc",
            WH40KChaosPatron.Nurgle => "wh40k-chaos-selector-nurgle-desc",
            WH40KChaosPatron.Slaanesh => "wh40k-chaos-selector-slaanesh-desc",
            WH40KChaosPatron.Tzeentch => "wh40k-chaos-selector-tzeentch-desc",
            _ => "wh40k-chaos-selector-khorne-desc",
        };
    }

    private static string GetDomainKey(WH40KChaosPatron patron)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => "wh40k-chaos-selector-khorne-domain",
            WH40KChaosPatron.Nurgle => "wh40k-chaos-selector-nurgle-domain",
            WH40KChaosPatron.Slaanesh => "wh40k-chaos-selector-slaanesh-domain",
            WH40KChaosPatron.Tzeentch => "wh40k-chaos-selector-tzeentch-domain",
            _ => "wh40k-chaos-selector-khorne-domain",
        };
    }

    private static string GetGiftTitleKey(WH40KChaosPatron patron, int index)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => $"w40k-ch-khorne-gift-{index}-title",
            WH40KChaosPatron.Nurgle => $"w40k-ch-nurgle-gift-{index}-title",
            WH40KChaosPatron.Slaanesh => $"w40k-ch-slaanesh-gift-{index}-title",
            WH40KChaosPatron.Tzeentch => $"w40k-ch-tzeentch-gift-{index}-title",
            _ => $"w40k-ch-khorne-gift-{index}-title",
        };
    }

    private static string GetGiftDescriptionKey(WH40KChaosPatron patron, int index)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => $"w40k-ch-khorne-gift-{index}-desc",
            WH40KChaosPatron.Nurgle => $"w40k-ch-nurgle-gift-{index}-desc",
            WH40KChaosPatron.Slaanesh => $"w40k-ch-slaanesh-gift-{index}-desc",
            WH40KChaosPatron.Tzeentch => $"w40k-ch-tzeentch-gift-{index}-desc",
            _ => $"w40k-ch-khorne-gift-{index}-desc",
        };
    }

    private static string GetGiftBriefKey(WH40KChaosPatron patron, int index)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => $"wh40k-chaos-selector-khorne-gift-{index}-brief",
            WH40KChaosPatron.Nurgle => $"wh40k-chaos-selector-nurgle-gift-{index}-brief",
            WH40KChaosPatron.Slaanesh => $"wh40k-chaos-selector-slaanesh-gift-{index}-brief",
            WH40KChaosPatron.Tzeentch => $"wh40k-chaos-selector-tzeentch-gift-{index}-brief",
            _ => $"wh40k-chaos-selector-khorne-gift-{index}-brief",
        };
    }

    private static SpriteSpecifier.Rsi GetGiftIconSpecifier(WH40KChaosPatron patron, int slot)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => slot switch
            {
                1 => new SpriteSpecifier.Rsi(EnergyKatanaRsi, "icon"),
                2 => new SpriteSpecifier.Rsi(MagicActionsRsi, "shield"),
                3 => new SpriteSpecifier.Rsi(JumpActionRsi, "icon"),
                _ => new SpriteSpecifier.Rsi(MagicActionsRsi, "fireball"),
            },
            WH40KChaosPatron.Nurgle => slot switch
            {
                1 => new SpriteSpecifier.Rsi(SmokeActionRsi, "smokeaction"),
                2 => new SpriteSpecifier.Rsi(MagicActionsRsi, "fireball"),
                3 => new SpriteSpecifier.Rsi(SmokeActionRsi, "smokeaction"),
                _ => new SpriteSpecifier.Rsi(SmokeActionRsi, "smokeaction"),
            },
            WH40KChaosPatron.Slaanesh => slot switch
            {
                1 => new SpriteSpecifier.Rsi(EldritchActionsRsi, "voidblink"),
                2 => new SpriteSpecifier.Rsi(SmokeActionRsi, "smokeaction"),
                3 => new SpriteSpecifier.Rsi(MagicActionsRsi, "blink"),
                _ => new SpriteSpecifier.Rsi(MagicActionsRsi, "blink"),
            },
            WH40KChaosPatron.Tzeentch => slot switch
            {
                1 => new SpriteSpecifier.Rsi(MagicActionsRsi, "shield"),
                2 => new SpriteSpecifier.Rsi(JumpActionRsi, "icon"),
                3 => new SpriteSpecifier.Rsi(OrgansRsi, "brain"),
                _ => new SpriteSpecifier.Rsi(MagicActionsRsi, "fireball"),
            },
            _ => slot switch
            {
                1 => new SpriteSpecifier.Rsi(MagicActionsRsi, "blink"),
                2 => new SpriteSpecifier.Rsi(MagicActionsRsi, "shield"),
                3 => new SpriteSpecifier.Rsi(MagicActionsRsi, "fireball"),
                _ => new SpriteSpecifier.Rsi(MagicActionsRsi, "fireball"),
            },
        };
    }

    private static string GetPatronLocKey(WH40KChaosPatron patron)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => "wh40k-chaos-patron-khorne",
            WH40KChaosPatron.Nurgle => "wh40k-chaos-patron-nurgle",
            WH40KChaosPatron.Slaanesh => "wh40k-chaos-patron-slaanesh",
            WH40KChaosPatron.Tzeentch => "wh40k-chaos-patron-tzeentch",
            WH40KChaosPatron.Undivided => "wh40k-chaos-patron-undivided",
            _ => "wh40k-chaos-window-patron-none",
        };
    }

    private static string GetPatronIconState(WH40KChaosPatron patron)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => "skrizhal_khorn",
            WH40KChaosPatron.Nurgle => "skrizhal_nurgk",
            WH40KChaosPatron.Slaanesh => "skrizhal_slaanesh",
            WH40KChaosPatron.Tzeentch => "skrizhal_tzinch",
            _ => "skrizhal_chaos",
        };
    }
}
