using Content.Client.Localization;
using Content.Client.UserInterface.Controls;
using Content.Shared._WH40K.Psyker;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WH40K.Psyker.UI;

[GenerateTypedNameReferences]
public sealed partial class WH40KChaosGiftsWindow : FancyWindow, ILocalizedControl
{
    private WH40KChaosGiftsViewState? _latestState;
    private readonly StyleBoxFlat _levelProgressBackgroundStyle = new()
    {
        BackgroundColor = Color.FromHex("#1A2430")
    };

    private readonly StyleBoxFlat _levelProgressForegroundStyle = new()
    {
        BackgroundColor = Color.FromHex("#60748B")
    };

    private readonly StyleBoxFlat _warpProgressBackgroundStyle = new()
    {
        BackgroundColor = Color.FromHex("#111A22")
    };

    private readonly StyleBoxFlat _warpProgressForegroundStyle = new()
    {
        BackgroundColor = Color.FromHex("#5579A5")
    };

    private readonly StyleBoxFlat _instabilityProgressBackgroundStyle = new()
    {
        BackgroundColor = Color.FromHex("#111A22")
    };

    private readonly StyleBoxFlat _instabilityProgressForegroundStyle = new()
    {
        BackgroundColor = Color.FromHex("#A86058")
    };

    private readonly StyleBoxFlat _headerStyle;
    private readonly StyleBoxFlat _telemetryStyle;
    private readonly StyleBoxFlat _altarStyle;

    public WH40KChaosGiftsWindow()
    {
        RobustXamlLoader.Load(this);

        _headerStyle = (StyleBoxFlat) HeaderPanel.PanelOverride!;
        _telemetryStyle = (StyleBoxFlat) TelemetryPanel.PanelOverride!;
        _altarStyle = (StyleBoxFlat) AltarPanel.PanelOverride!;

        LevelProgressBar.BackgroundStyleBoxOverride = _levelProgressBackgroundStyle;
        LevelProgressBar.ForegroundStyleBoxOverride = _levelProgressForegroundStyle;
        WarpChargeBar.BackgroundStyleBoxOverride = _warpProgressBackgroundStyle;
        WarpChargeBar.ForegroundStyleBoxOverride = _warpProgressForegroundStyle;
        WarpInstabilityBar.BackgroundStyleBoxOverride = _instabilityProgressBackgroundStyle;
        WarpInstabilityBar.ForegroundStyleBoxOverride = _instabilityProgressForegroundStyle;
    }

    public void Relocalize()
    {
        // State text is fully built by WH40KWarpUiController;
        // if we have a cached state, re-apply it (controller will push fresh strings next frame).
        if (_latestState != null)
            ApplyState(_latestState.Value);
    }

    public void ApplyState(WH40KChaosGiftsViewState state)
    {
        _latestState = state;
        ApplyAccent(state.Patron, state.WarpInstabilityFraction);

        RoleLabel.Text = state.RoleText;
        PatronLabel.Text = state.PatronText;
        SoulsLabel.Text = state.SoulsText;
        WarpChargeLabel.Text = state.WarpChargeText;
        WarpInstabilityLabel.Text = state.WarpInstabilityText;
        LevelLabel.Text = state.LevelText;
        XpLabel.Text = state.XpText;
        PassiveIncomeLabel.Text = state.PassiveIncomeText;
        AltarTitleLabel.Text = state.AltarTitleText;
        AttunementLabel.Text = state.AttunementText;
        RitualBonusLabel.Text = state.RitualText;
        SacrificeCooldownLabel.Text = state.CooldownText;
        AltarGuideLabel.Text = state.AltarGuideText;
        AltarRiskLabel.Text = state.AltarRiskText;
        DevelopmentPointsLabel.Text = state.DevelopmentPointsText;
        HintLabel.Text = state.HintText;
        LevelProgressBar.Value = state.LevelProgress;
        WarpChargeBar.Value = state.WarpChargeFraction;
        WarpInstabilityBar.Value = state.WarpInstabilityFraction;
    }

    private void ApplyAccent(WH40KChaosPatron patron, float instabilityFraction)
    {
        var accent = ResolvePatronAccent(patron);
        _levelProgressForegroundStyle.BackgroundColor = accent;
        _warpProgressForegroundStyle.BackgroundColor = MixColor(Color.FromHex("#2F77DC"), accent, 0.35f);
        _instabilityProgressForegroundStyle.BackgroundColor = MixColor(Color.FromHex("#C25A44"), accent, 0.18f + instabilityFraction * 0.12f);
        _headerStyle.BorderColor = accent.WithAlpha(0.52f);
        _telemetryStyle.BorderColor = accent.WithAlpha(0.54f);
        _altarStyle.BorderColor = accent.WithAlpha(0.58f);
    }

    private static Color ResolvePatronAccent(WH40KChaosPatron patron)
    {
        return patron switch
        {
            WH40KChaosPatron.Khorne => Color.FromHex("#C14B53"),
            WH40KChaosPatron.Nurgle => Color.FromHex("#4FA95E"),
            WH40KChaosPatron.Slaanesh => Color.FromHex("#9A63C8"),
            WH40KChaosPatron.Tzeentch => Color.FromHex("#5DA8D8"),
            _ => Color.FromHex("#7B88A6"),
        };
    }

    private static Color MixColor(Color a, Color b, float amount)
    {
        amount = Math.Clamp(amount, 0f, 1f);
        return new Color(
            a.R + (b.R - a.R) * amount,
            a.G + (b.G - a.G) * amount,
            a.B + (b.B - a.B) * amount,
            1f);
    }
}
