using System;
using System.Numerics;
using Content.Client._WH40K.Interface;
using Content.Client.Localization;
using Content.Shared._WH40K.Psyker;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._WH40K.Psyker.UI;

[GenerateTypedNameReferences]
public sealed partial class WH40KWarpHudControl : Control
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    private readonly SpriteSystem _sprite;

    private readonly StyleBoxFlat _rootFrameStyle = new();
    private readonly StyleBoxFlat _topAccentStyle = new();
    private readonly StyleBoxFlat _glyphPanelStyle = new();
    private readonly StyleBoxFlat _telemetryStyle = new();
    private readonly StyleBoxFlat _warpChargeBarStyle = new();
    private readonly StyleBoxFlat _warpInstabilityBarStyle = new();
    private readonly StyleBoxFlat _warpChargeBarBackgroundStyle = new();
    private readonly StyleBoxFlat _warpInstabilityBarBackgroundStyle = new();

    private bool? _lastChaosTheme;
    private InstabilityTierVisual? _lastTier;

    private static readonly ResPath SkrizhalRsi = new("_WH40K/Interface/Abilities/skrizhali_runes.rsi");

    private enum InstabilityTierVisual
    {
        Stable,
        Tense,
        Critical,
    }

    public WH40KWarpHudControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entityManager.System<SpriteSystem>();

        RootFrame.PanelOverride = _rootFrameStyle;
        TopAccent.PanelOverride = _topAccentStyle;
        HeaderGlyphPanel.PanelOverride = _glyphPanelStyle;
        TelemetryPanel.PanelOverride = _telemetryStyle;

        LayoutContainer.SetAnchorPreset(ContentRoot, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(CriticalFog, LayoutContainer.LayoutPreset.Center);
        LayoutContainer.SetPosition(CriticalFog, new Vector2(-110f, -56f));
        LayoutContainer.SetAnchorPreset(WarpChargeBar, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(WarpInstabilityBar, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(WarpChargeOverlay, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(WarpInstabilityOverlay, LayoutContainer.LayoutPreset.Wide);

        _warpChargeBarBackgroundStyle.BorderThickness = new Thickness(1f);
        _warpInstabilityBarBackgroundStyle.BorderThickness = new Thickness(1f);
        _warpChargeBarStyle.BorderThickness = new Thickness(0f);
        _warpInstabilityBarStyle.BorderThickness = new Thickness(0f);

        WarpChargeBar.BackgroundStyleBoxOverride = _warpChargeBarBackgroundStyle;
        WarpChargeBar.ForegroundStyleBoxOverride = _warpChargeBarStyle;
        WarpInstabilityBar.BackgroundStyleBoxOverride = _warpInstabilityBarBackgroundStyle;
        WarpInstabilityBar.ForegroundStyleBoxOverride = _warpInstabilityBarStyle;

        ModeTitleLabel.Align = Label.AlignMode.Left;
        TierBadgeLabel.Align = Label.AlignMode.Right;
        WarpChargeTitleLabel.Align = Label.AlignMode.Left;
        WarpChargeValueLabel.Align = Label.AlignMode.Right;
        WarpInstabilityTitleLabel.Align = Label.AlignMode.Left;
        WarpInstabilityValueLabel.Align = Label.AlignMode.Right;

        InitializeStaticVisuals();
        ApplyTheme(
            chaosTheme: false,
            patron: WH40KChaosPatron.None,
            tier: InstabilityTierVisual.Stable,
            instabilityFraction: 0f);
        UpdateModeIcon(false, WH40KChaosPatron.None);
        UpdateCriticalFog(false, WH40KChaosPatron.None, InstabilityTierVisual.Stable, 0f);
    }

    public void ApplyState(WH40KWarpHudViewState state)
    {
        Visible = state.Visible;
        if (!Visible)
            return;

        var tier = ResolveTier(state.WarpInstabilityFraction);
        ApplyTheme(state.ChaosTheme, state.Patron, tier, state.WarpInstabilityFraction);
        UpdateModeIcon(state.ChaosTheme, state.Patron);
        UpdateCriticalFog(state.ChaosTheme, state.Patron, tier, state.WarpInstabilityFraction);
        UpdateShake(state.WarpInstabilityFraction);

        ModeTitleLabel.Text = Loc.GetString(state.ChaosTheme
            ? "wh40k-warp-ui-button-chaos"
            : "wh40k-warp-ui-button-psyker");
        TierBadgeLabel.Text = Loc.GetString(GetTierLocKey(tier));

        WarpChargeTitleLabel.Text = Loc.GetString("wh40k-warp-ui-charge-label");
        WarpChargeValueLabel.Text = state.WarpChargeText;
        WarpChargeBar.Value = state.WarpChargeFraction;

        WarpInstabilityTitleLabel.Text = Loc.GetString("wh40k-warp-ui-instability-label");
        WarpInstabilityValueLabel.Text = state.WarpInstabilityText;
        WarpInstabilityBar.Value = state.WarpInstabilityFraction;
    }

    private void InitializeStaticVisuals()
    {
        ModeTitleLabel.FontColorOverride = Color.FromHex("#F3E8D8");
        TierBadgeLabel.FontColorOverride = Color.FromHex("#9FC0E2");

        WarpChargeTitleLabel.FontColorOverride = Color.FromHex("#F5F7FB");
        WarpChargeValueLabel.FontColorOverride = Color.FromHex("#F5F7FB");
        WarpInstabilityTitleLabel.FontColorOverride = Color.FromHex("#F5F7FB");
        WarpInstabilityValueLabel.FontColorOverride = Color.FromHex("#F5F7FB");
    }

    private void ApplyTheme(bool chaosTheme, WH40KChaosPatron patron, InstabilityTierVisual tier, float instabilityFraction)
    {
        var roleAccent = ResolveAccent(chaosTheme, patron);
        var tierAccent = tier switch
        {
            InstabilityTierVisual.Stable => Color.FromHex("#72A7D8"),
            InstabilityTierVisual.Tense => Color.FromHex("#D7BC72"),
            _ => Color.FromHex("#D66E6E"),
        };

        var shellBackground = chaosTheme
            ? Color.FromHex("#120D11")
            : Color.FromHex("#0D1320");
        var telemetryBackground = chaosTheme
            ? Color.FromHex("#161119")
            : Color.FromHex("#111827");
        var border = chaosTheme
            ? Color.FromHex("#6C3941")
            : Color.FromHex("#32536F");
        var accentBlend = Mix(roleAccent, tierAccent, 0.16f + instabilityFraction * 0.2f);

        ConfigurePanelStyle(_rootFrameStyle, shellBackground, accentBlend.WithAlpha(0.92f), 1f, 10f, 5f, 10f, 4f);
        ConfigurePanelStyle(_glyphPanelStyle, Mix(telemetryBackground, accentBlend, 0.2f), accentBlend.WithAlpha(0.82f), 1f, 4f, 4f, 4f, 4f);
        ConfigurePanelStyle(_telemetryStyle, telemetryBackground, border.WithAlpha(0.78f), 1f, 8f, 5f, 8f, 4f);

        _topAccentStyle.BackgroundColor = accentBlend;
        _topAccentStyle.BorderColor = accentBlend;
        _topAccentStyle.BorderThickness = new Thickness(0f);
        _topAccentStyle.ContentMarginLeftOverride = 0f;
        _topAccentStyle.ContentMarginTopOverride = 0f;
        _topAccentStyle.ContentMarginRightOverride = 0f;
        _topAccentStyle.ContentMarginBottomOverride = 0f;

        ConfigureBarBackground(_warpChargeBarBackgroundStyle, Mix(shellBackground, telemetryBackground, 0.5f), border.WithAlpha(0.66f));
        ConfigureBarBackground(_warpInstabilityBarBackgroundStyle, Mix(shellBackground, telemetryBackground, 0.5f), border.WithAlpha(0.66f));
        _warpChargeBarStyle.BackgroundColor = roleAccent;
        _warpInstabilityBarStyle.BackgroundColor = tierAccent;

        TierBadgeLabel.FontColorOverride = Mix(tierAccent, Color.White, tier == InstabilityTierVisual.Critical ? 0.2f : 0.34f);
        ModeIcon.Modulate = Mix(Color.White, accentBlend, 0.18f + instabilityFraction * 0.1f);

        if (_lastChaosTheme == chaosTheme && _lastTier == tier)
            return;

        var pulseSeconds = tier switch
        {
            InstabilityTierVisual.Stable => 3.6f,
            InstabilityTierVisual.Tense => 2.1f,
            _ => 1.2f,
        };

        WH40KUiChrome.StartLoopingPulse(TopAccent, "warp-hud-accent-pulse", accentBlend.WithAlpha(0.78f), Color.White, pulseSeconds);
        WH40KUiChrome.StartLoopingPulse(ModeIcon, "warp-hud-icon-pulse", accentBlend.WithAlpha(tier == InstabilityTierVisual.Critical ? 0.64f : 0.82f), Color.White, MathF.Max(1f, pulseSeconds - 0.1f));

        _lastChaosTheme = chaosTheme;
        _lastTier = tier;
    }

    private void UpdateModeIcon(bool chaosTheme, WH40KChaosPatron patron)
    {
        var state = chaosTheme
            ? patron switch
            {
                WH40KChaosPatron.Khorne => "skrizhal_khorn",
                WH40KChaosPatron.Nurgle => "skrizhal_nurgk",
                WH40KChaosPatron.Slaanesh => "skrizhal_slaanesh",
                WH40KChaosPatron.Tzeentch => "skrizhal_tzinch",
                _ => "skrizhal_chaos",
            }
            : "skrizhal_chaos";

        ModeIcon.Texture = _sprite.Frame0(new SpriteSpecifier.Rsi(SkrizhalRsi, state));
    }

    private void UpdateCriticalFog(bool chaosTheme, WH40KChaosPatron patron, InstabilityTierVisual tier, float instabilityFraction)
    {
        var visible = tier == InstabilityTierVisual.Critical;
        CriticalFog.Visible = visible;
        if (!visible)
        {
            CriticalFog.Modulate = Color.Transparent;
            return;
        }

        var state = chaosTheme
            ? patron switch
            {
                WH40KChaosPatron.Khorne => "skrizhal_khorn_tuchlo",
                WH40KChaosPatron.Nurgle => "skrizhal_nurgl_tuchlo",
                WH40KChaosPatron.Slaanesh => "skrizhal_slaanesh_tuchlo",
                WH40KChaosPatron.Tzeentch => "skrizhal_tzinch_tuchlo",
                _ => "skrizhal_chaos_tuchlo",
            }
            : "skrizhal_chaos_tuchlo";

        var time = (float) _timing.CurTime.TotalSeconds;
        var criticalFraction = Math.Clamp((instabilityFraction - 0.7f) / 0.3f, 0f, 1f);
        var pulse = 0.5f + 0.5f * MathF.Sin(time * 2.4f);
        var alpha = 0.04f + criticalFraction * 0.11f + pulse * 0.03f;
        var scale = 2.05f + criticalFraction * 0.28f + pulse * 0.08f;
        var accent = ResolveAccent(chaosTheme, patron);

        CriticalFog.Texture = _sprite.Frame0(new SpriteSpecifier.Rsi(SkrizhalRsi, state));
        CriticalFog.TextureScale = new Vector2(scale, scale);
        CriticalFog.Modulate = accent.WithAlpha(alpha);
    }

    private void UpdateShake(float instabilityFraction)
    {
        if (instabilityFraction <= 0.7f)
        {
            LayoutContainer.SetPosition(ContentRoot, Vector2.Zero);
            return;
        }

        var time = (float) _timing.CurTime.TotalSeconds;
        var criticalFraction = Math.Clamp((instabilityFraction - 0.7f) / 0.29f, 0f, 1f);
        var amplitude = 0.8f + criticalFraction * 6.8f;
        var offset = new Vector2(
            MathF.Sin(time * 47f) * amplitude + MathF.Sin(time * 81f + 0.9f) * amplitude * 0.38f,
            MathF.Cos(time * 39f + 0.45f) * amplitude * 0.62f + MathF.Sin(time * 67f + 1.7f) * amplitude * 0.22f);

        LayoutContainer.SetPosition(ContentRoot, offset);
    }

    private static Color ResolveAccent(bool chaosTheme, WH40KChaosPatron patron)
    {
        if (!chaosTheme)
            return Color.FromHex("#4A8FDF");

        return patron switch
        {
            WH40KChaosPatron.Khorne => Color.FromHex("#BA4747"),
            WH40KChaosPatron.Nurgle => Color.FromHex("#6E9A53"),
            WH40KChaosPatron.Slaanesh => Color.FromHex("#A86CDA"),
            WH40KChaosPatron.Tzeentch => Color.FromHex("#4A8FDF"),
            WH40KChaosPatron.Undivided => Color.FromHex("#C38A47"),
            _ => Color.FromHex("#BA4747"),
        };
    }

    private static InstabilityTierVisual ResolveTier(float instabilityFraction)
    {
        if (instabilityFraction >= 0.7f)
            return InstabilityTierVisual.Critical;

        if (instabilityFraction >= 0.35f)
            return InstabilityTierVisual.Tense;

        return InstabilityTierVisual.Stable;
    }

    private static string GetTierLocKey(InstabilityTierVisual tier)
    {
        return tier switch
        {
            InstabilityTierVisual.Stable => "wh40k-warp-ui-instability-tier-stable",
            InstabilityTierVisual.Tense => "wh40k-warp-ui-instability-tier-tense",
            _ => "wh40k-warp-ui-instability-tier-critical",
        };
    }

    private static void ConfigurePanelStyle(
        StyleBoxFlat style,
        Color background,
        Color border,
        float thickness,
        float marginLeft,
        float marginTop,
        float marginRight,
        float marginBottom)
    {
        style.BackgroundColor = background;
        style.BorderColor = border;
        style.BorderThickness = new Thickness(thickness);
        style.ContentMarginLeftOverride = marginLeft;
        style.ContentMarginTopOverride = marginTop;
        style.ContentMarginRightOverride = marginRight;
        style.ContentMarginBottomOverride = marginBottom;
    }

    private static void ConfigureBarBackground(StyleBoxFlat style, Color background, Color border)
    {
        style.BackgroundColor = background;
        style.BorderColor = border;
    }

    private static Color Mix(Color from, Color to, float amount)
    {
        amount = Math.Clamp(amount, 0f, 1f);
        return new Color(
            from.R + (to.R - from.R) * amount,
            from.G + (to.G - from.G) * amount,
            from.B + (to.B - from.B) * amount,
            from.A + (to.A - from.A) * amount);
    }
}
