using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;

namespace Content.Client.UserInterface.Systems.Character.Windows;

[GenerateTypedNameReferences]
public sealed partial class CharacterWindow : FancyWindow
{
    public CharacterWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
