- type: chameleonOutfit
  id: WH40KGuardsmanChameleonOutfit
  job: Guardsman
  startingGear: GuardsmanGear

- type: chameleonOutfit
  id: WH40KVoxScoutChameleonOutfit
  job: VoxScout
  startingGear: VoxScoutGear

- type: chameleonOutfit
  id: WH40KTitheSupplierChameleonOutfit
  job: TitheSupplier
  startingGear: TitheSupplierGear

- type: chameleonOutfit
  id: WH40KMunitorumOfficerChameleonOutfit
  job: MunitorumOfficer
  startingGear: MunitorumOfficerGear

- type: chameleonOutfit
  id: WH40KSpecialistSWSChameleonOutfit
  job: SpecialistSWS
  startingGear: GuardsmanSpesSpecGear

- type: chameleonOutfit
  id: WH40KSpecialistHWSChameleonOutfit
  job: SpecialistHWS
  startingGear: GuardsmanHevSpecGear

- type: chameleonOutfit
  id: WH40KSergeantChameleonOutfit
  job: Sergeant
  startingGear: SergeantGear

- type: chameleonOutfit
  id: WH40KSergeantSWSChameleonOutfit
  job: SergeantSWS
  startingGear: SergeantGear

- type: chameleonOutfit
  id: WH40KSergeantHWSChameleonOutfit
  job: SergeantHWS
  startingGear: SergeantGear

- type: chameleonOutfit
  id: WH40KPsykerChameleonOutfit
  job: Psyker
  startingGear: PsykerGear

- type: chameleonOutfit
  id: WH40KMedicChameleonOutfit
  job: Medic
  startingGear: MedicGear

- type: chameleonOutfit
  id: WH40KLieutenantChameleonOutfit
  job: Lieutenant
  startingGear: LieutenantGear

- type: chameleonOutfit
  id: WH40KColonelChameleonOutfit
  job: Colonel
  startingGear: ColonelGear

- type: chameleonOutfit
  id: WH40KCommissarChameleonOutfit
  job: Commissar
  startingGear: CommissarGear

- type: chameleonOutfit
  id: WH40KHGuardsmanChameleonOutfit
  job: HGuardsman
  startingGear: HeresyGuardsmanGear

- type: chameleonOutfit
  id: WH40KHBandSupplierChameleonOutfit
  job: HBandSupplier
  startingGear: HBandSupplierGear

- type: chameleonOutfit
  id: WH40KHSpecialistSWSChameleonOutfit
  job: HSpecialistSWS
  startingGear: HeresyGuardsmanGear

- type: chameleonOutfit
  id: WH40KHSpecialistHWSChameleonOutfit
  job: HSpecialistHWS
  startingGear: HeresyGuardsmanGear

- type: chameleonOutfit
  id: WH40KHSergeantChameleonOutfit
  job: HSergeant
  startingGear: HeresySergeantGear

- type: chameleonOutfit
  id: WH40KHSergeantSWSChameleonOutfit
  job: HSergeantSWS
  startingGear: HeresySergeantGear

- type: chameleonOutfit
  id: WH40KHSergeantHWSChameleonOutfit
  job: HSergeantHWS
  startingGear: HeresySergeantGear

- type: chameleonOutfit
  id: WH40KHLieutenantChameleonOutfit
  job: HLieutenant
  startingGear: HeresyLieutenantGear

- type: chameleonOutfit
  id: WH40KHColonelChameleonOutfit
  job: HColonel
  startingGear: HeresyColonelGear

- type: chameleonOutfit
  id: WH40KTauFireWarriorChameleonOutfit
  job: TauFireWarrior
  startingGear: TauFireWarriorGear

- type: chameleonOutfit
  id: WH40KTauEarthCasteChameleonOutfit
  job: TauEarthCaste
  startingGear: TauEarthCasteGear

- type: chameleonOutfit
  id: WH40KTauAirCasteChameleonOutfit
  job: TauAirCaste
  startingGear: TauAirCasteGear

- type: chameleonOutfit
  id: WH40KTauWaterCasteChameleonOutfit
  job: TauWaterCaste
  startingGear: TauWaterCasteGear

- type: chameleonOutfit
  id: WH40KTauOfficerChameleonOutfit
  job: TauOfficer
  startingGear: TauOfficerGear

- type: chameleonOutfit
  id: WH40KTauEtherealChameleonOutfit
  job: TauEthereal
  startingGear: TauEtherealGear

- type: chameleonOutfit
  id: WH40KChaplainChameleonOutfit
  job: WH40KChaplain
  startingGear: WH40KChaplainGear
