- type: department
  id: Mechanicus
  name: department-Mechanicus
  description: department-Mechanicus-description
  color: "#800000"
  roles:
  - Magos
  - Explorator
  - Genetor
  - Enginseer
  - Novice
  editorHidden: true

- type: department
  id: Imperium
  name: department-Imperium
  description: department-Imperium-description
  color: "#006400"
  roles:
  - Colonel
  - Commissar
  - Major
  - Lieutenant
  - Sergeant
  - SpecialistSWS
  - SpecialistHWS
  - Guardsman
  - Psyker
  - VoxScout
  - TitheSupplier
  - MunitorumOfficer
  - WH40KChaplain
  - Lexmechanic
  - Medic

- type: department
  id: DarkMechanicum
  name: department-Dark-Mechanicum
  description: department-Dark-Mechanicus-description
  color: "#800000"
  roles:
  - HMagos
  - HExplorator
  - HGenetor
  - HEnginseer
  - HNovice
  editorHidden: true

- type: department
  id: Heretics
  name: department-Heretics
  description: department-Heretics-description
  color: "#800000"
  roles:
  - HColonel
  - HLieutenant
  - HSergeant
  - HSpecialistSWS
  - HSpecialistHWS
  - HGuardsman
  - HVoxScout
  - HBandSupplier
  - HLexmechanic

- type: department
  id: Tau
  name: department-Tau
  description: department-Tau-description
  color: "#2f6f87"
  roles:
  - TauEthereal
  - TauOfficer
  - TauFireWarrior
