using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.Localization;
using Content.Shared._WH40K.Roadmap;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WH40K.Roadmap;

[GenerateTypedNameReferences]
public sealed partial class RoadmapWindow : DefaultWindow, ILocalizedControl
{
    [Dependency] private readonly RoadmapManager _roadmapManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    private readonly int _currentYear = DateTime.UtcNow.Year;

    public RoadmapWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        Relocalize();
    }

    public void Relocalize()
    {
        Title = Loc.GetString("server-info-roadmap-button");
        DiscordButton.Text = Loc.GetString("server-info-discord-button");
        CreditsButton.Text = Loc.GetString("server-info-credits-button");
        NowHeader.Text = Loc.GetString("roadmap-column-now");
        NextHeader.Text = Loc.GetString("roadmap-column-next");
        LaterHeader.Text = Loc.GetString("roadmap-column-later");

        var headerText = Loc.GetString("roadmap-header", ("year", _currentYear));
        var header = new FormattedMessage();
        header.AddMarkupOrThrow($"[font size=26][bold]{headerText}[/bold][/font]");
        Header.SetMessage(header);

        PopulateTasks();
    }

    protected override void Opened()
    {
        base.Opened();
        _roadmapManager.SaveNewReadId();
    }

    private void PopulateTasks()
    {
        WH40KRoadmapPrototype? roadmap = null;
        try
        {
            if (_prototypeManager.HasIndex<WH40KRoadmapPrototype>(RoadmapManager.RoadmapPrototypeId))
                roadmap = _prototypeManager.Index<WH40KRoadmapPrototype>(RoadmapManager.RoadmapPrototypeId);
        }
        catch (UnknownPrototypeException)
        {
            roadmap = null;
        }

        if (roadmap == null)
        {
            PopulateColumn(NowTasks, Array.Empty<WH40KRoadmapTaskEntry>());
            PopulateColumn(NextTasks, Array.Empty<WH40KRoadmapTaskEntry>());
            PopulateColumn(LaterTasks, Array.Empty<WH40KRoadmapTaskEntry>());
            return;
        }

        _roadmapManager.SetCurrentRevision(roadmap.Revision);
        PopulateColumn(NowTasks, roadmap.Now);
        PopulateColumn(NextTasks, roadmap.Next);
        PopulateColumn(LaterTasks, roadmap.Later);
    }

    private static void PopulateColumn(BoxContainer container, IReadOnlyCollection<WH40KRoadmapTaskEntry> entries)
    {
        container.RemoveAllChildren();
        foreach (var entry in entries.OrderBy(e => e.SortOrder))
        {
            var item = new RoadmapItem
            {
                ItemState = ToClientState(entry.State),
                HeaderText = Loc.GetString(entry.Title)
            };

            if (entry.Description is { } description && !string.IsNullOrWhiteSpace(description))
                item.Text = Loc.GetString(description);
            else
                item.Text = string.Empty;

            container.AddChild(item);
        }
    }

    private static RoadmapItemState ToClientState(WH40KRoadmapTaskState state)
    {
        return state switch
        {
            WH40KRoadmapTaskState.Complete => RoadmapItemState.Complete,
            WH40KRoadmapTaskState.InProgress => RoadmapItemState.InProgress,
            _ => RoadmapItemState.Planned
        };
    }
}
