using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.Localization;
using Content.Client.UserInterface.Controls;
using Content.Shared._WH40K.TacticalMap;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Localization;
using Robust.Shared.Map;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._WH40K.TacticalMap.UI;

[GenerateTypedNameReferences]
public sealed partial class WH40KTacticalMapWindow : FancyWindow, ILocalizedControl
{
    [Dependency] private  IEntityManager _entMan = default!;

    private const float LeftRailWidth = 308f;
    private static readonly Color AccentBorderBrightColor = Color.FromHex("#D7B65A".AsSpan());
    private static readonly Color AccentBorderSoftColor = Color.FromHex("#4A3A22".AsSpan());
    private static readonly Color OriginalSuccessPanelColor = Color.FromHex("#203227".AsSpan());
    private static readonly Color OriginalSuccessBorderColor = Color.FromHex("#63A77A".AsSpan());
    private static readonly Color OriginalViewOnlyPanelColor = Color.FromHex("#20313A".AsSpan());
    private static readonly Color OriginalViewOnlyBorderColor = Color.FromHex("#6EA2C7".AsSpan());
    private static readonly Color OriginalLocalOnlyPanelColor = Color.FromHex("#2E2526".AsSpan());
    private static readonly Color OriginalLocalOnlyBorderColor = Color.FromHex("#A57A7A".AsSpan());
    private static readonly Color OriginalPendingPanelColor = Color.FromHex("#26314A".AsSpan());
    private static readonly Color OriginalPendingBorderColor = Color.FromHex("#7FA0D8".AsSpan());
    private static readonly Color OriginalRemotePanelColor = Color.FromHex("#3A2E1D".AsSpan());
    private static readonly Color OriginalRemoteBorderColor = Color.FromHex("#D5A356".AsSpan());
    private static readonly Color OriginalDirtyPanelColor = Color.FromHex("#40311A".AsSpan());
    private static readonly Color OriginalDirtyBorderColor = Color.FromHex("#C6A45A".AsSpan());

    private readonly List<WH40KTacticalMapSignalEntry> _signalEntries = new();
    private readonly List<(ContainerButton Button, Color Color)> _colorButtons = new();
    private readonly ButtonGroup _colorGroup = new();
    private string? _latestGridName;
    private EntityUid? _latestMapUid;
    private IReadOnlyList<WH40KTacticalMapCapturePointMarker> _latestCapturePoints = Array.Empty<WH40KTacticalMapCapturePointMarker>();
    private bool _annotationsEnabled = true;

    private static readonly Color[] Palette =
    {
        Color.Red,
        Color.FromHex("#D68B3F".AsSpan()),
        Color.FromHex("#D1C24B".AsSpan()),
        Color.LimeGreen,
        Color.Cyan,
        Color.FromHex("#4AA4FF".AsSpan()),
        Color.FromHex("#9A6BFF".AsSpan()),
        Color.FromHex("#F067D0".AsSpan()),
        Color.White,
        Color.FromHex("#B2B7C0".AsSpan()),
        Color.FromHex("#8A5A3A".AsSpan()),
        Color.FromHex("#111111".AsSpan()),
    };

    public event Action<WH40KTacticalMapSaveAnnotationsMessage>? SaveAnnotationsPressed;

    public WH40KTacticalMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        BuildColorPalette();

        FilterBar.OnTextChanged += bar => OnFilterChanged(bar.Text);
        ToggleAlliesButton.OnPressed += _ =>
        {
            TacticalMapScreen.ShowAllies = !TacticalMapScreen.ShowAllies;
            RefreshOverlayUi();
        };
        ToggleAllyNamesButton.OnPressed += _ =>
        {
            TacticalMapScreen.ShowAllyNames = !TacticalMapScreen.ShowAllyNames;
            RefreshOverlayUi();
        };
        ToggleGridButton.OnPressed += _ =>
        {
            TacticalMapScreen.ShowChunkGrid = !TacticalMapScreen.ShowChunkGrid;
            RefreshOverlayUi();
        };
        ToggleCoordinatesButton.OnPressed += _ =>
        {
            TacticalMapScreen.ShowCursorCoordinates = !TacticalMapScreen.ShowCursorCoordinates;
            RefreshOverlayUi();
        };
        PanToolButton.OnPressed += _ => SetActiveTool(WH40KTacticalMapAnnotationTool.Pan);
        BrushToolButton.OnPressed += _ => SetActiveTool(WH40KTacticalMapAnnotationTool.Brush);
        EraserToolButton.OnPressed += _ => SetActiveTool(WH40KTacticalMapAnnotationTool.Eraser);
        RecenterButton.OnPressed += _ => TacticalMapScreen.ResetView();
        ReloadSavedButton.OnPressed += _ =>
        {
            TacticalMapScreen.ReloadSavedAnnotations();
            RefreshAnnotationUi();
        };
        ClearAnnotationsButton.OnPressed += _ =>
        {
            TacticalMapScreen.ClearWorkingAnnotations();
            RefreshAnnotationUi();
        };
        SaveAnnotationsButton.OnPressed += _ =>
        {
            if (!TacticalMapScreen.CanSaveAnnotations || !TacticalMapScreen.HasUnsavedAnnotations || TacticalMapScreen.IsSavePending)
                return;

            TacticalMapScreen.MarkSaveRequested();
            SaveAnnotationsPressed?.Invoke(TacticalMapScreen.BuildSaveMessage());
            RefreshAnnotationUi();
        };

        ThicknessSlider.OnValueChanged += _ => UpdateThickness((float) ThicknessSlider.Value);
        TacticalMapScreen.AnnotationStateChanged += RefreshAnnotationUi;
        TacticalMapScreen.ViewChanged += RefreshViewUi;

        UpdateThickness((float) ThicknessSlider.Value);
        SetAnnotationColor(Color.Red);
        SetActiveTool(WH40KTacticalMapAnnotationTool.Pan);
        ConfigureAnnotationMode(true);
        Relocalize();
        RefreshAnnotationUi();
        RefreshOverlayUi();
        RefreshViewUi();
    }

    public void Relocalize()
    {
        Title = Loc.GetString("wh40k-tactical-map-window-title");
        StatusTitleLabel.Text = Loc.GetString("wh40k-tactical-map-status-title");
        StatusToolLabel.Text = Loc.GetString("wh40k-tactical-map-status-tool");
        StatusSyncLabel.Text = Loc.GetString("wh40k-tactical-map-status-sync");
        StatusDocumentLabel.Text = Loc.GetString("wh40k-tactical-map-status-document");
        ToolsTitleLabel.Text = Loc.GetString("wh40k-tactical-map-tools-title");
        PanToolButton.Text = Loc.GetString("wh40k-tactical-map-tool-pan-button");
        BrushToolButton.Text = Loc.GetString("wh40k-tactical-map-tool-brush-button");
        EraserToolButton.Text = Loc.GetString("wh40k-tactical-map-tool-eraser-button");
        ColorTitleLabel.Text = Loc.GetString("wh40k-tactical-map-color-title");
        ThicknessTitleLabel.Text = Loc.GetString("wh40k-tactical-map-thickness-title");
        ThicknessFineLabel.Text = Loc.GetString("wh40k-tactical-map-thickness-fine");
        ThicknessHeavyLabel.Text = Loc.GetString("wh40k-tactical-map-thickness-heavy");
        AnnotationActionsTitleLabel.Text = Loc.GetString("wh40k-tactical-map-actions-title");
        ReloadSavedButton.Text = Loc.GetString("wh40k-tactical-map-action-reload");
        ClearAnnotationsButton.Text = Loc.GetString("wh40k-tactical-map-action-clear");
        SaveAnnotationsButton.Text = Loc.GetString("wh40k-tactical-map-action-save");
        OverviewTitleLabel.Text = Loc.GetString("wh40k-tactical-map-actions-title-readonly");
        RecenterButton.Text = Loc.GetString("wh40k-tactical-map-action-recenter");
        ViewportTitleLabel.Text = Loc.GetString("wh40k-tactical-map-viewport-title");
        ZoomLabel.Text = Loc.GetString("wh40k-tactical-map-zoom-label");
        CapturePointsTitleLabel.Text = Loc.GetString("wh40k-tactical-map-capture-points-title");
        CapturePointsSubtitleLabel.Text = Loc.GetString("wh40k-tactical-map-capture-points-subtitle");
        FilterBar.PlaceHolder = Loc.GetString("station-map-filter-placeholder");

        RefreshStationLabel();
        UpdateCapturePointList(_latestMapUid, _latestCapturePoints);
        ConfigureAnnotationMode(_annotationsEnabled);
        RefreshAnnotationUi();
        RefreshOverlayUi();
        RefreshViewUi();
    }

    public void Set(string gridName, EntityUid? mapUid, EntityUid tacticalMapUid, EntityUid? trackedEntity)
    {
        _latestGridName = gridName;
        var mapChanged = TacticalMapScreen.MapUid != mapUid;

        TacticalMapScreen.MapUid = mapUid;
        TacticalMapScreen.TacticalMapUid = tacticalMapUid;
        TacticalMapScreen.TrackedCoordinates.Clear();

        if (trackedEntity != null)
            TacticalMapScreen.TrackedCoordinates.Add(new EntityCoordinates(trackedEntity.Value, Vector2.Zero), (true, Color.Cyan));

        RefreshStationLabel();

        if (mapChanged)
        {
            TacticalMapScreen.ResetView();
            UpdateCapturePointList(mapUid, Array.Empty<WH40KTacticalMapCapturePointMarker>());
        }

        RefreshAnnotationUi();
        RefreshOverlayUi();
        RefreshViewUi();
    }

    public void ApplyState(WH40KTacticalMapBuiState state)
    {
        var mapUid = state.TargetGrid != NetEntity.Invalid ? _entMan.GetEntity(state.TargetGrid) : (EntityUid?) null;
        var trackedEntity = state.TrackedEntity != NetEntity.Invalid ? _entMan.GetEntity(state.TrackedEntity) : (EntityUid?) null;

        if (!string.IsNullOrWhiteSpace(state.SnapshotTexturePath))
            TacticalMapScreen.SnapshotTexturePath = new ResPath(state.SnapshotTexturePath);

        if (TacticalMapScreen.TacticalMapUid is { } tacticalMapUid)
            Set(state.GridName, mapUid, tacticalMapUid, trackedEntity);

        TacticalMapScreen.ApplyState(state);
        ConfigureAnnotationMode(state.CanAnnotate);
        UpdateCapturePointList(mapUid, state.CapturePoints);
        RefreshAnnotationUi();
        RefreshOverlayUi();
        RefreshViewUi();
    }

    public void ApplyOverlayState(WH40KTacticalMapOverlayState state)
    {
        TacticalMapScreen.ApplyOverlayState(state);
        UpdateCapturePointList(TacticalMapScreen.MapUid, state.CapturePoints);
        RefreshOverlayUi();
    }

    public void ApplyLiveRefreshState(WH40KTacticalMapLiveRefreshState state)
    {
        TacticalMapScreen.ApplyLiveRefreshState(state);
    }

    public void OnFilterChanged(string newFilter)
    {
        var visible = 0;

        foreach (var entry in _signalEntries)
        {
            entry.Visible = string.IsNullOrEmpty(newFilter) || (
                !string.IsNullOrEmpty(entry.SearchText) &&
                entry.SearchText.Contains(newFilter, StringComparison.OrdinalIgnoreCase));

            if (entry.Visible)
                visible++;
        }

        BeaconCountLabel.Text = visible.ToString();
    }

    public void UpdateCapturePointList(EntityUid? mapUid, IReadOnlyList<WH40KTacticalMapCapturePointMarker> capturePoints)
    {
        _latestMapUid = mapUid;
        _latestCapturePoints = new List<WH40KTacticalMapCapturePointMarker>(capturePoints);
        BeaconButtons.Children.Clear();
        _signalEntries.Clear();

        if (!mapUid.HasValue || capturePoints.Count == 0)
        {
            BeaconCountLabel.Text = "0";
            return;
        }

        foreach (var point in capturePoints)
        {
            var entry = new WH40KTacticalMapSignalEntry(mapUid.Value, point);
            entry.OnPressed += TacticalMapScreen.CenterToCoordinates;
            _signalEntries.Add(entry);
        }

        _signalEntries.Sort();

        foreach (var entry in _signalEntries)
        {
            BeaconButtons.AddChild(entry);
        }

        OnFilterChanged(FilterBar.Text);
    }

    private void BuildColorPalette()
    {
        foreach (var color in Palette)
        {
            var swatch = new ContainerButton
            {
                Group = _colorGroup,
                ToggleMode = true,
                MinSize = new Vector2(46f, 28f),
                HorizontalExpand = true,
                MuteSounds = true,
                StyleBoxOverride = CreateSwatchBorderStyle(false),
            };
            swatch.AddChild(new PanelContainer
            {
                PanelOverride = CreateSwatchFillStyle(color),
            });

            var capturedColor = color;
            swatch.OnToggled += args =>
            {
                if (!args.Pressed)
                    return;

                SetAnnotationColor(capturedColor);
            };

            ColorSwatches.AddChild(swatch);
            _colorButtons.Add((swatch, capturedColor));
        }
    }

    private void SetActiveTool(WH40KTacticalMapAnnotationTool tool)
    {
        if (!_annotationsEnabled)
            tool = WH40KTacticalMapAnnotationTool.Pan;

        PanToolButton.Pressed = tool == WH40KTacticalMapAnnotationTool.Pan;
        BrushToolButton.Pressed = tool == WH40KTacticalMapAnnotationTool.Brush;
        EraserToolButton.Pressed = tool == WH40KTacticalMapAnnotationTool.Eraser;
        TacticalMapScreen.SetAnnotationTool(tool);

        ToolSummaryLabel.Text = !_annotationsEnabled
            ? Loc.GetString("wh40k-tactical-map-tool-readonly-summary")
            : tool switch
        {
            WH40KTacticalMapAnnotationTool.Brush => Loc.GetString("wh40k-tactical-map-tool-brush-summary"),
            WH40KTacticalMapAnnotationTool.Eraser => Loc.GetString("wh40k-tactical-map-tool-eraser-summary"),
            _ => Loc.GetString("wh40k-tactical-map-tool-pan-summary")
        };

        MapModeBadgeLabel.Text = !_annotationsEnabled
            ? Loc.GetString("wh40k-tactical-map-mode-readonly")
            : tool switch
        {
            WH40KTacticalMapAnnotationTool.Brush => Loc.GetString("wh40k-tactical-map-mode-brush"),
            WH40KTacticalMapAnnotationTool.Eraser => Loc.GetString("wh40k-tactical-map-mode-eraser"),
            _ => Loc.GetString("wh40k-tactical-map-mode-active")
        };
    }

    private void UpdateThickness(float thickness)
    {
        TacticalMapScreen.SetAnnotationThickness(thickness);
        ThicknessValue.Text = $"{thickness:0.00}";
    }

    private void SetAnnotationColor(Color color)
    {
        TacticalMapScreen.SetAnnotationColor(color);
        CurrentColorLabel.Text = color.ToHexNoAlpha();
        CurrentColorPreview.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = color,
            BorderColor = AccentBorderBrightColor,
            BorderThickness = new Thickness(1),
        };

        UpdateColorPaletteSelection(color);
    }

    private void UpdateColorPaletteSelection(Color selectedColor)
    {
        foreach (var (button, color) in _colorButtons)
        {
            var selected = color.Equals(selectedColor);
            button.Pressed = selected;
            button.StyleBoxOverride = CreateSwatchBorderStyle(selected);
        }
    }

    private void RefreshAnnotationUi()
    {
        if (!_annotationsEnabled)
        {
            SaveAnnotationsButton.Disabled = true;
            ClearAnnotationsButton.Disabled = true;
            ReloadSavedButton.Disabled = true;

            AnnotationsStatus.Text = Loc.GetString("wh40k-tactical-map-annotations-view-only");
            OverlaySyncLabel.Text = Loc.GetString("wh40k-tactical-map-sync-view-only");
            SyncBadgeLabel.Text = Loc.GetString("wh40k-tactical-map-sync-badge-view");
            DraftBadgeLabel.Text = string.Empty;
            SyncBadge.PanelOverride = CreateBadgeStyle(
                OriginalViewOnlyPanelColor,
                OriginalViewOnlyBorderColor);
            return;
        }

        var canSave = TacticalMapScreen.CanSaveAnnotations;
        var dirty = TacticalMapScreen.HasUnsavedAnnotations;
        var remoteDirty = TacticalMapScreen.HasRemoteAnnotationChanges;
        var savePending = TacticalMapScreen.IsSavePending;

        SaveAnnotationsButton.Disabled = !canSave || !dirty || savePending;
        ClearAnnotationsButton.Disabled = !TacticalMapScreen.HasAnyWorkingAnnotations;
        ReloadSavedButton.Disabled = !dirty && !TacticalMapScreen.HasSavedAnnotations && !remoteDirty;

        AnnotationsStatus.Text = !canSave
            ? Loc.GetString("wh40k-tactical-map-annotations-local-only")
            : savePending
                ? Loc.GetString("wh40k-tactical-map-annotations-save-pending")
                : remoteDirty && dirty
                    ? Loc.GetString("wh40k-tactical-map-annotations-server-changed")
                    : dirty
                        ? Loc.GetString("wh40k-tactical-map-annotations-unsaved")
                        : Loc.GetString("wh40k-tactical-map-annotations-saved");

        OverlaySyncLabel.Text = canSave
            ? Loc.GetString("wh40k-tactical-map-sync-ready")
            : Loc.GetString("wh40k-tactical-map-sync-missing");
        SyncBadgeLabel.Text = canSave
            ? Loc.GetString("wh40k-tactical-map-sync-badge-team")
            : Loc.GetString("wh40k-tactical-map-sync-badge-local");
        DraftBadgeLabel.Text = savePending
            ? Loc.GetString("wh40k-tactical-map-draft-badge-pending")
            : remoteDirty
                ? Loc.GetString("wh40k-tactical-map-draft-badge-server")
                : dirty
                    ? Loc.GetString("wh40k-tactical-map-draft-badge-dirty")
                    : Loc.GetString("wh40k-tactical-map-draft-badge-saved");

        SyncBadge.PanelOverride = CreateBadgeStyle(
            canSave ? OriginalSuccessPanelColor : OriginalLocalOnlyPanelColor,
            canSave ? OriginalSuccessBorderColor : OriginalLocalOnlyBorderColor);

        DraftBadge.PanelOverride = CreateBadgeStyle(
            savePending
                ? OriginalPendingPanelColor
                : remoteDirty
                    ? OriginalRemotePanelColor
                    : dirty
                        ? OriginalDirtyPanelColor
                        : OriginalSuccessPanelColor,
            savePending
                ? OriginalPendingBorderColor
                : remoteDirty
                    ? OriginalRemoteBorderColor
                    : dirty
                        ? OriginalDirtyBorderColor
                        : OriginalSuccessBorderColor);
    }

    private void ConfigureAnnotationMode(bool canAnnotate)
    {
        _annotationsEnabled = canAnnotate;
        TacticalMapScreen.AnnotationsEnabled = canAnnotate;

        LeftRail.SetWidth = LeftRailWidth;
        HeaderTitleLabel.Text = Loc.GetString(canAnnotate
            ? "wh40k-tactical-map-header-title"
            : "wh40k-tactical-map-header-title-readonly");
        HeaderSubtitleLabel.Text = Loc.GetString(canAnnotate
            ? "wh40k-tactical-map-header-subtitle"
            : "wh40k-tactical-map-header-subtitle-readonly");
        LeftTitleLabel.Text = Loc.GetString(canAnnotate
            ? "wh40k-tactical-map-left-title"
            : "wh40k-tactical-map-left-title-readonly");
        LeftSubtitleLabel.Text = Loc.GetString(canAnnotate
            ? "wh40k-tactical-map-left-subtitle"
            : "wh40k-tactical-map-left-subtitle-readonly");
        ViewportSubtitleLabel.Text = Loc.GetString(canAnnotate
            ? "wh40k-tactical-map-viewport-subtitle"
            : "wh40k-tactical-map-viewport-subtitle-readonly");
        FooterLeftLabel.Text = Loc.GetString(canAnnotate
            ? "wh40k-tactical-map-footer-left"
            : "wh40k-tactical-map-footer-left-readonly");
        FooterRightLabel.Text = Loc.GetString(canAnnotate
            ? "wh40k-tactical-map-footer-right"
            : "wh40k-tactical-map-footer-right-readonly");
        AnnotationControlsStack.Visible = canAnnotate;
        AnnotationActionsPanel.Visible = canAnnotate;
        ToolsPanel.Visible = canAnnotate;
        ColorPanel.Visible = canAnnotate;
        ThicknessPanel.Visible = canAnnotate;
        ReloadSavedButton.Visible = canAnnotate;
        ClearAnnotationsButton.Visible = canAnnotate;
        SaveAnnotationsButton.Visible = canAnnotate;
        DraftBadge.Visible = canAnnotate;

        SetActiveTool(canAnnotate ? TacticalMapScreen.AnnotationTool : WH40KTacticalMapAnnotationTool.Pan);
    }

    private void RefreshOverlayUi()
    {
        var allyCount = TacticalMapScreen.AlliedMarkerCount;
        ToggleAlliesButton.Text = TacticalMapScreen.ShowAllies
            ? Loc.GetString("wh40k-tactical-map-toggle-allies-on", ("count", allyCount))
            : Loc.GetString("wh40k-tactical-map-toggle-allies-off", ("count", allyCount));
        ToggleAllyNamesButton.Text = TacticalMapScreen.ShowAllyNames
            ? Loc.GetString("wh40k-tactical-map-toggle-ally-names-on")
            : Loc.GetString("wh40k-tactical-map-toggle-ally-names-off");

        var chunkSize = Math.Max(1, TacticalMapScreen.FogChunkSize);
        ToggleGridButton.Text = TacticalMapScreen.ShowChunkGrid
            ? Loc.GetString("wh40k-tactical-map-toggle-grid-on", ("size", chunkSize))
            : Loc.GetString("wh40k-tactical-map-toggle-grid-off", ("size", chunkSize));
        ToggleCoordinatesButton.Text = TacticalMapScreen.ShowCursorCoordinates
            ? Loc.GetString("wh40k-tactical-map-toggle-coordinates-on")
            : Loc.GetString("wh40k-tactical-map-toggle-coordinates-off");
    }

    private void RefreshViewUi()
    {
        ZoomValueLabel.Text = $"{TacticalMapScreen.ZoomFactor:0.00}x";
        RecenterButton.Disabled = TacticalMapScreen.MapUid == null;
    }

    private void RefreshStationLabel()
    {
        StationName.Text = string.IsNullOrWhiteSpace(_latestGridName)
            ? Loc.GetString("station-map-unknown-station")
            : _latestGridName;
    }

    private static StyleBoxFlat CreateBadgeStyle(Color background, Color border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 10,
            ContentMarginTopOverride = 4,
            ContentMarginRightOverride = 10,
            ContentMarginBottomOverride = 4,
        };
    }

    private static StyleBoxFlat CreateSwatchBorderStyle(bool selected)
    {
        var borderThickness = selected ? 2 : 1;
        var inset = selected ? 2 : 1;
        return new StyleBoxFlat
        {
            BackgroundColor = Color.Transparent,
            BorderColor = selected ? AccentBorderBrightColor : AccentBorderSoftColor,
            BorderThickness = new Thickness(borderThickness),
            ContentMarginLeftOverride = inset,
            ContentMarginTopOverride = inset,
            ContentMarginRightOverride = inset,
            ContentMarginBottomOverride = inset,
        };
    }

    private static StyleBoxFlat CreateSwatchFillStyle(Color color)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = color,
            BorderColor = Color.Transparent,
            BorderThickness = new Thickness(0),
            ContentMarginLeftOverride = 0,
            ContentMarginTopOverride = 0,
            ContentMarginRightOverride = 0,
            ContentMarginBottomOverride = 0,
        };
    }

    [Obsolete]
    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            TacticalMapScreen.AnnotationStateChanged -= RefreshAnnotationUi;
            TacticalMapScreen.ViewChanged -= RefreshViewUi;
        }

#pragma warning disable CS0618
        base.Dispose(disposing);
#pragma warning restore CS0618
    }
}
