using Content.Client.Stylesheets;
using Content.Client.Lathe.UI;
using Content.Client._WH40K.Interface;
using Content.Shared.Materials;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client.Materials.UI;

/// <summary>
/// This widget is one row in the material storage control.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MaterialDisplay : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly MaterialStorageSystem _materialStorage;

    private readonly MaterialStorageUIController _materialUIController;

    private int _volume;
    private int _maxEjectableSheets = -1;
    private readonly EntityUid _ent;
    public readonly string Material;
    private readonly bool _canEject;
    private readonly Dictionary<int, Button> _ejectButtons = new();

    public MaterialDisplay(EntityUid ent, string material, int volume, bool canEject)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _materialStorage = _entityManager.System<MaterialStorageSystem>();
        _materialUIController = UserInterfaceManager.GetUIController<MaterialStorageUIController>();

        var spriteSys = _entityManager.System<SpriteSystem>();
        var materialProto = _prototypeManager.Index<MaterialPrototype>(material);
        Icon.Texture = spriteSys.Frame0(materialProto.Icon);
        PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(Color.FromHex("#12161D".AsSpan()), Color.FromHex("#2F3842".AsSpan()), 0);
        IconPanel.PanelOverride = WH40KLatheMenuStyles.CreateBadgeStyle(Color.FromHex("#111820".AsSpan()), Color.FromHex("#2F3842".AsSpan()), 4, 4);
        AccentBar.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = materialProto.Color.WithAlpha(0.85f),
        };
        ProductName.FontColorOverride = Color.FromHex("#D9E3E8".AsSpan());
        WH40KUiChrome.StartLoopingPulse(AccentBar, "accent-pulse", materialProto.Color.WithAlpha(0.72f), Color.White, 4.2f);

        _ent = ent;
        Material = material;
        _canEject = canEject;
        InitializeButtons();
        UpdateVolume(volume);
    }

    public void UpdateVolume(int volume)
    {
        if (_volume == volume)
            return;

        _volume = volume;
        var matProto = _prototypeManager.Index<MaterialPrototype>(Material);

        var sheetVolume = _materialStorage.GetSheetVolume(matProto);
        var sheets = (float) volume / sheetVolume;
        var maxEjectableSheets = (int) MathF.Floor(sheets);

        var unit = Loc.GetString(matProto.Unit);
        var amountText = Loc.GetString("lathe-menu-material-amount", ("amount", sheets), ("unit", unit));
        var name = Loc.GetString(matProto.Name);
        var mat = Loc.GetString("lathe-menu-material-display", ("material", name), ("amount", amountText));
        ProductName.Text = WH40KUiChrome.DecorateIfMissing(mat, WH40KUiChrome.DiamondOutline);

        UpdateButtons(maxEjectableSheets);
    }

    private void InitializeButtons()
    {
        if (!_canEject)
            return;

        int[] sheetsToEjectArray = { 1, 5, 10 };

        for (var i = 0; i < sheetsToEjectArray.Length; i++)
        {
            var sheetsToEject = sheetsToEjectArray[i];

            var styleClass = StyleClass.ButtonOpenBoth;
            if (i == 0)
                styleClass = StyleClass.ButtonOpenRight;
            else if (i == sheetsToEjectArray.Length - 1)
                styleClass = StyleClass.ButtonOpenLeft;

            var button = new Button
            {
                Name = $"{sheetsToEject}",
                Access = AccessLevel.Public,
                Text = sheetsToEject.ToString(),
                MinWidth = 45,
                StyleClasses = { styleClass }
            };

            WH40KLatheMenuStyles.ApplyButtonTheme(
                button,
                WH40KLatheMenuStyles.CreateSecondaryButtonStyle(WH40KLatheMenuTheme.Disabled),
                Color.FromHex("#D9E3E8".AsSpan()));
            button.OnMouseEntered += _ => WH40KUiChrome.PlayHoverFlash(this, $"eject-hover-{sheetsToEject}", Color.FromHex("#E0D19B".AsSpan()), 0.16f);
            WH40KUiChrome.PlayFadeIn(button, $"eject-appear-{sheetsToEject}", 0.14f, i * 0.02f);

            button.OnPressed += _ =>
            {
                _materialUIController.SendLatheEjectMessage(_ent, Material, sheetsToEject);
            };

            if (_prototypeManager.TryIndex<MaterialPrototype>(Material, out var proto))
            {
                button.ToolTip = Loc.GetString("lathe-menu-tooltip-display", ("amount", sheetsToEject), ("material", Loc.GetString(proto.Name)));
            }

            Content.AddChild(button);
            _ejectButtons[sheetsToEject] = button;
        }
    }

    private void UpdateButtons(int maxEjectableSheets)
    {
        if (!_canEject || _maxEjectableSheets == maxEjectableSheets)
            return;

        _maxEjectableSheets = maxEjectableSheets;

        foreach (var (sheetsToEject, button) in _ejectButtons)
        {
            button.Disabled = maxEjectableSheets < sheetsToEject;
        }
    }
}
