using System.Linq;
using System.Numerics;
using System.Text;
using Content.Client.Materials;
using Content.Client.UserInterface.Controls;
using Content.Client._WH40K.Interface;
using Content.Shared.Lathe;
using Content.Shared.Lathe.Prototypes;
using Content.Shared.Materials;
using Content.Shared.Materials.OreSilo;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Lathe.UI;

[GenerateTypedNameReferences]
public sealed partial class LatheMenu : FancyWindow
{
    private const string InfinitySymbol = "Inf";

    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly LatheSystem _lathe;
    private readonly MaterialStorageSystem _materialStorage;
    private WH40KLatheMenuTheme _theme = WH40KLatheMenuTheme.Disabled;
    private string _titleText = string.Empty;
    private string _subtitleText = string.Empty;
    private int _visibleRecipeCount;
    private int _totalRecipeCount;
    private int _queueBatchCount;
    private int _queueRequestedTotal;
    private int _queueInfiniteCount;
    private int _storedMaterialVolume;
    private int _loadedMaterialTypes;
    private bool _siloLinked;
    private bool _researchCapable;

    public event Action<BaseButton.ButtonEventArgs>? OnServerListButtonPressed;
    public event Action<string, int>? RecipeQueueAction;
    public event Action<string>? RecipeQueueInfiniteAction;
    public event Action<int>? QueueDeleteAction;
    public event Action<int>? QueueMoveUpAction;
    public event Action<int>? QueueMoveDownAction;
    public event Action? DeleteFabricatingAction;

    public List<ProtoId<LatheRecipePrototype>> Recipes = new();

    public List<ProtoId<LatheCategoryPrototype>>? Categories;

    public ProtoId<LatheCategoryPrototype>? CurrentCategory;

    public EntityUid Entity;
    private ProtoId<LatheRecipePrototype>? _progressRecipe;
    private ProtoId<LatheRecipePrototype>? _fabricatingDisplayRecipe;
    private int _progressPrinted;
    private TimeSpan _progressStepStart = TimeSpan.Zero;
    private TimeSpan _progressStepDuration = TimeSpan.Zero;
    private int? _materialStorageLimit;
    private static readonly TimeSpan ProgressSyncClamp = TimeSpan.FromMilliseconds(150);

    public LatheMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entityManager.System<SpriteSystem>();
        _lathe = _entityManager.System<LatheSystem>();
        _materialStorage = _entityManager.System<MaterialStorageSystem>();

        SearchBar.OnTextChanged += _ =>
        {
            PopulateRecipes();
        };
        AmountLineEdit.OnTextChanged += _ =>
        {
            if (int.TryParse(AmountLineEdit.Text, out var amount))
            {
                if (amount > LatheSystem.MaxItemsPerRequest)
                    AmountLineEdit.Text = LatheSystem.MaxItemsPerRequest.ToString();
                else if (amount < 0)
                    AmountLineEdit.Text = "0";
            }

            PopulateRecipes();
            RefreshMachineReadouts();
        };

        FilterOption.OnItemSelected += OnItemSelected;

        ServerListButton.OnPressed += a => OnServerListButtonPressed?.Invoke(a);
        DeleteFabricating.OnPressed += _ => DeleteFabricatingAction?.Invoke();

        FabricatingContainer.Visible = false;
        ApplyTheme();
        RefreshMachineReadouts();
    }

    public void SetEntity(EntityUid uid)
    {
        Entity = uid;
        this.SetInfoFromEntity(_entityManager, Entity);

        var metaData = _entityManager.GetComponent<MetaDataComponent>(Entity);
        _titleText = metaData.EntityName;
        _subtitleText = string.IsNullOrWhiteSpace(metaData.EntityDescription)
            ? Loc.GetString("lathe-menu-header-subtitle-fallback")
            : metaData.EntityDescription;
        _theme = WH40KLatheMenuStyles.ResolveTheme(metaData.EntityPrototype?.ID);

        if (_entityManager.TryGetComponent<LatheComponent>(Entity, out var latheComponent))
        {
            _researchCapable = latheComponent.DynamicPacks.Any();
            AmountLineEdit.SetText(latheComponent.DefaultProductionAmount.ToString());
        }
        else
        {
            _researchCapable = false;
        }

        MaterialsList.SetOwner(Entity);
        Title = _titleText;
        ApplyTheme();
        UpdateMaterialsTitle();
        RefreshMachineReadouts();
    }

    /// <summary>
    /// Populates the list of all the recipes
    /// </summary>
    public void PopulateRecipes()
    {
        var recipesToShow = new List<LatheRecipePrototype>();
        var totalRecipes = 0;
        foreach (var recipe in Recipes)
        {
            if (!_prototypeManager.Resolve(recipe, out var proto))
                continue;

            totalRecipes++;

            if (CurrentCategory != null)
            {
                if (proto.Categories.Count <= 0)
                    continue;

                if (!proto.Categories.Any(category => category == CurrentCategory))
                    continue;
            }

            if (SearchBar.Text.Trim().Length != 0)
            {
                if (_lathe.GetRecipeName(recipe).ToLowerInvariant().Contains(SearchBar.Text.Trim().ToLowerInvariant()))
                    recipesToShow.Add(proto);
            }
            else
            {
                recipesToShow.Add(proto);
            }
        }

        _totalRecipeCount = totalRecipes;
        _visibleRecipeCount = recipesToShow.Count;

        if (!int.TryParse(AmountLineEdit.Text, out var quantity) || quantity <= 0)
            quantity = 1;

        RecipeCountValueLabel.Text = Loc.GetString("lathe-menu-recipe-count", ("count", recipesToShow.Count));

        var sortedRecipesToShow = recipesToShow.OrderBy(_lathe.GetRecipeName);

        var oldChildCount = RecipeList.ChildCount;
        _entityManager.TryGetComponent(Entity, out LatheComponent? lathe);

        var idx = 0;
        foreach (var prototype in sortedRecipesToShow)
        {
            var canProduce = _lathe.CanProduce(Entity, prototype, quantity, component: lathe);
            var tooltipFunction = () => GenerateTooltipText(prototype);
            var metaText = BuildRecipeMetaText(prototype);

            if (idx >= oldChildCount)
            {
                var control = new RecipeControl(_lathe, prototype, tooltipFunction, canProduce, GetRecipeDisplayControl(prototype), metaText, _theme);
                control.OnButtonPressed += s =>
                {
                    if (!int.TryParse(AmountLineEdit.Text, out var amount) || amount <= 0)
                        amount = 1;
                    RecipeQueueAction?.Invoke(s, amount);
                };
                control.OnInfiniteButtonPressed += s =>
                {
                    RecipeQueueInfiniteAction?.Invoke(s);
                };
                RecipeList.AddChild(control);
                WH40KUiChrome.PlayFadeIn(control, "appear", 0.18f, MathF.Min(idx * 0.018f, 0.22f));
            }
            else
            {
                var child = RecipeList.GetChild(idx) as RecipeControl;

                if (child == null)
                {
                    DebugTools.Assert($"Lathe menu recipe control at {idx} is not of type RecipeControl"); // Something's gone terribly wrong.
                    continue;
                }

                child.SetRecipe(prototype, metaText);
                child.SetTooltipSupplier(tooltipFunction);
                child.SetCanProduce(canProduce);
                child.SetDisplayControl(GetRecipeDisplayControl(prototype), prototype.ID);
            }
            idx++;
        }

        for (var childIdx = oldChildCount - 1; idx <= childIdx; childIdx--)
        {
            RecipeList.RemoveChild(childIdx);
        }

        RecipeEmptyLabel.Visible = _visibleRecipeCount == 0;
        DesignsHeaderSubtitleLabel.Text = BuildDesignSubtitleText();
        RefreshMachineReadouts();
    }

    private string GenerateTooltipText(LatheRecipePrototype prototype)
    {
        StringBuilder sb = new();
        var multiplier = _entityManager.GetComponent<LatheComponent>(Entity).MaterialUseMultiplier;

        foreach (var (id, amount) in prototype.Materials)
        {
            if (!_prototypeManager.Resolve(id, out var proto))
                continue;

            var adjustedAmount = SharedLatheSystem.AdjustMaterial(amount, prototype.ApplyMaterialDiscount, multiplier);
            var sheetVolume = _materialStorage.GetSheetVolume(proto);

            var unit = Loc.GetString(proto.Unit);
            var sheets = adjustedAmount / (float) sheetVolume;

            var availableAmount = _materialStorage.GetMaterialAmount(Entity, id);
            var missingAmount = Math.Max(0, adjustedAmount - availableAmount);
            var missingSheets = missingAmount / (float) sheetVolume;

            var name = Loc.GetString(proto.Name);

            string tooltipText;
            if (missingSheets > 0)
            {
                tooltipText = Loc.GetString("lathe-menu-material-amount-missing", ("amount", sheets), ("missingAmount", missingSheets), ("unit", unit), ("material", name));
            }
            else
            {
                var amountText = Loc.GetString("lathe-menu-material-amount", ("amount", sheets), ("unit", unit));
                tooltipText = Loc.GetString("lathe-menu-tooltip-display", ("material", name), ("amount", amountText));
            }

            sb.AppendLine(tooltipText);
        }

        var desc = _lathe.GetRecipeDescription(prototype);
        if (!string.IsNullOrWhiteSpace(desc))
            sb.AppendLine(Loc.GetString("lathe-menu-description-display", ("description", desc)));

        // Remove last newline
        if (sb.Length > 0)
            sb.Remove(sb.Length - 1, 1);

        return sb.ToString();
    }

    public void UpdateCategories()
    {
        var currentCategories = new List<ProtoId<LatheCategoryPrototype>>();
        foreach (var recipeId in Recipes)
        {
            if (!_prototypeManager.TryIndex(recipeId, out LatheRecipePrototype? recipe))
                continue;

            if (recipe.Categories.Count <= 0)
                continue;

            foreach (var category in recipe.Categories)
            {
                if (currentCategories.Contains(category))
                    continue;

                currentCategories.Add(category);
            }
        }

        var changed = Categories == null ||
                      Categories.Count != currentCategories.Count ||
                      !Categories.All(currentCategories.Contains);

        if (!changed)
        {
            DesignsHeaderSubtitleLabel.Text = BuildDesignSubtitleText();
            return;
        }

        Categories = currentCategories;
        var sortedCategories = currentCategories
            .Select(p => _prototypeManager.Index(p))
            .OrderBy(p => Loc.GetString(p.Name))
            .ToList();

        FilterOption.Clear();
        FilterOption.AddItem(Loc.GetString("lathe-menu-category-all"), -1);
        foreach (var category in sortedCategories)
        {
            FilterOption.AddItem(Loc.GetString(category.Name), Categories.IndexOf(category.ID));
        }

        if (CurrentCategory != null && Categories.Contains(CurrentCategory.Value))
            FilterOption.SelectId(Categories.IndexOf(CurrentCategory.Value));
        else
            FilterOption.SelectId(-1);

        DesignsHeaderSubtitleLabel.Text = BuildDesignSubtitleText();
    }

    /// <summary>
    /// Populates the build queue list with all queued items
    /// </summary>
    /// <param name="queue"></param>
    public void PopulateQueueList(IReadOnlyCollection<LatheRecipeBatch> queue)
    {
        var oldChildCount = QueueList.ChildCount;
        _queueBatchCount = queue.Count;
        _queueRequestedTotal = queue.Where(batch => !batch.Infinite).Sum(batch => Math.Max(1, batch.ItemsRequested));
        _queueInfiniteCount = queue.Count(batch => batch.Infinite);

        var idx = 0;
        foreach (var batch in queue)
        {
            var recipe = _prototypeManager.Index(batch.Recipe);

            var itemName = _lathe.GetRecipeName(batch.Recipe);
            string displayText;
            if (batch.Infinite)
                displayText = Loc.GetString("lathe-menu-queue-row-infinite",
                    ("name", itemName),
                    ("printed", batch.ItemsPrinted),
                    ("infinity", InfinitySymbol));
            else if (batch.ItemsRequested > 1)
                displayText = Loc.GetString("lathe-menu-queue-row-batch", ("name", itemName), ("printed", batch.ItemsPrinted), ("total", batch.ItemsRequested));
            else
                displayText = Loc.GetString("lathe-menu-queue-row-single", ("name", itemName));

            if (idx >= oldChildCount)
            {
                var queuedRecipeBox = new QueuedRecipeControl(displayText, idx, GetRecipeDisplayControl(recipe), recipe.ID, _theme);
                queuedRecipeBox.OnDeletePressed += s => QueueDeleteAction?.Invoke(s);
                queuedRecipeBox.OnMoveUpPressed += s => QueueMoveUpAction?.Invoke(s);
                queuedRecipeBox.OnMoveDownPressed += s => QueueMoveDownAction?.Invoke(s);
                QueueList.AddChild(queuedRecipeBox);
                WH40KUiChrome.PlayFadeIn(queuedRecipeBox, "appear", 0.18f, MathF.Min(idx * 0.018f, 0.22f));
            }
            else
            {
                var child = QueueList.GetChild(idx) as QueuedRecipeControl;

                if (child == null)
                {
                    DebugTools.Assert($"Lathe menu queued recipe control at {idx} is not of type QueuedRecipeControl"); // Something's gone terribly wrong.
                    continue;
                }

                child.SetDisplayText(displayText);
                child.SetIndex(idx);
                child.SetDisplayControl(GetRecipeDisplayControl(recipe), recipe.ID);
            }
            idx++;
        }

        for (var childIdx = oldChildCount - 1; idx <= childIdx; childIdx--)
        {
            QueueList.RemoveChild(childIdx);
        }

        QueueEmptyLabel.Visible = _queueBatchCount == 0;
        RefreshMachineReadouts();
    }

    public void SetQueueInfo(
        ProtoId<LatheRecipePrototype>? recipeProto,
        LatheRecipeBatch? activeBatch,
        IReadOnlyList<LatheRecipeBatch> queue,
        bool isProducing,
        TimeSpan productionStartTime,
        TimeSpan productionLength)
    {
        FabricatingContainer.Visible = recipeProto != null;
        if (recipeProto == null)
        {
            FabricatingProgressBar.Value = 0;
            FabricatingNameLabel.Text = string.Empty;
            _progressRecipe = null;
            _fabricatingDisplayRecipe = null;
            RefreshMachineReadouts();
            return;
        }

        var recipe = _prototypeManager.Index(recipeProto.Value);
        var isInfiniteBatch = activeBatch?.Infinite == true;
        var printed = activeBatch != null ? Math.Max(0, activeBatch.ItemsPrinted) : 0;
        var requested = activeBatch != null ? Math.Max(0, activeBatch.ItemsRequested) : 0;

        if (_progressRecipe != recipe.ID ||
            _progressPrinted != printed ||
            _progressStepStart != productionStartTime ||
            _progressStepDuration != productionLength)
        {
            var cycleChanged = _progressRecipe != recipe.ID || _progressPrinted != printed;
            var stepStart = isProducing ? productionStartTime : TimeSpan.Zero;
            if (isProducing && cycleChanged && _progressRecipe != null)
            {
                var oldestVisibleStart = _timing.CurTime - ProgressSyncClamp;
                if (stepStart < oldestVisibleStart)
                    stepStart = oldestVisibleStart;
            }

            _progressRecipe = recipe.ID;
            _progressPrinted = printed;
            _progressStepStart = stepStart;
            _progressStepDuration = isProducing ? productionLength : TimeSpan.Zero;
        }

        if (_fabricatingDisplayRecipe != recipe.ID || FabricatingDisplayContainer.ChildCount == 0)
        {
            _fabricatingDisplayRecipe = recipe.ID;
            FabricatingDisplayContainer.Children.Clear();
            FabricatingDisplayContainer.AddChild(GetRecipeDisplayControl(recipe));
        }

        var nameText = _lathe.GetRecipeName(recipe);
        if (isInfiniteBatch)
        {
            nameText = Loc.GetString("lathe-menu-item-progress-infinite",
                ("name", nameText),
                ("printed", printed),
                ("infinity", InfinitySymbol));
        }
        else if (activeBatch != null && requested > 1)
        {
            nameText = $"{nameText} ({printed}/{requested})";
        }

        FabricatingNameLabel.Text = nameText;
        UpdateFabricatingProgress();
        RefreshMachineReadouts();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (FabricatingContainer.Visible)
            UpdateFabricatingProgress();

        RefreshMachineReadouts();
    }

    private void UpdateFabricatingProgress()
    {
        if (_progressRecipe == null)
        {
            FabricatingProgressBar.Value = 0f;
            return;
        }

        if (_progressStepDuration <= TimeSpan.Zero)
        {
            FabricatingProgressBar.Value = 0f;
            return;
        }

        var elapsed = _timing.CurTime - _progressStepStart;
        var stepProgress = Math.Clamp((float) (elapsed.TotalSeconds / _progressStepDuration.TotalSeconds), 0f, 1f);
        FabricatingProgressBar.Value = stepProgress;
    }

    public Control GetRecipeDisplayControl(LatheRecipePrototype recipe)
    {
        if (recipe.Icon != null)
        {
            var textRect = new TextureRect();
            textRect.Texture = _spriteSystem.Frame0(recipe.Icon);
            return textRect;
        }

        if (recipe.Result is { } result)
        {
            var entProtoView = new EntityPrototypeView();
            entProtoView.SetPrototype(result);
            return entProtoView;
        }

        return new Control();
    }

    private void OnItemSelected(OptionButton.ItemSelectedEventArgs obj)
    {
        FilterOption.SelectId(obj.Id);
        if (obj.Id == -1)
        {
            CurrentCategory = null;
        }
        else
        {
            CurrentCategory = Categories?[obj.Id];
        }
        PopulateRecipes();
        DesignsHeaderSubtitleLabel.Text = BuildDesignSubtitleText();
    }

    public void SetMaterialStorageLimit(int? limit)
    {
        _materialStorageLimit = limit;
        UpdateMaterialsTitle();
        RefreshMachineReadouts();
    }

    private void UpdateMaterialsTitle()
    {
        if (_materialStorageLimit is { } limit && limit > 0)
        {
            MaterialsHeaderLabel.Text = WH40KUiChrome.DecorateIfMissing(
                Loc.GetString("lathe-menu-materials-title-with-limit", ("max", limit)),
                WH40KUiChrome.Cog);
            return;
        }

        MaterialsHeaderLabel.Text = WH40KUiChrome.DecorateIfMissing(Loc.GetString("lathe-menu-materials-title"), WH40KUiChrome.Cog);
    }

    private void ApplyTheme()
    {
        Title = string.IsNullOrWhiteSpace(_titleText)
            ? Loc.GetString("lathe-menu-title")
            : _titleText;

        HeaderTitleLabel.Text = WH40KUiChrome.DecorateTitle(WH40KUiChrome.Cog, Title);
        HeaderSubtitleLabel.SetMessage(
            string.IsNullOrWhiteSpace(_subtitleText)
                ? Loc.GetString("lathe-menu-header-subtitle-fallback")
                : _subtitleText,
            defaultColor: _theme.SecondaryText);
        FooterLabel.Text = Loc.GetString(_theme.FooterLocKey);
        DeleteFabricating.Text = Loc.GetString("lathe-menu-abort-button");
        ServerPanelStatusLabel.SetMessage(Loc.GetString("lathe-menu-server-status-static"), defaultColor: _theme.SecondaryText);
        ServerPanelTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(ServerPanelTitleLabel.Text, WH40KUiChrome.DiamondNested);
        ProfileCardLabel.Text = WH40KUiChrome.DecorateIfMissing(ProfileCardLabel.Text, WH40KUiChrome.Diamond);
        DesignCardLabel.Text = WH40KUiChrome.DecorateIfMissing(DesignCardLabel.Text, WH40KUiChrome.DiamondOutline);
        QueueCardLabel.Text = WH40KUiChrome.DecorateIfMissing(QueueCardLabel.Text, WH40KUiChrome.Blade);
        MaterialsCardLabel.Text = WH40KUiChrome.DecorateIfMissing(MaterialsCardLabel.Text, WH40KUiChrome.Cog);
        DesignsHeaderLabel.Text = WH40KUiChrome.DecorateIfMissing(DesignsHeaderLabel.Text, WH40KUiChrome.Diamond);
        QueueHeaderLabel.Text = WH40KUiChrome.DecorateIfMissing(QueueHeaderLabel.Text, WH40KUiChrome.Blade);
        MaterialsHeaderLabel.Text = WH40KUiChrome.DecorateIfMissing(MaterialsHeaderLabel.Text, WH40KUiChrome.Cog);

        RootFrame.PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(_theme.WindowBackground, _theme.BorderStrongColor, 0);
        HeaderPanel.PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(_theme.PanelBackground, _theme.BorderStrongColor, 0);
        ServerPanel.PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);
        SearchPanel.PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);

        ProfileCard.PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);
        DesignCard.PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);
        QueueCard.PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);
        MaterialsCard.PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);

        DesignsPanel.PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(_theme.PanelBackground, _theme.BorderStrongColor, 0);
        DesignsHeaderPanel.PanelOverride = WH40KLatheMenuStyles.CreateEdgePanelStyle(
            _theme.HeaderBackground,
            _theme.BorderStrongColor,
            new Thickness(0f, 0f, 0f, 1f),
            0);
        DesignsBodyPanel.PanelOverride = WH40KLatheMenuStyles.CreateEdgePanelStyle(
            _theme.PanelBackground,
            Color.Transparent,
            new Thickness(0f),
            0);
        ControlsPanel.PanelOverride = WH40KLatheMenuStyles.CreateEdgePanelStyle(
            _theme.PanelAltBackground,
            _theme.BorderColor,
            new Thickness(0f, 1f, 0f, 0f),
            0);

        QueuePanel.PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(_theme.PanelBackground, _theme.BorderStrongColor, 0);
        QueueHeaderPanel.PanelOverride = WH40KLatheMenuStyles.CreateEdgePanelStyle(
            _theme.HeaderBackground,
            _theme.BorderStrongColor,
            new Thickness(0f, 0f, 0f, 1f),
            0);
        QueueStateBadge.PanelOverride = WH40KLatheMenuStyles.CreateBadgeStyle(_theme.PanelAltBackground, _theme.BorderColor, 10, 6);
        QueueDepthBadge.PanelOverride = WH40KLatheMenuStyles.CreateBadgeStyle(_theme.PanelAltBackground, _theme.BorderColor, 10, 6);
        RequestBadge.PanelOverride = WH40KLatheMenuStyles.CreateBadgeStyle(_theme.PanelAltBackground, _theme.BorderColor, 10, 6);
        QueueBodyPanel.PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);

        MaterialsPanel.PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(_theme.PanelBackground, _theme.BorderStrongColor, 0);
        MaterialsHeaderPanel.PanelOverride = WH40KLatheMenuStyles.CreateEdgePanelStyle(
            _theme.HeaderBackground,
            _theme.BorderStrongColor,
            new Thickness(0f, 0f, 0f, 1f),
            0);
        StorageBadge.PanelOverride = WH40KLatheMenuStyles.CreateBadgeStyle(_theme.PanelAltBackground, _theme.BorderColor, 10, 6);
        SourceBadge.PanelOverride = WH40KLatheMenuStyles.CreateBadgeStyle(_theme.PanelAltBackground, _theme.BorderColor, 10, 6);
        EfficiencyBadge.PanelOverride = WH40KLatheMenuStyles.CreateBadgeStyle(_theme.PanelAltBackground, _theme.BorderColor, 10, 6);
        MaterialsBodyPanel.PanelOverride = WH40KLatheMenuStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderColor, 0);

        SearchBar.StyleBoxOverride = WH40KLatheMenuStyles.CreateInputStyle(_theme);
        AmountLineEdit.StyleBoxOverride = WH40KLatheMenuStyles.CreateInputStyle(_theme);
        FilterOption.StyleBoxOverride = WH40KLatheMenuStyles.CreateSecondaryButtonStyle(_theme);
        FilterOption.PopupButtonStyleOverride = WH40KLatheMenuStyles.CreateSecondaryButtonStyle(_theme);
        FilterOption.PopupSelectedButtonStyleOverride = WH40KLatheMenuStyles.CreatePrimaryButtonStyle(_theme);
        FilterOption.PopupButtonFontColorOverride = _theme.PrimaryText;
        FilterOption.PopupSelectedButtonFontColorOverride = _theme.PrimaryText;
        FilterOption.RefreshPopupItemTheme();
        FabricatingProgressBar.BackgroundStyleBoxOverride = WH40KLatheMenuStyles.CreateProgressBackgroundStyle(_theme);
        FabricatingProgressBar.ForegroundStyleBoxOverride = WH40KLatheMenuStyles.CreateProgressForegroundStyle(_theme);

        FooterDivider.MinSize = new Vector2(0f, 1f);
        FooterDivider.PanelOverride = CreateDividerStyle(_theme.BorderStrongColor);

        HeaderTitleLabel.FontColorOverride = _theme.Accent;
        FooterLabel.FontColorOverride = _theme.SecondaryText;
        ServerPanelTitleLabel.FontColorOverride = _theme.LabelText;

        foreach (var label in new[]
                 {
                     ProfileCardLabel,
                     DesignCardLabel,
                     QueueCardLabel,
                     MaterialsCardLabel,
                     QueueStateKeyLabel,
                     QueueDepthKeyLabel,
                     RequestKeyLabel,
                     StorageKeyLabel,
                     SourceKeyLabel,
                     EfficiencyKeyLabel,
                     AmountLabel
                 })
        {
            label.FontColorOverride = _theme.LabelText;
        }

        foreach (var label in new[]
                 {
                     ProfileValueLabel,
                     DesignValueLabel,
                     QueueValueLabel,
                     MaterialsValueLabel,
                     QueueDepthValueLabel,
                     RequestValueLabel,
                     StorageValueLabel,
                     SourceValueLabel,
                     EfficiencyValueLabel,
                     RecipeCountValueLabel,
                     FabricatingNameLabel
                 })
        {
            label.FontColorOverride = _theme.PrimaryText;
        }

        QueueStateValueLabel.FontColorOverride = _theme.SecondaryText;

        foreach (var label in new[]
                 {
                     DesignsHeaderLabel,
                     QueueHeaderLabel,
                     MaterialsHeaderLabel
                 })
        {
            label.FontColorOverride = _theme.Accent;
        }

        foreach (var label in new[]
                 {
                     DesignsHeaderSubtitleLabel,
                     QueueHeaderSubtitleLabel,
                     MaterialsHeaderSubtitleLabel,
                     RecipeEmptyLabel,
                     QueueEmptyLabel
                 })
        {
            label.FontColorOverride = _theme.SecondaryText;
        }

        WH40KLatheMenuStyles.ApplyButtonTheme(ServerListButton, WH40KLatheMenuStyles.CreateSecondaryButtonStyle(_theme), _theme.PrimaryText);
        WH40KLatheMenuStyles.ApplyButtonTheme(DeleteFabricating, WH40KLatheMenuStyles.CreateDangerButtonStyle(_theme), _theme.PrimaryText);
        WH40KUiChrome.StartLoopingPulse(HeaderTitleLabel, "title-pulse", new Color(0.8f, 0.8f, 0.8f, 1f), Color.White, 3.1f);
        WH40KUiChrome.StartLoopingPulse(FooterDivider, "footer-pulse", new Color(0.55f, 0.55f, 0.55f, 1f), Color.White, 4.1f);
        WH40KUiChrome.StartLoopingPulse(ServerPanel, "server-pulse", new Color(0.82f, 0.82f, 0.82f, 1f), Color.White, 4.5f);
    }

    private void RefreshMachineReadouts()
    {
        if (Entity == default || !_entityManager.EntityExists(Entity))
            return;

        UpdateMaterialMetrics();

        if (!_entityManager.TryGetComponent(Entity, out LatheComponent? lathe))
            return;

        _researchCapable = lathe.DynamicPacks.Any();
        ServerListButton.Visible = _researchCapable;
        ServerListButton.Disabled = !_researchCapable;

        ProfileValueLabel.Text = Loc.GetString(_theme.ProfileLocKey);
        DesignValueLabel.Text = Loc.GetString("lathe-menu-summary-designs-value", ("visible", _visibleRecipeCount), ("total", _totalRecipeCount));
        QueueValueLabel.Text = Loc.GetString(
            _progressRecipe == null
                ? "lathe-menu-summary-queue-value-idle"
                : "lathe-menu-summary-queue-value-active",
            ("batches", _queueBatchCount));
        MaterialsValueLabel.Text = _materialStorageLimit is { } limit && limit > 0
            ? Loc.GetString("lathe-menu-summary-materials-value-limited", ("current", _storedMaterialVolume), ("max", limit))
            : Loc.GetString("lathe-menu-summary-materials-value", ("current", _storedMaterialVolume));

        ServerPanelStatusLabel.SetMessage(
            _researchCapable
                ? Loc.GetString("lathe-menu-server-status-linked", ("packs", lathe.DynamicPacks.Count))
                : Loc.GetString("lathe-menu-server-status-static"),
            defaultColor: _researchCapable ? _theme.Accent : _theme.SecondaryText);

        QueueStateValueLabel.Text = _progressRecipe == null
            ? Loc.GetString("lathe-menu-queue-state-idle")
            : Loc.GetString("lathe-menu-queue-state-printing", ("name", GetRecipeDisplayName(_progressRecipe.Value)));
        QueueStateValueLabel.FontColorOverride = _progressRecipe == null ? _theme.SecondaryText : _theme.Accent;

        QueueDepthValueLabel.Text = _queueInfiniteCount > 0
            ? Loc.GetString("lathe-menu-queue-depth-value-infinite", ("batches", _queueBatchCount), ("items", _queueRequestedTotal), ("infinite", _queueInfiniteCount))
            : Loc.GetString("lathe-menu-queue-depth-value", ("batches", _queueBatchCount), ("items", _queueRequestedTotal));

        RequestValueLabel.Text = Loc.GetString("lathe-menu-queue-request-value", ("amount", GetCurrentRequestedAmount()));
        StorageValueLabel.Text = _materialStorageLimit is { } max && max > 0
            ? Loc.GetString("lathe-menu-materials-storage-value-limited", ("current", _storedMaterialVolume), ("max", max), ("types", _loadedMaterialTypes))
            : Loc.GetString("lathe-menu-materials-storage-value", ("current", _storedMaterialVolume), ("types", _loadedMaterialTypes));

        SourceValueLabel.Text = Loc.GetString(_siloLinked
            ? "lathe-menu-materials-source-silo"
            : "lathe-menu-materials-source-internal");
        SourceValueLabel.FontColorOverride = _siloLinked ? _theme.Accent : _theme.PrimaryText;

        EfficiencyValueLabel.Text = Loc.GetString("lathe-menu-materials-efficiency-value", ("multiplier", lathe.MaterialUseMultiplier.ToString("0.##")));
        EfficiencyValueLabel.FontColorOverride = lathe.MaterialUseMultiplier < 1f
            ? _theme.SuccessAccent
            : _theme.PrimaryText;

        DesignsHeaderSubtitleLabel.Text = BuildDesignSubtitleText();
        QueueEmptyLabel.Visible = _queueBatchCount == 0;
        RecipeEmptyLabel.Visible = _visibleRecipeCount == 0;
    }

    private void UpdateMaterialMetrics()
    {
        _storedMaterialVolume = 0;
        _loadedMaterialTypes = 0;
        _siloLinked = false;

        if (!_entityManager.TryGetComponent(Entity, out MaterialStorageComponent? materialStorage))
            return;

        var stored = _materialStorage.GetStoredMaterials((Entity, materialStorage));
        _storedMaterialVolume = stored.Values.Sum();
        _loadedMaterialTypes = stored.Count(pair => pair.Value > 0);
        _siloLinked = _entityManager.TryGetComponent<OreSiloClientComponent>(Entity, out var client) && client.Silo != null;
    }

    private string BuildRecipeMetaText(LatheRecipePrototype prototype)
    {
        var materialKinds = prototype.Materials.Count;
        var seconds = Math.Max(1, (int) MathF.Ceiling((float) prototype.CompleteTime.TotalSeconds));

        if (prototype.Categories.Count > 0 &&
            _prototypeManager.TryIndex(prototype.Categories[0], out LatheCategoryPrototype? category))
        {
            return Loc.GetString("lathe-menu-recipe-meta-category", ("category", Loc.GetString(category.Name)), ("materials", materialKinds), ("seconds", seconds));
        }

        return Loc.GetString("lathe-menu-recipe-meta", ("materials", materialKinds), ("seconds", seconds));
    }

    private string BuildDesignSubtitleText()
    {
        if (CurrentCategory != null &&
            _prototypeManager.TryIndex(CurrentCategory.Value, out LatheCategoryPrototype? category))
        {
            return Loc.GetString("lathe-menu-designs-subtitle-filtered", ("category", Loc.GetString(category.Name)));
        }

        return Loc.GetString("lathe-menu-designs-subtitle", ("categories", Categories?.Count ?? 0));
    }

    private int GetCurrentRequestedAmount()
    {
        if (!int.TryParse(AmountLineEdit.Text, out var amount) || amount <= 0)
            return 1;

        return amount;
    }

    private string GetRecipeDisplayName(ProtoId<LatheRecipePrototype> recipe)
    {
        return _prototypeManager.TryIndex(recipe, out LatheRecipePrototype? prototype)
            ? _lathe.GetRecipeName(prototype)
            : recipe;
    }

    private static StyleBoxFlat CreateDividerStyle(Color color)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = color,
        };
    }
}
