using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class HighlightedContainer : PanelContainer
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public HighlightedContainer()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _cfg.OnValueChanged(CCVars.LobbyCustomizationPanelOpacity, OnCustomizationPanelOpacityChanged, true);
    }

    private void OnCustomizationPanelOpacityChanged(float opacity)
    {
        LobbyPanelOpacityHelper.ApplyPanelOpacity(this, opacity);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _cfg.UnsubValueChanged(CCVars.LobbyCustomizationPanelOpacity, OnCustomizationPanelOpacityChanged);
        }

        base.Dispose(disposing);
    }
}
