using Content.Shared.CCVar;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class HighlightedContainer : PanelContainer
{
    [Dependency] private  IConfigurationManager _cfg = default!;
    private float _lobbyOpacity = 1f;
    private float _uiWindowOpacity = 1f;
    private bool _useUiWindowOpacity;

    public bool UseUiWindowOpacity
    {
        get => _useUiWindowOpacity;
        set
        {
            _useUiWindowOpacity = value;
            ApplyConfiguredOpacity();
        }
    }

    public HighlightedContainer()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _cfg.OnValueChanged(CCVars.LobbyCustomizationPanelOpacity, OnCustomizationPanelOpacityChanged, true);
        _cfg.OnValueChanged(CCVars.UiWindowOpacity, OnUiWindowOpacityChanged, true);
    }

    private void OnCustomizationPanelOpacityChanged(float opacity)
    {
        _lobbyOpacity = opacity;
        if (!UseUiWindowOpacity)
            LobbyPanelOpacityHelper.ApplyPanelOpacity(this, opacity);
    }

    private void OnUiWindowOpacityChanged(float opacity)
    {
        _uiWindowOpacity = opacity;
        if (UseUiWindowOpacity)
            WindowOpacityHelper.ApplyPanelOpacity(this, opacity);
    }

    private void ApplyConfiguredOpacity()
    {
        if (UseUiWindowOpacity)
            WindowOpacityHelper.ApplyPanelOpacity(this, _uiWindowOpacity);
        else
            LobbyPanelOpacityHelper.ApplyPanelOpacity(this, _lobbyOpacity);
    }

    [Obsolete]
    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _cfg.UnsubValueChanged(CCVars.LobbyCustomizationPanelOpacity, OnCustomizationPanelOpacityChanged);
            _cfg.UnsubValueChanged(CCVars.UiWindowOpacity, OnUiWindowOpacityChanged);
        }

#pragma warning disable CS0618
        base.Dispose(disposing);
#pragma warning restore CS0618
    }
}
