using Content.Client.UserInterface.Controls;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Cargo.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CargoShuttleMenu : FancyWindow
    {
        public CargoShuttleMenu()
        {
            RobustXamlLoader.Load(this);
            Title = Loc.GetString("cargo-shuttle-console-menu-title");
        }

        public void SetAccountName(string name)
        {
            AccountNameLabel.Text = name;
        }

        public void SetShuttleName(string name)
        {
            ShuttleNameLabel.Text = name;
        }

        public void SetOrders(SpriteSystem sprites, IPrototypeManager protoManager, List<CargoOrderData> orders)
        {
            Orders.RemoveAllChildren();

            foreach (var order in orders)
            {
                 EntityPrototype? product = null;
                 string? productName = null;

                 if (!string.IsNullOrWhiteSpace(order.Product) &&
                     protoManager.Resolve(order.Product, out var productProto))
                 {
                     product = protoManager.Index<EntityPrototype>(productProto.Product);
                     productName = product.Name;
                 }
                 else if (!string.IsNullOrWhiteSpace(order.ProductId) &&
                          protoManager.TryIndex(order.ProductId, out var productProtoFallback))
                 {
                     product = productProtoFallback;
                     productName = order.ProductName;
                     if (string.IsNullOrWhiteSpace(productName))
                         productName = product.Name;
                 }

                 if (string.IsNullOrWhiteSpace(productName))
                     productName = !string.IsNullOrWhiteSpace(order.ProductName)
                         ? order.ProductName
                         : Loc.GetString("cargo-console-invalid-product");

                 var account = protoManager.Index(order.Account);

                 var row = new CargoOrderRow
                 {
                     Order = order,
                     ProductName =
                     {
                         Text = Loc.GetString(
                             "cargo-console-menu-populate-orders-cargo-order-row-product-name-text",
                             ("productName", productName),
                             ("orderAmount", order.OrderQuantity - order.NumDispatched),
                             ("orderRequester", order.Requester),
                             ("accountColor", account.Color),
                             ("account", Loc.GetString(account.Code)))
                     },
                     Description = {Text = Loc.GetString("cargo-console-menu-order-reason-description",
                         ("reason", order.Reason))}
                 };

                 if (product != null)
                     row.Icon.Texture = sprites.Frame0(product);

                 row.Approve.Visible = false;
                 row.Cancel.Visible = false;

                 Orders.AddChild(row);
            }
        }
    }
}
