using Content.Shared.Cargo.Prototypes;
using Content.Client._WH40K.Interface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Cargo.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CargoProductRow : BoxContainer
    {
        public CargoProductPrototype? Product { get; set; }

        public CargoProductRow()
        {
            RobustXamlLoader.Load(this);
        }

        public void ApplyWh40KTheme(WH40KCargoConsoleTheme theme)
        {
            var normalStyle = WH40KCargoConsoleStyles.CreatePanelStyle(theme.SurfaceBackground, theme.BorderColor, 0);
            var hoverStyle = WH40KCargoConsoleStyles.CreatePanelStyle(theme.SurfaceHoverBackground, theme.Accent.WithAlpha(0.84f), 0);

            CardPanel.PanelOverride = normalStyle;
            IconPanel.PanelOverride = WH40KCargoConsoleStyles.CreateBadgeStyle(theme.PreviewBackground, theme.BorderColor, 4, 4);
            PointCostPanel.PanelOverride = WH40KCargoConsoleStyles.CreateBadgeStyle(theme.PanelAltBackground, theme.Accent.WithAlpha(0.78f), 10, 6);
            MainButton.StyleBoxOverride = WH40KCargoConsoleStyles.CreateTransparentButtonStyle();
            ProductName.FontColorOverride = theme.PrimaryText;
            PointCost.FontColorOverride = theme.Accent;
            ProductName.Text = WH40KUiChrome.DecorateIfMissing(ProductName.Text, WH40KUiChrome.DiamondOutline);
            PointCost.Text = WH40KUiChrome.DecorateIfMissing(PointCost.Text, WH40KUiChrome.Arrow);

            MainButton.OnMouseEntered += _ =>
            {
                CardPanel.PanelOverride = hoverStyle;
                WH40KUiChrome.PlayHoverFlash(CardPanel, "hover-flash");
            };
            MainButton.OnMouseExited += _ => CardPanel.PanelOverride = normalStyle;
        }

        public void AnimateAppear(float delay)
        {
            WH40KUiChrome.PlayFadeIn(this, "appear", 0.2f, delay);
        }
    }
}
