using System;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Client._WH40K.Interface;
using Content.Shared.APC;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;

namespace Content.Client.Power.APC.UI;

[GenerateTypedNameReferences]
public sealed partial class ApcMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private static readonly Color Accent = Color.FromHex("#C9A94C".AsSpan());
    private static readonly Color WarningAccent = Color.FromHex("#A57C35".AsSpan());
    private static readonly Color BorderColor = Color.FromHex("#2A2418".AsSpan());
    private static readonly Color BorderStrongColor = Color.FromHex("#3D3422".AsSpan());
    private static readonly Color WindowBackground = Color.FromHex("#0B0C10".AsSpan());
    private static readonly Color PanelBackground = Color.FromHex("#0C0D10".AsSpan());
    private static readonly Color PanelAltBackground = Color.FromHex("#0E0F14".AsSpan());
    private static readonly Color SurfaceBackground = Color.FromHex("#0C0D12".AsSpan());
    private static readonly Color HeaderBackground = Color.FromHex("#0E0F14".AsSpan());
    private static readonly Color PrimaryText = Color.FromHex("#D4C8A0".AsSpan());
    private static readonly Color SecondaryText = Color.FromHex("#A09880".AsSpan());
    private static readonly Color LabelText = Color.FromHex("#8A7D5E".AsSpan());
    private static readonly Color DangerAccent = Color.FromHex("#8B3030".AsSpan());
    private static readonly Color SuccessAccent = Color.FromHex("#3A6A28".AsSpan());
    private static readonly Color SuccessBorder = Color.FromHex("#5B8F3E".AsSpan());

    private bool _mainBreaker;
    private bool _hasAccess = true;
    private bool _tripped;
    private int _power;
    private float _charge;
    private float _maxLoad;
    private ApcExternalPowerState _externalPower;

    public event Action? OnBreaker;

    public ApcMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        ApplyTheme();
        WireInteractions();
        ApplyDynamicState();

        BreakerButton.OnPressed += _ => OnBreaker?.Invoke();
    }

    protected override void Opened()
    {
        base.Opened();

        WindowHeader.Modulate = new Color(1f, 1f, 1f, 0f);
        WindowTitle.Modulate = new Color(1f, 1f, 1f, 0f);
        CloseButton.Modulate = new Color(1f, 1f, 1f, 0f);
        HeaderPanel.Modulate = new Color(1f, 1f, 1f, 0f);
        DevicePanel.Modulate = new Color(1f, 1f, 1f, 0f);
        StatusPanel.Modulate = new Color(1f, 1f, 1f, 0f);
        ChargePanel.Modulate = new Color(1f, 1f, 1f, 0f);
        ActionPanel.Modulate = new Color(1f, 1f, 1f, 0f);
        FooterDivider.Modulate = new Color(1f, 1f, 1f, 0f);
        FooterBar.Modulate = new Color(1f, 1f, 1f, 0f);

        WH40KUiChrome.PlayFadeIn(WindowHeader, "apc-window-header-appear", 0.12f);
        WH40KUiChrome.PlayFadeIn(WindowTitle, "apc-window-title-appear", 0.12f, 0.02f);
        WH40KUiChrome.PlayFadeIn(CloseButton, "apc-window-close-appear", 0.12f, 0.03f);
        WH40KUiChrome.PlayFadeIn(HeaderPanel, "apc-header-appear", 0.16f, 0.04f);
        WH40KUiChrome.PlayFadeIn(DevicePanel, "apc-device-appear", 0.18f, 0.08f);
        WH40KUiChrome.PlayFadeIn(StatusPanel, "apc-status-appear", 0.18f, 0.12f);
        WH40KUiChrome.PlayFadeIn(ChargePanel, "apc-charge-appear", 0.18f, 0.16f);
        WH40KUiChrome.PlayFadeIn(ActionPanel, "apc-action-appear", 0.18f, 0.2f);
        WH40KUiChrome.PlayFadeIn(FooterDivider, "apc-footer-appear", 0.18f, 0.24f);
        WH40KUiChrome.PlayFadeIn(FooterBar, "apc-footer-bar-appear", 0.18f, 0.26f);
    }

    public void SetEntity(EntityUid entity)
    {
        EntityView.SetEntity(entity);
        this.SetInfoFromEntity(_entityManager, entity);

        var resolvedName = string.IsNullOrWhiteSpace(Title)
            ? Loc.GetString("apc-menu-title")
            : Title;

        HeaderTitleLabel.Text = WH40KUiChrome.DecorateTitle(WH40KUiChrome.Cog, resolvedName.ToUpperInvariant());
    }

    public void UpdateState(ApcBoundInterfaceState state)
    {
        _mainBreaker = state.MainBreaker;
        _power = state.Power;
        _externalPower = state.ApcExternalPower;
        _charge = Math.Clamp(state.Charge, 0f, 1f);
        _maxLoad = state.MaxLoad;
        _tripped = state.Tripped;

        ApplyDynamicState();
    }

    public void SetAccessEnabled(bool hasAccess)
    {
        _hasAccess = hasAccess;
        ApplyDynamicState();
    }

    private void ApplyTheme()
    {
        SetSize = new Vector2(700f, 430f);
        MinSize = new Vector2(680f, 414f);

        if (GetChild(0) is PanelContainer windowBackdrop)
            windowBackdrop.PanelOverride = CreatePanelStyle(WindowBackground, BorderStrongColor, 0, 2);

        WindowHeader.PanelOverride = CreateEdgePanelStyle(
            HeaderBackground,
            BorderStrongColor,
            new Thickness(0f, 0f, 0f, 1f),
            0);

        WindowTitle.FontColorOverride = Accent;
        CloseButton.ModulateSelfOverride = LabelText;

        RootFrame.PanelOverride = CreatePanelStyle(WindowBackground, BorderStrongColor, 0);
        HeaderPanel.PanelOverride = CreatePanelStyle(PanelBackground, BorderStrongColor, 0);
        DevicePanel.PanelOverride = CreatePanelStyle(PanelBackground, BorderStrongColor, 0);
        DeviceViewportPanel.PanelOverride = CreatePanelStyle(PanelAltBackground, BorderColor, 0);
        StatusPanel.PanelOverride = CreatePanelStyle(PanelBackground, BorderStrongColor, 0);
        ChargePanel.PanelOverride = CreatePanelStyle(PanelBackground, BorderStrongColor, 0);
        ActionPanel.PanelOverride = CreatePanelStyle(PanelBackground, BorderStrongColor, 0);

        FooterDivider.MinSize = new Vector2(0f, 1f);
        FooterDivider.PanelOverride = CreateDividerStyle(BorderStrongColor);

        HeaderTitleLabel.FontColorOverride = Accent;
        HeaderSubtitleLabel.SetMessage(Loc.GetString("apc-menu-header-subtitle"), defaultColor: SecondaryText);

        DeviceSigilLabel.Text = WH40KUiChrome.Cog;
        DeviceSigilLabel.FontColorOverride = Accent;
        DeviceCaptionLabel.SetMessage(Loc.GetString("apc-menu-device-caption"), defaultColor: SecondaryText);

        StatusTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(Loc.GetString("apc-menu-status-title"), WH40KUiChrome.DiamondNested);
        ChargePanelTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(Loc.GetString("apc-menu-charge-title"), WH40KUiChrome.Diamond);
        ActionTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(Loc.GetString("apc-menu-action-title"), WH40KUiChrome.Blade);

        StatusTitleLabel.FontColorOverride = Accent;
        ChargePanelTitleLabel.FontColorOverride = Accent;
        ActionTitleLabel.FontColorOverride = Accent;

        BreakerKeyLabel.FontColorOverride = LabelText;
        ExternalKeyLabel.FontColorOverride = LabelText;
        LoadKeyLabel.FontColorOverride = LabelText;
        ChargePercentageLabel.FontColorOverride = SecondaryText;
        FooterLeftLabel.FontColorOverride = SecondaryText;
        FooterRightLabel.FontColorOverride = LabelText;
        FooterRightLabel.Text = Loc.GetString("apc-menu-footer-right");

        ChargeBar.BackgroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = SurfaceBackground,
            BorderColor = BorderStrongColor,
            BorderThickness = new Thickness(1),
        };
        ChargeBar.ForegroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = SuccessAccent,
            BorderColor = BorderColor,
            BorderThickness = new Thickness(1),
        };

        WH40KUiChrome.StartLoopingPulse(HeaderTitleLabel, "apc-title-pulse", Accent.WithAlpha(0.82f), Color.White, 3.2f);
        WH40KUiChrome.StartLoopingPulse(FooterDivider, "apc-divider-pulse", Accent.WithAlpha(0.34f), Color.White, 4.1f);
    }

    private void WireInteractions()
    {
        BreakerButton.OnMouseEntered += _ => WH40KUiChrome.PlayHoverFlash(ActionPanel, "apc-breaker-hover", ResolveBreakerHoverColor(), 0.18f);
        CloseButton.OnMouseEntered += _ => WH40KUiChrome.PlayHoverFlash(WindowHeader, "apc-close-hover", BorderStrongColor.WithAlpha(0.86f), 0.18f);
    }

    private void ApplyDynamicState()
    {
        BreakerValueLabel.Text = Loc.GetString(_mainBreaker
            ? "apc-menu-breaker-state-online"
            : "apc-menu-breaker-state-offline");
        BreakerValueLabel.FontColorOverride = _mainBreaker ? SuccessBorder : DangerAccent;

        ExternalPowerStateLabel.Text = Loc.GetString(ResolveExternalStateLocKey());
        ExternalPowerStateLabel.FontColorOverride = ResolveExternalColor();

        LoadValueLabel.Text = Loc.GetString(_tripped
            ? "apc-menu-power-state-label-tripped"
            : "apc-menu-power-state-label-text",
            ("power", _power),
            ("maxLoad", _maxLoad));
        LoadValueLabel.FontColorOverride = _tripped ? WarningAccent : PrimaryText;

        StatusHintLabel.SetMessage(Loc.GetString(ResolveStatusHintLocKey()), defaultColor: _tripped ? WarningAccent : SecondaryText);

        ChargeBar.Value = _charge;
        ChargePercentageLabel.Text = Loc.GetString("apc-menu-charge-label", ("percent", _charge.ToString("P0")));
        ChargePercentageLabel.FontColorOverride = ResolveChargeColor();
        ChargeHintLabel.SetMessage(Loc.GetString(ResolveChargeHintLocKey()), defaultColor: SecondaryText);

        ActionHintLabel.SetMessage(Loc.GetString(_hasAccess
            ? "apc-menu-action-note-authorized"
            : "apc-menu-action-note-locked"), defaultColor: SecondaryText);

        FooterLeftLabel.Text = Loc.GetString(ResolveFooterLocKey());
        FooterLeftLabel.FontColorOverride = ResolveFooterColor();
        FooterRightLabel.Text = Loc.GetString("apc-menu-footer-right");

        UpdateChargeBarStyle();
        UpdatePanelStyles();
        UpdateBreakerButton();
    }

    private void UpdateBreakerButton()
    {
        BreakerButton.Disabled = !_hasAccess;
        BreakerButton.ToolTip = _hasAccess
            ? null
            : Loc.GetString("apc-component-insufficient-access");

        if (!_hasAccess)
        {
            BreakerButton.Text = Loc.GetString("apc-menu-breaker-button-locked");
            ApplyButtonTheme(BreakerButton, CreateSecondaryButtonStyle(), PrimaryText, true);
            return;
        }

        if (_mainBreaker)
        {
            BreakerButton.Text = Loc.GetString("apc-menu-breaker-button-disable");
            ApplyButtonTheme(BreakerButton, CreateDangerButtonStyle(0.14f), PrimaryText, false);
            return;
        }

        BreakerButton.Text = Loc.GetString("apc-menu-breaker-button-enable");
        ApplyButtonTheme(BreakerButton, CreateSuccessButtonStyle(0.18f), PrimaryText, false);
    }

    private void UpdateChargeBarStyle()
    {
        if (ChargeBar.ForegroundStyleBoxOverride is not StyleBoxFlat foreground)
            return;

        foreground.BackgroundColor = ResolveChargeColor();
        foreground.BorderColor = BorderColor;
        foreground.BorderThickness = new Thickness(1);
    }

    private void UpdatePanelStyles()
    {
        var statusBorder = _tripped
            ? WarningAccent
            : ResolveExternalColor().WithAlpha(0.86f);

        StatusPanel.PanelOverride = CreatePanelStyle(
            _tripped ? Blend(PanelBackground, WarningAccent, 0.1f) : PanelBackground,
            statusBorder,
            0);

        ChargePanel.PanelOverride = CreatePanelStyle(
            PanelBackground,
            ResolveChargeColor().WithAlpha(0.86f),
            0);

        ActionPanel.PanelOverride = CreatePanelStyle(
            PanelBackground,
            !_hasAccess ? BorderColor : (_mainBreaker ? DangerAccent.WithAlpha(0.7f) : SuccessBorder.WithAlpha(0.7f)),
            0);
    }

    private string ResolveExternalStateLocKey()
    {
        return _externalPower switch
        {
            ApcExternalPowerState.Good => "apc-menu-power-state-good",
            ApcExternalPowerState.Low => "apc-menu-power-state-low",
            _ => "apc-menu-power-state-none",
        };
    }

    private string ResolveStatusHintLocKey()
    {
        if (_tripped)
            return "apc-menu-load-note-tripped";

        if (!_mainBreaker)
            return "apc-menu-breaker-note-offline";

        return _externalPower switch
        {
            ApcExternalPowerState.Good => "apc-menu-external-note-good",
            ApcExternalPowerState.Low => "apc-menu-external-note-low",
            _ => "apc-menu-external-note-none",
        };
    }

    private string ResolveChargeHintLocKey()
    {
        if (_charge >= 0.95f)
            return "apc-menu-charge-note-full";

        if (_charge >= 0.65f)
            return "apc-menu-charge-note-high";

        if (_charge >= 0.3f)
            return "apc-menu-charge-note-medium";

        return "apc-menu-charge-note-low";
    }

    private string ResolveFooterLocKey()
    {
        if (_tripped)
            return "apc-menu-footer-tripped";

        if (!_mainBreaker)
            return "apc-menu-footer-breaker-off";

        return _externalPower switch
        {
            ApcExternalPowerState.Good => "apc-menu-footer-ready",
            ApcExternalPowerState.Low => "apc-menu-footer-low",
            _ => "apc-menu-footer-none",
        };
    }

    private Color ResolveExternalColor()
    {
        return _externalPower switch
        {
            ApcExternalPowerState.Good => SuccessBorder,
            ApcExternalPowerState.Low => WarningAccent,
            _ => DangerAccent,
        };
    }

    private Color ResolveChargeColor()
    {
        if (_charge >= 0.95f)
            return SuccessBorder;

        if (_charge >= 0.65f)
            return Accent;

        if (_charge >= 0.3f)
            return WarningAccent;

        return DangerAccent;
    }

    private Color ResolveFooterColor()
    {
        if (_tripped)
            return WarningAccent;

        if (!_mainBreaker)
            return DangerAccent;

        return ResolveExternalColor();
    }

    private Color ResolveBreakerHoverColor()
    {
        if (!_hasAccess)
            return BorderStrongColor.WithAlpha(0.8f);

        return _mainBreaker
            ? DangerAccent.WithAlpha(0.72f)
            : SuccessAccent.WithAlpha(0.8f);
    }

    private static StyleBoxFlat CreatePanelStyle(Color background, Color border, int padding = 8, int borderThickness = 1)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(borderThickness),
            ContentMarginLeftOverride = padding,
            ContentMarginTopOverride = padding,
            ContentMarginRightOverride = padding,
            ContentMarginBottomOverride = padding,
        };
    }

    private static StyleBoxFlat CreateEdgePanelStyle(Color background, Color border, Thickness borderThickness, int padding = 8)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = borderThickness,
            ContentMarginLeftOverride = padding,
            ContentMarginTopOverride = padding,
            ContentMarginRightOverride = padding,
            ContentMarginBottomOverride = padding,
        };
    }

    private static StyleBoxFlat CreateDividerStyle(Color color)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = color,
        };
    }

    private static StyleBoxFlat CreateButtonStyle(Color border, Color tint, float tintAmount)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Blend(SurfaceBackground, tint, tintAmount),
            BorderColor = border,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 10,
            ContentMarginTopOverride = 4,
            ContentMarginRightOverride = 10,
            ContentMarginBottomOverride = 4,
        };
    }

    private static StyleBoxFlat CreateSecondaryButtonStyle()
    {
        return CreateButtonStyle(BorderStrongColor, BorderStrongColor, 0.16f);
    }

    private static StyleBoxFlat CreateSuccessButtonStyle(float tintAmount)
    {
        return CreateButtonStyle(SuccessBorder.WithAlpha(0.86f), SuccessAccent, tintAmount);
    }

    private static StyleBoxFlat CreateDangerButtonStyle(float tintAmount)
    {
        return CreateButtonStyle(DangerAccent.WithAlpha(0.84f), DangerAccent, tintAmount);
    }

    private static void ApplyButtonTheme(Button button, StyleBoxFlat style, Color fontColor, bool disabled)
    {
        button.StyleBoxOverride = style;
        button.Label.FontColorOverride = disabled ? LabelText : fontColor;
        button.ModulateSelfOverride = disabled
            ? new Color(0.84f, 0.84f, 0.88f, 0.84f)
            : Color.White;
    }

    private static Color Blend(Color baseColor, Color accent, float amount)
    {
        amount = Math.Clamp(amount, 0f, 1f);
        return new Color(
            baseColor.R + (accent.R - baseColor.R) * amount,
            baseColor.G + (accent.G - baseColor.G) * amount,
            baseColor.B + (accent.B - baseColor.B) * amount,
            MathF.Max(baseColor.A, accent.A));
    }
}
