using System;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Client._WH40K.Interface;
using Content.Shared.Disposal.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client.Disposal.Unit
{
    /// <summary>
    /// Client-side UI used to control a <see cref="Shared.Disposal.Components.DisposalUnitComponent"/>
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class DisposalUnitWindow : FancyWindow
    {
        private static readonly Color Accent = Color.FromHex("#C9A94C".AsSpan());
        private static readonly Color BorderColor = Color.FromHex("#2A2418".AsSpan());
        private static readonly Color BorderStrongColor = Color.FromHex("#3D3422".AsSpan());
        private static readonly Color WindowBackground = Color.FromHex("#0B0C10".AsSpan());
        private static readonly Color PanelBackground = Color.FromHex("#0C0D10".AsSpan());
        private static readonly Color PanelAltBackground = Color.FromHex("#0E0F14".AsSpan());
        private static readonly Color SurfaceBackground = Color.FromHex("#0C0D12".AsSpan());
        private static readonly Color HeaderBackground = Color.FromHex("#0E0F14".AsSpan());
        private static readonly Color PrimaryText = Color.FromHex("#D4C8A0".AsSpan());
        private static readonly Color SecondaryText = Color.FromHex("#A09880".AsSpan());
        private static readonly Color LabelText = Color.FromHex("#8A7D5E".AsSpan());
        private static readonly Color DangerAccent = Color.FromHex("#8B3030".AsSpan());
        private static readonly Color SuccessAccent = Color.FromHex("#3A6A28".AsSpan());
        private static readonly Color SuccessBorder = Color.FromHex("#5B8F3E".AsSpan());
        private static readonly Color WarningAccent = Color.FromHex("#D3A456".AsSpan());

        private DisposalsPressureState _pressureState = DisposalsPressureState.Ready;
        private bool _powered = true;
        private bool _engaged;

        public TimeSpan FullPressure;

        public DisposalUnitWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
            ApplyTheme();
            WireInteractions();
        }

        public void RefreshState(string machineName, DisposalsPressureState state, bool powered, bool engaged, TimeSpan fullPressure)
        {
            var resolvedName = string.IsNullOrWhiteSpace(machineName)
                ? Loc.GetString("ui-disposal-unit-title")
                : machineName;

            Title = resolvedName;
            HeaderTitleLabel.Text = WH40KUiChrome.DecorateTitle(WH40KUiChrome.Cog, resolvedName.ToUpperInvariant());

            _pressureState = state;
            _powered = powered;
            _engaged = engaged;
            FullPressure = fullPressure;

            ApplyDynamicState();
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            PressureBar.UpdatePressure(FullPressure);
            UpdatePressureReadout();
        }

        protected override void Opened()
        {
            base.Opened();

            WindowHeader.Modulate = new Color(1f, 1f, 1f, 0f);
            WindowTitle.Modulate = new Color(1f, 1f, 1f, 0f);
            CloseButton.Modulate = new Color(1f, 1f, 1f, 0f);
            HeaderPanel.Modulate = new Color(1f, 1f, 1f, 0f);
            StatePanel.Modulate = new Color(1f, 1f, 1f, 0f);
            DiagnosticsPanel.Modulate = new Color(1f, 1f, 1f, 0f);
            PressurePanel.Modulate = new Color(1f, 1f, 1f, 0f);
            ActionPanel.Modulate = new Color(1f, 1f, 1f, 0f);
            FooterDivider.Modulate = new Color(1f, 1f, 1f, 0f);
            FooterBar.Modulate = new Color(1f, 1f, 1f, 0f);

            WH40KUiChrome.PlayFadeIn(WindowHeader, "window-header-appear", 0.12f);
            WH40KUiChrome.PlayFadeIn(WindowTitle, "window-title-appear", 0.12f, 0.02f);
            WH40KUiChrome.PlayFadeIn(CloseButton, "window-close-appear", 0.12f, 0.03f);
            WH40KUiChrome.PlayFadeIn(HeaderPanel, "header-appear", 0.16f, 0.03f);
            WH40KUiChrome.PlayFadeIn(StatePanel, "state-panel-appear", 0.18f, 0.06f);
            WH40KUiChrome.PlayFadeIn(DiagnosticsPanel, "diagnostics-panel-appear", 0.18f, 0.09f);
            WH40KUiChrome.PlayFadeIn(PressurePanel, "pressure-panel-appear", 0.18f, 0.12f);
            WH40KUiChrome.PlayFadeIn(ActionPanel, "action-panel-appear", 0.18f, 0.15f);
            WH40KUiChrome.PlayFadeIn(FooterDivider, "footer-divider-appear", 0.18f, 0.18f);
            WH40KUiChrome.PlayFadeIn(FooterBar, "footer-panel-appear", 0.18f, 0.2f);
        }

        private void ApplyTheme()
        {
            SetSize = new Vector2(560f, 426f);
            MinSize = new Vector2(520f, 408f);

            if (GetChild(0) is PanelContainer windowBackdrop)
                windowBackdrop.PanelOverride = CreatePanelStyle(WindowBackground, BorderStrongColor, 0, 2);

            WindowHeader.PanelOverride = CreateEdgePanelStyle(HeaderBackground, BorderStrongColor, new Thickness(0f, 0f, 0f, 1f), 0);
            WindowTitle.ClipText = true;
            WindowTitle.FontColorOverride = Accent;
            CloseButton.ModulateSelfOverride = LabelText;

            RootFrame.PanelOverride = CreatePanelStyle(WindowBackground, BorderStrongColor, 0);
            HeaderPanel.PanelOverride = CreatePanelStyle(PanelBackground, BorderStrongColor, 0);
            StatePanel.PanelOverride = CreatePanelStyle(PanelAltBackground, BorderColor, 0);
            DiagnosticsPanel.PanelOverride = CreatePanelStyle(PanelAltBackground, BorderColor, 0);
            PressurePanel.PanelOverride = CreatePanelStyle(PanelBackground, BorderStrongColor, 0);
            ActionPanel.PanelOverride = CreatePanelStyle(PanelBackground, BorderStrongColor, 0);

            FooterDivider.MinSize = new Vector2(0f, 1f);
            FooterDivider.PanelOverride = CreateDividerStyle(BorderStrongColor);

            HeaderTitleLabel.FontColorOverride = Accent;
            HeaderSubtitleLabel.SetMessage(Loc.GetString("ui-disposal-unit-header-subtitle"), defaultColor: SecondaryText);

            StatePanelTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(Loc.GetString("ui-disposal-unit-card-state"), WH40KUiChrome.DiamondNested);
            DiagnosticsTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(Loc.GetString("ui-disposal-unit-card-diagnostics"), WH40KUiChrome.Cog);
            PressurePanelTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(Loc.GetString("ui-disposal-unit-pressure-panel-title"), WH40KUiChrome.Diamond);

            StatePanelTitleLabel.FontColorOverride = LabelText;
            DiagnosticsTitleLabel.FontColorOverride = LabelText;
            PowerKeyLabel.FontColorOverride = LabelText;
            SanctionKeyLabel.FontColorOverride = LabelText;
            PressurePanelTitleLabel.FontColorOverride = Accent;
            PressureFillLabel.FontColorOverride = SecondaryText;
            FooterLeftLabel.FontColorOverride = SecondaryText;
            FooterRightLabel.FontColorOverride = LabelText;

            WH40KUiChrome.StartLoopingPulse(HeaderTitleLabel, "title-pulse", Accent.WithAlpha(0.82f), Color.White, 3.2f);
            WH40KUiChrome.StartLoopingPulse(FooterDivider, "footer-pulse", Accent.WithAlpha(0.34f), Color.White, 4.1f);
        }

        private void WireInteractions()
        {
            WireButtonHover(Engage, "engage-hover", Accent.WithAlpha(0.72f));
            WireButtonHover(Eject, "eject-hover", BorderStrongColor.WithAlpha(0.88f));
            WireButtonHover(Power, "power-hover", ResolvePowerFlashColor());
            CloseButton.OnMouseEntered += _ => WH40KUiChrome.PlayHoverFlash(CloseButton, "close-hover", BorderStrongColor.WithAlpha(0.86f), 0.18f);
        }

        private void ApplyDynamicState()
        {
            StateValueLabel.Text = Loc.GetString($"disposal-unit-state-{_pressureState}");
            StateHintLabel.SetMessage(Loc.GetString(ResolveStateNoteLocKey()), defaultColor: SecondaryText);
            StateValueLabel.FontColorOverride = ResolveStateColor();

            SpiritValueLabel.Text = Loc.GetString(_powered
                ? "ui-disposal-unit-power-online"
                : "ui-disposal-unit-power-offline");
            SpiritValueLabel.FontColorOverride = _powered ? SuccessAccent : DangerAccent;

            SanctionValueLabel.Text = Loc.GetString(_engaged
                ? "ui-disposal-unit-sanction-engaged"
                : "ui-disposal-unit-sanction-idle");
            SanctionValueLabel.FontColorOverride = _engaged ? Accent : PrimaryText;

            UpdateButtons();
            UpdatePressureReadout();
        }

        private void UpdateButtons()
        {
            Engage.Text = Loc.GetString(_engaged
                ? "ui-disposal-unit-button-flush-active"
                : "ui-disposal-unit-button-flush-wh40k");
            Eject.Text = Loc.GetString("ui-disposal-unit-button-eject-wh40k");
            Power.Text = Loc.GetString(_powered
                ? "ui-disposal-unit-button-power-on"
                : "ui-disposal-unit-button-power-off");

            ApplyButtonTheme(Engage, _engaged
                ? CreatePrimaryButtonStyle(Accent, 0.28f)
                : CreatePrimaryButtonStyle(Accent, 0.22f), PrimaryText);
            ApplyButtonTheme(Eject, CreateSecondaryButtonStyle(), PrimaryText);
            ApplyButtonTheme(Power, _powered
                ? CreateSuccessButtonStyle()
                : CreateDangerButtonStyle(), PrimaryText);
        }

        private void UpdatePressureReadout()
        {
            var percent = (int)MathF.Round(PressureBar.CurrentPressure * 100f);
            PressureFillLabel.Text = Loc.GetString("ui-disposal-unit-pressure-percent", ("percent", percent));

            var pressureStatusKey = ResolvePressureStatusLocKey();
            var footerStatusKey = ResolveFooterStatusLocKey();

            PressureStatusLabel.SetMessage(Loc.GetString(pressureStatusKey), defaultColor: ResolvePressureStatusColor());
            FooterLeftLabel.Text = Loc.GetString(footerStatusKey);
            FooterLeftLabel.FontColorOverride = ResolveFooterColor();
            FooterRightLabel.Text = Loc.GetString("ui-disposal-unit-footer-right");
        }

        private string ResolveStateNoteLocKey()
        {
            return _pressureState switch
            {
                DisposalsPressureState.Flushed => "ui-disposal-unit-state-note-flushed",
                DisposalsPressureState.Pressurizing => "ui-disposal-unit-state-note-pressurizing",
                _ => "ui-disposal-unit-state-note-ready",
            };
        }

        private string ResolvePressureStatusLocKey()
        {
            if (!_powered)
                return "ui-disposal-unit-pressure-offline";

            if (_engaged)
                return "ui-disposal-unit-pressure-engaged";

            return PressureBar.CurrentPressure >= 0.999f
                ? "ui-disposal-unit-pressure-ready"
                : "ui-disposal-unit-pressure-charging";
        }

        private string ResolveFooterStatusLocKey()
        {
            if (!_powered)
                return "ui-disposal-unit-footer-offline";

            if (_engaged)
                return "ui-disposal-unit-footer-engaged";

            return _pressureState switch
            {
                DisposalsPressureState.Flushed => "ui-disposal-unit-footer-flushed",
                DisposalsPressureState.Pressurizing => "ui-disposal-unit-footer-pressurizing",
                _ => "ui-disposal-unit-footer-ready",
            };
        }

        private Color ResolveStateColor()
        {
            return _pressureState switch
            {
                DisposalsPressureState.Flushed => WarningAccent,
                DisposalsPressureState.Pressurizing => PrimaryText,
                _ => Accent,
            };
        }

        private Color ResolvePressureStatusColor()
        {
            if (!_powered)
                return DangerAccent;

            if (_engaged)
                return Accent;

            return PressureBar.CurrentPressure >= 0.999f
                ? Accent
                : SecondaryText;
        }

        private Color ResolveFooterColor()
        {
            if (!_powered)
                return DangerAccent;

            if (_engaged)
                return Accent;

            return SecondaryText;
        }

        private Color ResolvePowerFlashColor()
        {
            return (_powered ? SuccessBorder : DangerAccent).WithAlpha(0.82f);
        }

        private static void WireButtonHover(Button button, string key, Color flashColor)
        {
            button.OnMouseEntered += _ => WH40KUiChrome.PlayHoverFlash(button, key, flashColor, 0.18f);
        }

        private static StyleBoxFlat CreatePanelStyle(Color background, Color border, int padding = 8, int borderThickness = 1)
        {
            return new StyleBoxFlat
            {
                BackgroundColor = background,
                BorderColor = border,
                BorderThickness = new Thickness(borderThickness),
                ContentMarginLeftOverride = padding,
                ContentMarginTopOverride = padding,
                ContentMarginRightOverride = padding,
                ContentMarginBottomOverride = padding,
            };
        }

        private static StyleBoxFlat CreateEdgePanelStyle(Color background, Color border, Thickness borderThickness, int padding = 8)
        {
            return new StyleBoxFlat
            {
                BackgroundColor = background,
                BorderColor = border,
                BorderThickness = borderThickness,
                ContentMarginLeftOverride = padding,
                ContentMarginTopOverride = padding,
                ContentMarginRightOverride = padding,
                ContentMarginBottomOverride = padding,
            };
        }

        private static StyleBoxFlat CreateButtonStyle(Color border, Color tint, float tintAmount)
        {
            return new StyleBoxFlat
            {
                BackgroundColor = Blend(SurfaceBackground, tint, tintAmount),
                BorderColor = border,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 8,
                ContentMarginTopOverride = 4,
                ContentMarginRightOverride = 8,
                ContentMarginBottomOverride = 4,
            };
        }

        private static StyleBoxFlat CreatePrimaryButtonStyle(Color accent, float tintAmount)
        {
            return CreateButtonStyle(accent.WithAlpha(0.84f), accent, tintAmount);
        }

        private static StyleBoxFlat CreateSecondaryButtonStyle()
        {
            return CreateButtonStyle(BorderStrongColor, BorderStrongColor, 0.34f);
        }

        private static StyleBoxFlat CreateSuccessButtonStyle()
        {
            return CreateButtonStyle(SuccessBorder, SuccessAccent, 0.24f);
        }

        private static StyleBoxFlat CreateDangerButtonStyle()
        {
            return CreateButtonStyle(DangerAccent.WithAlpha(0.84f), DangerAccent, 0.18f);
        }

        private static StyleBoxFlat CreateDividerStyle(Color color)
        {
            return new StyleBoxFlat
            {
                BackgroundColor = color,
            };
        }

        private static void ApplyButtonTheme(Button button, StyleBoxFlat style, Color fontColor)
        {
            button.StyleBoxOverride = style;
            button.Label.FontColorOverride = fontColor;
        }

        private static Color Blend(Color baseColor, Color accent, float amount)
        {
            amount = Math.Clamp(amount, 0f, 1f);
            return new Color(
                baseColor.R + (accent.R - baseColor.R) * amount,
                baseColor.G + (accent.G - baseColor.G) * amount,
                baseColor.B + (accent.B - baseColor.B) * amount,
                MathF.Max(baseColor.A, accent.A));
        }
    }
}
