using System;
using System.Numerics;
using Content.Client.Cargo.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._WH40K.Vehicle.Fuel;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client._WH40K.Vehicle.Fuel.UI;

[GenerateTypedNameReferences]
public sealed partial class WH40KVehicleFuelTerminalWindow : FancyWindow
{
    private WH40KCargoConsoleTheme _theme = WH40KCargoConsoleTheme.Disabled;
    private WH40KVehicleFuelTerminalBuiState? _state;

    public event Action<bool>? OnAutoIntakePressed;
    public event Action<bool>? OnAutoRefuelPressed;

    public WH40KVehicleFuelTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        AutoIntakeButton.OnPressed += _ => OnAutoIntakePressed?.Invoke(!(_state?.AutoIntakeEnabled ?? false));
        AutoRefuelButton.OnPressed += _ => OnAutoRefuelPressed?.Invoke(!(_state?.AutoRefuelEnabled ?? false));
        ApplyTheme();
    }

    public void ApplyState(WH40KVehicleFuelTerminalBuiState state)
    {
        _state = state;
        var theme = WH40KCargoConsoleStyles.ResolveTheme(state.Account);

        if (!theme.Equals(_theme))
        {
            _theme = theme;
            ApplyTheme();
        }

        RefreshState();
    }

    private void ApplyTheme()
    {
        Title = Loc.GetString("wh40k-vehicle-fuel-ui-window-title");
        HeaderTitleLabel.Text = Title.ToUpperInvariant();
        HeaderSubtitleLabel.SetMessage(Loc.GetString("wh40k-vehicle-fuel-ui-subtitle"));
        FooterLabel.SetMessage(Loc.GetString("wh40k-vehicle-fuel-ui-footer"));

        if (GetChild(0) is PanelContainer root)
            root.PanelOverride = WH40KCargoConsoleStyles.CreatePanelStyle(_theme.WindowBackground, _theme.BorderStrongColor, 0, 2);

        HeaderPanel.PanelOverride = WH40KCargoConsoleStyles.CreateEdgePanelStyle(
            _theme.HeaderBackground,
            _theme.BorderStrongColor,
            new Thickness(0f, 0f, 0f, 1f),
            0);

        RootFrame.PanelOverride = WH40KCargoConsoleStyles.CreatePanelStyle(_theme.WindowBackground, _theme.BorderStrongColor, 0);
        BufferCard.PanelOverride = WH40KCargoConsoleStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderStrongColor, 0);
        SourceCard.PanelOverride = WH40KCargoConsoleStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderStrongColor, 0);
        VehicleCard.PanelOverride = WH40KCargoConsoleStyles.CreatePanelStyle(_theme.PanelAltBackground, _theme.BorderStrongColor, 0);
        ControlPanel.PanelOverride = WH40KCargoConsoleStyles.CreatePanelStyle(_theme.PanelBackground, _theme.BorderStrongColor, 0);
        DiagnosticsPanel.PanelOverride = WH40KCargoConsoleStyles.CreatePanelStyle(_theme.PanelBackground, _theme.BorderStrongColor, 0);
        FooterDivider.PanelOverride = new StyleBoxFlat { BackgroundColor = _theme.BorderStrongColor };
        FooterDivider.MinSize = new Vector2(0f, 1f);

        HeaderTitleLabel.FontColorOverride = _theme.Accent;
        BufferLabel.FontColorOverride = _theme.Accent;
        SourceLabel.FontColorOverride = _theme.Accent;
        VehicleLabel.FontColorOverride = _theme.Accent;
        DiagnosticsTitleLabel.FontColorOverride = _theme.Accent;

        HeaderSubtitleLabel.Modulate = _theme.SecondaryText;
        FooterLabel.Modulate = _theme.SecondaryText;
        BufferHintLabel.Modulate = _theme.SecondaryText;
        SourceHintLabel.Modulate = _theme.SecondaryText;
        VehicleHintLabel.Modulate = _theme.SecondaryText;

        PowerKeyLabel.FontColorOverride = _theme.LabelText;
        EngineKeyLabel.FontColorOverride = _theme.LabelText;
        ServiceKeyLabel.FontColorOverride = _theme.LabelText;
        RuntimeKeyLabel.FontColorOverride = _theme.LabelText;

        RefreshButtons();
    }

    private void RefreshState()
    {
        if (_state == null)
            return;

        var state = _state;

        var bufferPercent = GetPercent(state.BufferAmount, state.BufferCapacity);
        BufferValueLabel.Text = $"{MathF.Round(state.BufferAmount)} / {MathF.Round(state.BufferCapacity)}";
        BufferHintLabel.SetMessage(Loc.GetString("wh40k-vehicle-fuel-ui-buffer-hint", ("percent", bufferPercent)));

        if (string.IsNullOrWhiteSpace(state.SourceName))
        {
            SourceValueLabel.Text = Loc.GetString("wh40k-vehicle-fuel-ui-no-source");
            SourceHintLabel.SetMessage(Loc.GetString("wh40k-vehicle-fuel-ui-source-hint-none"));
        }
        else
        {
            SourceValueLabel.Text = state.SourceName;
            SourceHintLabel.SetMessage(Loc.GetString(
                "wh40k-vehicle-fuel-ui-source-hint",
                ("current", MathF.Round(state.SourceAmount)),
                ("capacity", MathF.Round(state.SourceCapacity))));
        }

        if (string.IsNullOrWhiteSpace(state.VehicleName))
        {
            VehicleValueLabel.Text = Loc.GetString("wh40k-vehicle-fuel-ui-no-vehicle");
            VehicleHintLabel.SetMessage(Loc.GetString("wh40k-vehicle-fuel-ui-vehicle-hint-none"));
        }
        else
        {
            var vehiclePercent = GetPercent(state.VehicleFuelAmount, state.VehicleFuelCapacity);
            VehicleValueLabel.Text = state.VehicleName;
            VehicleHintLabel.SetMessage(Loc.GetString(
                "wh40k-vehicle-fuel-ui-vehicle-hint",
                ("percent", vehiclePercent),
                ("current", MathF.Round(state.VehicleFuelAmount)),
                ("capacity", MathF.Round(state.VehicleFuelCapacity))));
        }

        PowerValueLabel.Text = Loc.GetString(state.Powered
            ? "wh40k-vehicle-toggle-on"
            : "wh40k-vehicle-toggle-off");
        PowerValueLabel.FontColorOverride = state.Powered ? _theme.Accent : _theme.DangerAccent;

        EngineValueLabel.Text = Loc.GetString(WH40KVehicleFuelLoc.GetEngineStateLocKey(state.VehicleEngineState));
        EngineValueLabel.FontColorOverride = state.VehicleEngineState == WH40KVehicleEngineState.Running
            ? _theme.Accent
            : state.VehicleEngineState == WH40KVehicleEngineState.Disabled
                ? _theme.DangerAccent
                : _theme.PrimaryText;

        ServiceValueLabel.Text = Loc.GetString(
            "wh40k-vehicle-fuel-ui-service-value",
            ("state", Loc.GetString(WH40KVehicleFuelLoc.GetServiceStateLocKey(state.VehicleServiceState))),
            ("integrity", MathF.Round(state.VehicleServiceRatio * 100f)));
        ServiceValueLabel.FontColorOverride = state.VehicleServiceState switch
        {
            WH40KVehicleServiceState.Critical => _theme.DangerAccent,
            WH40KVehicleServiceState.Disabled => _theme.DangerAccent,
            WH40KVehicleServiceState.Worn => _theme.Accent,
            _ => _theme.PrimaryText
        };

        RuntimeValueLabel.Text = FormatRuntime(state.VehicleFuelAmount);
        RuntimeValueLabel.FontColorOverride = _theme.PrimaryText;

        RefreshButtons();
    }

    private void RefreshButtons()
    {
        var intakeEnabled = _state?.AutoIntakeEnabled ?? false;
        var refuelEnabled = _state?.AutoRefuelEnabled ?? false;

        AutoIntakeButton.Text = Loc.GetString(intakeEnabled
            ? "wh40k-vehicle-fuel-ui-button-disable-intake"
            : "wh40k-vehicle-fuel-ui-button-enable-intake");
        WH40KCargoConsoleStyles.ApplyButtonTheme(
            AutoIntakeButton,
            intakeEnabled
                ? WH40KCargoConsoleStyles.CreateDangerButtonStyle(_theme)
                : WH40KCargoConsoleStyles.CreatePrimaryButtonStyle(_theme),
            _theme.PrimaryText);

        AutoRefuelButton.Text = Loc.GetString(refuelEnabled
            ? "wh40k-vehicle-fuel-ui-button-disable-refuel"
            : "wh40k-vehicle-fuel-ui-button-enable-refuel");
        WH40KCargoConsoleStyles.ApplyButtonTheme(
            AutoRefuelButton,
            refuelEnabled
                ? WH40KCargoConsoleStyles.CreateDangerButtonStyle(_theme)
                : WH40KCargoConsoleStyles.CreateSecondaryButtonStyle(_theme),
            _theme.PrimaryText);
    }

    private static int GetPercent(float current, float capacity)
    {
        if (capacity <= 0f)
            return 0;

        return (int) MathF.Round(Math.Clamp(current / capacity, 0f, 1f) * 100f);
    }

    private static string FormatRuntime(float seconds)
    {
        var clamped = Math.Max(0, (int) MathF.Round(seconds));
        var span = TimeSpan.FromSeconds(clamped);
        return span.TotalHours >= 1
            ? $"{span.Hours:D2}:{span.Minutes:D2}:{span.Seconds:D2}"
            : $"{span.Minutes:D2}:{span.Seconds:D2}";
    }
}
