using System.Linq;
using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Fragments;
using Content.Shared.Mech;
using Content.Shared.Mech.Components;
using Content.Shared.Mech.Equipment.Components;
using Content.Shared.Mech.Module.Components;
using Content.Shared.Mech.Systems;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Player;

namespace Content.Client.Mech.Ui;

/// <summary>
/// Interface control for mechs.
/// </summary>
/// <seealso cref="MechBoundUserInterface"/>
[GenerateTypedNameReferences]
public sealed partial class MechMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    // State.
    private EntityUid _mech;
    private bool _pilotPresent;
    private BoundUserInterface? _parentBui;

    // Events for the BUI to subscribe to.
    public event Action<EntityUid>? OnRemoveButtonPressed;
    public event Action<EntityUid>? OnRemoveModuleButtonPressed;

    public event Action<bool>? OnTankToggle;
    public event Action<MechTankMode>? OnTankModeChanged;
    public event Action<float>? OnTankPressureChanged;
    public event Action<bool>? OnFanToggle;
    public event Action<bool>? OnFilterToggle;
    public event Action<bool>? OnCompressorToggle;
    public event Action? OnDnaLockRegister;
    public event Action? OnDnaLockToggle;
    public event Action? OnDnaLockReset;
    public event Action? OnCardLockRegister;
    public event Action? OnCardLockToggle;
    public event Action? OnCardLockReset;

    public MechMenu()
    {
        RobustXamlLoader.Load(this);

        InitializeEventHandlers();
    }

    public void SetEntity(EntityUid entity)
    {
        _mech = entity;

        this.SetInfoFromEntity(_entityManager, _mech);

        MechView.SetEntity(entity);
        MechName.Text = _entityManager.GetComponent<MetaDataComponent>(_mech).EntityName;
    }

    public void SetParentBui(BoundUserInterface parentBui)
    {
        _parentBui = parentBui;
    }

    private void InitializeEventHandlers()
    {
        TankModeSelector.AddItem(Loc.GetString("mech-tank-mode-supply"), (int) MechTankMode.Supply);
        TankModeSelector.AddItem(Loc.GetString("mech-tank-mode-refill"), (int) MechTankMode.Refill);
        TankModeSelector.SelectId((int) MechTankMode.Supply);

        // Cabin life-support controls.
        TankToggle.StateChanged += isOn => OnTankToggle?.Invoke(isOn);
        TankModeSelector.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);
            OnTankModeChanged?.Invoke((MechTankMode) args.Id);
        };
        TankPressureSpin.OnValueChanged += args => OnTankPressureChanged?.Invoke(args.Value);

        // Fan controls.
        FanToggle.StateChanged += isOn => OnFanToggle?.Invoke(isOn);

        // Lock controls.
        DnaLockRegisterButton.OnPressed += _ => OnDnaLockRegister?.Invoke();
        DnaLockBlockButton.OnPressed += _ => OnDnaLockToggle?.Invoke();
        DnaLockResetButton.OnPressed += _ => OnDnaLockReset?.Invoke();

        CardLockRegisterButton.OnPressed += _ => OnCardLockRegister?.Invoke();
        CardLockBlockButton.OnPressed += _ => OnCardLockToggle?.Invoke();
        CardLockResetButton.OnPressed += _ => OnCardLockReset?.Invoke();

        // Filter control.
        FilterEnabledCheck.OnToggled += args => OnFilterToggle?.Invoke(args.Pressed);
        CompressorEnabledCheck.OnToggled += args => OnCompressorToggle?.Invoke(args.Pressed);
    }

    public void UpdateMechStats(MechBoundUiState state)
    {
        if (state.MaxIntegrity > 0f)
        {
            var integrityPercent = state.Integrity / state.MaxIntegrity;
            IntegrityDisplayBar.Value = integrityPercent;

            var integrityText = state.IsBroken
                ? Loc.GetString("mech-integrity-display-broken", ("amount", (int)(integrityPercent * 100)))
                : Loc.GetString("mech-integrity-display", ("amount", (int)(integrityPercent * 100)));

            IntegrityDisplay.Text = integrityText;
        }
        else
        {
            IntegrityDisplayBar.Value = 0f;
            IntegrityDisplay.Text = Loc.GetString("mech-integrity-display", ("amount", 0));
        }

        if (state.MaxEnergy > 0f)
        {
            var minVisibleEnergy = MathF.Max(0.01f, state.MaxEnergy * 0.01f);
            var energy = state.Energy < minVisibleEnergy ? 0f : state.Energy;
            var energyPercent = Math.Clamp(energy / state.MaxEnergy, 0f, 1f);
            EnergyDisplayBar.Value = energyPercent;
            EnergyDisplay.Text = Loc.GetString("mech-energy-display", ("amount", (int)(energyPercent * 100)));
        }
        else
        {
            EnergyDisplayBar.Value = 0f;
            EnergyDisplay.Text = Loc.GetString("mech-energy-missing");
        }

        UpdateEnergyDrainDisplay(state.EnergyDrainRate);

        SlotDisplay.Text = Loc.GetString("mech-equipment-slot-display-label",
            ("used", state.EquipmentUsed),
            ("max", state.MaxEquipmentAmount));

        ModuleSlotDisplay.Text = Loc.GetString("mech-module-slot-display-label",
            ("used", state.ModuleSpaceUsed),
            ("max", state.ModuleSpaceMax));
    }

    public void UpdateMechState(MechBoundUiState state)
    {
        _pilotPresent = state.PilotPresent;

        FanToggle.Visible = state.HasFanModule;
        FilterEnabledCheck.Visible = state.HasFanModule;
        CompressorEnabledCheck.Visible = state.HasFanModule;
        FanMissingLabel.Visible = !state.HasFanModule;

        var tankControlsVisible = state.CanAirtight && state.HasGasModule;
        TankToggle.Visible = tankControlsVisible;
        TankModeSelector.Visible = tankControlsVisible;
        TankPressureBox.Visible = tankControlsVisible
                                  && state.TankEnabled
                                  && state.TankMode == MechTankMode.Supply;
        AirtightUnavailableLabel.Visible = !tankControlsVisible;
        AirtightUnavailableLabel.Text = Loc.GetString(state.HasGasModule
            ? "mech-airtight-unavailable-label"
            : "mech-tank-missing-label");

        if (TankToggle.IsOn != state.TankEnabled)
            TankToggle.IsOn = state.TankEnabled;

        if (TankModeSelector.SelectedId != (int) state.TankMode)
            TankModeSelector.SelectId((int) state.TankMode);

        TankPressureSpin.IsValid = value => value >= 0f && value <= state.TankMaxTargetPressure;
        if (!TankPressureSpin.HasKeyboardFocus() && MathF.Abs(TankPressureSpin.Value - state.TankTargetPressure) > 0.01f)
            TankPressureSpin.Value = state.TankTargetPressure;

        if (state.HasFanModule)
        {
            if (FanToggle.IsOn != state.FanActive)
                FanToggle.IsOn = state.FanActive;

            if (FilterEnabledCheck.Pressed != state.FilterEnabled)
                FilterEnabledCheck.Pressed = state.FilterEnabled;

            if (CompressorEnabledCheck.Pressed != state.CompressorEnabled)
                CompressorEnabledCheck.Pressed = state.CompressorEnabled;

            CompressorEnabledCheck.Disabled = !state.HasGasModule
                                              || !state.TankEnabled
                                              || state.TankMode != MechTankMode.Refill;
        }

        // Display temperature in Celsius.
        var tempC = TemperatureHelpers.KelvinToCelsius(state.CabinTemperature);

        var hasCabinData = state.IsAirtight && state.CabinPressureLevel > 0.05f;
        if (hasCabinData)
        {
            CabinPressureLabel.Text = Loc.GetString("mech-cabin-pressure-level-label",
                ("level", FormatPressure(state.CabinPressureLevel)));
            CabinTemperatureLabel.Text = Loc.GetString("mech-cabin-temperature-level-label", ("tempC", $"{tempC:F1}"));
            CabinPressureLabel.FontColorOverride = Color.White;
            CabinTemperatureLabel.FontColorOverride = Color.Orange;
        }
        else
        {
            var statusKey = state.IsAirtight
                ? "mech-cabin-no-air-status"
                : "mech-cabin-not-airtight-status";

            CabinPressureLabel.Text = Loc.GetString(statusKey);
            CabinTemperatureLabel.Text = Loc.GetString(statusKey);
            CabinPressureLabel.FontColorOverride = Color.Gray;
            CabinTemperatureLabel.FontColorOverride = Color.Gray;
        }

        if (state.HasGasModule)
        {
            TankPressureLabel.Text = Loc.GetString("mech-tank-pressure-level-label",
                ("state", "ok"),
                ("pressure", FormatPressure(state.TankPressure)));
            TankPressureLabel.FontColorOverride = Color.White;
        }
        else
        {
            TankPressureLabel.Text = Loc.GetString("mech-tank-pressure-level-label", ("state", "na"));
            TankPressureLabel.FontColorOverride = Color.Gray;
        }

        UpdateFanStatusDisplay(state.FanState);
        UpdateLockInfoLabels(state);
        UpdateLockButtons(state);

        // Compare UI children vs new state to decide whether to rebuild.
        var currentEquip = EquipmentControlContainer.Children.OfType<MechEquipmentControl>()
            .Select(c => _entityManager.GetNetEntity(c.Entity));
        if (!currentEquip.SequenceEqual(state.Equipment))
            UpdateEquipmentView(state.Equipment);

        var currentMods = ModuleControlContainer.Children.OfType<MechEquipmentControl>()
            .Select(c => _entityManager.GetNetEntity(c.Entity));
        if (!currentMods.SequenceEqual(state.Modules))
            UpdateModuleView(state.Modules);

        // Apply access visibility.
        SetAccessVisibility(state.IsLocked);

        // Disable removing only if pilot is present.
        SetRemoveDisabledForContainer(EquipmentControlContainer, _pilotPresent);
        SetRemoveDisabledForContainer(ModuleControlContainer, _pilotPresent);

        RefreshEquipmentFragmentStates(state);
    }

    private void UpdateFanStatusDisplay(MechFanState fanState)
    {
        var stateKey = fanState switch
        {
            MechFanState.Off => "off",
            MechFanState.On => "on",
            MechFanState.Idle => "idle",
            _ => "na"
        };
        var stateColorKey = fanState switch
        {
            MechFanState.Off => Color.Red,
            MechFanState.On => Color.Green,
            MechFanState.Idle => Color.Yellow,
            _ => Color.Gray
        };

        FanStatusLabel.Text = Loc.GetString("mech-fan-status-level-label", ("state", stateKey));
        FanStatusLabel.FontColorOverride = stateColorKey;
    }

    private static string FormatPressure(float pressure)
    {
        return MathF.Round(MathF.Max(pressure, 0f)).ToString(CultureInfo.InvariantCulture);
    }

    public void UpdateEnergyDrainDisplay(float energyDrainRate)
    {
        EnergyDrainLabel.Text = Loc.GetString("mech-energy-drain-display",
            ("amount", FormatDrain(energyDrainRate)));
        EnergyDrainLabel.FontColorOverride = energyDrainRate > 0.01f
            ? Color.Orange
            : Color.Gray;
    }

    private static string FormatDrain(float drain)
    {
        drain = MathF.Max(drain, 0f);
        if (drain < 10f && MathF.Abs(drain - MathF.Round(drain)) > 0.05f)
            return drain.ToString("0.##", CultureInfo.InvariantCulture);

        return MathF.Round(drain).ToString(CultureInfo.InvariantCulture);
    }

    private void UpdateLockInfoLabels(MechBoundUiState state)
    {
        if (state.DnaLockRegistered && !string.IsNullOrEmpty(state.OwnerDna))
            DnaLockInfoLabel.Text = $"[{state.OwnerDna}]";
        else
            DnaLockInfoLabel.Text = Loc.GetString("mech-lock-not-set-label");

        if (state.CardLockRegistered && !string.IsNullOrEmpty(state.OwnerJobTitle))
            CardLockInfoLabel.Text = $"[{state.OwnerJobTitle}]";
        else
            CardLockInfoLabel.Text = Loc.GetString("mech-lock-not-set-label");
    }

    private void UpdateLockButtons(MechBoundUiState state)
    {
        var (dnaRegistered, dnaActive) = GetLockState(state, MechLockType.Dna);
        var (cardRegistered, cardActive) = GetLockState(state, MechLockType.Card);

        UpdateLockButtonSet(DnaLockRegisterButton, DnaLockBlockButton, DnaLockResetButton, dnaRegistered, dnaActive);
        UpdateLockButtonSet(CardLockRegisterButton, CardLockBlockButton, CardLockResetButton, cardRegistered, cardActive);
    }

    private static void UpdateLockButtonSet(Button registerButton,  Button blockButton, Button resetButton, bool isRegistered, bool isActive)
    {
        registerButton.Visible = !isRegistered;
        blockButton.Visible = isRegistered;
        resetButton.Visible = isRegistered;
        blockButton.Text = Loc.GetString(isActive ? "mech-lock-deactivate-button" : "mech-lock-activate-button");
        blockButton.Pressed = isActive;
    }

    private static void SetRemoveDisabledForContainer(Control container, bool disabled)
    {
        foreach (var control in container.Children.OfType<MechEquipmentControl>())
        {
            control.SetRemoveDisabled(disabled);
        }
    }

    private void RefreshEquipmentFragmentStates(MechBoundUiState state)
    {
        UpdateFragmentsForContainer(EquipmentControlContainer, state.EquipmentUiStates);
        UpdateFragmentsForContainer(ModuleControlContainer, state.EquipmentUiStates);
    }

    public void UpdateEquipmentFragmentState(NetEntity netEnt, BoundUserInterfaceState state)
    {
        if (TryUpdateFragmentForContainer(EquipmentControlContainer, netEnt, state))
            return;

        TryUpdateFragmentForContainer(ModuleControlContainer, netEnt, state);
    }

    private void UpdateFragmentsForContainer(Control container, Dictionary<NetEntity, BoundUserInterfaceState> states)
    {
        foreach (var control in container.Children.OfType<MechEquipmentControl>())
        {
            var ent = control.Entity;
            var netEnt = _entityManager.GetNetEntity(ent);
            if (!states.TryGetValue(netEnt, out var eqState))
                continue;

            var uicomp = _entityManager.GetComponentOrNull<UIFragmentComponent>(ent);
            if (uicomp?.Ui != null)
                uicomp.Ui.UpdateState(eqState);
        }
    }

    private bool TryUpdateFragmentForContainer(Control container, NetEntity netEnt, BoundUserInterfaceState state)
    {
        foreach (var control in container.Children.OfType<MechEquipmentControl>())
        {
            if (_entityManager.GetNetEntity(control.Entity) != netEnt)
                continue;

            var uicomp = _entityManager.GetComponentOrNull<UIFragmentComponent>(control.Entity);
            if (uicomp?.Ui != null)
                uicomp.Ui.UpdateState(state);

            return true;
        }

        return false;
    }

    private (bool IsRegistered, bool IsActive) GetLockState(MechBoundUiState state, MechLockType lockType)
    {
        return lockType switch
        {
            MechLockType.Dna => (state.DnaLockRegistered, state.DnaLockActive),
            MechLockType.Card => (state.CardLockRegistered, state.CardLockActive),
            _ => (false, false)
        };
    }

    private void SetAccessVisibility(bool isLocked)
    {
        var user = _playerManager.LocalEntity;
        if (user == null)
            return;

        var mechLock = _entityManager.System<MechLockSystem>();
        var noAccessActive = isLocked && !mechLock.CheckAccess(_mech, user.Value);
        HaveAccessEquipment.Visible = !noAccessActive;
        HaveAccessSettings.Visible = !noAccessActive;
        NoAccessSettings.Visible = noAccessActive;
        NoAccessEquipment.Visible = noAccessActive;
    }

    private void UpdateEquipmentView(List<NetEntity> equipment)
    {
        EquipmentControlContainer.Children.Clear();
        foreach (var netEnt in equipment)
        {
            var ent = _entityManager.GetEntity(netEnt);
            var size = _entityManager.GetComponentOrNull<MechEquipmentComponent>(ent)?.Size ?? 1;
            var control = HelperUpdateView(netEnt, ent, size);
            control.OnRemoveButtonPressed += () => OnRemoveButtonPressed?.Invoke(ent);
            EquipmentControlContainer.AddChild(control);
        }
    }

    private void UpdateModuleView(List<NetEntity> modules)
    {
        ModuleControlContainer.Children.Clear();
        foreach (var netEnt in modules)
        {
            var ent = _entityManager.GetEntity(netEnt);
            var size = _entityManager.GetComponentOrNull<MechModuleComponent>(ent)?.Size ?? 1;
            var control = HelperUpdateView(netEnt, ent, size);
            control.OnRemoveButtonPressed += () => OnRemoveModuleButtonPressed?.Invoke(ent);
            ModuleControlContainer.AddChild(control);
        }
    }

    private MechEquipmentControl HelperUpdateView(NetEntity netEnt, EntityUid ent, int size)
    {
        Control? ui = null;
        var uicomp = _entityManager.GetComponentOrNull<UIFragmentComponent>(ent);
        if (uicomp?.Ui != null)
        {
            uicomp.Ui.Setup(_parentBui!, ent);
            ui = uicomp.Ui.GetUIFragmentRoot();
        }

        var metaData = _entityManager.GetComponentOrNull<MetaDataComponent>(ent);
        var control = new MechEquipmentControl(ent, metaData?.EntityName ?? "", ui, size);
        return control;
    }

    /// <summary>
    /// Updates the UI state and refreshes all displays.
    /// </summary>
    public void UpdateState(MechBoundUiState state)
    {
        UpdateMechStats(state);
        UpdateMechState(state);
    }
}
