using System.Text;
using Content.Client.Items;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Mech.Ui;

/// <summary>
/// Control for displaying individual mech equipment items in the UI.
/// </summary>
/// <seealso cref="MechMenu"/>
[GenerateTypedNameReferences]
public sealed partial class MechEquipmentControl : Control
{
    [Dependency] private  IEntityManager _entMan = default!;

    private const int NameWrapLineLength = 26;

    public event Action? OnRemoveButtonPressed;
    public EntityUid Entity { get; private set; }

    public MechEquipmentControl(EntityUid entity, string itemName, Control? fragment, int size)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        InitializeControl(entity, itemName, fragment, size);
    }

    public void SetRemoveDisabled(bool disabled)
    {
        RemoveButton.Disabled = disabled;
        RemoveButton.ToolTip = disabled
            ? Loc.GetString("mech-remove-disabled-tooltip")
            : null;

        RemoveButton.Modulate = disabled
            ? new Color(0.5f, 0.5f, 0.5f, 1f)
            : Color.White;
    }

    public void UpdateControl(string itemName, Control? fragment, int size)
    {
        SetContent(itemName, fragment, size);
    }

    private void InitializeControl(EntityUid entity, string itemName, Control? fragment, int size)
    {
        Entity = entity;

        // Set equipment information
        SetContent(itemName, fragment, size);
        EquipmentView.SetEntity(entity);

        // Configure remove button
        RemoveButton.TexturePath = "/Textures/Interface/Nano/cross.svg.png";
        SetRemoveDisabled(true);

        // Wire up events
        RemoveButton.OnPressed += _ => OnRemoveButtonPressed?.Invoke();
    }

    private static void AddChildWithMargins(BoxContainer parent, Control child)
    {
        child.Margin = new Thickness(3);
        child.HorizontalExpand = true;
        child.HorizontalAlignment = HAlignment.Stretch;
        parent.AddChild(child);
    }

    private void SetContent(string itemName, Control? fragment, int size)
    {
        // Set equipment information
        EquipmentName.Text = WrapItemName(itemName);
        EquipmentName.ToolTip = itemName;
        EquipmentSize.Visible = size > 1;
        EquipmentSize.Text = $"[{size}]";

        // Update fragment if provided
        CustomControlContainer.Children.Clear();
        var showContainer = false;
        var customContent = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        // Try to collect item status controls for this equipment
        var status = new ItemStatusCollectMessage();
        _entMan.EventBus.RaiseLocalEvent(Entity, status);
        foreach (var control in status.Controls)
        {
            showContainer = true;
            AddStatusChildWithMargins(customContent, control);
        }

        if (fragment != null)
        {
            if (showContainer)
                AddDivider(customContent);

            showContainer = true;
            AddChildWithMargins(customContent, fragment);
        }

        if (showContainer)
            CustomControlContainer.AddChild(customContent);

        CustomControlContainer.Visible = showContainer;
        Separator.Visible = showContainer;
    }

    private static void AddDivider(BoxContainer parent)
    {
        parent.AddChild(new PanelContainer
        {
            StyleClasses = { "LowDivider" },
            HorizontalExpand = true,
            Margin = new Thickness(3, 1, 3, 1),
            MinHeight = 1,
        });
    }

    private static string WrapItemName(string itemName)
    {
        if (itemName.Length <= NameWrapLineLength || !itemName.Contains(' '))
            return itemName;

        var builder = new StringBuilder(itemName.Length + 4);
        var lineLength = 0;

        foreach (var word in itemName.Split(' ', StringSplitOptions.RemoveEmptyEntries))
        {
            if (lineLength > 0 && lineLength + word.Length + 1 > NameWrapLineLength)
            {
                builder.Append('\n');
                lineLength = 0;
            }
            else if (lineLength > 0)
            {
                builder.Append(' ');
                lineLength++;
            }

            builder.Append(word);
            lineLength += word.Length;
        }

        return builder.ToString();
    }

    private static void AddStatusChildWithMargins(BoxContainer parent, Control child)
    {
        child.Margin = new Thickness(3);
        child.HorizontalExpand = true;
        child.HorizontalAlignment = HAlignment.Stretch;
        child.RectClipContent = true;
        parent.AddChild(child);
    }
}
