using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Client._WH40K.Interface;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Kitchen.UI;

[GenerateTypedNameReferences]
public sealed partial class MicrowaveMenu : FancyWindow
{
    [Dependency] private  IGameTiming _timing = default!;

    private static readonly Color Accent = Color.FromHex("#C9A94C".AsSpan());
    private static readonly Color WarningAccent = Color.FromHex("#A57C35".AsSpan());
    private static readonly Color BorderColor = Color.FromHex("#2A2418".AsSpan());
    private static readonly Color BorderStrongColor = Color.FromHex("#3D3422".AsSpan());
    private static readonly Color WindowBackground = Color.FromHex("#0B0C10".AsSpan());
    private static readonly Color PanelBackground = Color.FromHex("#0C0D10".AsSpan());
    private static readonly Color PanelAltBackground = Color.FromHex("#0E0F14".AsSpan());
    private static readonly Color SurfaceBackground = Color.FromHex("#0C0D12".AsSpan());
    private static readonly Color HeaderBackground = Color.FromHex("#0E0F14".AsSpan());
    private static readonly Color PrimaryText = Color.FromHex("#D4C8A0".AsSpan());
    private static readonly Color SecondaryText = Color.FromHex("#A09880".AsSpan());
    private static readonly Color LabelText = Color.FromHex("#8A7D5E".AsSpan());
    private static readonly Color DangerAccent = Color.FromHex("#8B3030".AsSpan());
    private static readonly ResPath PlateRsi = new("/Textures/Objects/Consumable/Food/plates.rsi");
    private const float PlateStageAnchorY = 0.68f;
    private const float IngredientStageAnchorY = 0.59f;
    private const float IngredientPreviewWidth = 152f;
    private const float IngredientPreviewHeight = 108f;

    private readonly List<MicrowaveCookTimeButton> _cookTimeButtons = new();
    private readonly List<MicrowaveIngredientEntry> _ingredientEntries = new();
    private Texture? _plateTexture;

    private int _activeButtonIndex;
    private int _selectedIngredientIndex = -1;
    private uint _selectedCookTime;
    private bool _previewHovered;
    private bool _instantHovered;
    private bool _startHovered;
    private bool _ejectHovered;
    private bool _closeHovered;

    public event Action<int, uint>? OnCookTimeSelected;
    public event Action<int>? OnIngredientSelected;

    public ButtonGroup CookTimeButtonGroup { get; }

    public bool IsBusy { get; private set; }
    public TimeSpan CurrentCooktimeEnd { get; private set; }

    private bool HasIngredients => _ingredientEntries.Count > 0;
    private bool HasSelectedIngredient => _selectedIngredientIndex >= 0 && _selectedIngredientIndex < _ingredientEntries.Count;

    public MicrowaveMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CookTimeButtonGroup = new ButtonGroup();
        _plateTexture = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>().Frame0(new SpriteSpecifier.Rsi(PlateRsi, "plate"));

        ApplyTheme();
        ConfigurePreviewStage();
        WireInteractions();
        BuildCookTimeButtons();

        InstantCookButton.Group = CookTimeButtonGroup;
        InstantCookButton.ToggleMode = true;
        InstantCookButton.OnPressed += _ => SelectCookTime(0, 0, true);

        SetEntityName(Loc.GetString("microwave-menu-title"));
        SetCookTimeSelection(0, 0);
        SetIngredientEntries(Array.Empty<MicrowaveIngredientEntry>());
        SetBusyState(false, TimeSpan.Zero);
    }

    protected override void Opened()
    {
        base.Opened();

        WindowHeader.Modulate = new Color(1f, 1f, 1f, 0f);
        WindowTitle.Modulate = new Color(1f, 1f, 1f, 0f);
        HeaderPanel.Modulate = new Color(1f, 1f, 1f, 0f);
        FooterDivider.Modulate = new Color(1f, 1f, 1f, 0f);
        FooterBar.Modulate = new Color(1f, 1f, 1f, 0f);

        WH40KUiChrome.PlayFadeIn(WindowHeader, "microwave-window-header-appear", 0.12f);
        WH40KUiChrome.PlayFadeIn(WindowTitle, "microwave-window-title-appear", 0.12f, 0.02f);
        WH40KUiChrome.PlayFadeIn(HeaderPanel, "microwave-header-appear", 0.16f, 0.04f);
        WH40KUiChrome.PlayFadeIn(FooterDivider, "microwave-footer-appear", 0.18f, 0.16f);
        WH40KUiChrome.PlayFadeIn(FooterBar, "microwave-footer-panel-appear", 0.18f, 0.18f);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (IsBusy)
            UpdateCookTimeInfo();
    }

    public void SetEntityName(string entityName)
    {
        if (string.IsNullOrWhiteSpace(entityName))
            entityName = Loc.GetString("microwave-menu-title");

        Title = entityName;
        HeaderTitleLabel.Text = WH40KUiChrome.DecorateTitle(WH40KUiChrome.Cog, entityName.ToUpperInvariant());
    }

    public void SetCookTimeSelection(int buttonIndex, uint cookTime)
    {
        _activeButtonIndex = buttonIndex;
        _selectedCookTime = cookTime;

        InstantCookButton.Pressed = buttonIndex == 0;

        foreach (var button in _cookTimeButtons)
        {
            button.Pressed = button.ButtonIndex == buttonIndex;
        }

        UpdateCookTimeInfo();
        UpdateCookTimeButtonStyles();
        UpdateOperationalText();
    }

    public void SetBusyState(bool busy, TimeSpan currentCooktimeEnd)
    {
        IsBusy = busy;
        CurrentCooktimeEnd = currentCooktimeEnd;

        RefreshState();
    }

    public void SetIngredientEntries(IReadOnlyList<MicrowaveIngredientEntry> entries)
    {
        _ingredientEntries.Clear();
        _ingredientEntries.AddRange(entries);
        _selectedIngredientIndex = _ingredientEntries.Count switch
        {
            0 => -1,
            _ when _selectedIngredientIndex < 0 => 0,
            _ => Math.Clamp(_selectedIngredientIndex, 0, _ingredientEntries.Count - 1),
        };

        RebuildIngredientEntries();
        RefreshState();
    }

    public void ToggleBusyDisableOverlayPanel(bool shouldShow)
    {
        DisableCookingPanelOverlay.Visible = shouldShow;
    }

    private void ApplyTheme()
    {
        SetSize = new Vector2(796f, 486f);
        MinSize = new Vector2(772f, 466f);

        if (GetChild(0) is PanelContainer windowBackdrop)
            windowBackdrop.PanelOverride = CreatePanelStyle(WindowBackground, BorderStrongColor, 0, 2);

        WindowHeader.PanelOverride = CreateEdgePanelStyle(
            HeaderBackground,
            BorderStrongColor,
            new Thickness(0f, 0f, 0f, 1f),
            0);

        WindowTitle.FontColorOverride = Accent;
        RootFrame.PanelOverride = CreatePanelStyle(WindowBackground, BorderStrongColor, 0);
        HeaderPanel.PanelOverride = CreatePanelStyle(PanelBackground, BorderStrongColor, 0);
        IngredientsPanel.PanelOverride = CreatePanelStyle(PanelBackground, BorderStrongColor, 0);
        ControlPanel.PanelOverride = CreatePanelStyle(PanelBackground, BorderStrongColor, 0);
        StatusPanel.PanelOverride = CreatePanelStyle(PanelAltBackground, BorderColor, 0);
        TimePanel.PanelOverride = CreatePanelStyle(PanelAltBackground, BorderColor, 0);

        FooterDivider.MinSize = new Vector2(0f, 1f);
        FooterDivider.PanelOverride = CreateDividerStyle(BorderStrongColor);

        HeaderSubtitleLabel.SetMessage(Loc.GetString("microwave-menu-header-subtitle"), defaultColor: SecondaryText);
        ChamberTitleLabel.Text = WH40KUiChrome.DecorateIfMissing(Loc.GetString("microwave-menu-chamber-title"), WH40KUiChrome.Diamond);
        ChamberTitleLabel.FontColorOverride = Accent;
        IngredientCountLabel.FontColorOverride = SecondaryText;
        ChamberNoteLabel.SetMessage(Loc.GetString("microwave-menu-chamber-note-empty"), defaultColor: SecondaryText);
        SelectorTitleLabel.FontColorOverride = LabelText;

        CookTimeInfoLabel.FontColorOverride = LabelText;
        CookTimeValueLabel.FontColorOverride = Accent;
        MachineStatusLabel.FontColorOverride = SecondaryText;
        ModeStatusLabel.SetMessage(Loc.GetString("microwave-menu-mode-awaiting"), defaultColor: SecondaryText);
        SelectedIngredientLabel.FontColorOverride = PrimaryText;
        SelectedIngredientHintLabel.SetMessage(Loc.GetString("microwave-menu-stage-hint-empty"), defaultColor: SecondaryText);
        IngredientPreviewPlaceholderLabel.FontColorOverride = LabelText;

        FooterLeftLabel.FontColorOverride = SecondaryText;
        FooterRightLabel.FontColorOverride = LabelText;
        FooterRightLabel.Text = Loc.GetString("microwave-menu-footer-right");
        UpdateHeaderStyles();

        DisableCookingPanelOverlay.PanelOverride = CreatePanelStyle(
            WindowBackground.WithAlpha(0.62f),
            WarningAccent.WithAlpha(0.7f),
            0);

        WH40KUiChrome.StartLoopingPulse(HeaderTitleLabel, "microwave-title-pulse", Accent.WithAlpha(0.82f), Color.White, 3.2f);
        WH40KUiChrome.StartLoopingPulse(FooterDivider, "microwave-divider-pulse", Accent.WithAlpha(0.34f), Color.White, 4.1f);
    }

    private void ConfigurePreviewStage()
    {
        PlateTextureRect.Texture = _plateTexture;
        PlateTextureRect.ModulateSelfOverride = new Color(1f, 1f, 1f, 0.82f);

        LayoutContainer.SetAnchorPreset(StageBackdropPanel, LayoutContainer.LayoutPreset.Wide);

        SetCenteredStageRect(PlateTextureRect, 236f, 128f, PlateStageAnchorY);
        SetCenteredStageRect(IngredientPreviewTextureRect, IngredientPreviewWidth, IngredientPreviewHeight, IngredientStageAnchorY);

        LayoutContainer.SetAnchorPreset(IngredientPreviewPlaceholderLabel, LayoutContainer.LayoutPreset.Wide);
    }

    private void WireInteractions()
    {
        BindHoverState(InstantCookButton, hovered =>
        {
            _instantHovered = hovered;
            UpdateCookTimeButtonStyles();
        });

        BindHoverState(StartButton, hovered =>
        {
            _startHovered = hovered;
            UpdateActionButtonStyles();
        });

        BindHoverState(EjectButton, hovered =>
        {
            _ejectHovered = hovered;
            UpdateActionButtonStyles();
        });

        BindHoverState(PreviewActionButton, hovered =>
        {
            _previewHovered = hovered;
            UpdatePanelStyles();
        });

        BindHoverState(CloseButton, hovered =>
        {
            _closeHovered = hovered;
            UpdateHeaderStyles();
        });

        PreviewActionButton.OnPressed += _ =>
        {
            if (!IsBusy && HasSelectedIngredient)
                OnIngredientSelected?.Invoke(_selectedIngredientIndex);
        };
    }

    private void BuildCookTimeButtons()
    {
        for (var i = 1; i <= 6; i++)
        {
            var buttonIndex = i;
            var cookTime = (uint) (i * 5);

            var button = new MicrowaveCookTimeButton
            {
                ButtonIndex = buttonIndex,
                CookTime = cookTime,
                Text = cookTime.ToString(),
                TextAlign = Label.AlignMode.Center,
                ToggleMode = true,
                Group = CookTimeButtonGroup,
                HorizontalExpand = true,
                MinHeight = 24,
            };

            button.OnPressed += _ => SelectCookTime(buttonIndex, cookTime, true);
            BindHoverState(button, hovered =>
            {
                button.HoveredState = hovered;
                UpdateCookTimeButtonStyles();
            });

            _cookTimeButtons.Add(button);
            CookTimeButtonVbox.AddChild(button);
        }
    }

    private void SelectCookTime(int buttonIndex, uint cookTime, bool raiseEvent)
    {
        SetCookTimeSelection(buttonIndex, cookTime);

        if (raiseEvent)
            OnCookTimeSelected?.Invoke(buttonIndex, cookTime);
    }

    private void RefreshState()
    {
        var controlsDisabled = IsBusy || !HasIngredients;

        StartButton.Disabled = controlsDisabled;
        EjectButton.Disabled = controlsDisabled;
        InstantCookButton.Disabled = controlsDisabled;

        foreach (var button in _cookTimeButtons)
        {
            button.Disabled = controlsDisabled;
        }

        ToggleBusyDisableOverlayPanel(IsBusy);
        RebuildIngredientEntries();
        UpdatePanelStyles();
        UpdateCookTimeInfo();
        UpdateCookTimeButtonStyles();
        UpdateActionButtonStyles();
        UpdateOperationalText();
        UpdatePreviewStage();
    }

    private void RebuildIngredientEntries()
    {
        IngredientSelectorGrid.RemoveAllChildren();
        SelectorPanel.Visible = _ingredientEntries.Count > 1;

        if (!SelectorPanel.Visible)
            return;

        foreach (var entry in _ingredientEntries)
        {
            IngredientSelectorGrid.AddChild(CreateIngredientSelectorButton(entry));
        }
    }

    private void UpdateCookTimeInfo()
    {
        var displayTime = BuildSelectedCookTimeText();

        if (IsBusy && CurrentCooktimeEnd > _timing.CurTime)
        {
            var secondsLeft = (int) Math.Ceiling((CurrentCooktimeEnd - _timing.CurTime).TotalSeconds);
            displayTime = Math.Max(secondsLeft, 0).ToString();
        }

        CookTimeValueLabel.Text = displayTime;
    }

    private void UpdatePanelStyles()
    {
        var chamberBorder = IsBusy
            ? WarningAccent
            : HasIngredients
                ? BorderStrongColor
                : BorderColor;

        var chamberBackground = IsBusy
            ? Blend(PanelBackground, WarningAccent, 0.12f)
            : PanelBackground;
        var stageHovered = _previewHovered && !PreviewActionButton.Disabled;
        var stageBorder = stageHovered
            ? Accent.WithAlpha(0.92f)
            : chamberBorder;

        IngredientsPanel.PanelOverride = CreatePanelStyle(chamberBackground, chamberBorder, 0);
        PreviewActionButton.StyleBoxOverride = CreateStageButtonStyle(
            stageBorder,
            IsBusy ? 0.1f : stageHovered ? 0.24f : 0.18f);
        StageBackdropPanel.PanelOverride = CreateStageBackdropStyle(stageHovered);
        SelectorPanel.PanelOverride = CreatePanelStyle(PanelAltBackground, BorderColor, 0);

        var statusBorder = IsBusy
            ? WarningAccent
            : HasIngredients
                ? Accent.WithAlpha(0.7f)
                : BorderColor;

        StatusPanel.PanelOverride = CreatePanelStyle(
            IsBusy ? Blend(PanelAltBackground, WarningAccent, 0.12f) : PanelAltBackground,
            statusBorder,
            0);

        TimePanel.PanelOverride = CreatePanelStyle(
            PanelAltBackground,
            HasIngredients ? BorderStrongColor : BorderColor,
            0);
    }

    private void UpdateOperationalText()
    {
        IngredientCountLabel.Text = Loc.GetString("microwave-menu-chamber-count", ("count", _ingredientEntries.Count));
        ChamberNoteLabel.SetMessage(Loc.GetString(ResolveChamberNoteLocKey()), defaultColor: SecondaryText);

        MachineStatusLabel.Text = Loc.GetString(ResolveStatusLocKey());
        MachineStatusLabel.FontColorOverride = ResolveStatusColor();

        ModeStatusLabel.SetMessage(Loc.GetString(ResolveModeLocKey(), ("mode", BuildSelectedCookTimeText())), defaultColor: SecondaryText);

        FooterLeftLabel.Text = Loc.GetString(ResolveFooterLocKey());
        FooterLeftLabel.FontColorOverride = ResolveStatusColor();
        FooterRightLabel.Text = Loc.GetString("microwave-menu-footer-right");
    }

    private void UpdatePreviewStage()
    {
        PreviewActionButton.Disabled = IsBusy || !HasSelectedIngredient;
        PlateTextureRect.Visible = true;
        PlateTextureRect.ModulateSelfOverride = HasSelectedIngredient
            ? new Color(1f, 1f, 1f, 0.82f)
            : new Color(1f, 1f, 1f, 0.42f);

        if (!HasSelectedIngredient)
        {
            IngredientPreviewTextureRect.Texture = null;
            IngredientPreviewTextureRect.Visible = false;
            IngredientPreviewPlaceholderLabel.Visible = true;
            IngredientPreviewPlaceholderLabel.Text = Loc.GetString("microwave-menu-stage-empty");
            SelectedIngredientLabel.Text = Loc.GetString("microwave-menu-stage-empty");
            SelectedIngredientLabel.FontColorOverride = SecondaryText;
            SelectedIngredientHintLabel.SetMessage(Loc.GetString("microwave-menu-stage-hint-empty"), defaultColor: SecondaryText);
            return;
        }

        var selected = _ingredientEntries[_selectedIngredientIndex];
        IngredientPreviewTextureRect.Texture = selected.Icon;
        IngredientPreviewTextureRect.Visible = selected.Icon != null;
        IngredientPreviewPlaceholderLabel.Visible = selected.Icon == null;
        IngredientPreviewPlaceholderLabel.Text = WH40KUiChrome.DiamondOutline;
        IngredientPreviewPlaceholderLabel.FontColorOverride = LabelText;
        SelectedIngredientLabel.Text = selected.Name;
        SelectedIngredientLabel.FontColorOverride = PrimaryText;
        SelectedIngredientHintLabel.SetMessage(
            Loc.GetString(IsBusy
                ? "microwave-menu-stage-hint-busy"
                : "microwave-menu-stage-hint-ready"),
            defaultColor: IsBusy ? WarningAccent : SecondaryText);
    }

    private void UpdateCookTimeButtonStyles()
    {
        ApplyButtonTheme(
            InstantCookButton,
            CreateTimeButtonStyle(InstantCookButton.Pressed, InstantCookButton.Disabled, _instantHovered),
            PrimaryText,
            InstantCookButton.Disabled);

        foreach (var button in _cookTimeButtons)
        {
            ApplyButtonTheme(
                button,
                CreateTimeButtonStyle(button.Pressed, button.Disabled, button.HoveredState),
                PrimaryText,
                button.Disabled);
        }
    }

    private void UpdateActionButtonStyles()
    {
        ApplyButtonTheme(
            StartButton,
            CreatePrimaryButtonStyle(StartButton.Disabled ? 0.1f : _startHovered ? 0.3f : 0.22f),
            PrimaryText,
            StartButton.Disabled);

        ApplyButtonTheme(
            EjectButton,
            CreateDangerButtonStyle(EjectButton.Disabled ? 0.08f : _ejectHovered ? 0.24f : 0.16f),
            PrimaryText,
            EjectButton.Disabled);

        UpdateHeaderStyles();
    }

    private Control CreateIngredientSelectorButton(MicrowaveIngredientEntry entry)
    {
        var selected = entry.Index == _selectedIngredientIndex;
        var normalButtonStyle = CreateSelectorButtonStyle(selected, IsBusy, false);
        var hoverButtonStyle = CreateSelectorButtonStyle(selected, IsBusy, true);
        var normalPanelStyle = CreateSelectorPanelStyle(selected, false);
        var hoverPanelStyle = CreateSelectorPanelStyle(selected, true);

        var button = new ContainerButton
        {
            HorizontalExpand = true,
            MinHeight = 42,
            Disabled = IsBusy,
            ToolTip = entry.Name,
            StyleBoxOverride = normalButtonStyle,
            ModulateSelfOverride = Color.White,
        };

        var panel = new PanelContainer
        {
            MinSize = new Vector2(32f, 32f),
            HorizontalExpand = true,
            VerticalExpand = true,
            PanelOverride = normalPanelStyle,
        };

        if (entry.Icon != null)
        {
            panel.AddChild(new TextureRect
            {
                Texture = entry.Icon,
                TextureScale = new Vector2(1.05f, 1.05f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalExpand = true,
                VerticalExpand = true,
            });
        }
        else
        {
            panel.AddChild(new Label
            {
                Text = WH40KUiChrome.DiamondOutline,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                FontColorOverride = LabelText,
            });
        }

        button.AddChild(panel);
        button.OnPressed += _ =>
        {
            if (IsBusy)
                return;

            _selectedIngredientIndex = entry.Index;
            UpdatePreviewStage();
            RebuildIngredientEntries();
        };
        button.OnMouseEntered += _ =>
        {
            if (IsBusy)
                return;

            button.StyleBoxOverride = hoverButtonStyle;
            panel.PanelOverride = hoverPanelStyle;
        };
        button.OnMouseExited += _ =>
        {
            button.StyleBoxOverride = normalButtonStyle;
            panel.PanelOverride = normalPanelStyle;
        };

        return button;
    }

    private void UpdateHeaderStyles()
    {
        CloseButton.ModulateSelfOverride = _closeHovered ? Accent : LabelText;
    }

    private string ResolveStatusLocKey()
    {
        if (IsBusy)
            return "microwave-menu-status-busy";

        return HasIngredients
            ? "microwave-menu-status-ready"
            : "microwave-menu-status-empty";
    }

    private string ResolveChamberNoteLocKey()
    {
        if (IsBusy)
            return "microwave-menu-chamber-note-busy";

        return HasIngredients
            ? "microwave-menu-chamber-note-ready"
            : "microwave-menu-chamber-note-empty";
    }

    private string ResolveModeLocKey()
    {
        if (IsBusy)
            return "microwave-menu-mode-busy";

        return HasIngredients
            ? "microwave-menu-mode-selected"
            : "microwave-menu-mode-awaiting";
    }

    private string ResolveFooterLocKey()
    {
        if (IsBusy)
            return "microwave-menu-footer-busy";

        return HasIngredients
            ? "microwave-menu-footer-ready"
            : "microwave-menu-footer-empty";
    }

    private Color ResolveStatusColor()
    {
        if (IsBusy)
            return WarningAccent;

        return HasIngredients ? Accent : SecondaryText;
    }

    private string BuildSelectedCookTimeText()
    {
        return _activeButtonIndex == 0
            ? Loc.GetString("microwave-menu-instant-button")
            : _selectedCookTime.ToString();
    }

    private static StyleBoxFlat CreatePanelStyle(Color background, Color border, int padding = 8, int borderThickness = 1)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(borderThickness),
            ContentMarginLeftOverride = padding,
            ContentMarginTopOverride = padding,
            ContentMarginRightOverride = padding,
            ContentMarginBottomOverride = padding,
        };
    }

    private static StyleBoxFlat CreateEdgePanelStyle(Color background, Color border, Thickness borderThickness, int padding = 8)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = borderThickness,
            ContentMarginLeftOverride = padding,
            ContentMarginTopOverride = padding,
            ContentMarginRightOverride = padding,
            ContentMarginBottomOverride = padding,
        };
    }

    private static StyleBoxFlat CreateDividerStyle(Color color)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = color,
        };
    }

    private static StyleBoxFlat CreateButtonStyle(Color border, Color tint, float tintAmount)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Blend(SurfaceBackground, tint, tintAmount),
            BorderColor = border,
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 10,
            ContentMarginTopOverride = 4,
            ContentMarginRightOverride = 10,
            ContentMarginBottomOverride = 4,
        };
    }

    private static StyleBoxFlat CreatePrimaryButtonStyle(float tintAmount)
    {
        return CreateButtonStyle(Accent.WithAlpha(0.88f), Accent, tintAmount);
    }

    private static StyleBoxFlat CreateDangerButtonStyle(float tintAmount)
    {
        return CreateButtonStyle(DangerAccent.WithAlpha(0.84f), DangerAccent, tintAmount);
    }

    private static StyleBoxFlat CreateTimeButtonStyle(bool active, bool disabled, bool hovered)
    {
        if (disabled)
            return CreateButtonStyle(BorderStrongColor, BorderStrongColor, 0.08f);

        if (hovered && !active)
            return CreateButtonStyle(Accent.WithAlpha(0.74f), Accent, 0.2f);

        return active
            ? CreateButtonStyle(Accent.WithAlpha(0.9f), Accent, hovered ? 0.32f : 0.24f)
            : CreateButtonStyle(BorderStrongColor, BorderStrongColor, 0.16f);
    }

    private static StyleBoxFlat CreateListButtonStyle(Color border, float tintAmount)
    {
        return CreateButtonStyle(border, border, tintAmount);
    }

    private static StyleBoxFlat CreateStageButtonStyle(Color border, float tintAmount)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Blend(SurfaceBackground, Accent, tintAmount),
            BorderColor = border.WithAlpha(0.88f),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 0,
            ContentMarginTopOverride = 0,
            ContentMarginRightOverride = 0,
            ContentMarginBottomOverride = 0,
        };
    }

    private static StyleBoxFlat CreateStageBackdropStyle(bool hovered)
    {
        return CreatePanelStyle(
            Blend(SurfaceBackground, Accent, hovered ? 0.1f : 0.06f),
            hovered ? Accent.WithAlpha(0.7f) : BorderColor,
            0);
    }

    private static StyleBoxFlat CreateSelectorButtonStyle(bool selected, bool disabled, bool hovered)
    {
        if (disabled)
            return CreateButtonStyle(BorderStrongColor, BorderStrongColor, 0.08f);

        if (hovered && !selected)
            return CreateButtonStyle(Accent.WithAlpha(0.76f), Accent, 0.18f);

        return selected
            ? CreateButtonStyle(Accent.WithAlpha(0.88f), Accent, hovered ? 0.32f : 0.26f)
            : CreateButtonStyle(BorderStrongColor, BorderStrongColor, 0.14f);
    }

    private static StyleBoxFlat CreateSelectorPanelStyle(bool selected, bool hovered)
    {
        if (hovered && !selected)
            return CreatePanelStyle(Blend(PanelAltBackground, Accent, 0.08f), Accent.WithAlpha(0.82f), 0);

        return CreatePanelStyle(
            PanelAltBackground,
            selected ? Accent.WithAlpha(0.7f) : BorderColor,
            0);
    }

    private static void SetCenteredStageRect(Control control, float width, float height, float anchorY)
    {
        LayoutContainer.SetAnchorLeft(control, 0.5f);
        LayoutContainer.SetAnchorRight(control, 0.5f);
        LayoutContainer.SetAnchorTop(control, anchorY);
        LayoutContainer.SetAnchorBottom(control, anchorY);
        LayoutContainer.SetMarginLeft(control, -width / 2f);
        LayoutContainer.SetMarginRight(control, width / 2f);
        LayoutContainer.SetMarginTop(control, -height / 2f);
        LayoutContainer.SetMarginBottom(control, height / 2f);
    }

    private static void BindHoverState(Control control, Action<bool> onChanged)
    {
        control.OnMouseEntered += _ => onChanged(true);
        control.OnMouseExited += _ => onChanged(false);
    }

    private static void ApplyButtonTheme(Button button, StyleBoxFlat style, Color fontColor, bool disabled)
    {
        button.StyleBoxOverride = style;
        button.Label.FontColorOverride = disabled ? LabelText : fontColor;
        button.ModulateSelfOverride = Color.White;
    }

    private static Color Blend(Color baseColor, Color accent, float amount)
    {
        amount = Math.Clamp(amount, 0f, 1f);
        return new Color(
            baseColor.R + (accent.R - baseColor.R) * amount,
            baseColor.G + (accent.G - baseColor.G) * amount,
            baseColor.B + (accent.B - baseColor.B) * amount,
            MathF.Max(baseColor.A, accent.A));
    }

    public readonly record struct MicrowaveIngredientEntry(int Index, string Name, Texture? Icon);

    public sealed class MicrowaveCookTimeButton : Button
    {
        public int ButtonIndex;
        public uint CookTime;
        public bool HoveredState;
    }
}
