- type: job
  id: CaptainWH40K
  name: job-name-captain-wh40k
  description: job-description-captain-wh40k
  playTimeTracker: JobCaptainWH40K
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Science
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 4h
  weight: 20
  startingGear: CaptainWH40KGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainWH40KGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCommand
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter

- type: chameleonOutfit
  id: CaptainWH40KChameleonOutfit
  job: CaptainWH40K
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    neck: ClothingNeckCloakCap
