- type: job
  id: FirstAssistant
  name: job-name-first-assistant
  description: job-description-hop  # Assuming similar to HoP
  playTimeTracker: JobFirstAssistant
  weight: 20
  startingGear: HoPGear  # Reuse HoP gear for now
  icon: "JobIconFirstAssistant"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
