using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client._WH40K.Command;
using Content.Client._WH40K.TacticalMap.UI;
using Content.Client.Localization;
using Content.Client.UserInterface.Controls;
using Content.Shared._WH40K.StrategicPoints;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._WH40K.StrategicPoints.UI;

[GenerateTypedNameReferences]
public sealed partial class WH40KStrategicPointWindow : FancyWindow, ILocalizedControl
{
    [Dependency] private readonly ILocalizationManager _localization = default!;

    private WH40KStrategicPointBuiState? _state;
    private WH40KStrategicPointBuiState? _renderedState;
    private Color _accent = WH40KCommandUiStyles.DefaultAccent;
    private bool _chaosTheme;
    private float _refreshAccumulator;

    public event Action? OnUpgradePressed;
    public event Action? OnRefreshRequested;

    public WH40KStrategicPointWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SetWidth = 540f;
        SetHeight = float.NaN;

        UpgradeButton.OnPressed += _ => OnUpgradePressed?.Invoke();
        Relocalize();
    }

    public void Relocalize()
    {
        Title = Loc.GetString("wh40k-strategic-point-ui-window-title");
        IncomeTitleLabel.Text = Loc.GetString("wh40k-strategic-point-ui-income-title");
        UpgradeTitleLabel.Text = Loc.GetString("wh40k-strategic-point-ui-upgrade-title");
        UpgradeButton.Text = Loc.GetString("wh40k-strategic-point-ui-upgrade-button");

        if (_state != null)
            Refresh(force: true);
    }

    public void ApplyState(WH40KStrategicPointBuiState state)
    {
        _state = state;
        Refresh();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_state == null)
            return;

        _refreshAccumulator += args.DeltaSeconds;
        while (_refreshAccumulator >= 1f)
        {
            _refreshAccumulator -= 1f;
            OnRefreshRequested?.Invoke();
        }
    }

    private void Refresh(bool force = false)
    {
        if (_state == null)
            return;

        var state = _state;
        if (!force && _renderedState != null && StatesEqual(_renderedState, state))
            return;

        if (force || _renderedState == null || ThemeStateChanged(_renderedState, state))
            ApplyTheme(state);

        var resolvedOwner = string.IsNullOrWhiteSpace(state.OwnerTeamId)
            ? Loc.GetString("wh40k-strategic-point-owner-neutral")
            : ResolveOptionalLoc(state.OwnerTeamId);
        var callsign = ResolveCallsign(state.Callsign);

        HeaderTitleLabel.Text = Loc.GetString(
            GetHeaderLocKey(state.PointType),
            ("tier", (int) state.Tier));
        WH40KCommandUiStyles.SetWrappedText(HeaderSubtitleLabel, Loc.GetString(
            "wh40k-strategic-point-ui-subtitle",
            ("callsign", callsign)), WH40KCommandUiStyles.SoftText);
        WH40KCommandUiStyles.SetWrappedText(HeaderHealthLabel, Loc.GetString(
            "wh40k-strategic-point-ui-health-line",
            ("hp", state.Hp),
            ("maxHp", state.MaxHp)), WH40KCommandUiStyles.SoftText);
        TeamBadgeLabel.Text = resolvedOwner.ToUpperInvariant();
        TierBadgeLabel.Text = Loc.GetString("wh40k-strategic-point-ui-tier-badge", ("tier", (int) state.Tier));
        StatusBadgeLabel.Text = Loc.GetString(GetStatusLocKey(state.Status)).ToUpperInvariant();

        WH40KCommandUiStyles.SetWrappedText(IncomeValueLabel, BuildIncomeText(state), WH40KCommandUiStyles.SoftText);
        WH40KCommandUiStyles.SetWrappedText(UpgradeMetaLabel, BuildUpgradeMetaText(state), WH40KCommandUiStyles.SoftText);

        UpgradeMaterialsLabel.Visible = state.HasNextUpgrade;
        if (state.HasNextUpgrade)
        {
            WH40KCommandUiStyles.SetWrappedText(
                UpgradeMaterialsLabel,
                BuildUpgradeMaterialsText(state),
                WH40KCommandUiStyles.SoftText);
        }

        UpgradeButton.Disabled = !state.HasNextUpgrade || !state.MaterialsComplete || state.UpgradeInProgress;
        UpgradeButton.Text = !state.HasNextUpgrade
            ? Loc.GetString("wh40k-strategic-point-ui-upgrade-button-max")
            : state.UpgradeInProgress
                ? Loc.GetString("wh40k-strategic-point-ui-upgrade-button-progress")
                : Loc.GetString(
                    "wh40k-strategic-point-ui-upgrade-button-tier",
                    ("tier", (int) state.NextTier),
                    ("seconds", state.UpgradeSeconds));
        WH40KCommandUiStyles.ApplyPrimaryButtonTheme(UpgradeButton, _accent, UpgradeButton.Disabled, _chaosTheme);

        InvalidateMeasure();
        SetHeight = float.NaN;

        _renderedState = state;
    }

    private static string BuildIncomeText(WH40KStrategicPointBuiState state)
    {
        if (state.IncomeEntries.Length == 0)
            return Loc.GetString("wh40k-strategic-point-ui-income-empty");

        return string.Join(
            "\n",
            state.IncomeEntries.Select(entry => Loc.GetString(
                "wh40k-strategic-point-ui-income-row",
                ("name", Loc.GetString(entry.LocKey)),
                ("base", FormatIncomeAmount(entry.LocKey, entry.BaseAmount)),
                ("effective", FormatIncomeAmount(entry.LocKey, entry.EffectiveAmount)),
                ("seconds", state.IncomeIntervalSeconds))));
    }

    private string BuildUpgradeMetaText(WH40KStrategicPointBuiState state)
    {
        if (!state.HasNextUpgrade)
            return Loc.GetString("wh40k-strategic-point-ui-upgrade-meta-max");

        if (state.UpgradeInProgress)
        {
            return Loc.GetString(
                "wh40k-strategic-point-ui-upgrade-meta-in-progress",
                ("tier", (int) state.NextTier),
                ("seconds", state.UpgradeSeconds));
        }

        if (state.MaterialsComplete)
        {
            return Loc.GetString(
                "wh40k-strategic-point-ui-upgrade-meta-ready",
                ("tier", (int) state.NextTier),
                ("seconds", state.UpgradeSeconds));
        }

        return Loc.GetString(
            "wh40k-strategic-point-ui-upgrade-meta-next",
            ("tier", (int) state.NextTier),
            ("seconds", state.UpgradeSeconds));
    }

    private string BuildUpgradeMaterialsText(WH40KStrategicPointBuiState state)
    {
        if (!state.HasNextUpgrade)
            return string.Empty;

        if (state.MaterialEntries.Length == 0)
            return Loc.GetString("wh40k-strategic-point-ui-upgrade-materials-empty");

        var materials = string.Join(
            " | ",
            state.MaterialEntries.Select(entry => Loc.GetString(
                "wh40k-strategic-point-ui-upgrade-material-entry",
                ("name", ResolveMaterialName(entry)),
                ("loaded", entry.Loaded),
                ("required", entry.Required))));
        return Loc.GetString("wh40k-strategic-point-ui-upgrade-materials-line", ("materials", materials));
    }

    private string ResolveMaterialName(WH40KStrategicPointMaterialUiEntry entry)
    {
        if (!string.IsNullOrWhiteSpace(entry.NameLocKey))
            return ResolveOptionalLoc(entry.NameLocKey);

        return entry.StackId;
    }

    private string ResolveOptionalLoc(string value)
    {
        return _localization.TryGetString(value, out var localized)
            ? localized
            : value;
    }

    private static string ResolveCallsign(string? callsign)
    {
        if (string.IsNullOrWhiteSpace(callsign))
            return Loc.GetString("wh40k-strategic-point-callsign-unknown");

        var localized = WH40KTacticalMapLoc.LocalizeCallsign(callsign);
        return string.IsNullOrWhiteSpace(localized)
            ? Loc.GetString("wh40k-strategic-point-callsign-unknown")
            : localized;
    }

    private static string GetPointTypeLocKey(WH40KStrategicPointType pointType)
    {
        return pointType switch
        {
            WH40KStrategicPointType.Resource => "wh40k-strategic-point-type-resource",
            WH40KStrategicPointType.Research => "wh40k-strategic-point-type-research",
            WH40KStrategicPointType.Influence => "wh40k-strategic-point-type-influence",
            _ => "wh40k-strategic-point-type-unknown"
        };
    }

    private static string GetStatusLocKey(WH40KStrategicPointUiStatus status)
    {
        return status switch
        {
            WH40KStrategicPointUiStatus.Ready => "wh40k-strategic-point-ui-status-ready",
            WH40KStrategicPointUiStatus.MaxTier => "wh40k-strategic-point-ui-status-max-tier",
            WH40KStrategicPointUiStatus.MissingMaterials => "wh40k-strategic-point-ui-status-missing-materials",
            WH40KStrategicPointUiStatus.UpgradeInProgress => "wh40k-strategic-point-ui-status-upgrade-in-progress",
            _ => "wh40k-strategic-point-ui-status-missing-materials"
        };
    }

    private static string GetHeaderLocKey(WH40KStrategicPointType pointType)
    {
        return pointType switch
        {
            WH40KStrategicPointType.Resource => "wh40k-strategic-point-ui-header-resource",
            WH40KStrategicPointType.Research => "wh40k-strategic-point-ui-header-research",
            WH40KStrategicPointType.Influence => "wh40k-strategic-point-ui-header-influence",
            _ => "wh40k-strategic-point-ui-header"
        };
    }

    private void ApplyTheme(WH40KStrategicPointBuiState state)
    {
        var teamId = !string.IsNullOrWhiteSpace(state.ThemeTeamId)
            ? state.ThemeTeamId
            : state.OwnerTeamId;

        _accent = WH40KTeamIdentityClientResolver.ResolveAccentColor(teamId, WH40KCommandUiStyles.DefaultAccent);
        _chaosTheme = WH40KTeamIdentityClientResolver.UsesHereticsDoctrinePresentation(teamId);

        HeaderPanel.PanelOverride = WH40KCommandUiStyles.CreateBorderPanelStyle(
            WH40KCommandUiStyles.ResolveHeaderBackground(_chaosTheme),
            _accent,
            2);
        IncomeCard.PanelOverride = WH40KCommandUiStyles.CreateCardStyle(
            WH40KCommandUiStyles.ResolveCardBackground(_chaosTheme),
            _accent);
        UpgradeCard.PanelOverride = WH40KCommandUiStyles.CreateCardStyle(
            WH40KCommandUiStyles.ResolveCardBackgroundAlt(_chaosTheme),
            WH40KCommandUiStyles.ResolveStrongBorder(_chaosTheme));

        TeamBadge.PanelOverride = WH40KCommandUiStyles.CreateBadgeStyle(
            WH40KCommandUiStyles.ResolveBadgeBackground(_chaosTheme),
            _accent);
        TierBadge.PanelOverride = WH40KCommandUiStyles.CreateBadgeStyle(
            WH40KCommandUiStyles.ResolveBadgeBackground(_chaosTheme),
            WH40KCommandUiStyles.InfoBadge);
        StatusBadge.PanelOverride = ResolveStatusBadgeStyle(state.Status);

        HeaderTitleLabel.ModulateSelfOverride = _accent;
        HeaderSubtitleLabel.ModulateSelfOverride = WH40KCommandUiStyles.ResolveSoftText(_chaosTheme);
        HeaderHealthLabel.ModulateSelfOverride = WH40KCommandUiStyles.ResolveSoftText(_chaosTheme);
        TeamBadgeLabel.ModulateSelfOverride = WH40KCommandUiStyles.ResolveSoftText(_chaosTheme);
        TierBadgeLabel.ModulateSelfOverride = WH40KCommandUiStyles.ResolveSoftText(_chaosTheme);
        StatusBadgeLabel.ModulateSelfOverride = WH40KCommandUiStyles.ResolveSoftText(_chaosTheme);

        IncomeTitleLabel.ModulateSelfOverride = _accent;
        UpgradeTitleLabel.ModulateSelfOverride = _accent;
        IncomeValueLabel.ModulateSelfOverride = WH40KCommandUiStyles.ResolveSoftText(_chaosTheme);
        UpgradeMetaLabel.ModulateSelfOverride = WH40KCommandUiStyles.ResolveSoftText(_chaosTheme);
        UpgradeMaterialsLabel.ModulateSelfOverride = WH40KCommandUiStyles.ResolveMutedText(_chaosTheme);
    }

    private StyleBoxFlat ResolveStatusBadgeStyle(WH40KStrategicPointUiStatus status)
    {
        return status switch
        {
            WH40KStrategicPointUiStatus.Ready => WH40KCommandUiStyles.CreateBadgeStyle(
                Color.FromHex("#162015".AsSpan()),
                WH40KCommandUiStyles.ReadyBadge),
            WH40KStrategicPointUiStatus.MaxTier => WH40KCommandUiStyles.CreateBadgeStyle(
                _chaosTheme ? Color.FromHex("#170C0E".AsSpan()) : Color.FromHex("#171810".AsSpan()),
                _accent),
            WH40KStrategicPointUiStatus.UpgradeInProgress => WH40KCommandUiStyles.CreateBadgeStyle(
                _chaosTheme ? Color.FromHex("#221012".AsSpan()) : Color.FromHex("#2C1F12".AsSpan()),
                WH40KCommandUiStyles.WarningBadge),
            _ => WH40KCommandUiStyles.CreateBadgeStyle(
                _chaosTheme ? Color.FromHex("#170C0E".AsSpan()) : WH40KCommandUiStyles.ResolveBadgeBackground(false),
                _chaosTheme ? WH40KCommandUiStyles.DangerBadge : WH40KCommandUiStyles.WarningBadge)
        };
    }

    private static string FormatIncomeAmount(string locKey, int amount)
    {
        return locKey switch
        {
            "wh40k-strategic-point-ui-income-funds" => WH40KCommandUiStyles.FormatThroneGelt(amount),
            "wh40k-strategic-point-ui-income-influence" => WH40KCommandUiStyles.FormatInfluence(amount),
            "wh40k-strategic-point-ui-income-research" => WH40KCommandUiStyles.FormatResearch(amount),
            _ => WH40KCommandUiStyles.FormatExperience(amount)
        };
    }

    private static bool ThemeStateChanged(WH40KStrategicPointBuiState oldState, WH40KStrategicPointBuiState newState)
    {
        return oldState.ThemeTeamId != newState.ThemeTeamId ||
               oldState.OwnerTeamId != newState.OwnerTeamId ||
               oldState.Status != newState.Status;
    }

    private static bool StatesEqual(WH40KStrategicPointBuiState left, WH40KStrategicPointBuiState right)
    {
        return left.ThemeTeamId == right.ThemeTeamId &&
               left.OwnerTeamId == right.OwnerTeamId &&
               left.Callsign == right.Callsign &&
               left.PointType == right.PointType &&
               left.Tier == right.Tier &&
               left.Hp == right.Hp &&
               left.MaxHp == right.MaxHp &&
               left.IncomeIntervalSeconds == right.IncomeIntervalSeconds &&
               left.Status == right.Status &&
               left.NextTier == right.NextTier &&
               left.UpgradeSeconds == right.UpgradeSeconds &&
               left.UpgradeInProgress == right.UpgradeInProgress &&
               left.HasNextUpgrade == right.HasNextUpgrade &&
               left.MaterialsComplete == right.MaterialsComplete &&
               IncomeEntriesEqual(left.IncomeEntries, right.IncomeEntries) &&
               MaterialEntriesEqual(left.MaterialEntries, right.MaterialEntries);
    }

    private static bool IncomeEntriesEqual(
        IReadOnlyList<WH40KStrategicPointIncomeUiEntry> left,
        IReadOnlyList<WH40KStrategicPointIncomeUiEntry> right)
    {
        if (left.Count != right.Count)
            return false;

        for (var i = 0; i < left.Count; i++)
        {
            if (left[i].LocKey != right[i].LocKey ||
                left[i].BaseAmount != right[i].BaseAmount ||
                left[i].EffectiveAmount != right[i].EffectiveAmount)
            {
                return false;
            }
        }

        return true;
    }

    private static bool MaterialEntriesEqual(
        IReadOnlyList<WH40KStrategicPointMaterialUiEntry> left,
        IReadOnlyList<WH40KStrategicPointMaterialUiEntry> right)
    {
        if (left.Count != right.Count)
            return false;

        for (var i = 0; i < left.Count; i++)
        {
            if (left[i].StackId != right[i].StackId ||
                left[i].NameLocKey != right[i].NameLocKey ||
                left[i].Required != right[i].Required ||
                left[i].Loaded != right[i].Loaded)
            {
                return false;
            }
        }

        return true;
    }
}
